codesandbox/codesandbox-client

.all-contributorsrc, README.md, src/app/pages/Sandbox/Editor/Workspace/Dependencies/ExternalResource.js, src/app/pages/Sandbox/Editor/Workspace/Dependencies/ExternalResource.test.js, src/app/pages/Sandbox/Editor/Workspace/Dependencies/VersionEntry.js, src/app/pages/Sandbox/Editor/Workspace/Dependencies/__snapshots__/ExternalResource.test.js.snap, src/app/pages/Sandbox/Editor/Workspace/Dependencies/index.js, src/app/pages/Sandbox/Editor/Workspace/Files/DirectoryEntry/Entry/EditIcons.js, src/app/pages/Sandbox/Editor/Workspace/Icon.js
Add a refresh icon to each npm package dependency. This is more discoverable that entering the package name and clicking "Replace Package".
=> Package Refresh Icon

package.json, src/app/containers/Navigation/index.js, src/app/pages/CLI/Prompt.js, src/app/pages/CLI/index.js, src/app/store/user/actions.js, yarn.lock
This PR rewrites the CLI authentication. Instead of using a websocket server (which doesn't work on SSL) we use a token based authorization.
It works like this:
1. User logins in the CLI
2. User gets directed to the CLI page, where the user will get a one use token
3. User will insert the token to request the user data
=> Token based auth

.all-contributorsrc, README.md, package.json, src/app/components/sandbox/CodeEditor/index.js, src/app/utils/codemirror.js, yarn.lock
=> Add emmet support

src/app/utils/url-generator.js, src/app/utils/url-generator.test.js
=> handle different GitHub URL input formats

src/app/containers/Modal.js, src/app/containers/modals/SignOutNotice.js, src/app/store/user/actions.js, src/app/store/user/reducer.js, src/app/store/user/utils/jwt.js
Change authentication to only save the `jwt` to localStorage. Also allow for signing out by blacklisting the token.
=> Change Authentication

README.md, src/app/components/sandbox/DeleteSandboxButton.js, src/app/components/sandbox/SandboxList.js, src/app/pages/Profile/Sandboxes/index.js, src/app/pages/Sandbox/Editor/Workspace/SandboxActions/index.js, src/app/pages/Sandbox/Editor/Workspace/index.js, src/app/store/entities/sandboxes/actions/index.js, src/app/utils/url-generator.js
Allows you to delete a sandbox from your list view on your profile page. No need to open the sandbox just to delete it. Addresses https://github.com/CompuIves/codesandbox-client/issues/52.
=> Delete Sandbox from Profile/Sandboxes

src/homepage/index.html
if u dont want the pink color i added to my name, all good. just let me know and i'll change it.
=> fix($deepLinks): RFR homepage boxes

config/webpack.dev.js
Fixes https://github.com/CompuIves/codesandbox-client/issues/165.
=> Webpack dev config: make "react-hot-loader/patch" first entry.

src/app/components/sandbox/CodeEditor/CodeMirror.js, src/app/utils/codemirror/eslint-lint.js
Fixes https://github.com/CompuIves/codesandbox-client/issues/142.
=> Fix eslint issues in the sandbox editor.

config/webpack.common.js, package.json, src/app/components/sandbox/CodeEditor/Monaco.js, src/app/components/sandbox/CodeEditor/monaco/MonacoReactComponent.js, src/app/index.html, src/app/store/entities/sandboxes/modules/entity.js, src/embed/index.html, yarn.lock
Thanks to the amazing work of @rebornix we get monaco-vue support with this PR.
Added to the cake is default code when you create a .vue file.
=> Monaco Vue support

src/app/components/sandbox/CodeEditor/Monaco.js, src/app/components/sandbox/Preview/index.js, src/app/containers/LikeHeart/LikeHeart.js, src/app/pages/Sandbox/Editor/Content/Header/index.js
Refactored `onClick={cond && func}` to `onClick={cond ? func : null }`.
=> Fix onClick={cond && func}

src/sandbox/url-listeners.js
Test sandbox: https://codesandbox.io/s/3y146z2qop.
=> Fix history preventing click on <a href="#">s

src/app/components/sandbox/CodeEditor/Monaco.js, src/embed/components/Content.js
=> Resolve issue #226. Fix console errors while editing in embed.

src/app/pages/Sandbox/Editor/index.js
=> Workspace pane was missing a minSize

src/app/store/entities/sandboxes/actions/files.js
When creating a new file, highlight it after.
=> File explorer enhancement

src/app/components/sandbox/PrivacyStatus.js
=> Small refactoring

config/webpack.common.js, config/webpack.prod.js, package.json, src/app/components/sandbox/CodeEditor/CodeMirror.js, src/app/components/sandbox/CodeEditor/Monaco.js, src/app/components/sandbox/CodeEditor/index.js, src/app/pages/index.js, src/app/store/entities/sandboxes/actions/index.js, src/app/store/entities/sandboxes/utils/create-zip/index.js, src/common/load-dynamic-polyfills.js, src/sandbox/eval/transpilers/babel/babel-worker.js, src/sandbox/eval/transpilers/babel/index.js, src/sandbox/eval/transpilers/css/get-modules.js, src/sandbox/eval/transpilers/less/index.js, src/sandbox/eval/transpilers/sass/index.js, src/sandbox/eval/transpilers/stylus/index.js, src/sandbox/eval/transpilers/svelte/index.js, src/sandbox/eval/transpilers/typescript/index.js, src/sandbox/eval/transpilers/vue/index.js, src/sandbox/eval/transpilers/vue/style-compiler/index.js, src/sandbox/eval/transpilers/vue/template-compiler/index.js, src/sandbox/eval/transpilers/vue/template-compiler/loader.js, yarn.lock
Optimizations for production bundle:
1. We use ModuleConcatenation
2. We create a common chunk for app/embed+sandbox
3. We create a common chunk for app + embed
4. We name all workers and splitted bundles
5. We use new Uglify plugin
=> Production bundle optimizations

src/app/components/sandbox/CodeEditor/Monaco.js, src/app/utils/codemirror/prettify.js
Bug fix
#285
JSON files are correctly prettified.
**Checklist**:
=> Fix Prettify for json (#285)

src/sandbox/console/index.js
=> Fix console not clearing on console.clear()

config/webpack.prod.js
=> Adjust Uglify for Safari 10

package.json, packages/app/src/sandbox/eval/presets/preact-cli/index.js, packages/app/src/sandbox/eval/transpilers/css/index.js, packages/codesandbox-api/package.json
=> Fix preact css loading

.all-contributorsrc, packages/app/src/app/components/sandbox/Preview/DevTools/Console/Message.js, packages/app/src/app/components/sandbox/Preview/DevTools/Console/index.js
enhancement
with 
```
console.log('BEFORE', JSON.stringify(variable, null, 2));
console.log('AFTER', JSON.stringify(variable, null, 2));
```
**Checklist**:
=> Improve formatting of string arguments in integrated console

packages/app/src/sandbox/eval/loaders/eval.js, packages/app/src/sandbox/eval/loaders/utils/process.js, packages/app/src/sandbox/eval/manager.js, packages/app/src/sandbox/eval/npm/fetch-npm-module.js, packages/app/src/sandbox/eval/presets/create-react-app/index.js, packages/app/src/sandbox/eval/presets/index.js, packages/app/src/sandbox/eval/transpiled-module.js
2 birds in one stone! Fixes #320 and #314. Note that we don't look for `package.json` environment variables yet, this is tricky because we don't run a command.
=> Environment Variables & NODE_PATH support

packages/app/src/app/pages/Sandbox/Editor/Workspace/Advertisement/index.js
Try Carbon as advertisement provider.
=> Try Carbon ads

packages/app/src/sandbox/eval/loaders/utils/process.js
(adapted from https://unpkg.com/process@0.11.10/browser.js)
=> Update process with some missing APIs (mosy notably nextTick())

packages/app/src/sandbox/eval/transpilers/svelte/svelte-worker.js
Adds support for using the [Svelte store](https://svelte.technology/guide#state-management) in Svelte apps.
The Svelte compiler does not know about the store
The Svelte compiler knows about the store (because of the `store: true` option).
**Checklist**:
I cloned this to run on my computer, but I couldn't actually figure out how to create a local Svelte sandbox, so I skipped checking the "Ready to be merged" option for the time being. I'll post this PR in the Svelte gitter to hopefully get some feedback that the changes from this PR are all that is necessary to add store support.
=> Add support for svelte/store to svelte compile

packages/homepage/src/screens/home/Animation/Cubes.js
Add title attribute to the cubes on Homepage
Nothing is shown on cube hover
Title is shown when hovering on the cubes
**Checklist**:
=> Add title attribute to the cubes

CONTRIBUTING.md
=> docs: remove run from yarn example

packages/app/package.json, packages/app/src/app/components/Preference/PreferenceKeybinding/KeybindingInput.js, packages/app/src/app/containers/KeybindingManager.js, packages/app/src/app/store/preferences/keybindings.js, yarn.lock
The last shortkey manager had problems with recognizing 3+ patterns. This one does work.
=> Custom shortkey manager

packages/app/src/app/store/preferences/reducer.js
There is button for this now.
Open file is prettified on save.
No longer prettifies on save.
**Checklist**:
=> Set prettifyOnSaveEnabled to false

.circleci/config.yml
yarn.lock changed for no reason
=> Check if build succeeds

packages/homepage/src/layouts/index.js
For some reason `layout---index.js` doesn't change its hash, even if content changes.
=> Debug Gatsby

packages/app/src/app/pages/Sandbox/Editor/Workspace/Dependencies/SearchDependencies.js, packages/app/src/sandbox/eval/npm/fetch-npm-module.js, packages/app/src/sandbox/npm/fetch-dependencies.js
- Support for version ranges
- Support for GitHub dependencies (fixes #278)
=> Packager upgrades

packages/app/package.json, packages/app/src/app/components/buttons/Button.js, packages/app/src/app/components/buttons/__snapshots__/Button.test.js.snap, packages/app/src/app/components/sandbox/DeleteSandboxButton.js, packages/app/src/app/pages/Profile/Navigation.js, yarn.lock
These fixes address several React warnings; see commit messages.
=> Small fixes

packages/app/src/sandbox/eval/manager.js
=> Fix browser false scenario

README.md
Update `README.md` to include link to the github project page for the phoenix framework.
=> update `README.md` to include link for phoneix framework

packages/common/url.js
=> Default to 'Run on Click' for Linux embeds

packages/app/src/sandbox/eval/manager.js
=> Fix native module cached paths

packages/app/src/sandbox/eval/npm/fetch-npm-module.js
=> Fix dynamic package.json resolving from unpkg

packages/app/src/app/pages/Sandbox/Editor/Workspace/Advertisement/CodeSponsor.js, packages/app/src/app/pages/Sandbox/Editor/Workspace/Advertisement/index.js
Ad copy and links updated.
Links to legacy Code Sponsor server.
Links to new Code Sponsor server.
**Checklist**:
Thanks!
=> Update Code Sponsor URLs and copy

packages/app/src/sandbox/eval/manager.js
=> Fix conflict resolving for dependencies in dependencies

packages/app/src/sandbox/eval/manager.js, packages/app/src/sandbox/eval/npm/fetch-npm-module.js
=> Fix dynamic fetching npm modules for conflicting libraries

packages/app/src/app/components/Preview/DevTools/Console/index.js
Bug fix
Console return values, display the correct type (`false`  =>  `false`...)
**Checklist**:
=> Return the proper eval-result type

packages/app/src/app/components/Preview/DevTools/Tests/index.js, packages/app/src/sandbox/eval/tests/jest-lite.js
=> Add Jest Setup support for CRA

packages/app/src/app/pages/Sandbox/Editor/Content/Preview/FlyingContainer.js, packages/app/src/app/pages/Sandbox/Editor/Content/Preview/index.js, packages/common/utils/keybindings.js
=> Align preview and set min width/height

packages/app/src/sandbox/eval/loaders/eval.js, packages/app/src/sandbox/eval/manager.js, packages/app/src/sandbox/eval/npm/fetch-npm-module.js, packages/app/src/sandbox/eval/presets/angular-cli/index.js, packages/app/src/sandbox/eval/transpiled-module.js
=> Fix dynamic dependency resolving

packages/app/src/app/store/modules/profile/actions.js
=> update sandbox count when deleted

packages/homepage/content/docs/2-embedding.md
=> Improving embed doc. The example code was missing.

packages/app/src/app/components/CodeEditor/Monaco/index.js
=> Preserve scroll position

packages/app/package.json, packages/app/src/app/pages/Sandbox/SearchDependencies/DependencyHit/index.js, yarn.lock
=> Sort dependency versions

packages/app/src/embed/components/App/index.js, packages/app/src/embed/components/Content/elements.js, packages/app/src/embed/components/Content/index.js, packages/common/url.js, packages/homepage/content/docs/2-embedding.md
=> Allow vertical embedding for embeds

packages/app/src/sandbox/eval/manager.js, packages/app/src/sandbox/eval/npm/fetch-npm-module.js
=> Disable throwing errors on dynamic dep fetch 404

packages/app/src/sandbox/eval/presets/parcel/transpilers/html-worker.js
Maybe a better solution would be inlining script tags containing the transpiled code.
Fixes #599
=> Add Parcel on load

packages/app/src/sandbox/eval/presets/parcel/transpilers/html-worker.js
=> Fix no parcel loading for html without resources

packages/app/src/sandbox/compile.js, packages/app/src/sandbox/eval/manager.js
=> Fix dependency caching

packages/app/src/sandbox/eval/transpilers/sass/sass-worker.js
=> Fix resolving sass files more than 1 level deep

packages/app/src/sandbox/url-listeners.js
=> Fix overridden history.go() to sendUrlChange()

packages/homepage/content/docs/2-importing.md
This makes it easy to find the options that you can use in assembling the query. :)
This is a docs update.
**Checklist**:
=> Add link to embed options

packages/homepage/content/docs/2-importing.md
Cli repo has been moved.
update outdated link
an outdated link is present in the documentation
an up-to date link is present in the documentation
**Checklist**:
=> Update link to cli repo

packages/homepage/content/docs/2-importing.md
Docs change
**Checklist**:
Adding information on react-codesandboxer
Added this as its own section, with a simple example as a code snippet. Happy to make this briefer and point to the external docs, and make it longer to make the link more superfluous.
=> Add information on using react-codesandboxer

packages/app/src/app/components/SandboxList/index.js
=> bugfix: Display correct template icons.

packages/homepage/src/screens/home/Animation/Cubes.js, packages/homepage/src/screens/home/ExtraFeatures/Feature.js, packages/homepage/src/screens/home/ExtraFeatures/index.js, packages/homepage/src/utils/media.js
Improve Features section's layout
https://github.com/CompuIves/codesandbox-client/issues/666
**Checklist**:
=> Improve Features section's layout

packages/app/src/app/store/modules/preferences/index.js
=> Default clearConsoleEnabled to true

packages/app/src/app/pages/Sandbox/Editor/Content/Preview/DevTools/Console.js, packages/app/src/app/pages/Sandbox/Editor/Content/Preview/DevTools/Navigator.js, packages/app/src/app/pages/Sandbox/Editor/Content/Preview/DevTools/Tests.js
Add the "Clear console" action for the console preview panel.
**Checklist**:
=> Add the "Clear console" action for the console preview panel

packages/app/package.json, yarn.lock
<details><summary>Visual representation</summary><p>
</p></details>
```diff
+ console.time / console.timeEnd
+ console.assert
+ console.count
+ Linkified URLs
+ Quoted / unquoted string styles
- Overflowing text bug
```
=> console-feed@2.7.3

packages/common/templates/cxjs.js, packages/common/templates/icons.js
Finishing up. Can't wait to see it online 🎉
=> Add CxJS cube to the homepage and fix CxJS and Dojo icons

packages/app/src/app/components/Alert/index.js, packages/app/src/app/components/Button/elements.js, packages/app/src/app/pages/Sandbox/Editor/Workspace/SandboxActions/elements.js, packages/app/src/app/pages/Sandbox/Editor/Workspace/SandboxActions/index.js, packages/common/theme.js
=> Make sandbox delete button and alert popup confirm button red

packages/app/src/app/store/modules/files/actions.js, packages/app/src/app/store/modules/files/sequences.js, packages/app/src/app/store/providers/Api.js
=> Show descriptive error message on file too large upload error

packages/app/src/sandbox/react-error-overlay/overlay.js, packages/app/src/sandbox/react-error-overlay/styles.js
=> Fix error overlay closing and make it translucent

packages/app/src/app/pages/Search/index.js
=> Fix update search state when navigating back / forward

packages/app/src/app/pages/Profile/Sandboxes/elements.js, packages/app/src/app/pages/Profile/Sandboxes/index.js, packages/app/src/app/pages/Profile/Showcase/index.js
* shows "This user doesn't have any sandboxes yet" ("You don't have any sandboxes yet" if it's you) on both Showcase and Sandboxes tabs
* shows "This user didn't like any sandboxes yet" ("You didn't like any sandboxes yet") on Likes tab
Fixes #433 .
=> Show message if user doesn't have any (liked) sandboxes

packages/common/templates/dojo.js
=> Fix typo in Dojo template

packages/app/src/sandbox/url-listeners.js
Fixes #595 .
Test: http://pr810.cs.lbogdan.tk/s/pk8807zz0 .
=> Fix vue-router <router-link> in hash mode

packages/app/src/app/components/CodeEditor/Monaco/elements.js, packages/app/src/app/components/CodeEditor/Monaco/index.js, packages/app/src/app/components/CodeEditor/Monaco/workers/syntax-highlighter.js
This PR improves the syntax highlighting in the Monaco editor.
Parent "kinds" are added in the decoration data passed to Monaco. This creates ambiguities and syntax highlighting bugs.
Instead of including the range of the node it iterates over the childs to only keep tokens. I also added `type-of-kind` classifiers, for example `typeName-of-TypeReference`.
Example using `^` for `CallExpression` and `~` for `VariableDeclarationList`
**`master`** : 
```js
const value = this.call(param)
^^^^^^^^^^^^^^^^
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
**PR** : 
```js
const value = this.call(param)
~~~~~~                 ^     ^
```
**`master`** : 
*`<li`, `<button`, and `<span` are not correctly …
=> Improve Monaco syntax highlighting 

packages/homepage/content/docs/2-git.md
Copy change to reflect the actual functionality.
It does not support private github repos.
It is more specific in the docs.
**Checklist**:
=> Specify only public github repos work.

packages/sandpack/README.md
docs update
Throws an error because the options are passed incorrectly with the example code.
Fixes the docs so that the example code is correct.
**Checklist**:
=> Fix sandpack updatePreview docs

packages/app/src/embed/components/Header/elements.js, packages/app/src/embed/components/Header/index.js, packages/app/src/embed/components/Sidebar/elements.js, packages/app/src/embed/components/Sidebar/index.js
Bug fix. Closes #908.
#908
Dynamic height when long title on sidebar and add white space when title is long on header.
**Checklist**:
=> fix embed title

packages/react-sandpack/src/components/Navigator/BackwardIcon.tsx, packages/react-sandpack/src/components/Navigator/ForwardIcon.tsx, packages/react-sandpack/src/components/Navigator/Navigator.tsx
Feature
No way to navigate the browser
You can now use the arrows to navigate the browser history
**Checklist**:
=> Add browser navigation for BrowserPreview

yarn.lock
=> Upgrade console-feed to 2.8.3

.circleci/config.yml, package.json, packages/app/config/webpack.prod.js, packages/app/package.json, packages/app/src/sandbox/eval/transpilers/babel/babel-parser.js, packages/app/src/sandbox/eval/transpilers/babel/worker/babel-worker.js, yarn.lock
=> Use Terser instead of uglify-es for uglifying code

packages/app/src/app/pages/Sandbox/Editor/Workspace/items/Deployment/index.js
Bugfix
Link is broken and ends up pointing to https://codesandbox.io/s/zeit.co/now
Link points to https://zeit.co/now
**Checklist**:
=> Fix external URL

packages/app/src/app/components/NewSandbox/index.js, packages/common/templates/dojo.js, packages/homepage/src/screens/home/Frameworks/index.js
This is just a simple change, dropping the "2" from Dojo now that Dojo 3 is out.
Currently, CodeSandbox features Dojo 2.
**Checklist**:
=> Drop '2' From Dojo Branding

packages/app/src/sandbox/eval/transpilers/babel/worker/babel-worker.js
=> Allow dynamic import in ESModule dependencies

packages/app/src/app/components/NewSandbox/index.js, packages/app/src/app/pages/Sandbox/Editor/Header/index.js
Only modified for references that are visible in the UI
=> GitHub has a capital H

packages/app/package.json, yarn.lock
Updated the version of `mobx-state-tree` to version 3.3.0. 
The user is unable to remove a tag from the list of tags by clicking the delete button ( See #1063)
**Checklist**:
=> Update mobx-state-tree to version 3.3.0

packages/common/themes/index.js
I think this minimal yet contrasty theme would make an outstanding addition to codesandbox. 
It has already been downloaded by 65K+ users on the VSCode marketplace. I would be honored to see it offered inside of my favorite online code editor.
https://github.com/juliettepretot/lucy-vscode
=> 💅Add Lucy syntax theme

CONTRIBUTING.md
Adds a note to the contribution guide about linting the code before submitting a PR.
Docs
I submit a PR that fails because I didn't run the linter.
I can only make the above excuse if I don't read the contributing guide :wink:.
**Checklist**:
=> Add note to lint PRs

packages/app/src/app/index.html, packages/app/src/app/pages/Dashboard/Content/CreateNewSandbox/Modal/Template/elements.js, packages/app/src/app/pages/Dashboard/Content/CreateNewSandbox/Modal/elements.js, packages/app/src/app/pages/Dashboard/Content/CreateNewSandbox/Modal/index.js, packages/app/src/app/pages/Dashboard/Content/SandboxGrid/elements.js, packages/app/src/app/pages/Dashboard/Content/Sandboxes/Filters/elements.js, packages/app/src/app/pages/Dashboard/Content/Sandboxes/index.js, packages/app/src/app/pages/Dashboard/Content/elements.js, packages/app/src/app/pages/Dashboard/Content/routes/TeamView/elements.js, packages/app/src/app/pages/Dashboard/Sidebar/elements.js, packages/app/src/app/pages/Dashboard/Sidebar/index.js, packages/app/src/app/pages/Dashboard/elements.js, packages/app/src/app/pages/Dashboard/index.js, packages/app/src/app/pages/NewSandbox/index.js, packages/app/src/app/pages/common/Navigation/elements.js, packages/app/src/app/pages/common/Navigation/index.js
feature
Things do not look okay in mobile
Things look okay in mobile
**Checklist**:
=> Make dashboard and new Sanbox mobile freindly

packages/homepage/src/screens/home/NPMFeature/SandboxCount.js, packages/homepage/src/screens/home/NPMFeature/SearchInput/index.js, packages/homepage/src/screens/home/NPMFeature/index.js, packages/homepage/src/utils/algolia.js
The "sandbox count" on the homepage now gets fetched from Algolia
The "sandbox count" was hardcoded
The "sandbox count" is now fetched from Algolia with a fallback (of 10x more than the static value!!)
I also made sure the "lite" version of Algolia is used on the home page (it's a significant difference in bundle size)
**Checklist**:
=> chore(homepage): make sure sandbox count is updated

packages/app/src/app/pages/Dashboard/Content/Sandboxes/index.js, packages/app/src/app/pages/Search/Filters/Filter/elements.js, packages/app/src/app/pages/Search/Filters/Filter/index.js, packages/app/src/app/pages/Search/Filters/elements.js, packages/app/src/app/pages/Search/Filters/index.js, packages/app/src/app/pages/Search/Results/elements.js, packages/app/src/app/pages/Search/SandboxCard/SandboxInfo/elements.js, packages/app/src/app/pages/Search/SandboxCard/elements.js, packages/app/src/app/pages/Search/SandboxCard/index.js, packages/app/src/app/pages/Search/elements.js, packages/app/src/app/pages/Search/index.js, packages/app/src/app/utils/get-type.js, packages/common/components/flex/MaxWidth.js
This PR makes the Search page mobile responsive
Here are some pics
=> make search responsive

packages/app/src/app/pages/common/GithubIntegration/index.js, packages/app/src/app/store/modules/git/index.js, packages/app/src/app/store/modules/git/model.js
Fix a typo
The word is spelled "Commiting"
The word has been changed to "Committing"
**Checklist**:
=> fix typo, "Commiting" should be "Committing"

packages/app/src/app/pages/Sandbox/Editor/Workspace/Dependencies/VersionEntry/elements.js, packages/app/src/app/pages/Sandbox/Editor/Workspace/Dependencies/VersionEntry/index.js, packages/app/src/app/pages/Sandbox/Editor/Workspace/elements.js
Adds all dependency sizes to a dependency
**Checklist**:
=> Add Dependency Size

packages/app/src/app/pages/Sandbox/Editor/Workspace/items/Deployment/Elements.js, packages/app/src/app/pages/Sandbox/Editor/Workspace/items/Deployment/index.js, packages/app/src/app/pages/common/Modals/DeleteDeploymentModal/index.js, packages/app/src/app/pages/common/Modals/index.js, packages/app/src/app/store/modules/deployment/actions.js, packages/app/src/app/store/modules/deployment/index.js, packages/app/src/app/store/modules/deployment/model.js, packages/app/src/app/store/modules/deployment/sequences.js
Adds better now integration
You can deploy things but no feedback is given on what you deployed
* You can see a list of deployments done with that sandbox
* You can delete deployments
* Visit them
* Alias them to what you set up in your now.json
=> Now integration

CODE_OF_CONDUCT.md, CONTRIBUTING.md
=> add CODE_OF_CONDUCT

packages/common/themes/index.js
Adds the [Palenight theme](https://bit.ly/palenight-theme) with ~300K installs on the VSCode Marketplace to **CodeSandbox**.
**Checklist**:
=> Adds Palenight Theme

CODE_OF_CONDUCT.md
In part just raising that this is missing. This is probably not the ideal email. If you know what a better email would be, probably reject this and update with that instead.
**Checklist**:
=> Provide contact address in code of conduct

packages/react-sandpack/README.md
=> Missing styles Ives :(

packages/app/src/app/pages/common/Modals/CommitModal/index.js
Simple typo fix for something I have seen lots of as of late :) Thanks once again for CodeSandbox!
=> Fix typo in CommitModal

packages/app/src/app/store/modules/deployment/actions.js, packages/app/src/app/store/modules/deployment/sequences.js, packages/app/src/app/store/sequences.js, packages/common/templates/template.js
Fixes:
- Stuck on loading after signing in
- Deployment error not resetting modal
- Altering deployment data
Updates:
- Serve in the deployment boilerplate
=> Fix common deployment problems

packages/app/src/app/pages/Sandbox/Editor/Workspace/items/Deployment/index.js, packages/app/src/app/store/modules/deployment/actions.js, packages/app/src/app/store/modules/deployment/index.js, packages/app/src/app/store/modules/deployment/model.js, packages/app/src/app/store/modules/deployment/sequences.js, packages/app/src/app/store/utils/pushToAirtable.js, packages/app/src/app/store/utils/setAirtable.js
Feature 
No warning saying we only support version 1 of zeit
Adds a new warning for version 1 and also a way for people to say they want version 2
It also shows a notification saying your feedback was saved but that's not on the gif
=> add zeit warning

.all-contributorsrc, packages/homepage/src/pages/explore.js
Feature
The featured sandboxes on the explore page can only be changed by clicking the right and left arrow
This change allows a user navigate the featured sandboxes by pressing the arrow keys on the keyboard
**Checklist**:
=> Navigate between featured sandboxes using left and right arrow keys

packages/homepage/src/pages/explore.js
=> Remove event listeners when unmounting

packages/app/src/app/pages/common/Modals/StorageManagementModal/FilesList/elements.js, packages/app/src/app/pages/common/Modals/StorageManagementModal/FilesList/index.js, packages/app/src/app/pages/common/Modals/StorageManagementModal/index.js
A feature, adds selections to media so you can add several to project at once and also delete several at once
closes #941
=> add bulk delete and add to project to media

packages/app/src/app/components/DeploymentIntegration/DetailInfo/elements.js, packages/app/src/app/components/DeploymentIntegration/DetailInfo/index.js, packages/app/src/app/components/DeploymentIntegration/elements.js, packages/app/src/app/components/DeploymentIntegration/index.js, packages/app/src/app/pages/Sandbox/Editor/Workspace/items/Deployment/Elements.js, packages/app/src/app/pages/Sandbox/Editor/Workspace/items/Deployment/index.js, packages/app/src/app/pages/Sandbox/Editor/Workspace/items/Deployment/zeit.js
This PR refactors the deployment UI to get it ready for more deployment options
Any UI advice would be great
=> refactor deployment ui

packages/homepage/src/screens/home/NPMFeature/SearchInput/Hit.js
Better formatter for search results
**Checklist**:
=> chore: add toLocaleString for better format

packages/app/src/app/index.html, packages/app/src/app/pages/common/Modals/ShareModal/Title.js, packages/app/src/app/pages/common/Modals/ShareModal/elements.js, packages/app/src/app/pages/common/Modals/ShareModal/getCode.js, packages/app/src/app/pages/common/Modals/ShareModal/index.js, packages/common/utils/url-generator.js
A cleaner look for the share modal
Issues:
Monaco does not load text
=> make up on share modal

packages/homepage/content/docs/2-embedding.md
otherwise these links are eg 404 at https://codesandbox.io/docs/embedding
doc fix
these two links go to 404
the links are valid
**Checklist**:
- [x ] Documentation
=> make links valid

yarn.lock
=> Update console-feed to 2.8.6

packages/app/src/app/pages/common/Modals/ShareModal/getCode.js
Feature
The `iframe` embed text doesn't include a `title` attribute.
Add a `title` attribute to the `iframe` embed text.
**Checklist**:
=> Set iframe title in embed code

package.json, packages/app/src/app/pages/Dashboard/Content/CreateNewSandbox/Modal/Template/elements.js, packages/app/src/app/pages/Dashboard/Content/CreateNewSandbox/Modal/Template/index.js, packages/app/src/app/pages/Dashboard/Content/CreateNewSandbox/Modal/availableTemplates.js, packages/app/src/app/pages/Dashboard/Content/CreateNewSandbox/Modal/elements.js, packages/app/src/app/pages/Dashboard/Content/CreateNewSandbox/Modal/index.js, packages/common/src/templates/angular.ts, packages/common/src/templates/gatsby.ts, packages/common/src/templates/next.ts, packages/common/src/templates/node.ts, packages/common/src/templates/nuxt.ts, packages/common/src/templates/parcel.ts, packages/common/src/templates/react.ts, packages/common/src/templates/template.ts, packages/common/src/templates/vue.ts
Adds tabs to the new sandbox modal since we are getting too many templates
Currently ut's a long modal
Tabs for popular, client, server and preset templates
=> Make tabs on new sandbox modal

packages/app/src/app/store/modules/deployment/actions.js, yarn.lock
There was an issue where the package.json was being sent twice
I now check if it is in the array of files before adding it 
closes #1620
=> Fix duplicate files on now deploys

packages/app/package.json, yarn.lock
=> Update vue loader to support slots

packages/app/src/app/components/CodeEditor/Configuration/elements.ts, packages/app/src/app/components/CodeEditor/VSCode/Configuration/elements.ts, packages/app/src/app/pages/common/Modals/PreferencesModal/CodeFormatting/Prettier/index.js, packages/common/src/templates/configuration/prettierRC/ui.tsx
Also adds a max height to make it scrollable
=> add arrowParens to prettier config

packages/app/babel.config.js, packages/app/src/app/components/Alert/elements.js, packages/app/src/app/components/Alert/index.js, packages/app/src/app/components/CodeEditor/VSCode/Configuration/elements.ts, packages/app/src/app/components/CodeEditor/VSCode/MonacoReactComponent.js, packages/app/src/app/components/Preview/DevTools/Terminal/terminal-theme.js, packages/app/src/app/index.html, packages/app/src/app/pages/Sandbox/Editor/Workspace/Files/DirectoryEntry/index.js, packages/app/src/app/pages/Sandbox/Editor/Workspace/Git/Changes/elements.js, packages/app/src/app/pages/Sandbox/Editor/utils/get-vscode-theme.js, packages/common/src/templates/configuration/elements.ts
Some things were taking the theme into consideration
This PR fixes some like:
closes #1702
closes #1399
closes #1703 
closes #1701
=> fix readability issues with white themes

packages/app/src/app/components/Preview/DevTools/Tabs/elements.ts, packages/app/src/embed/components/App/elements.js, packages/app/src/embed/components/Sidebar/elements.js, packages/app/src/embed/index.html, packages/app/src/sandbox/eval/cache.ts, packages/app/src/sandbox/eval/manager.ts, packages/common/src/__snapshots__/theme.test.js.snap, packages/common/src/theme.ts
Tested the embed of CodeSandbox on my iPhone. Found a couple things.
=> Fix all Safari problems with embed

packages/common/src/components/logos/Nuxt.tsx
=> fix(nuxt): Update logo

.circleci/config.yml
=> Rewrote circleci/config.yml to 2.1 schema

packages/app/src/app/components/Preview/DevTools/Terminal/index.js, packages/app/src/app/components/Preview/DevTools/Terminal/styles.css
Fixed UI bug #1804 where console shows empty space in server sandboxes
console shows empty space in server sandboxes
console does not shows empty space in server sandboxes
**Checklist**:
=> Fixed console empty space issue on server sandbox

packages/homepage/content/users.json
Adds the SitePoint logo and URL to the list of companies using CodeSandbox
Renders the current list of companies.
Renders the current list of companies *plus* SitePoint
**Checklist**:
=> Add SitePoint

packages/app/src/app/pages/common/Modals/ShareModal/index.js
=> Add Share on Dev and Share on Twitter

CONTRIBUTING.md
Docs update
When cloning a clean version of this repo and following the "Submitting a Pull Request" section, I get errors
No errors after following the whole section
**Checklist**:
Closes #1868
=> Add a notice about building packages before running the linter

.eslintrc, package.json, packages/homepage/src/screens/home/NPMFeature/SearchInput/Hit.js, packages/homepage/src/screens/home/NPMFeature/SearchInput/Input.js, packages/homepage/src/screens/home/NPMFeature/SearchInput/index.js, yarn.lock
Update components to functional components with Hooks
Class components
Functional components with Hooks
**Checklist**:
=> Refactor SearchInput to functional component with hooks

packages/app/src/app/pages/Dashboard/Content/Sandboxes/Filters/FilterOptions/index.js
BugFix
https://monosnap.com/file/ss1wzqBckFfWpTwjFJdriwdgaF2OTk
Solves the bug in Dashboard sandboxes template filter
**Checklist**:
=> [Dashboard] fix sandboxses template filter

packages/dynamic-pages/pages/user-sandboxes/index.js, packages/dynamic-pages/utils/useWindowSize.js
Fix ESLint hooks warnings
ESLint warnings
No ESLint warnings
**Checklist**:
=> Fix ESLint hooks warnings

packages/app/src/app/pages/Search/Filters/index.js, packages/app/src/app/pages/Search/Results/index.js
Adds search by date in the search page(most recent first)
closes #1909
=> add search by date

packages/homepage/src/components/Cube.js
Update Cube to functional component with Hooks
**Checklist**:
=> Refactor Cube to functional component with hooks

packages/app/src/app/pages/CLI/Prompt/index.js, packages/app/src/app/pages/CLI/index.js
Update CLI to functional components with Hooks
Class components
Functional components with Hooks
**Checklist**:
=> Refactor CLI to functional components with hooks

packages/app/src/app/pages/CliInstructions/index.js
Update CliInstructions to functional component with Hooks
**Checklist**:
=> Refactor CliInstructions to functional component with hooks

packages/app/src/app/pages/NewSandbox/index.js
Update NewSandbox to functional component with Hooks
**Checklist**:
=> Refactor NewSandbox to functional component with hooks

packages/homepage/content/users.json, packages/homepage/src/screens/home/Frameworks/index.js
Bugfixes
A broken image link and icons weren't resizing correctly.
Displays Vue Vixens logo, and resizes icon container at 800px rather than 660px
**Checklist**:
=> Home page fixes

packages/homepage/src/components/layout.js
Update layout to functional component with Hooks
**Checklist**:
=> Refactor layout to functional component with hooks

packages/homepage/src/components/DocSearch.js
Update DocSearch to functional component with Hooks
**Checklist**:
=> Refactor DocSearch to functional component with hooks

packages/homepage/src/components/LoadInView.js
Update LoadInView to functional component with Hooks
**Checklist**:
=> Refactor LoadInView to functional component with hooks

packages/app/src/app/pages/Search/Filters/Filter/Sort.js, packages/app/src/app/pages/Search/Filters/Filter/index.js, packages/app/src/app/pages/Search/Filters/index.js, packages/app/src/app/pages/Search/ResultInfo/index.js, packages/app/src/app/pages/Search/Results/index.js, packages/app/src/app/pages/Search/index.js
Update Search to functional components with Hooks
Class components
Functional components with Hooks
**Checklist**:
=> Refactor Search to functional components with hooks

packages/app/src/app/pages/Curator/SandboxCard/index.js, packages/app/src/app/pages/Curator/index.js
Update Curator to functional components with Hooks
Class components
Functional components with Hooks
**Checklist**:
Supersed #1951
=> Refactor Curator to functional components with hooks

packages/notifications/src/component/Toast.tsx, packages/notifications/src/state.ts
=> Add condition for primary action in toast

packages/app/src/app/pages/CLI/index.js, packages/app/src/app/pages/CliInstructions/index.js, packages/app/src/app/pages/GitHub/index.js, packages/app/src/app/pages/NewSandbox/index.js, packages/app/src/app/pages/Search/index.js
Use mobx-react-lite & new useSignals hook
- Use `mobx-react`
- Use `inject` HOC
- Use `mobx-react-lite`
- Use new `useSignals` hook
**Checklist**:
=> Use mobx-react-lite & new useSignals hook

.drone.yml, .prettierignore, packages/common/src/components/Preview/index.tsx, packages/common/src/utils/host.ts
Use Drone.io for building PRs.
=> Add Drone.io pipeline config

packages/app/src/app/pages/common/Modals/ShareModal/getCode.js, packages/common/src/components/Preview/index.tsx
=> allow webcam and audio when possible

packages/app/src/app/components/Preview/DevTools/Console/index.tsx
> Fixes #1984
- It is switching up the console clear icon. 
**Checklist**:
=> Change console clear icon

.github/FUNDING.yml
Add [GitHub Sponsorship](https://github.com/sponsors)
N/A
N/A
**Checklist**:
=> Add GitHub Sponsorship

packages/app/src/app/pages/Sandbox/Editor/Content/index.js
It's a fix for an obvious bug and should be easy to review, so please allow me to skip the rest.
**Checklist**:
=> fixed a bug caused by typo

.github/PULL_REQUEST_TEMPLATE.md
Change the PR template so the hierarchy is a bit clearer
Each title is just a bolded line
Each title is a H2
Use it as the template for this PR
=> Make the PR template hierarchy a bit clearer

packages/app/src/app/components/Preview/DevTools/Terminal/index.js, packages/app/src/app/components/Preview/DevTools/Terminal/styles.css
=> fix(devtools): Fix terminal output when it's positioned along with the browser

CONTRIBUTING.md
=> docs: Add how to debug the app with Cerebral Debugger

CONTRIBUTING.md
Fix wrong text from the previous PR. My bad. :man_facepalming:
=> docs: Fix text about how to debug the app

packages/app/src/app/components/Preview/DevTools/Terminal/index.js, packages/app/src/app/components/Preview/DevTools/Terminal/styles.css
Looks like #2040 is causing #2062 , reverting to check that's actually the case.
=> Revert #2040

packages/app/src/app/pages/Dashboard/Content/routes/PathedSandboxes/Folders.js, packages/app/src/app/pages/Dashboard/Content/routes/PathedSandboxes/index.js, packages/app/src/app/pages/Dashboard/Sidebar/SandboxesItem/FolderEntry/CreateFolderEntry.tsx, packages/app/src/app/pages/Dashboard/Sidebar/SandboxesItem/FolderEntry/elements.ts, packages/app/src/app/pages/Dashboard/Sidebar/SandboxesItem/FolderEntry/index.tsx, packages/app/src/app/pages/Dashboard/Sidebar/SandboxesItem/index.js, packages/app/src/app/pages/Dashboard/utils/get-direct-children.js
Fixes #2080
Dashboard now supports hashes in folders
Folders are not opened correctly with a hash
Folders are opened and edited correctly with a hash
Open folder, create sandbox in folder, rename folder.
=> Fix hashes in folder names on dashboard

.circleci/config.yml, packages/app/src/app/components/Preview/DevTools/Terminal/Shell/index.js, packages/app/src/app/components/Preview/DevTools/Terminal/ShellTabs/elements.js, packages/app/src/app/components/Preview/DevTools/Terminal/index.js, packages/app/src/app/components/Preview/DevTools/Terminal/styles.css, packages/app/src/app/components/Preview/DevTools/elements.ts, packages/app/src/app/components/Preview/DevTools/index.tsx
Should fix #2103, #1654 .
This mainly uses Flexbox to shrink / grow containers instead of manually managing widths / heights.
=> DevTools / Terminal UI fixes

packages/homepage/content/docs/2-importing.md
Docs Update
2 consecutive `a` 
@CompuIves @SaraVieira  Is there any way we can create a sandbox with files inside a folder using `Define API` ? For eg: having files inside the `components` directory or `pages`  directory.
=> docs: Remove extra a

packages/app/src/app/pages/Sandbox/Editor/Header/Header.tsx, packages/app/src/app/pages/Sandbox/Editor/Header/SandboxName/SandboxName.tsx, packages/app/src/app/pages/Sandbox/Editor/Header/SandboxName/elements.ts, packages/app/src/app/pages/Sandbox/Editor/Workspace/Project/Project.tsx
=> Show Template Banner and name for not owned sandboxes

packages/common/src/types/index.ts
Fixes duplicate typing issue related to merge
=> Fix duplicate typing

packages/app/src/app/components/CodeEditor/FuzzySearch/index.js, packages/app/src/app/components/CodeEditor/MonacoDiff/index.js, packages/app/src/app/components/ModeIcons/index.js, packages/app/src/app/components/Preview/DevTools/Console/index.tsx, packages/app/src/app/components/Preview/DevTools/Tests/index.tsx, packages/app/src/app/components/SubscribeForm/CheckoutForm/index.tsx, packages/app/src/app/pages/Dashboard/Content/DragLayer/SelectedSandboxItems/AnimatedSandboxItem.js, packages/app/src/app/pages/Dashboard/Content/SandboxCard/index.tsx, packages/app/src/app/pages/Dashboard/Sidebar/Item/index.js, packages/app/src/app/pages/Dashboard/Sidebar/SandboxesItem/FolderEntry/index.tsx, packages/app/src/app/pages/Live/index.js, packages/app/src/app/pages/Sandbox/Editor/Workspace/Dependencies/VersionEntry/index.js, packages/app/src/app/pages/Sandbox/index.js, packages/app/src/app/pages/common/Modals/ForkServerModal/index.js, packages/app/src/embed/components/App/index.js, packages/app/src/embed/components/Content/index.tsx, packages/common/src/components/ContributorsBadge/index.tsx, packages/common/src/components/Preview/index.tsx, packages/homepage/src/screens/explore/SandboxModal.js, packages/homepage/src/screens/home/Animation/Cubes.js, packages/react-embed/src/SandboxEmbed/SandboxEmbed.tsx
Refactor. Rename unsafe lifecycle methods to use the `UNSAFE_` prefix.
- [Update on Async Rendering](https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html): referenced here in the update post
- [React Component: Legacy Lifecycle Methods](https://reactjs.org/docs/react-component.html#legacy-lifecycle-methods): referenced here in the `React.Component` documentation
These methods are considered unsafe. I wanted to test changes made in https://github.com/reactjs/react-codemod/pull/228 to add support for TypeScript in the `react-codemod` package against a public repository.
If this is something you don't want feel free to close this PR. 
Should be identical _(but these methods will not be removed in React 17 and make it clearer these methods should be changed if refactoring)_ …
=> Rename unsafe React lifecycle methods

packages/homepage/src/components/Footer.js
Blog Link update
Links to medium page
Link to codesanbox.io/blog
=> Fix: Blog Link in footer

yarn.lock
~(Might) fix #1978 .~ It doesn't, unfortunately.
=> Update console-feed to 2.8.8

packages/app/src/sandbox/eval/npm/fetch-npm-module.ts, packages/app/src/sandbox/eval/transpiled-module.ts
Implementing this so we can close outdated #1599
=> Implement improvements from #1599

packages/app/package.json, packages/app/src/app/pages/Sandbox/Editor/Workspace/Project/SandboxConfig/Icon/elements.ts, packages/app/src/app/pages/Sandbox/Editor/Workspace/Project/SandboxConfig/Icon/index.tsx, packages/app/src/app/pages/Sandbox/Editor/Workspace/Project/SandboxConfig/SandboxConfig.tsx, packages/app/src/app/pages/Sandbox/Editor/Workspace/Project/SandboxConfig/TemplateConfig.tsx, packages/app/src/app/pages/Sandbox/Editor/Workspace/Project/SandboxConfig/elements.ts, packages/app/src/app/pages/Sandbox/Editor/Workspace/Project/elements.ts, packages/app/src/app/store/modules/editor/model.js, packages/app/tsconfig.check.json, packages/common/src/components/Switch/index.tsx, packages/common/src/components/Template/UserTemplate.tsx, yarn.lock
This PR adds two new features to the templates
* Adding a custom icon to your template
* set it to public
=> Templates v2 - Change Icon and make public

packages/app/src/app/pages/CLI/index.tsx, packages/app/src/app/pages/Curator/index.js, packages/app/src/app/pages/Dashboard/Content/CreateNewSandbox/NewSandboxModal/NewSandboxModal.tsx, packages/app/src/app/pages/Patron/PricingModal/PricingChoice/index.tsx, packages/app/src/app/pages/Sandbox/Editor/Header/index.tsx, packages/app/src/app/pages/Sandbox/Editor/Workspace/Dependencies/index.js, packages/app/src/app/pages/Sandbox/Editor/Workspace/Project/Alias/Alias.tsx, packages/app/src/app/pages/Sandbox/Editor/Workspace/Project/Description/Description.tsx, packages/app/src/app/pages/Sandbox/Editor/Workspace/Project/Frozen/Frozen.tsx, packages/app/src/app/pages/Sandbox/Editor/Workspace/Project/Keywords.tsx, packages/app/src/app/pages/Sandbox/Editor/Workspace/Project/Project.tsx, packages/app/src/app/pages/Sandbox/Editor/Workspace/Project/SandboxConfig/Icon/index.tsx, packages/app/src/app/pages/Sandbox/Editor/Workspace/Project/Title/Title.tsx, packages/app/src/app/pages/Sandbox/Editor/Workspace/items/GitHub/CreateRepo/CreateRepo.tsx, packages/app/src/app/pages/Sandbox/Editor/Workspace/items/GitHub/Git/Git.tsx, packages/app/src/app/pages/Sandbox/Editor/Workspace/items/More/More.tsx, packages/app/src/app/pages/common/GithubIntegration/index.tsx, packages/app/src/app/pages/common/LikeHeart/index.tsx, packages/app/src/app/pages/common/Modals/ForkFrozenSandboxModal/ForkFrozenSandboxModal.tsx, packages/app/src/app/pages/common/Navigation/index.tsx, packages/app/src/app/pages/common/NotFound/index.tsx, packages/app/src/app/pages/common/UserMenu/index.tsx, packages/app/src/app/pages/common/ZeitIntegration/index.tsx
Just like #2178, observe all other components that use the `useStore` hook
Components that use the `useStore` hook aren't observed
Components that use the `useStore` hook are observed
N/A
=> Observe components that use useStore hook

packages/app/src/app/pages/Sandbox/Editor/Workspace/SSEDownNotice/SSEDownNotice.tsx, packages/app/src/app/pages/Sandbox/Editor/Workspace/items/GitHub/Git/Git.tsx, packages/app/src/app/pages/Sandbox/Editor/Workspace/items/More/More.tsx
Resolve discussions for
- `SSEDownNotice`: #1965
- `GitHub`: #1968
- `More`: #1970
N/A
N/A
**Checklist**:
=> Resolve discussions

packages/app/src/app/components/CodeEditor/VSCode/index.tsx, packages/app/src/app/pages/Live/index.js, packages/app/src/app/store/sequences.js, packages/app/src/app/utils/user.ts
Fixes #2212
Fixes #2208
Fixes issues with:
- Need to sign in to join live session
- Executors (server) not working live
- File opening causing desynchronization
- Live session not setting workspace defaults and settings
=> Fix live regressions

packages/app/src/app/pages/common/Modals/Changelog/Dashboard/index.js, packages/common/src/components/Footer.tsx, packages/homepage/src/screens/home/RecentPublications/index.js
Update Blog Query & Link
- Currently, on Homepage in the recent publication, we show medium posts I have changed it to use the current blog query.
- Update blog link from `medium` to `/blog`
Confirmed on localhost as seen in above image.
=> fix: Blog Link and Blogs Query on Homepage

packages/app/src/app/pages/Sandbox/Editor/Workspace/Files/DirectoryEntry/Entry/EntryTitleInput/index.js
Closes #2229 
Bug Fix
Tested locally.
=> Fix: trim space

packages/app/src/app/pages/common/Modals/PreferencesModal/EditorPageSettings/EditorSettings/index.js, packages/app/src/app/pages/common/Modals/PreferencesModal/elements.js
It doesn't work and we won't have time to fix it anytime soon
=> remove vim mode option on ff

packages/app/src/app/index.html, packages/app/src/embed/index.html
Removing duplicate `theme-color` meta tag from head.
When running CodeSandbox as desktop pwa, [theme-color](https://github.com/codesandbox/codesandbox-client/blob/master/packages/app/src/app/index.html#L22) meta tag from page head takes precedence over [manifest.json](https://github.com/codesandbox/codesandbox-client/blob/master/packages/app/public/manifest.json#L56) value. In this case, `theme-color` is being used to style the app window [title bar](https://developers.google.com/web/progressive-web-apps/desktop#app-window) and that vivid blue color introduces huge visual inconsistence.
According to Google web app manifest [article](https://developers.google.com/web/updates/2015/08/using-manifest-to-set-sitewide-theme-color),
> If you page already has a theme-color meta tag — for example …
=> Fix duplicate theme-color meta tag

packages/homepage/content/docs/3-deployment.md
Change the wording in 3-deployment.md using a grammar checker.
docs update
Re-read the document with my suggested changes.
- [ x] Documentation
- [ x] Testing  
- [x ] Ready to be merged 
I tried to add myself as a contributor but the local install using the steps from [Contributing to CodeSandbox Client](https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md) failed.
=> use grammar checker

packages/app/src/sandbox/eval/manager.ts, packages/common/src/templates/configuration/index.ts, packages/common/src/templates/configuration/jsconfig/index.ts, packages/common/src/templates/react.ts
Test sandbox: https://pr2296.build.csb.dev/s/github/markerikson/rsk-convert-todos-example/tree/accc5896b5d092e736ec2d24d10246ff18aec7cf
=> Add support for baseUrl in tsconfig/jsconfig for CRA

packages/app/src/app/components/Preview/DevTools/React-Devtools/index.tsx
=> Fix iframe detecting for react devtools if no iframe is loaded or available

packages/app/src/app/index.html
Fixes #2321 .
Swiping two-finger causes chrome to navigate back or forward
Disable the two-finger swipe that causes Chrome going back or forward
=> fix: add overscroll-behavior-x to body tag for app package

packages/app/src/app/pages/Sandbox/Editor/Workspace/Files/DirectoryEntry/index.js, packages/app/src/app/pages/common/Modals/DeleteDeploymentModal/index.js, packages/app/src/app/pages/common/Modals/DeleteProfileSandboxModal/index.js, packages/app/src/app/pages/common/Modals/DeleteSandboxModal/index.js, packages/app/src/app/pages/common/Modals/EmptyTrash/index.js
The `Alert` component does not take a `onDelete` prop, but `onConfirm`
=> Fix wrong prop usage

packages/homepage/content/users.json
We really like working with codesandbox and would be proud to be seen as supporter / testimonial of this online web editor. As an influential website in WordPress and web design, we're happy to push tools we love to work with.
Update to companies using codesandbox. 
N/A
N/A
N/A
N/A
=> We're happy to get listed as a promoter / supporter of codesandbox

packages/homepage/content/users.json
Glad to be using CodeSandbox in our docs and other feature use to generate CodeSandbox link 💯
Link: appbase.io
Github: https://github.com/appbaseio
Tested Locally
=> Add Appbaseio as user

packages/app/src/app/pages/Sandbox/Editor/Workspace/Dependencies/VersionEntry/BundleSizes.tsx, packages/app/src/app/pages/Sandbox/Editor/Workspace/Dependencies/VersionEntry/index.js
=> only call bundlephobia on click

packages/app/src/app/pages/Sandbox/SearchDependencies/DependencyHit/index.js
=> non show description if html or markdown

packages/app/config/webpack.common.js, packages/common/package.json, packages/common/src/templates/configuration/jsonlint.browser.js, packages/common/src/templates/configuration/parse.ts, yarn.lock
It is a reduction in code complexity (hopefully)
We use the `jsonlint` package which requires `file` and `system` based on environment. 
To use `jsonlint` on the browser, we have to declare [`file`, `system`] as "external" for each build process that consumes `common`.
This pull request removes the file system dependencies of `jsonlint` by adding a forked version into our codebase.
@CompuIves Right now, I've created a new file `jsonlint.browser.js` next to the place it's used. Is there a convention for where we drop forked vendor-ish files?
- [NA] Added myself to contributors table
=> Browser compatible jsonlint

packages/common/src/templates/configuration/jsonlint.browser.js
Bug fix
Make `jsonlint.parse` a `function`
- Tested /s/new
- Tested /s/node
- Tested /embed/new
- Tested /embed/node
- [NA] Added myself to contributors table
=> Fix jsonlint arguments bug

packages/app/src/app/overmind/effects/api/index.ts, packages/app/src/app/overmind/namespaces/editor/actions.ts, packages/app/src/app/overmind/namespaces/editor/internalActions.ts, packages/app/src/app/overmind/namespaces/files/actions.ts
Fixes issue with syncing `savedCode` property. We should probably create some abstraction that ensures our database entities are actually populated with values.  `undefined` is a bit of a tricky thing.
=> Fixed saveCode sync

packages/app/src/sandbox/eval/npm/fetch-npm-module.ts
We now support URLs got GitHub as versions as well.
=> Add support for GitHub URLs as versions

packages/app/src/app/index.html, packages/app/src/app/pages/Dashboard/Content/routes/DeletedSandboxes/index.js, packages/app/src/app/pages/Dashboard/Content/routes/PathedSandboxes/index.js, packages/app/src/app/pages/Dashboard/Content/routes/RecentSandboxes/index.js, packages/app/src/app/pages/Dashboard/Content/routes/SearchSandboxes/index.js, packages/app/src/app/pages/Dashboard/Content/routes/TeamView/index.js, packages/app/src/app/pages/Dashboard/Content/routes/Templates/Templates.tsx, packages/app/src/app/pages/Live/index.js, packages/app/src/app/pages/Patron/PricingModal/index.js, packages/app/src/app/pages/Patron/index.js, packages/app/src/app/pages/Profile/index.js, packages/app/src/app/pages/Sandbox/index.js, packages/app/src/app/pages/Search/index.js, packages/app/src/app/pages/common/Modals/PreferencesModal/PaymentInfo/index.tsx
Stripe only loads when the patron page or the payment info tab in the modal is open
Also replaces most instances of document.title with https://github.com/nfl/react-helmet
=> Fixes stripe Loading

packages/app/src/app/overmind/namespaces/editor/actions.ts, packages/app/src/app/overmind/namespaces/editor/state.ts, packages/app/src/app/pages/Sandbox/Editor/index.js, packages/app/src/app/store/modules/editor/index.js, packages/app/src/app/store/modules/editor/model.js, packages/app/src/app/store/modules/editor/sequences.js, packages/app/src/app/vscode/index.ts
This adds ability to toggle the status bar
closes #2150
=> add toggle statusbar

packages/app/src/app/pages/Dashboard/Sidebar/SandboxesItem/FolderEntry/index.tsx, packages/app/src/app/pages/Dashboard/Sidebar/SandboxesItem/folder-drop-target.js, packages/app/src/app/pages/Dashboard/Sidebar/SandboxesItem/index.js, packages/app/src/app/pages/Dashboard/Sidebar/index.js
Fix issue with dashboard. Note to self. Refactor to react beautiful DND instead and consider using the "graphql" effect instead as there is a lot of complexity in the components now. But I might be tired of React DND 😂
=> Fix drag and drop in dashboard

packages/homepage/content/users.json
We use it in our training exercises and for our open source projects: Loadable Components, SVGR, Smooth UI...
=> Add Smooth Code to Codesandbox clients

packages/app/src/app/pages/common/Navigation/index.tsx
I dunno how this got left out, but these fixes notifications. Most likely was there a bug here where new notifications were not indicated, only initial. So this should fix that as well.
=> Fix notifications

packages/app/src/app/overmind/effects/api/index.ts, packages/app/src/app/overmind/namespaces/editor/state.ts, packages/app/src/app/overmind/namespaces/workspace/actions.ts
=> fix templates

packages/app/src/app/overmind/namespaces/preferences/actions.ts, packages/homepage/src/screens/home/NPMFeature/SandboxCount.js
Also includes a typecheck fix. No need to return fragment with single children... can return number, strings etc. from a component
=> Fix storing settings

.circleci/config.yml, packages/app/src/sandbox/eval/npm/fetch-npm-module.ts, packages/app/src/sandbox/eval/transpilers/babel/worker/dynamic-download.ts
The main reason of the download getting stuck was due to our id generation, it was between 0 and 10,0000, which sometimes caused a duplicate id to occur. Now it's sequential.
=> Fix the dynamic downloading of babel getting stuck

packages/app/src/app/custom.d.ts, packages/app/src/app/pages/Dashboard/Sidebar/SandboxesItem/FolderEntry/index.tsx, packages/app/src/app/pages/Dashboard/Sidebar/SandboxesItem/folder-drop-target.js, packages/app/src/app/pages/Sandbox/Editor/Header/index.tsx
Also fixes typing issue with SVG imports
=> Fix nested dashboard and wrong usage of mobx

packages/app/src/app/overmind/factories.ts
Bugfix
When one sandbox is frozen and shows the model to fork or unfreeze if you close the modal run the action
If close the modal is select one option the action is canceled
before:
After:
=> cancel action on close modal

packages/app/src/app/overmind/effects/netlify.ts, packages/app/src/app/pages/common/Modals/NetlifyLogs/index.js
=> Fix claim site on netlify

packages/app/src/app/components/CodeEditor/CodeMirror/index.js
Temporarily "fixes": https://sentry.io/organizations/codesandbox/issues/1161759546/?project=155188&query=is%3Aunresolved&statsPeriod=14d
=> Do nullcheck on textarea for codemirror

packages/app/src/app/pages/Sandbox/Editor/Workspace/Files/DirectoryEntry/Entry/index.js, packages/app/src/app/pages/Sandbox/Editor/Workspace/Files/DirectoryEntry/index.js, packages/app/src/app/pages/Sandbox/Editor/Workspace/elements.js
Bug fix
When renaming a file the validation is not working
Run validation when renaming a file and show error styles
Before: 
After:
=> Validate name when renaming file

packages/app/src/app/overmind/namespaces/editor/actions.ts, packages/app/src/app/pages/Dashboard/Content/SandboxCard/index.tsx, packages/app/src/app/pages/Dashboard/Content/SandboxGrid/index.js
Adds fork to the context menu in the dashboard
only works with one selected
=> add fork to context menu

packages/app/src/app/components/Preview/DevTools/index.tsx
fix, this is another approach to #2593 
#2522
=> fix console height issues

packages/app/src/app/pages/Dashboard/Content/SandboxCard/elements.ts
=> make bg image on dashboard cover

packages/app/src/app/components/HeaderSearchBar/HeaderSearchBar.tsx, packages/app/src/app/overmind/actions.ts, packages/app/src/app/overmind/state.ts, packages/app/src/app/pages/common/Navigation/elements.ts, packages/app/src/app/pages/common/Navigation/index.tsx, packages/app/src/app/pages/common/UserMenu/Menu/elements.ts, packages/app/src/app/pages/common/UserMenu/Menu/index.tsx, packages/app/src/app/pages/common/UserMenu/elements.ts, packages/app/src/app/pages/common/UserMenu/index.tsx
Improve
navigation has a few a11y issues
=> navigation a11y

packages/app/src/app/pages/Dashboard/Content/CreateNewSandbox/NewSandboxModal/NewSandboxModal.tsx, packages/app/src/app/pages/Dashboard/Content/CreateNewSandbox/NewSandboxModal/elements.ts
update
the new sandbox modal has a few accessibilities issues 
use Reakit for tab
=> new sandbox tabs a11y

packages/app/package.json, packages/app/src/app/pages/Sandbox/Editor/Workspace/Project/SandboxConfig/Icon/index.tsx, packages/common/package.json, packages/common/src/components/Template/UserTemplate.tsx, packages/common/src/templates/iconsDark.ts, packages/common/src/templates/iconsLight.ts, standalone-packages/vscode-textmate/package-lock.json, yarn.lock
Updates the package for us to have the light and dark icons too
=> update icons package

packages/app/src/app/pages/Dashboard/Content/routes/DeletedSandboxes/index.js
Bug Fix
Incorrect templates value passed on `FilterOptions` in Delete Sandbox.
Tested Locally
=> fix: filter options for deleted sandboxes

packages/app/src/app/overmind/state.ts, packages/app/src/app/pages/Sandbox/Editor/Workspace/items/GitHub/GitHub.tsx
Bugfix
#2674 
Don't crash when open Github integration without login
=> GitHub integration prevent crash

packages/homepage/gatsby-browser.js, packages/homepage/gatsby-config.js, packages/homepage/src/components/Companies.js, packages/homepage/src/html.js, packages/homepage/src/screens/home/NPMFeature/EmbedAnimation/index.js, packages/homepage/src/screens/home/NPMFeature/SearchInput/index.js, packages/homepage/src/screens/home/Patron/index.js
improves
Searchdoc and fonts are blocking render
load search doc async
swap fonts 
use native lazy loading (chrome)
=> Improve performance home page

packages/app/src/app/overmind/namespaces/editor/state.ts, packages/app/src/app/overmind/namespaces/server/actions.ts, packages/app/src/app/overmind/utils/server.ts
bugfix
#2583 
you can open a new main port tab but you can't close it
1. Open container sandbox
2. Open main port tab
=> fix prevent open new main ports

.all-contributorsrc, README.md, packages/app/src/app/pages/NewSandbox/index.tsx
@Saeris @christianalfoni @SaraVieira
/app/pages/NewSandbox/index.js was using inject and hooksObserver from app/componentConnectors and written in JS.
uses useOvermind hook from app/overmind and converted to tsx.
1. Step A
2. Step B
3. Step C
=> 🔨Refactored 🧠 Overmind Hacktober | /app/pages/NewSandbox/index.js : refactor to replace Cerebral with Overmind

packages/app/src/app/pages/common/Modals/PreferencesModal/index.tsx
@Saeris @christianalfoni @SaraVieira
/app/pages/common/Modals/PreferencesModal/index.js was using inject and hooksObserver from app/componentConnectors and written in JS.
uses useOvermind hook from app/overmind and converted to tsx.
1. Step A
2. Step B
3. Step C
=> 🔨Refactored 🧠 Overmind Hacktober | /app/pages/common/Modals/PreferencesModal/index.js : refactor to replace Cerebral with Overmind 

packages/app/src/app/vscode/index.ts
So I’ve always dreamt of having just browser installed and code everything inside of it. But something was always stopping me from doing so. Lack of a good IDE, slow response, etc. I was really happy to see CodeSandbox implement VSCode and even more happy to see how snappy it is! But still, I was sometimes frustrated when I forgot I was using a browser-based IDE and that the system shortcuts don’t work. My primary cause of headaches was always hitting <kbd>⌘+W</kbd> 🙄. Never got used to it. And it looks like I’m [not](https://github.com/codesandbox/codesandbox-client/issues/1044) [the](https://github.com/codesandbox/codesandbox-client/issues/1997) [only](https://github.com/codesandbox/codesandbox-client/issues/2089) [one](https://github.com/codesandbox/codesandbox-client/issues/2107).
So …
=> Add support for native keyboard shortcuts in fullscreen

packages/common/src/components/Preview/index.tsx, yarn.lock
Sorry for multiple commits, I am new to open source. I will squash the commits together soon.
I have done changes as suggested by Ives here,
https://github.com/codesandbox/codesandbox-client/issues/2626#issuecomment-538369269
This is a bug fix for #2626
Console isn't cleared when we switch codesandboxes in the same folder.
#2626 
I cannot test it, I have added a comment on the issue #2626 
https://github.com/codesandbox/codesandbox-client/issues/2626#issuecomment-538453122
N/A - [ ] Documentation
I want to continue further discussions at this PR.
Thanks, @CompuIves for giving me the opportunity to contribute.
🍪 Here's a cookie for you 😉
=> Clear Console after opening a new Sandbox in the same folder.

packages/app/src/app/pages/common/Modals/PreferencesModal/index.tsx
=> Fix empty items in preferences modal

packages/app/src/app/pages/common/Modals/EmptyTrash/index.tsx, packages/app/src/app/pages/common/Modals/index.js
=> 🔨 Switch EmptyTrash to use useOvermind

packages/app/src/app/pages/common/Modals/DeleteDeploymentModal/index.tsx, packages/app/src/app/pages/common/Modals/index.js
=> 🔨 Switch DeleteDeploymentModal to use useOvermind

packages/app/src/app/pages/Sandbox/Editor/Workspace/Files/DirectoryEntry/DirectoryChildren/ModuleEntry.js, packages/app/src/app/pages/Sandbox/Editor/Workspace/Files/DirectoryEntry/DirectoryChildren/index.js, packages/app/src/app/pages/Sandbox/Editor/Workspace/Files/DirectoryEntry/index.js, packages/app/src/app/pages/Sandbox/Editor/Workspace/Files/DirectoryEntry/validateTitle.js, packages/common/src/sandbox/modules.ts
Fix
You can create a file with a name that already exist but you'll get an error
Validate if already exist a folder/file with the same name
Validate if name includes `/` or `\`
1. Try to rename a folder or file, name it with a name that already exist
2. Try to create a new folder or file, name it with a name that already exist
3. In the above cases you'll get an error
=> Validate if a folder/file already exist

packages/homepage/src/css/global.css, packages/homepage/src/hooks/index.js, packages/homepage/src/hooks/useInterval.js, packages/homepage/src/hooks/useMatchMedia.js, packages/homepage/src/screens/home/Animation/index.js, packages/homepage/src/screens/home/CycleFeature/index.js, packages/homepage/src/screens/home/NPMFeature/SearchInput/Hit.js, packages/homepage/src/screens/home/NPMFeature/index.js, packages/homepage/src/screens/home/Patron/index.js
fix
when user select `reduce motion` in the SO, we don't disable the animations
Disable animations if user preferences is set to reduce motion,
https://developers.google.com/web/updates/2019/03/prefers-reduced-motion
1. Open homepage
2. Disable animations
3. All animations are hidden
=> Hide animations on prefers-reduced-motion

packages/app/src/app/pages/Sandbox/QuickActions/index.tsx
=> fix quick actions

.all-contributorsrc, README.md, package.json, yarn.lock
Bug fix: updates `all-contributors` from `6.9.1` to `6.9.2`
`yarn contributors:add` throws an error `is/are invalid contribution type(s)`.
The issue is described [here](https://github.com/all-contributors/all-contributors-cli/issues/209).
`yarn contributors:add` works properly.
1. `yarn lint`
2. `yarn test`
3. `yarn contributors:add`
=> update broken all-contributors to 6.9.2

packages/app/src/app/pages/Dashboard/Sidebar/SandboxesItem/index.js
Fixed type error reported in #2792
@Saeris @CompuIves
No safe check for undefined data.me
Added a safe-check for the same
1. Step A
2. Step B
3. Step C
=> fix #2792: added safe-check for undefined data.me

packages/app/src/sandbox/eval/transpilers/babel/worker/evaluate.js
Fixes: https://codesandbox.io/s/react-hooks-22c9h
=> Fix babel preval incompatabilities in setting cwd

packages/app/src/app/overmind/effects/live/index.ts, packages/app/src/app/overmind/namespaces/live/liveMessageOperators.ts, packages/common/src/types/index.ts
Now you stay as an owner when you reconnect, and we detect the disconncet state more easily.
=> Make the reconnect action of live more robust

.circleci/config.yml, packages/app/integration-tests/browser-tests/browsers.test.js, packages/app/scripts/deploy.js, packages/app/scripts/sentry-create-release.js, packages/app/src/app/index.js, packages/common/src/utils/analytics.ts
=> Add deployment option to CI workflow

packages/app/src/app/pages/Sandbox/Editor/Workspace/Project/Project.tsx
This enables the option to make servers private! @lbogdan
=> Allow server private

packages/app/src/app/pages/Dashboard/Content/CreateNewSandbox/NewSandboxModal/Imports/GitHubImport.tsx
Improve
- Currently on pressing enter on Input on Import tab. It doesnt redirect to the CodeSandbox.
- On pressing enter it now redirects to the app.
1. Added invalid URL and checked
2. Tested with correct URL
=> feat: redirect import url on pressing enter

packages/app/src/app/pages/Dashboard/Content/routes/Templates/Templates.tsx
Spacing Issue Fix
Minor spacing issue
Fixed
1. Tested the page locally
=> fix: spacing issue

packages/homepage/content/docs/3-deployment.md
Fixes up a typo in Netlify and a few other tweaks.
=> Fix typo in 3-deployment.md

packages/app/src/app/pages/common/Modals/FeedbackModal/Feedback.tsx
Improvement
You can submit spaces to the form
Disable button unless there is a valid message in feedback input
Locally tested by submitting the form.
=> fix: submitting spaces to feedback form

packages/app/src/app/pages/Dashboard/Sidebar/SandboxesItem/FolderEntry/index.tsx
Bug Fix
When we rename a folder in Dashboard Sandboxes, it doesn't update the route. 
Update the route when the folder is renamed
1. Tested on local check the above GIF for more details
I was seeing a `TypeScript` error on `DropFolderEntry`  and I am not sure how to fix that. May be CI pipeline will fail for that. 
Any help is appreciated on this!
=> fix: renaming folder in sidebar doesnt update Route

packages/app/src/embed/components/Sidebar/ExternalResources/elements.js
Minor Style Fix
1. Locally Tested
=> fix(embed): external resources styles

packages/app/src/app/components/Preview/DevTools/Terminal/Shell/Term.tsx, packages/app/src/app/components/Preview/DevTools/Terminal/Shell/index.tsx, packages/app/src/app/components/Preview/DevTools/Terminal/index.tsx
When trying to input in the main terminal you now get this:
=> Add notice about main terminal

packages/app/src/embed/components/Sidebar/ExternalResources/index.js
Enhancement
Currently, in embed external dependencies, we show full URL link of Google Font
Parse to show the family name
1. Locally tested
=> feat(embed): parse google font external deps

README.md
sorry, had to do it
border-radius: 3000
=> PR #3000 New readme banner

packages/app/package.json, packages/app/src/app/overmind/effects/git/export-to-github.ts, packages/app/src/app/overmind/effects/zip/create-zip/create-react-app-typescript/index.ts, packages/app/src/app/overmind/effects/zip/create-zip/full/index.ts, packages/app/src/app/overmind/effects/zip/create-zip/index.ts, packages/app/src/app/overmind/effects/zip/create-zip/vue-cli/index.ts, yarn.lock
fix
#323 
1. Create a sandbox or fork https://pr3003.build.csb.dev/s/falling-sun-uth2m
2. Add `.gitignore`
3. Create a repositorio from sandbox
=> Fix honoured gitignore

packages/common/src/global.css
@DannyRuchtie Test the PR link once available 😄
=> Default to subpixel anti-aliasing for non-retina screens

packages/app/src/app/components/Preview/DevTools/Console/index.tsx, packages/app/src/app/components/Preview/DevTools/Tabs/Tab/UnreadDevToolsCount.tsx, packages/common/src/components/Button/elements.ts
Theme Fix
For the light themes, the count on devtools is not visible and the secondary button mismatch the theme color. The first console message is not visible in light theme.
Check the screenshot below:
Buttons on Light theme: 
Buttons on Dark theme:
Button on Hover on Dark theme:
Devtools on light theme:
First Console Message not visible:
Buttons on light theme:
Button hover on light theme:
Devtools on light theme:
Console Message on light theme:
1. Visual Testing on most of the themes
Thoughts on adding support of this color over here:
- On hover of any file
- Link color, currently links are not having proper contrast with the background in Light theme
=> fix(theme): theme fixes in secondary button & devtools

packages/app/src/app/pages/Sandbox/Editor/Workspace/Dependencies/VersionEntry/index.tsx, packages/app/src/embed/components/Sidebar/Dependencies/index.js, packages/common/src/utils/ci.ts
Enhancement
Embed shows full version URL for CSB CI package
Parse the package name like in-app
1. Tested both app and embed
=> fix(embed): parse csb package version number

packages/app/src/sandbox/status-screen/loading-screen.html, packages/app/src/sandbox/status-screen/run-on-click-screen.html, packages/common/src/components/RunOnClick/elements.js, packages/common/src/components/RunOnClick/index.tsx
Goes well with https://github.com/codesandbox/codesandbox-client/pull/2941
I'd really like if someone can test this @CompuIves
=> Emo loading screens

packages/app/src/embed/components/App/index.js
just removed some logic that forces runonclick on mobile
=> Embed: Don't force run on click on mobile

packages/app/src/app/pages/Dashboard/Content/CreateNewSandbox/index.tsx
Bug Fix
When we visit a nested route for sandboxes like `/dashboard/sandboxes/${NAME}` it breaks the UI. This check is missing: https://github.com/codesandbox/codesandbox-client/commit/c000f60f77d96b15eb52af7d25bf3862334559c4#diff-49445e53b61b882865073a56f962aee4L114
Added the check
1. Tested Locally
=> fix: add undefined check for mostUsedTemplates

testpr-script.js
Also delete the existing test branch, as you want to start fresh
=> delete existing branch

packages/app/src/app/pages/Sandbox/Editor/Header/Buttons/RefreshButton/UpdateFound/UpdateFound.tsx, packages/app/src/app/pages/Sandbox/Editor/Navigation/Navigation.tsx, packages/app/src/app/pages/Sandbox/Editor/Workspace/Dependencies/VersionEntry/index.tsx, packages/app/src/app/pages/Sandbox/Editor/Workspace/Files/DirectoryEntry/Entry/EditIcons/index.js, packages/common/__mocks__/styleMock.js, packages/common/package.json, packages/common/src/components/Tooltip/index.tsx, yarn.lock
Improves UX of tooltips and fixes overlapping issues. `updateDuration` (position update transition) can be changed to a more suitable value if need be
See #3059 
See #3059 
Unfortunately it seems like importing CSS files in `Tooltip/index.tsx` is breaking Jest. Any help on this? 
```bash
yarn test
yarn lint
```
=> fix(Tooltip): fix overlapping and use tippy singletons where applicable

packages/app/src/app/components/CreateNewSandbox/MostUsedSandbox/elements.ts, packages/app/src/app/components/CreateNewSandbox/MostUsedSandbox/index.tsx, packages/app/src/app/components/CreateNewSandbox/elements.ts, packages/app/src/app/components/CreateNewSandbox/index.tsx
=> Extract MostUsedSandbox from CreateNewSandbox

packages/app/src/app/pages/Sandbox/Editor/Header/Header.tsx, packages/app/src/app/pages/Sandbox/Editor/Header/SandboxName/SandboxName.tsx, packages/app/src/app/pages/Sandbox/Editor/Header/SandboxName/elements.ts, packages/app/src/app/pages/Sandbox/Editor/Navigation/Navigation.tsx, packages/app/src/app/pages/Sandbox/Editor/Navigation/elements.ts
fix
- sandbox name use a not focusable element (trigger rename)
- you can't reach sandbox navigation with the keyboard
- if your owner, sandbox name use a button (without button styles, and outline) 
- Navigation sandbox uses a `nav` element, and each item is a `button`
1. Enter sandbox
2. Reach navigation with keyboard
=> Sandbox navigation a11y

packages/app/src/app/pages/Sandbox/Editor/Workspace/Files/DirectoryEntry/DirectoryChildren/index.tsx
@Saeris  @christianalfoni
package /app/pages/Sandbox/Editor/Workspace/Files/DirectoryEntry/DirectoryChildren/index.js was using Cerebral
packages /app/pages/Sandbox/Editor/Workspace/Files/DirectoryEntry/DirectoryChildren/index.tsx is using Overmind
1. yarn test
2. yarn lint
3. yarn typecheck
=> 🔨 Refactor, 🧠 Overmind Hactoberfest | Refactor /app/pages/Sandbox/Editor/Workspace/Files/DirectoryEntry/DirectoryChildren/index.js  to use Overmind

packages/common/src/utils/analytics/amplitude.ts
Only load amplitude messages once it's loaded or if the timeout exceeded.
=> Amplitude first messages

packages/app/src/app/pages/common/Stats/index.tsx
The stats component showing views and forks. Tested it by turning on and off like. Should be good 😄
=> StatsComponent: refactor to overmind

packages/app/src/app/components/DeploymentIntegration/DeploymentIntegration.tsx, packages/app/src/app/pages/Sandbox/Editor/Workspace/items/Deployment/Netlify/DeployButton/DeployButton.tsx, packages/app/src/app/pages/Sandbox/Editor/Workspace/items/GitHub/Git/Git.tsx
=> remove beta notices from git and netlify

packages/common/src/components/SandboxCard/elements.ts
=> Fix Dashboard truncate description

packages/app/src/app/pages/Sandbox/Editor/Workspace/Files/DirectoryEntry/DirectoryChildren/index.tsx, packages/app/src/app/pages/Sandbox/Editor/Workspace/Files/DirectoryEntry/index.js, packages/app/src/app/pages/Sandbox/Editor/Workspace/Files/index.tsx
Refactor `packages/app/src/app/pages/Sandbox/Editor/Workspace/Files/DirectoryEntry/index.js`
As a request from @christianalfoni only app connectors were removed as this file is bound for further UX improvements next sprint
=> refactor DirectoryEntry

standalone-packages/sse-loading-screen/package.json, standalone-packages/sse-loading-screen/src/index.css, standalone-packages/sse-loading-screen/src/index.js, standalone-packages/sse-loading-screen/yarn.lock
This is already used in the SSE manager in production, so I guess we can just merge it.
=> SSE loading screen updates

packages/app/src/app/pages/Sandbox/Editor/Header/PrivacyTooltip/index.tsx
Tested to confirm that this works, it works!
=> Only track opening the tooltip when it actually opens

packages/app/package.json, yarn.lock
Resubmission of #2477 since all fix PRs are merged (https://github.com/codesandbox/codesandbox-client/pull/2477#issuecomment-564778033) 🙂
Closes #2435
Closes #3053
=> Use console-feed upstream again

packages/app/src/app/pages/common/Modals/LiveSessionEnded/elements.js, packages/app/src/app/pages/common/Modals/LiveSessionEnded/elements.ts, packages/app/src/app/pages/common/Modals/LiveSessionEnded/index.tsx
=> 🔨 Switch LiveSessionEnded to use useOvermind

packages/app/src/app/components/Preview/DevTools/Tabs/Tab/elements.ts, packages/common/src/components/Preview/AddressBar/elements.ts, packages/common/src/components/Preview/Navigator/elements.ts
=> fork of sara's PR

packages/homepage/content/features/devrel/index.md
Replaces a quote tweet from a user which has removed their Twitter account
Broken twitter avatar
Fixed twitter avatar and new quote
Preview LGTM https://pr3276.build.csb.dev/devrel
=> Updating removed quote tweet

.circleci/config.yml, packages/components/package.json, yarn.lock
Because we use squash and merge, our snapshots are regenerated and the diff says everything is new.
To make this work, we can auto-accept snapshots from master to mark them as baseline
Docs: https://docs.chromaticqa.com/setup_ci#maintain-a-clean-master-branch
=> Chromatic: auto accept changes for master

standalone-packages/codesandbox-browserfs/src/generic/setImmediate.ts
It fixes the bug described in #2368, in which the `setImmediate` API of CodeSandbox does not correspond to the API it mimics from Node.js.
#2368: Calls such as `setImmediate(fn, a, b)` will fail to pass the arguments `a` and `b` to `fn`, even though [the Node.js API says they must](https://nodejs.org/api/timers.html#timers_setimmediate_callback_args).
Calls such as `setImmediate(fn, a, b)` will pass the arguments `a` and `b` to `fn`, in accordance with [the Node.js API](https://nodejs.org/api/timers.html#timers_setimmediate_callback_args).
- Unfortunately, there do not seem to be any existing unit tests for this behavior.
However, this particular PR receives quite some support from the TypeScript typings.
- It works in Chrome and Firefox.
=> Fix setImmediate parameters (#2368)

packages/app/src/sandbox/eval/presets/angular-cli/index.js, packages/app/src/sandbox/eval/transpiled-module.ts
=> Fix loading angular resources from node_modules

packages/app/src/app/overmind/namespaces/files/actions.ts
We only updated the container on code change, now we also do it for file/dir moving/creating/removing
Fixes #3341
=> Update SSE on file/dir changes

package.json, packages/app/scripts/start.js, packages/app/src/app/pages/DevAuth/index.tsx, packages/app/src/app/utils/executor-manager.ts, packages/common/src/components/Preview/index.tsx, packages/common/src/config/env.ts, packages/executors/src/executor.ts, packages/executors/src/serverExecutor.ts
This PR changes stream to default API. This is just for dev purposes, the goal is to make this switchable with a flag, but we need to make some more changes before that will be possible.
=> Add stream option flag

packages/app/src/app/overmind/utils/items.ts, packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/ProjectInfo/Config.tsx, packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/ProjectInfo/Privacy.tsx, packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/ProjectInfo/TemplateConfig.tsx, packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/ProjectInfo/index.tsx, packages/components/src/components/Select/index.tsx
Also fixes the `css` prop yay!
=> Adds Create and Edit Template to new sidebar

.drone.yml, packages/app/src/sandbox/startup.js, packages/app/src/sandbox/utils/metrics.ts, packages/common/src/utils/analytics/utils.ts, packages/sandbox-hooks/url-listeners.js, packages/sse-hooks/index.js, packages/sse-hooks/package.json
In `app` we were only checking for `!window.opener`, which is not enough, while in `sse-hooks` we weren't checking at all.
=> Fix checking if preview is standalone

packages/app/src/app/overmind/namespaces/workspace/actions.ts
Bug
We can pass empty spaces while editing title and description in sandbox info
Avoid update if empty spaces are only present
1. Go to sandbox info
2. Click edit icon
3. Put empty spaces only on input and press enter or remove focus from input
=> fix: avoid empty spaces on title & description

packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Deployment/Netlify.tsx, packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Deployment/NotLoggedIn.tsx, packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Deployment/NotOwner.tsx, packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Deployment/Zeit.tsx, packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Deployment/index.tsx, packages/components/src/components/Integration/index.stories.tsx, packages/components/src/components/Integration/index.tsx
Polished the design for deployments.
Missing pieces:
1. Danny will come back with changes for the default state which looks inconsistent
2. (for the last 5%) we can improve how multiple deployments look.
=> Sidebar: Polish deployments

packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Explorer/index.tsx
=> Sidebar -  remove old files from new design

packages/app/src/app/overmind/namespaces/files/internalActions.ts
=> Fix uploading empty files

packages/app/src/app/pages/Sandbox/Editor/Workspace/Dependencies/VersionEntry/index.tsx
=> Fix dependency version select

.all-contributorsrc, README.md, packages/app/src/app/components/ContextMenu/index.tsx, standalone-packages/vscode-textmate/package-lock.json
Bug fix
Fix for https://github.com/codesandbox/codesandbox-client/issues/3274
The ContextMenu opens to the left and not to the button when the window height is too small. 
1. yarn test
This is my first contribution to codesandbox so it is very hard for me to see what kind of unexpected and unintended effects my tiny change might have ;-) Before merging it would be nice to know in what other places the ContextMenu component is used and test if it still behaves as expected...
=> Fix: ContextMenu cutoff on dashboard

packages/components/.storybook/config.tsx
Make stories skinnier so that we have better diffs to look at.
this no good:
=> make stories smaller

packages/app/src/app/overmind/internalActions.ts
=> Fix checking for an undefined response

packages/components/src/components/Collapsible/index.tsx, packages/components/src/components/Link/index.tsx, packages/components/src/components/Stats/index.tsx, packages/components/src/examples/sandbox-info.stories.tsx
=> Sidebar - tiny design tweaks for themeing

packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/ConfigurationFiles/index.tsx, packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Explorer/Files/DirectoryEntry/Entry/FileInput.tsx, packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Live/LiveNow.tsx, packages/app/src/app/pages/Sandbox/Editor/index.tsx, packages/components/src/components/List/index.tsx
yay? closer to the edge OF GLORY
=> more design fixes

packages/app/src/sandbox/eval/transpilers/babel/convert-esmodule/__snapshots__/index.test.ts.snap, packages/app/src/sandbox/eval/transpilers/babel/convert-esmodule/index.ts
Potentially fixes #3448.
We need to check if this breaks anything else.
=> Move esmodule export to be after the declaration

packages/app/src/app/pages/Sandbox/Editor/index.tsx
=> Fixes 3449, Min width based on visibility

packages/components/src/components/Avatar/index.tsx
=> pro badge should merge into background

packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/ProjectInfo/Config.tsx, packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/ProjectInfo/Delete.tsx, packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/ProjectInfo/index.tsx
=> Sidebar - fix position of delete button

packages/app/src/app/overmind/utils/items.ts, packages/app/src/app/pages/Sandbox/Editor/Workspace/Chat/index.tsx, packages/app/src/app/pages/Sandbox/Editor/Workspace/ChatOld/index.tsx, packages/app/src/app/pages/Sandbox/Editor/Workspace/index.tsx, packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Explorer/Files/DirectoryEntry/index.tsx
New design for the chat, much pretty
=> Adds new chat

packages/common/src/design-language/typography.ts
chromatic build should make this easier
=> bump fontsize 11 to 12!

packages/app/src/app/pages/Dashboard/elements.ts, packages/app/src/app/pages/Dashboard/index.tsx, packages/app/src/app/pages/index.tsx
Follow-up of #2833 & #2914
Things  I did extra:
- Make `DashboardComponent` a `FunctionComponent`
- Inline `DashboardContent`
- Export `Dashboard` by a named export  instead of a `default export`
=> 🔨 Switch Dashboard to use useOvermind

.imgbotconfig
=> Update imgbot config

packages/components/src/components/Textarea/index.tsx
Deleted a bunch of code, now it works :D
Did you know textarea supports a maxlength html attribute!?!
=> Fix textarea max length bug

packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Live/LiveNow.tsx, packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/ProjectInfo/Summary.tsx, packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Server/EnvVars.tsx, packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Server/VarForm.tsx
Fixes: 
12. Server secret: button should be disabled without values + clicking button doesnt send @Sara Vieira 
13. Server secret: Space between description and keys should be 16px @Sara Vieira
9. Live doesn't show reconnecting status. @Sara Vieira
=> Env Variable Fixes

packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Explorer/ExternalResources/index.tsx
1. Removed the extra space in external deps caused by an empty list
2. I broke font addition earlier, fixed it now. Checked all the other forms, they work 👍
=> Fixes in external deps

packages/homepage/src/pages/ide/_tweets.js, packages/homepage/src/pages/ide/index.js
Added fallback for broken avatar.io image
Broken image
Fallback to a default image
1. Step A
2. Step B
3. Step C
Seems like @EmmaWedekind's account is suspended for some reason thats why avatars.io is failing to fetch the image
Fallback img url: https://avatars.io/static/default_128.jpg
=> Fix: Added fallback for avatar.io failing image

packages/app/package.json, packages/app/src/app/pages/Sandbox/Editor/Header/Actions.tsx, packages/common/src/themes/codesandbox-black.js, packages/components/src/components/Button/index.tsx, packages/components/src/components/Select/index.stories.tsx, packages/components/src/components/Select/index.tsx
=> Feedback for system and header

packages/app/src/app/pages/Sandbox/Editor/Workspace/items/GitHub/Git/Git.tsx, packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/GitHub/CommitForm.tsx
=> Fix GitHub commit

packages/common/src/templates/configuration/now/index.ts
=> update the configuration of zeit copy

packages/app/src/app/overmind/namespaces/preferences/actions.ts, packages/app/src/app/pages/Sandbox/Editor/Navigation/elements.ts, packages/app/src/app/pages/common/Modals/PreferencesModal/Experiments/ContainerLSP.tsx, packages/app/src/app/pages/common/Modals/PreferencesModal/Experiments/index.tsx, packages/components/src/utils/polyfill-theme.ts
changes in polyfill settings:
1. File tree and other lists in sidebar ensure list.hover and list.background (sidebar.background) are different colors by falling back to list.inactiveSelectionBackground
2. Activity bar: ensure enough contrast between selected foreground and inactive foreground
=> Sidebar enhacements

packages/app/src/app/overmind/effects/vscode/index.ts, packages/app/src/app/overmind/namespaces/editor/actions.ts, packages/app/src/app/pages/common/Modals/PreferencesModal/Experiments/ContainerLSP.tsx, packages/app/src/app/pages/common/Modals/PreferencesModal/Experiments/NewSidebar.tsx, packages/common/src/types/index.ts, packages/common/src/utils/feature-flags.js, packages/common/src/utils/feature-flags.ts
Fixes https://github.com/codesandbox/codesandbox-client/pull/3571#pullrequestreview-363563732
=> Use feature flags instead of accessing localStorage directly

packages/app/src/app/pages/common/Modals/PreferencesModal/Experiments/ContainerLSP.tsx
with the implementation in #3577 if the user is logged out the experiments tab breaks
=> fix experiments tab when logged out

packages/common/src/themes/codesandbox-black.js, packages/components/src/utils/polyfill-theme.ts
clone the theme in polyfill to make sure we don't overwrite the global object!
=> Fix bug in polyfill + change terminal color

packages/common/src/themes/codesandbox-black.js, packages/components/src/utils/polyfill-theme.ts
Reverts codesandbox/codesandbox-client#3579
This created more bugs than it fixed!!
chromatic tried to help, but i didn't see :(
=> Revert "Fix bug in polyfill + change terminal color"

packages/app/src/app/components/CreateNewSandbox/CreateSandbox/Import/elements.ts
=> fix input in new sandbox

packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Explorer/Files/DirectoryEntry/Entry/FileInput.tsx, packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Explorer/Files/DirectoryEntry/Entry/index.tsx, packages/common/src/themes/codesandbox-black.js, packages/components/src/components/Collapsible/index.tsx
=> Sidebar feedback 999

packages/components/package.json, packages/components/src/components/Element/index.tsx, packages/components/src/components/Menu/index.tsx, packages/components/src/components/Menu/menu.stories.tsx, packages/components/src/utils/polyfill-theme.ts
new component, who dis
we will use this in comments and access sheet
the tests are kinda useless because the menu is closed 😄 will find ways to improve in another PR
=> Add menu component

packages/components/src/components/Menu/index.tsx, packages/components/src/index.ts
data-component are selectors too
=> Menu app styles which work with global styles

.all-contributorsrc
=> Update contributor Josh Waller profile url

packages/app/src/app/pages/Sandbox/Editor/Workspace/Project/BookmarkTemplateButton/BookmarkTemplateButton.tsx, packages/app/src/app/pages/Sandbox/Editor/Workspace/index.tsx, packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/GitHub/CommitForm.tsx, packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/GitHub/CreateRepo.tsx, packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/NotOwnedSandboxInfo/BookmarkTemplateButton/index.tsx, packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/NotOwnedSandboxInfo/Summary.tsx, packages/components/src/components/Icon/icons.tsx, packages/components/src/components/Menu/index.tsx, packages/components/src/index.ts
=> Sidebar bugs + ad

packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Comments/index.tsx, packages/components/src/components/Collapsible/index.tsx
=> fix alignment on collapsible

packages/app/src/app/pages/Dashboard/Content/Sandboxes/utils.ts
Bug Fix
1. Delete 2-3 sandboxes permanently
=> fix(trash): accessing from undefined on permanent deleting

packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Explorer/Dependencies/Dependency/index.tsx
remove hovering on mouse over for browser hover :)
reported here: https://twitter.com/ful1e5_/status/1235436048148094976
=> Fix dependency dropdown for firefox

packages/app/src/app/overmind/effects/fakeGql/comments/mutations.ts, packages/app/src/app/overmind/effects/fakeGql/comments/queries.ts, packages/app/src/app/overmind/effects/fakeGql/comments/types.ts
This PR adds types to the GraphQL mutations and also adds the metadata field we will need for the next work
=> add types for mutations

packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Explorer/Dependencies/Dependency/BundleSizes.tsx, packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Explorer/Dependencies/Dependency/index.tsx
This PR solves two things:
* Unable to click on a dependency name
* Wrong value in the select
Also hookify the code
=> Fix small dependency bugs

packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/GitHub/index.tsx
Adds Github Link in the sidebar
=> Fix Github Link

packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Live/LiveNow.tsx
=> Fix live input

packages/app/src/app/overmind/effects/fakeGql/comments/mutations.ts, packages/app/src/app/overmind/effects/fakeGql/comments/types.ts, packages/app/src/app/overmind/namespaces/editor/actions.ts
=> add mutations and actions for replies

packages/app/src/app/pages/common/UserMenu/index.tsx
Fixes issue with logging out as user is not there anymore
Typecheck issue unrelated to this
=> fix bug with error logging out

packages/app/src/app/overmind/namespaces/editor/actions.ts
=> Fix typecheck error

packages/app/src/app/overmind/namespaces/editor/actions.ts
Fix the bug that showed up in the demo welp
=> fix demo bug

packages/app/src/app/overmind/namespaces/editor/actions.ts, packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Comments/AddComment.tsx, packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Comments/Comment.tsx, packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Comments/Dialog/Comment.tsx, packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Comments/Dialog/Reply.tsx, packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Comments/Dialog/index.tsx, packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Comments/index.tsx, packages/components/src/components/Element/index.tsx, packages/components/src/components/Link/index.tsx
Bunch of spacing fixes, more to come
=> UI improvements for comments

packages/components/src/components/IconButton/index.tsx, packages/components/src/components/Menu/index.tsx, packages/components/src/components/Menu/menu.stories.tsx
It's the start of motion in components
=> Add open transition to menu

packages/components/package.json, packages/components/src/components/IconButton/iconbutton.stories.tsx, packages/components/src/components/IconButton/index.tsx, packages/components/src/components/Menu/index.tsx, packages/components/src/components/Tooltip/index.tsx, packages/components/src/components/Tooltip/tooltip.stories.tsx, yarn.lock
this is not a component my friends, this is a song
Read the source for a the story
=> Tooltip component

packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Explorer/ExternalResources/index.tsx
Enhancement
We can add empty/blank resource & font
Throws default warning because of required attribute
- Locally by just clicking Add resource with blank input. Same for font.
- Documentation - N/A
=> feat: add required attribute to font & resource

packages/app/src/app/overmind/namespaces/workspace/actions.ts
Fixes issue with trying to delete templates
=> fix issue with deleting template

packages/sandbox-hooks/preview-secret.js
=> Explicitly set Same-Site:None on preview secret cookies

packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/CommentThreads/Dialog/index.tsx, packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/CommentThreads/Dialog/use-scroll-top.tsx, packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/CommentThreads/index.tsx
I've started polishing, here's v1/200 :)
sidebar:
dialog:
=> Comments polish 1

packages/components/src/components/Textarea/index.stories.tsx, packages/components/src/components/Textarea/index.tsx
Rewrote the textarea to allow controlled textarea with autosizing
Clearing the value will now resize textarea
=> Contolled autosizing textarea

packages/app/src/app/pages/Sandbox/Editor/Skeleton/elements.ts, packages/app/src/app/pages/Sandbox/Editor/Skeleton/index.tsx
=> Enhancements to skeleton

packages/app/src/sandbox/eval/npm/fetch-npm-module.ts
Fixes #3727
When a dependency uses a npm alias, the package is not resolved.
When a dependency uses a npm alias, the package is resolved.
1. Create a new React sandbox
1. Edit the `package.json`
1. Add a package with an npm alias to the dependencies.
```diff
"dependencies": {
"react": "16.12.0",
"react-dom": "16.12.0",
"react-scripts": "3.0.1",
+   "carbon-react": "https://pkg.csb.dev/jamime/carbon/commit/60c9c3e8/carbon-react"
},
```
=> feat: add support for npm alias in subdependencies

packages/homepage/content/docs/6-templates.md
docs update - fixed a typo. Changed 'setup' to 'set up'
setup = noun
set up = verb phrase
=> Change setup to set up

packages/app/src/app/pages/Sandbox/Editor/Content/index.tsx, packages/common/src/utils/keycodes.ts, standalone-packages/vscode-textmate/package-lock.json
feat #2813
No shortcut available for opening or closing the `console` like in `vscode`
Added shortcut to toggle console `ctrl + Backtick`
The testing was done visually.
1. Open the a new sandbox `http://localhost:3000/s/new`
2. Press `ctrl + Backtick` which will open the console.
3. And on again pressing `ctrl + Backtick` will close the console.
=> feat(shortcut): add shortcut for console

packages/app/src/app/overmind/namespaces/comments/actions.ts, packages/app/src/app/overmind/namespaces/editor/internalActions.ts, packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Comments/AddComment.tsx, packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Comments/Dialog/Code.tsx, packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Comments/Dialog/index.tsx
- Delete comment not working @Sara Vieira 
- Unable to delete reply @Sara Vieira 
- Order of contextmenu (delete always last)  @Sara Vieira 
-  Don't allow empty comments (validate input field submit) @Sara Vieira
=> fix comment delete

packages/app/config/webpack.common.js, packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Comments/Dialog/index.tsx
Fix the colors, height needs more work
=> Dialog - textarea colors, not height yet

packages/app/src/app/overmind/namespaces/comments/state.ts, packages/common/src/types/index.ts
=> fix filters

packages/app/src/app/overmind/namespaces/comments/actions.ts, packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Comments/components/MultiComment.tsx
=> Add Ability to close the multi comment selector

packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Comments/AddComment.tsx, packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Comments/Dialog/Reply.tsx, packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Comments/Dialog/index.tsx
=> Comments polish - Day 1, v2

packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Comments/AddComment.tsx, packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Comments/Dialog/index.tsx, packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Comments/components/MultiComment.tsx
=> Polish v1234

packages/app/src/app/pages/Sandbox/Editor/Navigation/icons.tsx
=> update comments icon

packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Comments/Dialog/Code.tsx
=> check if value before rendering prism

packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Comments/Dialog/Markdown.tsx
=> style forbidden images and add modal

packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Comments/AddComment.tsx, packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Comments/Dialog/index.tsx, packages/components/src/components/Textarea/index.stories.tsx, packages/components/src/components/Textarea/index.tsx
had to tweak the component first
=> textarea: minheight + autosize

packages/app/src/app/graphql/schema.graphql, packages/app/src/app/graphql/types.ts, packages/app/src/app/overmind/effects/gql/comments/mutations.ts, packages/app/src/app/overmind/effects/gql/comments/subscriptions.ts, packages/app/src/app/overmind/effects/gql/index.ts, packages/app/src/app/overmind/namespaces/comments/actions.ts, packages/app/src/app/overmind/namespaces/editor/actions.ts
=> Subs and resolve

packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Comments/Dialog/index.tsx
use a css transition
Alternate implementation of https://github.com/codesandbox/codesandbox-client/pull/3830
=> Dialog: Smoother list shadow

packages/app/src/app/pages/Profile/Sandboxes/index.tsx
Bug Fix
Non-functional delete button in Liked sandboxes in Profile view
Hide delete button in Liked Sandboxes page
- tested locally by traversing sandboxes page & Like sandbox page
=> fix: hide delete button from liked sandboxes

packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Comments/Comment.tsx, packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Comments/Dialog/Markdown/Link.tsx, packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Comments/Dialog/Reply.tsx, packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Comments/Dialog/index.tsx, packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Comments/components/AvatarBlock.tsx, packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Comments/components/MultiComment.tsx, packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Comments/index.tsx, packages/components/src/components/Element/index.tsx, packages/components/src/components/List/index.tsx, packages/components/src/components/Text/index.tsx
Improve comments SEO
https://www.notion.so/Improve-SEO-with-better-meta-data-and-JSON-LD-support-b55fe62920734c48a1bf571c085ed0ea#6f5652718e4046c08af9db097f70a34a
=> Some seo improvements

packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Comments/Dialog/index.tsx
When you drag the comment dialog around, it tends to select elements in the background that you can drop things in. Example: the url bar in preview.
To prevent this, we create an overlay that is shown only when the user is dragging.
We track "dragging" by hooking on to the `onPanEnd` on `DragHandle`
=> Comments dialog: create an overlay when dragging

packages/app/src/app/graphql/schema.graphql, packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Comments/AddComment.tsx, packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Comments/Comment.tsx, packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Comments/Dialog/Markdown/Code.tsx, packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Comments/Dialog/Markdown/makeTheme/collectStyles.ts, packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Comments/Dialog/Markdown/makeTheme/index.ts, packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Comments/Dialog/Markdown/makeTheme/minify.ts, packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Comments/Dialog/Markdown/makeTheme/scopeMapper.ts, packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Comments/Dialog/Markdown/makeTheme/scopeScore.ts, packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Comments/Dialog/Markdown/makeTheme/transformSettings.ts, packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Comments/Dialog/index.tsx
> Took the vscode theme we use and made it into prisma theme using the tool here: https://github.com/FormidableLabs/prism-react-renderer/tree/master/tools/themeFromVsCode and making it work in the browser
=> more things

packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Comments/Dialog/index.tsx, packages/common/src/utils/keycodes.ts
Also includes: https://github.com/codesandbox/codesandbox-client/pull/3866
- scroll to latest reply when comment is opened (after animations)
- hitting escape should close dialog
=> Comments: scroll to latest reply + ESCAPE to close

packages/app/config/webpack.prod.js
Just use static files instead, easier than having to run a dev server
=> use static analysis

contributor-docs/adding-template.md
=> docs(adding-template): fix /sandbox/eval/index.ts link

packages/app/src/app/pages/common/Modals/ShareModal/getCode.ts, packages/common/src/components/Preview/index.tsx, packages/homepage/content/docs/2-embedding.md, packages/homepage/content/docs/2-importing.md, packages/homepage/content/docs/2-tests.md, packages/homepage/content/docs/5-secrets.md, packages/homepage/src/screens/home/explore/index.js, standalone-packages/react-sandpack/src/components/SandpackProvider/SandpackProvider.tsx
=> chore: Update all embed frames

packages/app/src/app/pages/common/Modals/CommitModal/index.tsx, packages/app/src/app/pages/common/Modals/LiveSessionEnded/index.tsx, packages/app/src/app/pages/common/Modals/PRModal/index.tsx, packages/components/src/components/Button/button.stories.tsx, packages/components/src/components/Button/index.tsx, packages/components/src/components/IconButton/iconbutton.stories.tsx, packages/components/src/components/IconButton/index.tsx
=> Loading state for button

packages/app/config/webpack.common.js, packages/app/src/watermark-button.js
We now show an "Open Sandbox" button for sandboxes that are shared externally. This only happens for non-pro users.
=> Add watermark button for non-pro sandboxes

packages/app/src/app/components/CodeEditor/VSCode/workbench-theme.css
Bug Fix
Fixes #3882 
Add a scroll bar.
1. Press (`CMD + SHIFT + SPACE`) over here: https://codesandbox.io/s/virtualizedlist-react-yemug?file=/src/VirtualizedList.js:309-310
2. The scrollbar is visible now
=> fix: overflow content in vscode hint

packages/app/src/embed/components/Content/index.tsx, packages/common/src/themes/codesandbox-black.js
=> Add support for terminal messages from sse in embed

packages/app/src/app/pages/Dashboard/Content/SandboxGrid/index.tsx
Might fix #3928
Might fix #3929
Might fix #3930
=> Fix extra elements crash

packages/app/src/app/pages/GitHub/index.tsx, packages/app/src/app/pages/Sandbox/index.tsx
=> fix gh crash

packages/app/src/app/pages/NewDashboard/Header/index.tsx, packages/app/src/app/pages/NewDashboard/index.tsx, packages/components/src/components/Icon/icons.tsx
=> Dashboard - add header

packages/app/src/app/pages/NewDashboard/Components/SandboxCard/index.tsx, packages/app/src/app/pages/NewDashboard/Content/index.tsx, packages/app/src/app/pages/NewDashboard/Content/routes/StartSandboxes/index.tsx, packages/app/src/app/pages/NewDashboard/Header/index.tsx, packages/app/src/app/pages/NewDashboard/Sidebar/index.tsx, packages/app/src/app/pages/NewDashboard/index.tsx
=> Dashboard: responsive grid - first draft

packages/app/src/app/overmind/namespaces/dashboard/actions.ts, packages/app/src/app/pages/NewDashboard/Components/FolderCard/index.tsx
Makes the mutations in the dashboard optimistic
=> Make all mutations optimistic

packages/app/src/app/overmind/namespaces/dashboard/actions.ts, packages/app/src/app/overmind/namespaces/dashboard/state.ts, packages/app/src/app/pages/NewDashboard/Components/Header/index.tsx, packages/app/src/app/pages/NewDashboard/Components/Sandbox/index.tsx, packages/app/src/app/pages/NewDashboard/Components/SandboxItem/Menu.tsx, packages/app/src/app/pages/NewDashboard/Components/SandboxItem/index.tsx, packages/app/src/app/pages/NewDashboard/Content/routes/All/index.tsx, packages/app/src/app/pages/NewDashboard/Content/routes/Deleted/index.tsx, packages/app/src/app/pages/NewDashboard/Content/routes/Drafts/index.tsx, packages/app/src/app/pages/NewDashboard/Content/routes/Recent/SandboxesGroup.tsx, packages/app/src/app/pages/NewDashboard/Content/routes/Recent/index.tsx, packages/app/src/app/pages/NewDashboard/Content/routes/Search/index.tsx, packages/app/src/app/pages/NewDashboard/Content/routes/Templates/index.tsx, packages/app/src/app/pages/NewDashboard/Content/utils.ts
Adds the list version of the sandbox grid
=> add skeleton for listItem sandbox

packages/app/src/app/overmind/namespaces/dashboard/actions.ts, packages/app/src/app/pages/NewDashboard/Components/Filters/ViewOptions/icons.tsx, packages/app/src/app/pages/NewDashboard/Components/Filters/ViewOptions/index.tsx, packages/app/src/app/pages/NewDashboard/Components/Filters/index.tsx, packages/app/src/app/pages/NewDashboard/Components/Sandbox/index.tsx, packages/app/src/app/pages/NewDashboard/Content/index.tsx
Creates the list/grid toggle and its persistence in local storage
=> add persistent view toggle

packages/app/src/app/pages/NewDashboard/Content/routes/StartSandboxes/index.tsx, packages/components/src/components/Icon/icons.tsx
=> Dashboard: add icon + alignment for new sandbox button

packages/app/src/app/graphql/schema.graphql, packages/app/src/app/graphql/types.ts, packages/app/src/app/overmind/effects/gql/dashboard/queries.ts, packages/app/src/app/overmind/namespaces/dashboard/actions.ts, packages/app/src/app/overmind/namespaces/dashboard/state.ts, packages/app/src/app/pages/NewDashboard/Components/Filters/ViewOptions/index.tsx, packages/app/src/app/pages/NewDashboard/Components/FolderCard/index.tsx
=> add sandbox count for folder

packages/app/src/app/pages/NewDashboard/Components/Sandbox/index.tsx, packages/app/src/app/pages/NewDashboard/Components/SandboxCard/index.tsx, packages/app/src/app/pages/NewDashboard/Components/SandboxGrid/index.tsx, packages/app/src/app/pages/NewDashboard/Content/index.tsx, packages/app/src/app/pages/NewDashboard/Content/routes/All/index.tsx, packages/app/src/app/pages/NewDashboard/Content/routes/Drafts/index.tsx, packages/app/src/app/pages/NewDashboard/Content/routes/Recent/SandboxesGroup.tsx, packages/app/src/app/pages/NewDashboard/Content/routes/Recent/index.tsx, packages/app/src/app/pages/NewDashboard/Content/routes/StartSandboxes/index.tsx, packages/app/src/app/pages/NewDashboard/Content/routes/Templates/index.tsx, packages/app/src/app/pages/NewDashboard/index.tsx
=> Loading skeletons for dashboard

packages/app/src/app/overmind/effects/gql/dashboard/mutations.ts, packages/app/src/app/overmind/namespaces/dashboard/actions.ts, packages/app/src/app/pages/NewDashboard/Components/FolderCard/index.tsx, packages/app/src/app/pages/NewDashboard/Components/Header/index.tsx, packages/app/src/app/pages/NewDashboard/Components/Sandbox/index.tsx, packages/app/src/app/pages/NewDashboard/Content/routes/All/index.tsx, packages/app/src/app/pages/NewDashboard/Content/routes/Recent/SandboxesGroup.tsx, packages/app/src/app/pages/NewDashboard/Content/routes/Templates/index.tsx
Removed columns in most places as they were breaking the list view
=> Add ability to create folders

packages/app/package.json, packages/app/src/app/pages/NewDashboard/Header/index.tsx, yarn.lock
can't use lodash.debounce inside a component with hooks :)
Added tiny library [use-debounce](https://github.com/xnimorz/use-debounce) that uses useCallback to handle debounce across renders
Closes CSB-132
=> Dashboard: debounce search input

packages/app/src/app/pages/Sandbox/Editor/Content/EditorToast.tsx, packages/app/src/app/pages/Sandbox/Editor/Content/index.tsx
Improve the performance of switching files by moving a hook on `editor.currentModule` to a separate component.
=> Improve performance of switching files

packages/app/src/app/overmind/namespaces/dashboard/actions.ts
Show pretty loading
closes CSB-151
=> reset state when changing teams

packages/app/src/app/pages/NewDashboard/Components/SandboxCard/Menu.tsx, packages/app/src/app/pages/NewDashboard/Components/SandboxCard/index.tsx, packages/app/src/app/pages/NewDashboard/Content/routes/Search/index.tsx
- Handle autofocus
- Handle escape
- Handle save on blur
=> Rename sandbox: Handle keyboard interactions + focus for editing

packages/app/src/app/pages/NewDashboard/Components/SandboxCard/index.tsx, packages/app/src/app/pages/NewDashboard/Components/SandboxGrid/index.tsx
Only needed to handle in one place <3
=> Make grid at least have 4 elements + shadow instead of scale

packages/app/src/app/graphql/schema.graphql, packages/app/src/app/graphql/types.ts, packages/app/src/app/overmind/effects/gql/dashboard/queries.ts, packages/app/src/app/overmind/namespaces/dashboard/actions.ts, packages/app/src/app/overmind/namespaces/dashboard/state.ts, packages/app/src/app/pages/NewDashboard/Content/index.tsx, packages/app/src/app/pages/NewDashboard/Content/routes/Settings/TeamSettings.tsx, packages/app/src/app/pages/NewDashboard/Content/routes/Settings/UserSettings.tsx, packages/app/src/app/pages/NewDashboard/Content/routes/Settings/components/Box.tsx, packages/app/src/app/pages/NewDashboard/Content/routes/Settings/components/Typography.tsx, packages/app/src/app/pages/NewDashboard/Content/routes/Settings/index.tsx, packages/app/src/app/pages/NewDashboard/Content/utils.ts, packages/components/src/components/Button/index.tsx
Please merge https://github.com/codesandbox/codesandbox-client/pull/4033 first
=> Create Team Info in Team Settings page

packages/app/src/app/graphql/schema.graphql, packages/app/src/app/graphql/types.ts, packages/app/src/app/overmind/effects/gql/dashboard/queries.ts, packages/app/src/app/overmind/namespaces/dashboard/actions.ts, packages/app/src/app/pages/NewDashboard/Content/index.tsx, packages/app/src/app/pages/NewDashboard/Content/routes/Settings/TeamSettings.tsx, packages/app/src/app/pages/NewDashboard/Content/routes/Settings/UserSettings.tsx, packages/app/src/app/pages/NewDashboard/Content/routes/Settings/components/Box.tsx, packages/app/src/app/pages/NewDashboard/Content/routes/Settings/components/Typography.tsx, packages/app/src/app/pages/NewDashboard/Content/routes/Settings/index.tsx, packages/components/src/components/Button/index.tsx
=> User Settings

packages/app/src/app/graphql/schema.graphql, packages/app/src/app/graphql/types.ts, packages/app/src/app/overmind/effects/gql/dashboard/mutations.ts, packages/app/src/app/overmind/namespaces/dashboard/actions.ts, packages/app/src/app/pages/NewDashboard/Content/routes/Settings/TeamSettings.tsx, packages/app/src/app/pages/common/UserMenu/Menu/elements.tsx
Adds:
* List of members in a team
* Remove members
* Leave team
=> Team Settings

packages/components/package.json
=> Chromatic 2: project token is now a flag instead of process env

packages/app/src/app/overmind/namespaces/editor/state.ts, packages/app/src/app/pages/Sandbox/Editor/Workspace/Files/DirectoryEntry/index.tsx, packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Explorer/Files/DirectoryEntry/index.tsx
Auto opening directories behaved a bit weird. Repro and fix can be seen here: https://www.loom.com/share/47022da092ae4c388ed6203367f2c135
=> Fix automatically opening directories

packages/app/src/app/pages/NewDashboard/Components/Sandbox/SandboxCard.tsx, packages/app/src/app/pages/NewDashboard/Components/Sandbox/SandboxListItem.tsx, packages/app/src/app/pages/NewDashboard/Components/Sandbox/index.tsx
work in progress, so much more to come :)
=> Dashboard: draggable cards!

packages/homepage/content/docs/2-importing.md
Making this a PR while we wait for the new firefox extension page to be approved.
=> Update importing doc with GitHubBox and Browser Extension options

packages/app/src/app/pages/NewDashboard/Components/Sandbox/DragPreview.tsx, packages/app/src/app/pages/NewDashboard/Components/Sandbox/SandboxCard.tsx, packages/app/src/app/pages/NewDashboard/Components/Sandbox/SandboxListItem.tsx, packages/app/src/app/pages/NewDashboard/Components/Sandbox/index.tsx, packages/app/src/app/pages/NewDashboard/Content/routes/StartSandboxes/index.tsx, packages/app/src/app/pages/NewDashboard/Sidebar/index.tsx, packages/app/src/app/pages/NewDashboard/index.tsx
Works for the grid view
Need to design previews list view
=> Sandbox drag preview

packages/app/src/app/pages/NewDashboard/Components/Sandbox/DragPreview.tsx, packages/app/src/app/pages/NewDashboard/Components/Sandbox/index.tsx
It's not much, but it's honest work
=> Drag preview for list view

packages/app/src/app/pages/Dashboard/Content/elements.js, packages/app/src/app/pages/Dashboard/Content/routes/TeamView/index.js, packages/app/src/app/pages/Dashboard/queries.ts
I went for a simple version since we're updating the dashboard anyway soon.
How it works: https://www.loom.com/share/e756118b536c47cc80931278e8eb3b6a
=> Allow for editing the team name

packages/app/src/app/pages/NewDashboard/Components/Sandbox/index.tsx, packages/app/src/app/pages/NewDashboard/Sidebar/index.tsx
Don't have favorites or all sandboxes yet
=> Give sandboxes somewhere to drop

packages/app/src/app/components/CodeEditor/VSCode/index.tsx
Got this when going from one page to the other, this fixes it.
=> Fix crash on CodeSandbox when loading sandbox

packages/app/src/app/overmind/namespaces/dashboard/actions.ts, packages/app/src/app/pages/NewDashboard/Components/Sandbox/index.tsx, packages/app/src/app/pages/NewDashboard/Sidebar/index.tsx
Show folders in sidebar + make them drop targets
=> Dashboard folders part 1

packages/app/src/app/components/CreateNewSandbox/CreateSandbox/Explore/Explore.tsx, packages/app/src/app/components/CreateNewSandbox/CreateSandbox/Explore/SearchResults/ExploreResultList.tsx, packages/app/src/app/components/CreateNewSandbox/CreateSandbox/Explore/SearchResults/SearchResults.tsx
=> add loader to template universe too

packages/common/src/templates/node.ts, packages/common/src/templates/sapper.ts
Docs links update.
Page 404 shown for Node.js and old domain is linked for Sapper.
As docs/sse is not found, at least the docs is shown.
1. Links are working.
=> Updated links to some templates

packages/app/src/app/pages/NewDashboard/Components/Folder/DragPreview.tsx, packages/app/src/app/pages/NewDashboard/Components/Folder/FolderCard.tsx, packages/app/src/app/pages/NewDashboard/Components/Folder/FolderListItem.tsx, packages/app/src/app/pages/NewDashboard/Components/Folder/index.tsx, packages/app/src/app/pages/NewDashboard/Content/routes/Deleted/index.tsx, packages/app/src/app/pages/NewDashboard/Sidebar/index.tsx
Creating some additional tasks to handle optimistic updates: https://linear.app/project/dashboard-c13f7ba8b4f5/CSB
=> Delete + Move folders

packages/app/src/app/overmind/internalActions.ts, packages/app/src/app/overmind/namespaces/dashboard/actions.ts, packages/app/src/app/overmind/onInitialize.ts, packages/app/src/app/pages/NewDashboard/Content/index.tsx, packages/app/src/app/pages/NewDashboard/Content/routes/Settings/UserSettings.tsx
I was setting the view mode after the app loaded and now I set it on the init of the application and no more flicker
=> Fix Skeleton Flicker when view mode is List

packages/homepage/src/components/Navigation/MobileNav.js, packages/homepage/src/components/Navigation/index.js
Video with the fix: https://www.loom.com/share/2568e7add36f4bffa2071d49b8787754
=> Make mobile sign in work

packages/app/package.json, packages/app/src/app/overmind/utils/pushToFront.ts, packages/app/src/app/pages/common/Modals/FeedbackModal/Feedback.tsx, packages/app/src/app/pages/common/Modals/FeedbackModal/index.tsx
In-app feedback currently gets sent to Airtable. This sends it along to Front too.
=> Send in-app feedback to Front also

packages/app/src/app/pages/common/Modals/DeploymentModal/VercelLogo.tsx
Bug fix
Oversized Vercel logo
Smaller Vercel logo
1. Step A
Replicated the environment in plain HTML and copied styles over to test.
2. Step B
Edited HTML directly in codesandbox.
=> Fix logo dimensions

.codesandbox/ci.json
=> Add CodeSandbox CI for notifications

packages/app/package.json, packages/app/src/sandbox/eval/manager.ts, packages/app/src/sandbox/eval/npm/fetch-npm-module.ts, packages/app/src/sandbox/eval/presets/create-react-app/v1.ts, packages/app/src/sandbox/eval/presets/create-react-app/v3.ts, packages/app/src/sandbox/eval/presets/index.ts, packages/app/src/sandbox/eval/transpiled-module.ts, packages/app/src/sandbox/eval/transpilers/babel/convert-esmodule/__snapshots__/index.test.ts.snap, packages/app/src/sandbox/eval/transpilers/babel/convert-esmodule/index.test.ts, packages/app/src/sandbox/eval/transpilers/babel/convert-esmodule/index.ts, packages/app/src/sandbox/eval/transpilers/babel/convert-esmodule/utils.ts, packages/app/src/sandbox/eval/utils/resolve-utils.ts, yarn.lock
=> Fix esmodule converter for cyclic dependencies

packages/homepage/content/docs/2-importing.md
=> Docs typo fix, reactjs > reduxjs

packages/@styled-system/css/dist/index.js, packages/@styled-system/css/package.json
Fix old edge by using commonjs version of styled-system. It's still the patched version.
=> Fix old edge

packages/common/src/templates/vue.ts
=> Add support for tsconfig in Vue

packages/app/src/app/overmind/namespaces/dashboard/actions.ts, packages/app/src/app/pages/NewDashboard/Components/Selection/index.tsx
Also fixes renaming folders
closes CSB-205
=> When moving a folder delete old one from state

packages/homepage/src/components/Button.js
My OCD could not take it any longer! 
I aligned the border-radius of the homepage buttons with the button in the App
=> I aligned the buttons on the homepage with app 

packages/homepage/src/components/Button.js, packages/homepage/src/screens/home/hero/index.js, packages/homepage/src/screens/home/heroB/index.js
Fixed Big Button border radius. I did break the styling with the prev PR . 
Big button now looks like a button again
Old
Fixed
=> Updated cta homepage

packages/app/src/app/components/UserSearchInput/UserSearchInput.tsx, packages/app/src/app/pages/Sandbox/Editor/Header/Collaborators/Collaborators.tsx
@compuives I wanted to add the border-radius but turns out the paddingY was hiding the round courners. I removed the paddingY.
Also Added border radius on the container
It seems like it was there for a reason. Not sure I can delete it
Old
New 
------
**Container**
Old
New
=> Consistency tweak on autofill user /ui

packages/app/src/sandbox/eval/transpilers/babel/convert-esmodule/__snapshots__/index.test.ts.snap, packages/app/src/sandbox/eval/transpilers/babel/convert-esmodule/index.test.ts, packages/app/src/sandbox/eval/transpilers/babel/convert-esmodule/index.ts
=> Fix object shorthand

packages/executors/src/serverExecutor.ts, standalone-packages/sse-loading-screen/src/index.js
This adds SSE edge compatibility by sending the sandbox id in the URL query when connecting to the SSE websocket.
=> Add SSE edge compatibility

packages/app/src/app/overmind/namespaces/editor/actions.ts
Bug Fix
URL gets updated to `file=undefined` when we go to file `index.d.ts` in React element definition.
Prevent URL Update.
1. Local testing by going through the same file (index.d.ts present in node_modules)
=> fix: setting undefined in URL

packages/sandbox-hooks/url-listeners.js
Typo in https://github.com/codesandbox/codesandbox-client/pull/4203
1. Step A
2. Step B
3. Step C
Well now I understand why it didn't work... I made a typo...
=> fix: typo in method isInsideVue

packages/app/src/app/pages/NewDashboard/Components/Breadcrumbs/index.tsx, packages/app/src/app/pages/NewDashboard/Components/Folder/index.tsx, packages/app/src/app/pages/NewDashboard/Components/Sandbox/index.tsx, packages/app/src/app/pages/NewDashboard/Components/Selection/index.tsx, packages/app/src/app/pages/NewDashboard/Components/VariableGrid/index.tsx
Built on top of https://github.com/codesandbox/codesandbox-client/pull/4279
=> WIP Dashboard: Fix virtualised list skeleton 

packages/app/src/sandbox/eval/transpilers/babel/convert-esmodule/__snapshots__/index.test.ts.snap, packages/app/src/sandbox/eval/transpilers/babel/convert-esmodule/index.test.ts, packages/app/src/sandbox/eval/transpilers/babel/convert-esmodule/index.ts
=> Keep import order when transpiling

packages/app/src/sandbox/eval/manager.ts, packages/app/src/sandbox/npm/fetch-dependencies.ts
=> Use new packager that sanitizes wrongly configured npm packages

packages/app/src/app/graphql/schema.graphql, packages/app/src/app/graphql/types.ts, packages/app/src/app/overmind/effects/gql/dashboard/queries.ts, packages/app/src/app/overmind/namespaces/dashboard/actions.ts, packages/app/src/app/pages/NewDashboard/Content/routes/Settings/Invite.tsx, packages/app/src/app/pages/NewDashboard/Content/routes/Settings/NewTeam.tsx
=> Create Teams + Invite Link

packages/app/src/app/graphql/types.ts, packages/app/src/app/overmind/effects/gql/dashboard/mutations.ts, packages/app/src/app/overmind/namespaces/dashboard/actions.ts, packages/app/src/app/pages/NewDashboard/Content/routes/Settings/TeamSettings.tsx, packages/app/src/app/pages/NewDashboard/Sidebar/index.tsx
Issues:
The defaultValue of textarea doesn't work :(
=> update name and description

packages/app/src/app/pages/NewDashboard/Components/Folder/FolderCard.tsx, packages/app/src/app/pages/NewDashboard/Components/Folder/FolderListItem.tsx, packages/app/src/app/pages/NewDashboard/Components/Folder/index.tsx, packages/app/src/app/pages/NewDashboard/Components/Sandbox/SandboxCard.tsx, packages/app/src/app/pages/NewDashboard/Components/Sandbox/SandboxListItem.tsx, packages/app/src/app/pages/NewDashboard/Components/Sandbox/index.tsx, packages/app/src/app/pages/NewDashboard/Components/Selection/ContextMenu.tsx, packages/app/src/app/pages/NewDashboard/Components/Selection/index.tsx
brought back this feature that got lost in refactoring
=> WIP Dashboard: Rename

packages/app/src/app/overmind/namespaces/dashboard/actions.ts
Only checked everything that was an array 🤦
=> Rename nested sandboxes

packages/app/src/app/pages/NewDashboard/Components/Sandbox/SandboxCard.tsx, packages/app/src/app/pages/NewDashboard/Components/Sandbox/SandboxListItem.tsx, packages/app/src/app/pages/NewDashboard/Components/Sandbox/index.tsx, packages/app/src/app/pages/NewDashboard/Components/Selection/ContextMenu.tsx, packages/app/src/app/pages/NewDashboard/Components/Selection/DragPreview.tsx, packages/app/src/app/pages/NewDashboard/Content/routes/StartSandboxes/index.tsx
handle context menus better 
don't drag start templates
=> WIP Dashboard: handle start templates better

packages/app/src/app/pages/NewDashboard/Components/Breadcrumbs/index.tsx, packages/app/src/app/pages/NewDashboard/Components/Filters/FilterOptions/index.tsx, packages/app/src/app/pages/NewDashboard/Components/Folder/index.tsx, packages/app/src/app/pages/NewDashboard/Components/Header/index.tsx, packages/app/src/app/pages/NewDashboard/Content/utils.ts, packages/app/src/app/pages/NewDashboard/Header/index.tsx, packages/app/src/app/pages/NewDashboard/Sidebar/TeamAvatar.tsx, packages/app/src/app/pages/NewDashboard/Sidebar/index.tsx
Fix key warnings in filter
Use first letter as team avatar
=> WIP Dashboard polish 5

packages/app/src/app/pages/NewDashboard/Sidebar/index.tsx
=> Reload folders when changing teams

packages/app/src/app/pages/NewDashboard/Components/Sandbox/SandboxListItem.tsx
Fuck safari and their date stuff
https://stackoverflow.com/questions/4310953/invalid-date-in-safari
=> fix date on safari
