src/sandbox/eval/index.js, src/sandbox/eval/index.test.js, src/sandbox/eval/js/babel-parser.js, src/sandbox/eval/js/index.js
Fix for https://github.com/CompuIves/codesandbox-client/issues/40
=> Support for cyclic dependencies

src/app/components/Preference/PreferenceSwitch.js, src/app/components/Preference/PreferenceText.js, src/app/components/Preference/index.js, src/app/components/sandbox/CodeEditor/index.js, src/app/containers/Preferences/EditorPageSettings/EditorSettings/Preferences.js, src/app/containers/Preferences/EditorPageSettings/PreviewSettings/Preferences.js, src/app/pages/Sandbox/Editor/Content/Header/ShareView.js, src/app/store/preferences/actions.js, src/app/store/preferences/keys.js, src/app/store/preferences/reducer.js, src/app/utils/codemirror.js
Add font family for preference. AFAIK this should be all from the client side, haven't got to test it yet until we have staging server :)
Also, why do we need to `injectGlobal` here @CompuIves ? I think we can move it to `CodeContainer`?
=> [WIP] Add font family to preferences

src/app/components/sandbox/CodeEditor/Header.js, src/app/components/sandbox/CodeEditor/index.js, src/app/pages/Sandbox/Editor/Content/Header/ShareView.js, src/app/pages/Sandbox/Editor/Content/index.js, src/app/pages/Sandbox/Editor/Workspace/Files/index.js, src/app/store/entities/sandboxes/modules/selectors.js, src/embed/App.js, src/embed/components/Content.js, src/embed/components/File.js, src/embed/components/Files.js, src/sandbox/utils/resolve-module.js
Need to review this PR myself too later today.
This changes the url structure from:
`/s/new?module=J38najh`
to
`/s/new?module=%20FHello.js`
Which means that now default modules are specified using paths instead of shortids, since shortids can change between updates. There should still be backward compatability with shortid.
=> Use module path for selecting current module

src/app/utils/codemirror/eslint-lint.js
ugly hack to work around eslint dependency which redefines the require instance on window
this breaks the monaco loader.js
the following workaround can be removed after migration to monaco (vim mode) is done
That is the most basic solution I could came up with. Please let me know what you think :)
fixes #118
=> fix vim mode switch

src/app/hoc/show-alternative-component.test.js
I was reading through the code base and found this very minor typo.  Figured I'd fix it...
Keep up the good work, this app is great! And `AlternativeComponent` looks cool as well. 🎉
=> Fix typo: render instead of remder

src/app/pages/Sandbox/Editor/Content/Header/Action.js
Current behaviour:
With this PR:
Now all the tooltips are aligned in the same position and the blue bottom border is visible on hover on the actions. I believe this is the original idea behind the hover behaviour for these actions. If I assumed wrong, please let me know how you'd like it to be! 😄
Created an issue as well: https://github.com/CompuIves/codesandbox-client/issues/134
=> Make action tooltips positions more consistent

config/babel.dev.js, config/babel.prod.js, config/env.js, config/paths.js, config/webpack.config.js, package.json, scripts/build.js, scripts/utils/WatchMissingNodeModulesPlugin.js, scripts/utils/prompt.js
Previous issue to remove trailing comma rule so that versions before node 8 could be supported was not properly resolved as the git hook still ran prettier with the `--trailing-comma all` command line options.
This PR fixes those options and removes trailing commas from files that are run with node.
=> Remove trailing comma all command line option from prettier githook

src/app/components/sandbox/ModeIcons.js
One of the things which I absolutely like about Code Sandbox is that it has a lot of fast smooth transitions in the UI. Actually, I have found inspiration from your work and applied to it to my own works, so thanks for that! 😄 
One small thing disturbed me though. There's a very nice animation when hovering over the current mode to show the sub-modes, but there is no "leaving" animation:
I tried adding a leaving animation (first commit). It wasn't that hard, and worked fine initially:
However, I quickly discovered a nasty side effect: the mode changes instantly, so when clicking a mode, it looks a bit weird:
I tried two things:
- Only changing all the modes after the animation ended; didn't work out so well because the selected mode would switch when animation ends, which looked odd
- …
=> Add animation when sub-modes disappear in the header

src/sandbox/eval/transpilers/babel/babel-parser.js
For example https://codesandbox.io/s/2vmzpM0wK is now broken. See also: https://github.com/mobxjs/mobx/issues/1154
Fixes https://github.com/CompuIves/codesandbox-client/issues/151
=> Fix plugin order to re-enable using decorators

scripts/start.js
Fixes https://github.com/CompuIves/codesandbox-client/issues/158.
=> Rewrite /embed to /embed.html. Fixes #158.

src/app/pages/Sandbox/Editor/Content/Header/ShareView.js
Fixes https://github.com/CompuIves/codesandbox-client/issues/162.
=> ShareView: make inputs and textareas explicit readonly.

src/app/pages/Sandbox/Editor/Workspace/Dependencies/index.js, src/sandbox/external-resources.js
The order in which resources (especially `<script>`s) are loaded is important in cases where there are dependencies between them (most notable case is jQuery). That's the reason for which sorting the resources by name in the Dependencies > External Resources section in the left pane can be misleading.
Also the reason for which I removed `sort()` from `getExternalResourcesConcatenation()` (`['a.js', 'b.js']` should not be equivalent to `['b.js', 'a.js']`).
There was another issue with the way `async` was set on resources `<script>`s, as a HTML attribute instead of a DOM element attribute (see https://developer.mozilla.org/en/docs/Web/API/HTMLScriptElement#async_property).
After these changes, adding jQuery and a plugin that depends on it works, regardless of the time they load in (I was …
=> Preserve resource order

src/app/components/Alert.js, src/app/components/buttons/Button.js, src/app/components/buttons/Button.test.js, src/app/components/buttons/__snapshots__/Button.test.js.snap, src/app/pages/Sandbox/Editor/Workspace/Files/DirectoryEntry/DeleteFile.js, src/app/pages/Sandbox/Editor/Workspace/Files/DirectoryEntry/index.js, src/app/pages/Sandbox/Editor/Workspace/SandboxActions/index.js
This PR adds a modal for confirming file deletion, instead of using `alert()`. If you're happy with it, we can also do something similar for deleting sandboxes.
I'm not particularly happy with the design. It's not something I'm very good at. I tried using elements that exist on other places already. Actually, the red colour for the Delete button doesn't feel right...
I'm not sure if you want this. Maybe you want to keep `alert()` but I assumed it was done this way initially because it was the easiest approach. 😄 
As usual, I learned quite a lot by looking at your Modal implementation (1 instance of `Modal` and keeping everything else in the state), and I'll probably use the same approach for another project where we recently started adding more modals. 
**PS:** I noticed my diff includes …
=> Introduce delete file modal

src/app/components/sandbox/CodeEditor/CodeMirror.js, src/app/components/sandbox/CodeEditor/Monaco.js
Check that newCode is actually defined before switching the output. I hope the issue description and fix speak for itself. 😄 
https://github.com/CompuIves/codesandbox-client/issues/185
**Edit:** I don't understand why my commits contain stylistic changes to other parts of the code in the same file. I suppose it's some issue from my side with Prettier?
=> Fix issue when clicking prettify when the sandbox contains syntax errors

src/app/components/sandbox/Preview/index.js
`historyPosition` starts at 1 (because of the initial `sendUrlChange()` -> `commitUrl()` with the sandbox URL), so the condition `historyPosition > 0` is always true.
Fixes https://github.com/CompuIves/codesandbox-client/issues/195.
=> Sandbox preview: make navigator's back button inactive on first load

src/app/components/sandbox/Preview/index.js, src/sandbox/url-listeners.js
…, when inside the editor.
To do:
- ~~debug Firefox issue where `window.history.__proto__` is reset when bluring and focusing the window (tab?) again~~
I tested in latest versions of Chrome and Firefox, with both a React app and a Vue app using their corresponding routing libraries, in both `history` and `hash` mode.
Fixes https://github.com/CompuIves/codesandbox-client/issues/115 (and probably other issues related to history navigation behavior).
=> Sandbox preview: replace window.history with our own emulated history

yarn.lock
They merged my PRs for fixing the HMR logging and making the error overlay translucent.
=> Upgrade webpack-dev-server to 2.9.1

src/app/pages/Profile/Sandboxes/index.js, src/app/pages/Sandbox/Editor/Workspace/SandboxActions/index.js
Add a modal (the same that is used in the editor when deleting a sandbox) when deleting sandbox from profile page, instead of alert.
Locally could only test it by forcing `isCurrentUser` to `true` in the code. But otherwise I could not manage to log in to Github when running locally. Though it seems to be working, but please do double-check 😄
=> Show modal instead of alert

src/sandbox/eval/transpilers/vue/style-compiler/loader.js
Bugfix.
Sandbox crashes on CSS errors in the `<style>` section of `.vue` files.
=> Vue style-compiler: fix un-rejectable promise

src/app/components/sandbox/Preview/DevTools/Console/Message.js, src/app/components/sandbox/Preview/index.js, src/app/store/preferences/reducer.js
- enable "Clear console" by default;
- also clear devtools console when "Clear console" is enabled;
- make inspector's theme background transparent, fixes warnings and errors showing like this in the console:
Fixes #286.
=> Console enhancements

packages/app/src/app/store/entities/sandboxes/utils/export-to-github/index.js
=> Create Repo: send an array instead of an object to API

packages/homepage/src/screens/home/Animation/Cubes.js
Hello
Fix
https://github.com/CompuIves/codesandbox-client/issues/301
**Checklist**:
The welcome screen is quite heavy on CPU. When I open it, lights on my street fade. Until I get some idea how to replace those 3d rotations with no hardware support, I'll just keep checking is there any car traffic before entering that page.
=> fix: make react cube clickable by reducing radius size

packages/app/src/app/pages/Sandbox/Editor/Workspace/Dependencies/AddVersion.js, packages/app/src/app/pages/Sandbox/Editor/Workspace/Dependencies/DependencyHit.js, packages/app/src/app/pages/Sandbox/Editor/Workspace/Dependencies/SearchDependencies.js
Did some small visual improvements:
1. Allow user to add a dependency by typing and pressing enter (in case Algolia index is not updated yet)
2. Add user of npm package (to make sure you add trustworthy packages)
3. Add search icon (if you want to find examples sandboxes)
4. Small visual changes for consistency with the coming redesign
=> Small improvements to dependency picker

packages/common/components/flex/MaxWidth.js
Bug fix
MaxWidth__Container exceeds 100% width because of the additional paddings in content-box box-sizing
Use box-sizing: border-box for the Container, hence the paddings are incorporated into the actual width.
**Checklist**:
**Additional Comments**
Ideally we should use global border-box box-sizing as the following. It will make the sizing more predictable.
However, introducing that at this stage kinda messes up the sizing of some layouts. We could have another PR to refactor it.
```
html {
box-sizing: border-box;
}
*, *:before, *:after {
box-sizing: inherit;
}
```
=> Fix overflowing MaxWidth__Container

packages/app/src/app/components/sandbox/CodeEditor/Tabs/index.js
Change closeListener to evaluate keyCode for W
https://github.com/CompuIves/codesandbox-client/issues/396
evaluates `e.code` and not `e.keyCode`
evaluate `e.keyCode`
**Checklist**:
=> closeListener keyCode change

packages/app/src/sandbox/eval/transpilers/babel/babel-worker.js, packages/app/src/sandbox/eval/transpilers/babel/plugins/babel-plugin-transform-prevent-infinite-loops.js
=> Fix infinite loops

packages/app/src/app/containers/Preferences/CodeFormatting/Prettier.js, packages/app/src/app/containers/Preferences/CodeFormatting/index.js, packages/app/src/app/store/entities/sandboxes/actions/files.js, packages/app/src/app/store/entities/sandboxes/modules/actions.js
It adds support for `.prettierrc` file placed at the root of the sandbox. It updates the Prettier preferences when the `.prettierrc` is saved.
Idea from @kentcdodds at https://twitter.com/kentcdodds/status/944817103814692864
Staging demo: http://pr419.cs.lbogdan.tk/s/rj733y8y6o
This is a kinda raw experiment but it's working fine so far but I already have some improvements in mind: 
- keep the default values for the keys not provided by the `.prettierrc` so the preferences UI is not broken. Like below for the "Tab width":
=> Handle .prettierrc file at root

packages/app/src/app/pages/Sandbox/Editor/Workspace/Dependencies/DependencyHit.js
For some reason the `cq-demo` package has no 'versions' field, but it has a 'version', so we use that.
Fixes #435.
=> Fixes bug with dependencies having no 'versions' field

packages/app/src/app/components/sandbox/Preview/DevTools/Console/Input.js
Bug fix
Style issues when Console's height is small, multiline input's monaco editor sets the input's height to be higher than console's height.
Limit Console `<Input>`'s height to console `<Container>`'s height so when inserting new lines it doesn't overflow.
**Checklist**:
=> Fix: Limit the height of multiline input to Console Container's height

packages/app/src/sandbox/eval/npm/fetch-npm-module.js
Fixes the case where we can't find the right dependency version when dynamically fetching a dependency that's marked as subdependency (eg. `/node_modules/readable-stream/node_modules/string_decoder`). 
Fixes #444
=> Fix duplicate dependency resolving

packages/common/utils/url-generator.js
Update github regex for names containing a dash
Bug Fix
Github regex currently fails if the username contains a dash `-`.
Github regex passes if the username contains a dash `-`.
**Checklist**:
=> Update github regex for names containing a dash

packages/app/config/env.js, packages/app/src/app/pages/Sandbox/SearchDependencies/DependencyHit/index.js, packages/app/src/app/pages/common/Modals/ShareModal/index.js, packages/app/src/sandbox/index.js
Needed for staging environment. Default value is `https://codesandbox.io`.
Usage:
`ROOT_URL=http://staging.cs.lbogdan.tk yarn build`.
=> Add "ROOT_URL" build environment variable

packages/app/src/sandbox/eval/presets/index.js, packages/app/src/sandbox/eval/presets/parcel/transpilers/html-transpiler.js, packages/app/src/sandbox/eval/presets/parcel/transpilers/html-worker.js, packages/app/src/sandbox/eval/transpiled-module.js, packages/app/src/sandbox/eval/transpilers/worker-transpiler.js
If you'd change a style that is referenced by the HTML file then the browser would reset, because the JS was cached. This will bust the cache of all entries when an entry changes.
=> Fix HMR cache of parcel when first entry is changed

packages/app/src/sandbox/eval/manager.js, packages/app/src/sandbox/eval/presets/parcel/transpilers/html-worker.js, packages/app/src/sandbox/eval/transpiled-module.js
Fixes #644 by using the `module.hot` API to reload modules changed in the deeper levels of the dependency graph.
=> Fix Parcel HMR

packages/app/src/app/pages/common/Modals/PreferencesModal/EditorPageSettings/EditorSettings/index.js
Bug fix
Switching the VIM mode setting on enables CodeMirror without notifying the user.
It now indicates the current behavior.
**Checklist**:
I have stumbled upon this when I started with a React Typescript sandbox but didn't see type errors I was expecting. I opened the same sandbox in a different browser to test and the errors were present there. At first, I thought it was a browser problem, but then I noticed the errors were gone after I switched the vim mode on there too. It was confusing.
The wording and detail are up to debate, but it should be indicated. A future improvement can be to make the CodeMirror option disabled at `on` state if VIM mode is selected. I don't know …
=> Indicate turning VIM mode on will enable CodeMirror

packages/app/package.json
Upgrade to console-feed@2.6.1 - makes the console responsive, without overflowing containers.
Bug fix
=> Responsive console styles

packages/react-sandpack/src/components/OpenInCodeSandbox/OpenInCodeSandbox.tsx, packages/react-sandpack/stories/OpenInCodeSandbox.js
Allows overriding the rendering behavior in `OpenInCodeSandbox`.
Currently, the button is hardcoded to output `<input type="submit" />`.
**Checklist**:
Also, fixed up all the storybook examples with `OpenInCodeSandbox`
=> Add prop to override button rendering in OpenInCodeSandbox

packages/app/src/sandbox/eval/transpilers/babel/worker/babel-worker.js
Currently, `babel-transpiler.json` has two inconsistently named options: `babelURL` vs `babelEnvUrl`.
`babelEnvUrl` -> `babelEnvURL`
**Checklist**:
=> Make babel transpiler options more consistent

packages/app/src/app/pages/Sandbox/Editor/Workspace/Files/DirectoryEntry/index.js, packages/app/src/app/pages/common/Modals/StorageManagementModal/AddFileToSandboxButton/elements.js, packages/app/src/app/pages/common/Modals/StorageManagementModal/AddFileToSandboxButton/index.js, packages/app/src/app/pages/common/Modals/StorageManagementModal/FilesList/index.js, packages/app/src/app/pages/common/Modals/StorageManagementModal/index.js, packages/app/src/app/store/modules/files/index.js, packages/app/src/app/store/modules/files/sequences.js
Feature:
There is a "+" button that will allow users to add uploaded files to the sandbox
Fix: 
Allow users to upload files directly to directory via the buttons on the directories
Always uploads to the root directory
No way to put already uploaded files in sandbox if files are deleted from sandbox
See picture.
Users and upload files to specified directories.
**Checklist**:
=> feat: Allow users to add uploaded files to project

packages/app/src/sandbox/eval/presets/vue-cli/index.js
This was pretty much broken from the get-go, strangely enough no one noticed. :smile: As seen here https://github.com/vuejs-templates/webpack/blob/develop/template/build/webpack.base.conf.js#L40 , `@` should point to `/src`, not `/`.
=> Fix vue-cli @ alias

packages/app/src/sandbox/eval/presets/dojo/index.js, packages/app/src/sandbox/eval/presets/dojo/transpilers/style.js, packages/app/src/sandbox/eval/transpilers/style/index.js, packages/app/src/sandbox/eval/transpilers/style/utils/to-definition.js
**What kind of change does this PR introduce?** Bug fix
**What is the current behavior?** Theming in Dojo examples does not work properly as the CSS Module JS file is missing a `" _key"` property that the Dojo theming system relies on.
For Dojo themes to work properly a special `" _key"` property should exist on the CSS module JS file that's value is the package name plus the name of the css file.
This commit makes the following changes:
- add a custom styles transpiler for Dojo that adds the `" _key"` property
- Update the Dojo preset to use the new styles transpiler
- split out the `classesToDefinition` method into its own utility module and import it into the existing and Dojo style transpilers
**Checklist**:
=> Add support for Dojo theming

packages/app/src/app/components/CodeEditor/Monaco/workers/fetch-dependency-typings.js
Fixes #559 .
Test: http://pr811.cs.lbogdan.tk/s/kkpplyrqqo , go to `src/app/app.module.ts`, there's no `Cannot find module 'angular-bootstrap-md'.` error.
=> Fallback to looking for .ts files if no .d.ts files found

packages/app/src/app/store/providers/KeybindingManager.js, packages/common/utils/keybindings.js
This is a proof of concept for some of the ideas I suggested on #507.
tl;dr: iOS doesn’t trigger key events just by pressing alt, shift, etc.
The solution I’m proposing to fix this comes with pros/cons:
* The ability to have shortcuts on iOS 😎.
* Can only use `Alt` and `Shift` as key modifiers.
* Not able anymore to use the keys generated by one of the shortcuts (e.g.: Alt+Shift+P prints ∏ on my keyboard) [I have another workaround in mind to solve this though].
=> [RFC] Shortcuts support for iOS devices

packages/app/src/app/pages/common/Navigation/index.js, packages/app/src/app/pages/common/UserMenu/index.js
Bug fix. Closes #852.
After signing out, the UI breaks because the `UserMenu` component is connected to the store and reacts to the `user` property being updated. (See #852)
Instead of being connected to the store, the `UserMenu` component receives the `user` and `userMenuOpen` props from the `Navigation` component, which also decides if the `UserMenu` should render or not based on the `user` property.
**Checklist**:
=> fix(signout): Fixing UI updates after sign out

packages/homepage/src/screens/home/Animation/canvas/index.js
After switch tabs wave animations will stop. Reset variable lowPerf to false to recover it when tab regain focus.
=> Recover wave animation after tabs switch

packages/app/src/app/store/actions.js
Bug fix. Closes #353.
#353 - When you enable "Expand console" it should save in `preferences.showDevtools`, however, it saved as `preferences.showConsole`.
It saves on store as `preferences.showDevtools` which is expected in _Content_.
**Checklist**:
=> fix(actions): set preferences showDevTools

packages/app/src/sandbox/npm/index.js
**Bug Fix**
The dependency loader excludes dependencies for types by checking that the keys of a dependency object do not include the string `"@types"`.
The helper `pickBy` eventually calls `getAllKeys` which gets symbols up the prototype chain in addition to keys on the object.
When a package introduces symbols to the `Object.prototype`, the type check fails when the document is reloaded because symbols do not have an `includes` method (`key.includes is not a function`)
**To Reproduce**
1. Create a new sandbox
2. Add "funcadelic" to dependencies
3. `import "funcadelic"` in the index
4. Wait for dependencies to build
5. Making any changes displays the error
**Link to existing sandbox with bug:** https://codesandbox.io/s/wozkol0n7
Check that `key.includes` is defined before calling it when …
=> Fix app dependency loader error

packages/app/src/sandbox/eval/presets/vue-cli/index.js
as discussed on Discord ... this will allow bare `.ts` files to be transpiled instead of just relying on TS embedded in .vue files
=> add typescript files for Vue projects

packages/app/src/app/pages/Sandbox/QuickActions/index.js
One of the cool things about genie is it's sorting algorithm takes into account the user's previous choices. By providing the input value when you make the wish, genie can keep track of what input values lead to which wishes and can optimistically suggest certain wishes as the user's typing.
**What kind of change does this PR introduce?** Bug Fix
**What is the current behavior?** genie isn't able to make proper suggestions based on previous wishes made
**What is the new behavior?** genie will optimistically suggest wishes
**Checklist**:
=> fix(genie): allow genie to sort wishes properly

packages/app/src/app/components/CodeEditor/Monaco/workers/fetch-dependency-typings.js
Ensure that all fetch Promises have been resolved when returning from the fetchFromMeta method in fetch-dependency-typings.
Currently, it causes inconsistencies when it comes to fetching inline typings as the promise can resolve before all of the types are downloaded.
The new fix causes the `fetchFromMeta` to return a `Promise.all` of its fetch calls to ensure its returned Promise doesn't resolve until all of them do.
**Checklist**:
=> Fix async issue with fetching typings from meta Fixes #1021

packages/homepage/content/docs/2-tests.md
Instead of saying "... creating files that **end** with `.test.js`, ..." it said "... creating files that **and** with `.test.js`, ...".
Minor change in documentation, correcting a typo
text states (emphasis added): "... creating files that **and** with `.test.js`, ...".
text now states (emphasis added): "... creating files that **end** with `.test.js`, ..."
**Checklist**:
Documentation change only, so no tests run
=> Correcting minor typo

packages/app/src/app/store/modules/files/actions.js
Add (le|sa|sc)ss and style files types to the list of forced text extensions.
https://github.com/CompuIves/codesandbox-client/issues/348#issuecomment-416019773
When uploading(le|sa|sc)ss or styl (and probably other) files, and error message is thrown:
"This file is too big to edit
We will add support for this as soon as possible
Open file externally". 
It seems the zip implementation does not recognize them as text files. CompuIves recommends to add them to the list of forced text extensions.
Important: This happens only, when such files are *uploaded*! (creating such files within the editor works fine.)
On upload, recognize more file types. (Again: on *upload*!)
**Checklist**: …
=> Add (le|sa|sc)ss and styl file types to list of forced text extensions.

packages/app/src/app/components/Preview/DevTools/Tests/index.js, packages/app/src/sandbox/compile.js, packages/app/src/sandbox/eval/tests/jest-lite.js
Helps with #1075 and #1074.
All the Jest tests are currently executing in the same window as the main application, which can cause some trouble when tests alter the main DOM or do things like `location.reload`. The solution is to execute the tests in a separate iframe, but this will be quite some work before we can get there.
In the meantime I propose to only run the tests when the tests tab is opened, contrary to what we have now where we eagerly run tests as soon as the sandbox is evaluated. This will help with infinite loops cause by eg. `onSubmit` in a test and will not infer with the main evaluation of the sandbox.
There are some drawbacks:
- It will take a bit longer to load the tests when you open the Tests tab
- We will not show eagerly the green/red notification on the Tests tab …
=> Make running tests conditional

packages/react-sandpack/package.json
Hi! I started using react-sandpack with Webpack 4 (CRA v2) and loading `react-smooshpack/dist/styles.css` is broken in production mode. The problem seems to be the sideEffects in package.json.
More info:
- https://webpack.js.org/guides/tree-shaking/#mark-the-file-as-side-effect-free
- https://github.com/facebook/create-react-app/issues/5140
=> Add *.css to sideEffects

packages/homepage/content/docs/2-importing.md, packages/homepage/content/docs/3-configuration.md
Documentation describing the ability to specify a `template` in `sandbox.config.json`
=> [docs] importing - template can be specified in sandbox.config.json

packages/app/src/app/pages/Patron/PricingModal/Badge/Particles/index.js
Bug fix. Closes #1138.
The app breaks on Chrome when the slider goes over $14 (and the badge would change) because `Array.forEach` is `undefined` (I had no idea about this).
Using lodash-es' `forEach, the app doesn't break.
An alternative would be using `Array.from().forEach`, but lodash-es' `forEach` syntax is simpler, in my opinion. Let me know if you prefer the native method.
=> fix(patron): Fixing crash on slider

packages/app/src/app/store/modules/git/sequences.js
Bug fix. Closes #1131.
When the "Create Repository" button is clicked, the input's value is validated and when there is an error, it's saved in the `git.error` state. But when the user changes the input's value (maybe solving the previous error), the button doesn't become enabled again.
When the user changes the input's value, the `git.error` state is set to `null`, so the button become enabled again.
=> fix(github): Resetting error state when changing the repo title

packages/app/src/app/pages/Dashboard/queries.js
Bug fix.
After permanently deleting sandboxes, the grid is not updated because the `oldDeleteCache` is mutated when updating the cache.
Creating a `newDeleteCache` with all the previous data and overriding `me.sandboxes`, the grid is updated as expected.
=> fix(trash): Updating list of deleted sandboxes after permanent removal

packages/app/src/app/pages/Profile/Sandboxes/index.js, packages/app/src/app/store/modules/profile/actions.js, packages/app/src/app/store/modules/profile/sequences.js
Bug fix.
If you are on your profile and delete a sandbox, the sandboxes count is not updated.
The count is updated if the delete operation is successful.
=> fix(profile): Update sandboxes count after delete

packages/app/src/app/pages/Sandbox/SearchDependencies/DependencyHit/index.js
Really small but this was bugging me from my previous PR (#1110) - don't have an else so ternary is unnecessary :)
Use logical `&&` instead.
Ternary.
=> Remove ternary in favor of short &&

packages/app/src/app/components/Preview/index.js, packages/sandbox-hooks/url-listeners.js
This alters how the fake browser (`<Preview>`) manages its `history` state.
Fixes #1102.
Previously, all `urlchange` dispatches were treated as pushes (append URL to end of `history.state` and increment `state.historyPosition`). The fake browser's back and forward buttons got around this by manually updating the state, but manual `history.go()` and `history.replaceState()` calls resulted in an incorrect history array/position.
This behavior can be seen here:
https://codesandbox.io/s/vqw1mnnl9y
(steps to reproduce are described in #1102)
When `history.go()` is called, the `state.history` array is unchanged while the `state.historyPosition` is altered by the go amount.
When …
=> Correctly update history for pop and replace actions

packages/app/src/app/components/Preview/index.js, packages/sandbox-hooks/url-listeners.js
Follow up to #1158. I noticed that pushing locations when there is "future" history doesn't work correctly (the "forward" button is still active after pushing).
Pushing adds the new location to the end of the history array. This bug is hidden because the `<Preview>` keeps a `urlInAddressBar` property in state.
`history[historyPosition]` _should_ be usable everywhere that `urlInAddressBar` is. I can take a look at whether that works in another PR, but I'd rather get this fix merged in first.
Pushing a new location adds it after the current location, wiping out any "future" locations.
I also updated the `historyList` array kept in `url-listeners` to drop "future" locations when …
=> Pushing wipes "future" history

packages/app/src/app/components/Preview/elements.js, packages/app/src/app/components/Preview/index.js, packages/app/src/app/pages/Sandbox/Editor/Workspace/SSEDownNotice/index.js, packages/app/src/app/pages/Sandbox/Editor/Workspace/items/Server/Status.js, packages/app/src/app/store/factories.js, packages/app/src/app/store/modules/server/model.js
- Fixed "Server Connection Trouble" warning showing when hibernating a sandbox
- Added two more container statuses, `hibernated` and (unrecoverable) `error`
- On unrecoverable `sandbox:error`, show overlay and close the socket connection
- On recoverable `sandbox:error`, show toast notification
- Fixed "Server Connection Trouble" not showing on failed initial socket connection (now it shows after a 3 seconds timeout)
- Increased the showing time of toast notifications to 3 seconds (from 2), and 6 seconds for errors
- Refactored terminal messages
=>  SSE bug fixes & improvements

packages/app/src/app/pages/Sandbox/Editor/Content/index.js
Gets rid of a console warning
No warning
**Checklist**:
=> Use ref on host component

packages/common/templates/configuration/tsconfig/index.js, packages/common/templates/dojo.js
This fixes #1258 - issues with Dojo codesandboxes where TSX ends up using the wrong pragma via the following changes:
- Add /tsconfig.json as a configuration to the Dojo template
- Add a default tsconfig option for Dojo template
Current Dojo templates fail by trying to use `react.createElement`
This fixes Dojo templates to instead use the `tsx` pragma. 
**Checklist**:
I didn't see any tests for this portion of the code, but I am happy to add tests if I missed them!
=> Fix support for TSX in Dojo template

packages/app/src/embed/components/App/index.js, packages/common/__snapshots__/url.test.js.snap, packages/common/url.js
This is especially useful when looking with a phone. We automatically change the layout of embeds to vertical when width < height.
Curious what you think @SaraVieira, @lbogdan.
=> Default to vertical layout when height > width

packages/app/src/app/store/modules/workspace/actions.js, packages/app/src/app/store/modules/workspace/sequences.js, packages/app/src/app/store/providers/Router.js
This PR changes where the user is redirected after deleting a sandbox.
Fixes #1312 
The user is redirected to the new React template (`/s/new`).
The user is redirected to the sandbox wizard (`/s`).
**Checklist**:
=> Redirect to sandbox wizard when deleting sandbox

packages/app/package.json, packages/app/src/sandbox/eval/transpilers/babel/worker/babel-worker.js, packages/app/src/sandbox/eval/transpilers/babel/worker/dynamic-download.js, packages/app/src/sandbox/eval/transpilers/babel/worker/evaluate.js, packages/app/src/sandbox/eval/transpilers/svgr/index.js, packages/app/src/sandbox/eval/transpilers/worker-transpiler.js, yarn.lock
This change will detect if an error is thrown for a missing module, if this
error is detected we will try to traverse the file and download all remaining
dependencies recursively. We then sync this back to the manager so new babel
workers will have these files as well.
This comes down to having a mini bundler and file fetcher for every babel
worker to execute babel macros.
Fixes #981 #1266 #1179 #1286
=> Add support for dynamic macros

packages/app/src/app/pages/Patron/PricingModal/PricingInfo/index.js
Docs update.
Adds the fact that private github import is from patrons only
=> add private gh to patron features

packages/app/src/app/pages/Sandbox/Editor/Workspace/items/Deployment/index.js, packages/app/src/app/store/modules/deployment/actions.js, packages/app/src/app/store/modules/deployment/index.js, packages/app/src/app/store/modules/deployment/model.js, packages/app/src/app/store/modules/deployment/sequences.js, packages/common/templates/configuration/now/index.js, packages/common/templates/template.js
Adds support for zeit now version 2
Currently we have a counter and it had like 140 people so I guess it's time
If the now.json has `version:2` specified the new now platform will be used
Here is an example: 
https://codesandbox-v2-test.now.sh/graphql
Also all the other endpoints remained the same so it was easier then I thought o.o
cc @timothyis @rauchg
=> Add zeit 2 support

packages/app/src/app/utils/get-type.js
Is it a "feature"
Just add highlight for .mjs files.
- [V ] Documentation
- [ X] Tests
- [ V] Ready to be merged 
- [ X] Added myself to contributors table
=> add .mjs extension to utils/get-type

packages/app/src/app/components/CodeEditor/Monaco/index.js, packages/app/src/app/components/CodeEditor/VSCode/index.js
Fixes https://github.com/CompuIves/codesandbox-client/issues/1487
Does not use tsconfig compilerOptions for `jsxFactory` or `reactNamespace` which results in editor errors.
Uses tsconfig compilerOptions for `jsxFactory` or `reactNamespace`.
**Checklist**:
I don't think any Documentation needs to be updated as I believe this is desired behaviour (the correct options are passed to the actual ts transpiler). I tested the changes locally with the sandbox linked in the original bug report.
=> Use tsconfig setting for jsxFactory and reactNamespace in editor(s)

packages/app/src/app/pages/common/Notifications/Notification/elements.js
What kind of change does this PR introduce?
Fix a typo
What is the current behavior?
The word is spelled "verical-align"
What is the new behavior?
The word has been changed to "vertical-align"
**Checklist**:
=> fix typo, 'verical-align'  should be ' vertical-align'

packages/app/src/app/pages/Sandbox/SearchDependencies/index.js
This is to make sure we can correctly know how many of the queries are from codesandbox, and which kind of empty queries are done
Adds tags to the dependency search
no specific tags are sent
a tag "codesandbox-dependencies" is sent when people search for dependencies
**Checklist**:
=> add search analytics tag to dependencies search

packages/app/src/app/store/modules/deployment/actions.js
Fix
If you omit the `files` entry in your `now.json` then the deployment works without any issues but if you customize the `now.files` and you happen to have `package.json` in that list, it will be ignored from the deployment. If the package.json is omitted then zeit won't install the required dependencies.
Example configuration:
now.json
```
{
"version": 2,
"files": [
"index.js",
"package.json"
],
"builds": [{
"src": "index.js",
"use": "@now/node"
}]
}
```
package.json
```
{
"dependencies": {
"express": "4.16.4"
}
}
```
index.js
```
require('express');
```
The deployment of a sandbox with the configuration above will be successful but when you are trying to open your deployment it'll crash with an error of …
=> Do not silently ignore package.json in zeit deployment

packages/app/src/app/pages/Sandbox/Editor/Header/elements.js
- Create a new sandbox
- Give it a name (preferably something long)
- Try to click the codesanbox logo in the left top corner
The navigation container's centered style overrides the position of the logo's <a> element.
Removing `position: absolute` makes it clickable again. The title of the sandbox is not positioned the same way as before though.
=> Make CodeSandbox logo icon clickable again

packages/app/src/app/index.html, packages/app/src/embed/index.html
Partial fix of #1187 
codesandbox crashes in IE11
Fixed 
```
Syntax error
vanilla (6,27)
```
**Checklist**:
[Arrow functions#Browser compatibility](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions#Browser_compatibility)
=> fix: Syntax error in IE11

packages/app/src/app/pages/Sandbox/Editor/Header/index.tsx, packages/app/src/app/pages/Sandbox/Editor/Workspace/items/More/index.tsx
Fixes #844.
This is a first improvement:
After this, I'd like to work on a better feedback, maybe a circular loader inside the button. What do you think?
**Checklist**:
=> Disable fork button while forking

packages/app/src/app/pages/Sandbox/Editor/Content/index.js
Adds a min-width of 100px to both panes so you can't drag anything out of view
closes #1615
=> add min width 100 to both panes

packages/common/src/components/Preview/index.tsx
Bug fix
The browser preview starts with an empty `history` array in state and a `historyPosition` of `-1`. After initializing, the URL listener dispatches a `REPLACE`, which adds an entry to the preview's `history` array, but the `historyPosition` is still `-1`. This causes two incorrect behaviors: 1) the preview thinks that it can go forward immediately and 2) the preview can never return to the initial location.
(I made the `REPLACE` change in #1158, so I suppose that this bug is my fault. I'm not sure how I didn't notice the issue until now, but I didn't spot any other changes, so it must have existed since that PR.)
By starting with the `historyPosition` of `0`, the preview …
=> Start Preview's history at index of 0

packages/app/src/app/pages/Dashboard/Content/SandboxCard/index.js
Adds code to check if the user has click cmd(or ctrl)+ double click, if so opens the sandbox in a new tab
closes #1024
=> add cmd+click for opening in new tab in dashboard

packages/app/src/app/components/Preview/DevTools/index.tsx
Fix issue #639 where the terminal's height going way above the editor's height, resulting in issues with dragging.
https://github.com/CompuIves/codesandbox-client/issues/639
**Checklist**:
Added `flexShrink: 0` to the terminal. Necessary to ensure it drags naturally. Otherwise there's an issue where flex tries to allocate equal space to the preview and the terminal, resulting in a very jaggy experience
=> Set max size on drag resize handlers

packages/app/package.json, packages/app/src/app/pages/Sandbox/Editor/Content/__snapshots__/utils.test.ts.snap, packages/app/src/app/pages/Sandbox/Editor/Content/index.js, packages/app/src/app/pages/Sandbox/Editor/Content/utils.test.ts, packages/app/src/app/pages/Sandbox/Editor/Content/utils.ts, packages/common/src/templates/devtools/index.ts, yarn.lock
Add support for ?previewwindow and prevent duplicate tabs. Generally improves the function responsible for moving tabs since the mutations now happen in `immer`. There's now a smaller chance of mutation weirdness.
Fixes #1672
Fixes #1651
=> Preview Tabs Fixes

packages/homepage/src/screens/explore/SandboxModal.js
Fix issue #1699  where Second picked sandbox doesn't open in explore sandcodebox
#1699 
Able to open second picked sandbox in popup and navigate to left and right with new sandbox
**Checklist**:
=> Fix(homepage): Second picked sandbox doesn't open in explore

packages/app/src/app/pages/Dashboard/Content/CreateNewSandbox/Modal/index.js, packages/app/src/app/pages/GitHub/index.js
Adds a link from the import from Github to the actual link to import from GitHub.
In there is a link to the docs
closes #1209
=> fix UX confusion with Github

packages/app/src/app/pages/Sandbox/Editor/Header/index.tsx, packages/app/src/app/store/modules/editor/index.js
Added feature #1719 where Pick Sandbox is added at header when the user is the curator.
#1719 
The user who is a curator will see the Pick button at the header of the sandbox.
**Checklist**:
=> #1719 Pick Sandbox is now shown at header when user is a curator

packages/app/src/app/components/Preview/DevTools/Tabs/Tab/UnreadDevToolsCount.tsx, packages/app/src/app/components/Preview/DevTools/Tabs/Tab/index.tsx, packages/app/src/app/components/Preview/DevTools/Tabs/index.tsx, packages/app/src/app/components/Preview/DevTools/index.tsx
Only for the secondary devtools (so the bottom tabs)
=> Put the devtools counter back

packages/app/src/app/pages/Sandbox/Editor/Workspace/Dependencies/VersionEntry/index.js
A tooltip was added for each version entry action: 
- Show/Hide sizes
- Update to latest
- Remove
There is no tooltip and the Refresh button is not 100% obvious.
There is now a tooltip for each action
I had to force `outline: none` to avoid having a blue square around the icon:
=> Add a tooltip for each VersionEntry button

packages/app/src/app/components/Preview/DevTools/Terminal/index.js
Fixed bug #1654 where Terminal does not resize with its container
Terminal does resize with its container
**Checklist**:
The bug occurred when `ResizeObserver` was not called even though the HTML element `ResizeObserver` was listening to changed, I gave `height` and `width` to this element to `100%` to fix the issue.
=> Terminal does resize with it's container

packages/app/src/app/store/sequences.js
This issue fixes a bug and maintains resonance of the sandbox name between the dashboard and the header.
#1750 
Now the sandbox name between the dashboard and the header is same
**Checklist**:
=> Fix: Sandbox title is not changed, if the name change from dashboard

packages/homepage/src/screens/home/Frameworks/index.js
Bug fix - cosmetic
Currently the text & icons in the 'Tailored for web applications' section flow off the screen at mobile resolution.
Bug report - #1745 
- Text no longer flows off the screen 
- Framework icons can be scrolled horizontally by the user
- Homepage appears as before at desktop resolution
**Checklist**:
Scrolling behaviour could be removed and replaced with wrapping icons; but this could affect the UX of clicking a framework icon and viewing the information underneath.
=> Homepage - Fix frameworks text / icons overflowing at mobile rez

packages/app/src/app/pages/Sandbox/Editor/Header/index.tsx, packages/app/src/app/pages/Sandbox/Editor/Workspace/items/More/index.tsx, packages/common/src/components/Button/elements.ts, packages/common/src/components/Button/index.tsx, packages/common/src/components/ProgressButton/elements.ts, packages/common/src/components/ProgressButton/index.tsx
This is a follow-up of #1667.
The effect is simple because for now I didn't want to modify the markup of the button.
With my limited CSS skills, I think @CompuIves suggestion regarding nzbin.github.io/three-dots would require to have a div wrapper around the button and a div to display the 3 dots. Do we want to do this?
=> Show a loader on the button while forking

packages/react-sandpack/src/components/FileExplorer/ModuleList/ModuleList.tsx
Hi,
I want to try codesandbox in storybook (and thus vice versa)
When the project has not got any file in the subdirectory but only folders, 
the file explorer is not displaying anything.
This is a fix to the file explorer in react codesandbox
It will keep the display consistent accross any project.
This was debugged thanks to these unit tests : 
```javascript
import { modulesList } from './index'
test("empty list", () => {
const result = modulesList({}, '')
const { directoriesToShow, filesToShow } = result
expect(directoriesToShow).toEqual(new Set([]))
});
test("simple case", () => {
const result = modulesList({
"/src/panel.js": {},
"/src/panel.stories.js": {}, …
```
=> Bug fixed : file explorer not displaying anything

packages/app/src/app/pages/Dashboard/Content/SandboxCard/elements.ts
Make more explicit the clickability of the SandboxCard kebab button
Cursor is default
Cursor is pointer
=> Dashboard: show pointer cursor on KebabIcon

.circleci/config.yml, packages/app/src/sandbox/eval/manager.ts, packages/app/src/sandbox/eval/transpiled-module.ts, packages/app/src/sandbox/eval/utils/query-path.ts
When we downloaded a dependency dynamically we dropped the query path parameters, which in turn dropped `!raw-loader`. This PR fixes that.
Fixes #1784
**Checklist**:
=> Retain loader specification when downloading asynchronous dependency

docker/run-docker.sh, packages/app/src/app/store/modules/editor/sequences.js, packages/app/src/app/store/modules/live/actions.js
There were two big problems with the current live implementation:
1. We camelized keys in module sync, and the keys for shortids. So sometimes the wrong modules got synced back
2. Adding a dependency called changeCode two times, which caused an operation mismatch
3. For applyClient we didn't do an automatic repair, it could even crash the whole editor
This PR fixes those issues
=> Fix live syncing issues

packages/app/src/sandbox/eval/transpilers/typescript/index.ts, packages/app/src/sandbox/eval/transpilers/typescript/typescript-worker.js, packages/app/src/sandbox/eval/utils/get-dependencies.ts, packages/common/src/templates/angular.ts, packages/common/src/templates/configuration/types.ts, packages/common/src/templates/template.ts, packages/common/src/templates/vue.ts, packages/common/src/utils/is-babel-7.ts
Fixes #942
Fixes #1683
This doesn't change which version is used by the editor yet, I'm meaning to change this later by introducing a BrowserFS backend that can handle UNPKG.
=> Support dynamic typescript version from package.json

packages/app/src/app/pages/Dashboard/Content/SandboxCard/index.tsx, packages/app/src/app/pages/Dashboard/Content/SandboxGrid/index.js
Feature
#1844
Allows exporting a single Sandbox and multiple Sandboxes from the dashboard
**Checklist**:
The getSandbox function is copied from here (with track removed):
https://github.com/codesandbox/codesandbox-client/blob/5f09dec3a59fdec5b4f63c48feed6b050047c0f3/packages/homepage/src/screens/explore/SandboxModal.js#L46
Not sure if this should be duplicated here?
=> Export sandboxes from dashboard

packages/app/src/app/graphql/client.js
Instead of reassigning values on the result object, which previously required disabling eslint, this refactor uses ES6 object destructuring  and rest/spread to create a new result object.
**Checklist**:
=> Refactor GraphQL Result Param Reassignment

packages/app/src/app/pages/Dashboard/Content/routes/SearchSandboxes/index.js
At the moment, the search algorithm is too fuzzy in my opinion.
First, it give too much importance to the match being at the beginning of the text. This is why I've increased the distance from 100 (default) to 1000.
Then (and more importantly), it accepts matches that are pretty far. For instance, if I search for `"music"` it will match `"MUI icon bug"` or even more surprisingly `"unistore-rsm"` 🤔. This is why I've decreased the threshold from 0.6 (default) to 0.1. I came up picking this number after outputting the score of each match.
Please try it on your dashboard and let me know if those settings sound reasonable.
=> Dashboard: make the search less fuzzy

packages/app/src/app/pages/Dashboard/Sidebar/index.js, packages/app/src/app/pages/Dashboard/index.js
bufix
https://monosnap.com/file/O9IAIPM33jyxfAo86DvVzSwtHv4n3R
When user focuses on sandboxes search, it closes the side menu. 
We're passing history.push state to not close sidemenu when it is redirected from sandbox search input focus. 
**Checklist**:
=> [Dashboard] Keep sidebar open when search input is focused

packages/app/src/app/pages/GitHub/index.js
Update GitHub to functional component with Hooks
**Checklist**:
=> Refactor GitHub to functional component with hooks

packages/app/src/app/pages/Sandbox/Editor/Workspace/Dependencies/VersionEntry/index.js
Finishing of https://github.com/codesandbox/codesandbox-client/pull/1954
cc @Haroenv
=> Make more efficient query

packages/app/package.json, packages/app/src/app/index.js, packages/app/src/app/store/index.js, yarn.lock
I extracted @Saeris' changes to use `mobx-react-lite` out of #1925, so other PR's (like #1949 & #1951) can already make use of it.
It's not possible to use hooks whenever a component is wrapped in an `observer`.
It _is_ possible to use hooks whenever a component is wrapped in an `observer`.
**Checklist**:
=> Add mobx-react-lite

packages/app/src/app/pages/common/LikeHeart/index.tsx
It fixes the alignment of the Like button on the Project Info tab
=> Fix Like icon alignment in Project Info tab

packages/app/src/app/pages/Sandbox/Editor/Workspace/ConnectionNotice/ConnectionNotice.tsx, packages/app/src/app/pages/Sandbox/Editor/Workspace/ConnectionNotice/elements.js, packages/app/src/app/pages/Sandbox/Editor/Workspace/ConnectionNotice/elements.ts, packages/app/src/app/pages/Sandbox/Editor/Workspace/ConnectionNotice/index.ts
I've extracted @Saeris' changes to `ConnectionNotice` out of #1925.
> Small example refactor showing how to use Cerebral with React Hooks
- Use `mobx-react`
- Use `inject` HOC
- Use `mobx-react-lite`
- Use new `useStore ` hook
**Checklist**:
=> 🔨 Refactor ConnectionNotice to use hooks

.circleci/config.yml
When using `[ -n "$DOCKER_USER" ]` to check if the environment variable is set, the quotes are mandatory. PR https://github.com/codesandbox/codesandbox-client/pull/1786 removed the quotes, this PR adds them back.
=> CircleCI: fix check for environment variable not set

packages/app/src/app/pages/Sandbox/Editor/Workspace/WorkspaceItem/index.tsx, packages/app/src/app/pages/Sandbox/Editor/Workspace/index.tsx, packages/app/src/app/pages/Sandbox/Editor/Workspace/items/GitHub/CreateRepo/CreateRepo.tsx, packages/app/src/app/pages/Sandbox/Editor/Workspace/items/GitHub/Git/Git.tsx, packages/app/src/app/pages/Sandbox/Editor/Workspace/items/GitHub/GitHub.tsx, packages/app/src/app/pages/common/GithubIntegration/index.js
Fix TypeScript errors
`yarn typescheck` runs _with_ errors
`yarn typescheck` runs _without_ errors
**Checklist**:
=> Fix TypeScript errors

.eslintrc
`overrides` [should be an array](https://github.com/SchemaStore/schemastore/blob/master/src/schemas/json/eslintrc.json#L547)
`overrides` isn't an array
`overrides` is an array
**Checklist**:
=> Fix .eslintrc

packages/app/src/app/components/CodeEditor/VSCode/workbench-theme.css
Styling issue in firefox
File tab on editor requires a firefox prefix for `min-width`
- Checked the developer tools which was saying `invalid property`,  than checked the browser compatibility over [here](https://developer.mozilla.org/en-US/docs/Web/CSS/min-width#Browser_compatibility)
- Tested it over localhost:3000 on both chrome and firefox
**Checklist**:
Using CodeSandbox for more than a year. Really awesome work guys 💯
=> fix: add vendor prefix for file tab styling

packages/app/config/webpack.common.js, packages/app/config/webpack.prod.js, packages/app/src/app/index.html, packages/app/src/app/vscode/constants.ts, packages/app/src/app/vscode/metadata.ts, standalone-packages/vscode-extensions/out/extensions/jamesbirtles.svelte-vscode-0.7.1/package.json
Remove HTML ownership from svelte vscode extension.
The VSCode extension for Svelte overrode html files, which caused linting errors to appear in html files for other templates.
Svelte extension doesn't activate for html files.
Tested /s/vanilla and opened html files, tested autocomplete.
Tested /s/svelte and opened svelte files, tested autocomplete.
**Checklist**:
I had to force a new cache for vscode extensions, and because that path now changed we also need to update the cache of vscode itself.
=> Remove Svelte extension from html files

packages/app/src/app/components/CodeEditor/CodeMirror/index.js, packages/app/src/app/components/CodeEditor/Monaco/index.js, packages/app/src/app/components/CodeEditor/Monaco/mode.ts, packages/app/src/app/components/CodeEditor/MonacoDiff/index.js
Instead of returning `typescript` from `getMode` we return `undefined`, this makes it possible for the caller to set a default if `undefined` is returned.
We return `typescript` as default value for `getMode`, this causes our new linter (which supports `.ts`) to lint `package.json` and `.html` files etc. 
We return `undefined` in `getMode` if the mode is unknown, and change the existing calls to default to `typescript` to not break any existing behaviour.
- Tested if linting stopped happening in `package.json`
- Tested if linting happens in JavaScript/TypeScript
- Tested if syntax highlighting worked in CodeMirror editor (since …
=> Make getMode return undefined as default instead of 'typescript'

packages/app/src/app/pages/Dashboard/Content/Sandboxes/Filters/FilterOptions/index.js
Looks like a bug, but I am not sure if this was intentional 
Updating Filter option message when there are no deleted sandboxes
We currently see all the templates even when we don't have a deleted sandbox and when we deselect a template it shows message `Showing 0 templates` and in `OverlayContainer`, select all option is always checked. 
Now if we don't have sandboxes it shows `Showing 0 templates` with message `No templates found`.Check the below gif :
**Checklist**:
=> fix filter options in deleted sandboxes

packages/app/src/app/pages/Sandbox/Editor/Workspace/Dependencies/VersionEntry/index.js
Bug fix, fixes #1908
We check if a version is a string, if it's not a string we don't render the dependency in the dependency overview.
There is no check for a string, which causes React to error since we try to render an object.
No crashing editor on object for version :)
Loaded https://codesandbox.io/s/88zo93kxz0
**Checklist**:
=> Add a check to make sure that versions are strings in version UI

packages/app/src/app/pages/Sandbox/Editor/Workspace/index.tsx, packages/app/src/app/pages/Sandbox/Editor/Workspace/items/NotOwnedSandboxInfo/NotOwnedSandboxInfo.tsx, packages/app/src/app/pages/Sandbox/Editor/Workspace/items/NotOwnedSandboxInfo/index.ts
I've extracted @Saeris' changes to `NotOwnedSandboxInfo` out of #1925.
N/A
- Refactor code to TS
**Checklist**:
=> 🔨 Apply coding conventions to NotOwnedSandboxInfo Workspace

packages/app/src/app/store/getters.js
This PR aims to fix two bugs I noticed related to sign out that are described below.
- When you're on the dashboard and signs out, the dashboard doesn't update;
- When you're on a sandbox page and signs out, the sidebar doesn't update;
I believe the problem it's in how `hasLogIn` is computed, because it uses `store.jwt`, which doesn't get updated in the `signOut` sequence. I'm not sure if removing it from the computation is the proper fix to these problems, but since in [this commit](https://github.com/codesandbox/codesandbox-client/commit/705679b88d6057583587b8ab32539f3062a4a479#diff-fcc68a385e98ecb8fed8d41e68d69c39L14) the logic was changed to add `!!this.jwt` and not only use `!!store.get('jwt')` I …
=> fix(getters): Do not use store.jwt to compute hasLogIn

packages/app/src/sandbox/compile.ts, packages/app/src/sandbox/eval/transpilers/babel/worker/evaluate.js
Bug fix for sandboxes that use babel plugins from the `devDependencies`. Test case: https://codesandbox.io/s/hyperapp-playground-utmms.
The problem here was that we:
1. Didn't detect which devDependencies we need to download. We normally only download dependencies and download devDependencies that we see fit, this check didn't work for babel since it didn't flatten the config and wasn't able to find babel plugins defined in arrays.
2. Didn't convert the existing babel plugins from esModules to commonjs when running it in the babel-worker.
It will show a "Module Not Found".
We download the babel dependency and resolve it from the babel-worker.
**What steps did you take to test …
=> Fix dynamic downloading of babel dependencies

packages/app/src/app/pages/common/Modals/ShareModal/index.js
Bug fix.
When sharing on Twitter, if the `text` query string contains `&` characters, they will be interpreted as another parameter to the `intent/tweet` URL.
The link created works as expected.
Current URL: https://twitter.com/intent/tweet?text=7kj86.+https://codesandbox.io/s/purple-worker-7kj86?autoresize=1&fontsize=14&hidenavigation=1
New URL: https://twitter.com/intent/tweet?text=7kj86.%2Bhttps%3A%2F%2Fcodesandbox.io%2Fs%2Fpurple-worker-7kj86%3Fautoresize%3D1%26fontsize%3D14%26hidenavigation%3D1
=> fix(share): Text generation when sharing on Twitter

packages/app/src/app/pages/Dashboard/Sidebar/TrashItem/index.js, packages/app/src/app/pages/Dashboard/Sidebar/index.js
Bug fix.
When you are in a dashboard route that's not `dashboard/trash` (e.g `dashboard/recent`) and switch to the trash route, the menu doesn't update properly because the `TrashItem` component doesn't rerender.
And if you start in the `dashboard/trash` route and switch to another menu, the menu stays highlighted for the same reason above.
The menu updates properly in both cases described.
Note: Only passing down the `currentPath` prop would solve the problem, but I decided to add the `active` computation to prevent someone from thinking that the prop is useless and remove it, bringing back the bug.
Follow the use cases described in the current behaviour section.
=> fix(dashboard): Properly highlight the trash menu when the route is active

packages/homepage/src/components/layout.js
CSS Fix
Explore Modal does not open locally it gives the error of accessing from undefined. And I don't see any data on explore page. 
So I first tested it on live site using developer tools as in the above screenshot and did the required changes locally.
=> fix: Navbar and Explore Modal overlap

package.json, yarn.lock
babel/babel-eslint#772 is fixed by babel/babel-eslint#773, so we can use the official `babel-eslint` dependency again instead of [our own fork](https://github.com/codesandbox/babel-eslint).
The fork can be deleted too now.
=> Use official babel-eslint dependency instead of own fork

packages/app/src/app/components/Preview/DevTools/Tests/index.tsx, packages/app/src/sandbox/compile.ts, packages/app/src/sandbox/eval/tests/jest-lite.ts
Bug fix.
Preconditions:
- 15 files in the project
- 50 tests in 8 different files
- Tests tab is open
- Watching for tests is **on**
Editor freeze, sometimes quite often, when you write code because it runs tests after each editing
Editor freeze less often (at least twice less)
Test methodology described here with few test output:
https://gist.github.com/batiskafff/925f07637485ffc88940d47b36872bd1
Brief description:
- use sandbox https://codesandbox.io/s/boring-dawn-fzvzd 
- include performance meter component in UI
- edit code
It is proposal fix. It solves some issues, however, it is not the best possible solution for this issue.
The best possible solution from my opinion is added webworkers as test runner env, however, quite a big amount of dependency's and not simple implementation …
=> client test performance improvement, reduce screen freezing

packages/app/integration-tests/tests/__image_snapshots__/__diff_output__/.gitignore, packages/app/integration-tests/tests/sandboxes.test.js
~Description to come!~
This explicitly manages the sandbox loading timeouts, instead of only letting `jest` do that. For now, we're trying to load a sandbox twice, with a 30 seconds timeout (the idea being that, even if it times out the first time, it will most probably succeed on the second try). Also logs sandboxes loading times.
=> Integration tests improvements

packages/app/src/app/pages/Profile/Sandboxes/elements.js
When a user hasn't liked anything, it currently reads "You didn't like any sandboxes yet" which doesn't quite scan. This changes that to "You haven't liked any sandboxes yet" which reads a little better.
Grammar tweak.
When a user hasn't liked anything, it currently reads "You didn't like any sandboxes yet".
This changes that to "You haven't liked any sandboxes yet" which reads a little better.
N/A
=> grammar tweak to empty likes page

packages/app/scripts/start.js, packages/common/src/components/Preview/index.tsx, packages/executors/src/serverExecutor.ts
Fixes a problem of running local development build. After opening http://localhost:3000/s/new fails with a 404 because https://codesandbox.stream/api/v1/sandboxes/new returns a 404.
> `curl -i 'https://codesandbox.stream/api/v1/sandboxes/new'`
```
HTTP/2 404
date: Thu, 11 Jul 2019 14:44:20 GMT
content-length: 17
set-cookie: __cfduid=d18d203693b38a69bbdda5b58d427e9661562856260; expires=Fri, 10-Jul-20 14:44:20 GMT; path=/; domain=.codesandbox.stream; HttpOnly; Secure
cache-control: max-age=0, private, must-revalidate
x-request-id: 2mo62v80q6r814dai8007nbh
via: 1.1 google
alt-svc: clear
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
server: cloudflare
cf-ray: 4f4b8e0a2c92dbeb-LHR
```
/api requests are forwarded to to …
=> Fix local development build

packages/app/src/app/store/modules/editor/sequences.js
Right now we have some protection for duplicate saving, but I think they're not needed anymore now that we use VSCode by default. This removes the logic, and could possibly fix the 'file changed locally' logic.
=> Don't make a fuss about duplicate saving

packages/app/src/app/components/Preview/DevTools/Problems/index.tsx, packages/app/src/app/utils/corrections.ts
After 2c137cd these disable statements aren't necessary anymore.
N/A
N/A
Run `yarn lint` in the root of the project
=> Delete unnecessary eslint-disable

contributor-docs/adding-template.md
Closes #2160
`contributor-docs/adding-template.md` refers to `logos` folder
`contributor-docs/adding-template.md` refers to `codesandbox-templates` repo
N/A
=> Refer to codesandbox-templates repo instead of logos folder

package.json, packages/app/package.json, packages/codesandbox-api/package.json, packages/common/package.json, packages/deps/package.json, packages/dynamic-pages/package.json, packages/executors/package.json, packages/homepage/package.json, packages/node-services/package.json, packages/notifications/package.json, packages/react-embed/package.json, packages/react-sandpack/package.json, packages/sandbox-hooks/package.json, packages/sandpack/package.json, packages/sse-hooks/package.json
Specifying the directory as part of the `repository` field in a `package.json` allows third party tools to provide better support when working with monorepos. For example, it allows them to correctly construct a commit diff for a specific package.
This format was accepted by `npm` in npm/rfcs#19.
N/A
N/A
N/A
=> Add directory details to the package.json of all packages

packages/app/src/app/pages/Sandbox/Editor/Workspace/items/Deployment/Netlify/DeployButton/DeployButton.tsx, packages/app/src/app/pages/Sandbox/Editor/Workspace/items/Deployment/Netlify/SiteInfo/Actions/Actions.tsx, packages/app/src/app/pages/Sandbox/Editor/Workspace/items/Deployment/Netlify/SiteInfo/Actions/ClaimSiteButton/ClaimSiteButton.tsx, packages/app/src/app/pages/Sandbox/Editor/Workspace/items/Deployment/Netlify/SiteInfo/Actions/VisitSiteButton/VisitSiteButton.tsx, packages/app/src/app/pages/Sandbox/Editor/Workspace/items/Deployment/Netlify/SiteInfo/Functions/Function/Function.tsx, packages/app/src/app/pages/Sandbox/Editor/Workspace/items/Deployment/Zeit/DeployButton/DeployButton.tsx, packages/app/src/app/pages/Sandbox/Editor/Workspace/items/Deployment/Zeit/Deploys/Actions/Actions.tsx, packages/app/src/app/pages/Sandbox/Editor/Workspace/items/Deployment/Zeit/Deploys/Actions/AliasDeploymentButton/AliasDeploymentButton.tsx, packages/app/src/app/pages/Sandbox/Editor/Workspace/items/Deployment/Zeit/Deploys/Actions/DeleteDeploymentButton/DeleteDeploymentButton.tsx, packages/app/src/app/pages/Sandbox/Editor/Workspace/items/Deployment/Zeit/Deploys/Actions/types.ts, packages/app/src/app/pages/Sandbox/Editor/Workspace/items/Deployment/Zeit/Deploys/Deploys.tsx
Follow-up of #1969
Observe components that use the `useStore` hook
Components that use the `useStore` hook aren't observed
Components that use the `useStore` hook are observed
=> Observe deployment components

packages/app/src/sandbox/eval/transpilers/sass/worker/sass-worker.js
Fixes #2184 .
So this is weird: while trying to debug the above issue, I've noticed that, while it breaks on prod, it works fine on dev. Looking at the [sass/scss worker](https://github.com/codesandbox/codesandbox-client/blob/49645df97753c867652da1a030c7e5570990ecab/packages/app/src/sandbox/eval/transpilers/sass/worker/sass-worker.js#L6-L10), we're loading different (minified on prod vs. unminified on dev) `sass.js` bundles, and it seems like the minified one doesn't work?! Like I said - weird.
This PR uses the unminified bundle, regardless of environment, and also updates `sass.js` to the very next / latest `0.11.0` version.
You can see the test sandbox from the issue above failing in prod https://codesandbox.io/s/vue-template-set68 , and working in this PR build: …
=> Fix sass/scss

packages/app/src/app/components/CodeEditor/VSCode/index.tsx, packages/app/src/app/components/CodeEditor/types.js, packages/app/src/app/components/CodeEditor/types.ts, packages/app/src/app/pages/Sandbox/Editor/Content/index.js, packages/app/src/app/store/sequences.js
Change the change module check to use shortid instead of id. VSCode component tries to load a new module before the fs is finished loading, which is not even necessary in this case since in forks the module is the same.
=> Remove loading indicator for sandboxes

packages/common/.storybook/addons.js, packages/common/package.json, packages/common/src/components/SandboxCard/fixtures.ts, packages/common/src/components/SandboxCard/index.stories.tsx, packages/common/src/components/flex/fixtures.tsx, packages/common/src/components/flex/index.stories.tsx
Added storybook knobs to the SandboxCard stories. Also adds stories for the flex package
This adds a new feature to the existing storybook stories. There were previously no stories for the flex package.
Adds knobs to SandboxCard stories, that allows Storybook users to edit props and see the changes live in the story. Also adds stories with knobs for the flex package.
Tested locally.
=> Added knobs and additional stories

packages/common/src/components/flex/index.stories.tsx
Adds a "Flex Playground" story with configurable containers to the common package storybook.
Pre-configured flex stories
Users can configure the order of flex containers in the Playground 🚀 story.
Tested locally
=> Added flex playground :rocket:

packages/node-services/package.json, packages/node-services/src/module.ts, yarn.lock
Fixes #2288
Due to our dependency clean we actually lost some random dependencies like `string_decoder`. This adds it explicitly
=> Fix the string_decoder dependency missing

packages/common/src/components/Preview/index.tsx, packages/sandbox-hooks/url-listeners.js
Bug fix-ish
Currently the fake browser's history is stored in two places: the `Preview` component's state and in the `url-listeners` module. 
The history is only stored in the `url-listeners` module. Instead of having the `Preview` store an array of locations and an index, it keeps track of the current url and knows whether or not it can go backwards and forwards.
This PR also removes the automatic decoding of the URL displayed in the `Preview`'s address bar, which fixes #2050.
I have verified that it works as I expect it to with this sandbox: https://codesandbox.io/s/suspicious-river-unnjk This includes:
1. On load, neither forward nor back are usable
2. On navigation (push), the user can go back.
3. After going back, the user can go forward.
4. If you push while you can go forward, you …
=> Keep history in one place

packages/app/src/app/pages/common/Modals/ShareModal/getCode.js, packages/common/src/components/Preview/index.tsx
Closes #2304
Bugfix
See #2304. USB permission is blocked, so the only way to develop WebUSB sandboxes is to use the "open in new window" pop-out.
WebUSB is now allowed in the integrated preview window.
See repro steps in #2304. Using Chrome or Brave, enter `window.navigator.usb.requestDevice({ filters: []})` in the Preview console. It should open the browser's WebUSB device picker.
=> Add allow="usb" to Preview iframe

packages/app/src/app/components/Preview/DevTools/index.tsx, packages/app/src/app/pages/Dashboard/Content/CreateNewSandbox/NewSandboxModal/Imports/GitHubImport.tsx, packages/app/src/app/pages/Sandbox/Editor/Content/index.js, packages/app/src/app/pages/Sandbox/Editor/Workspace/items/Deployment/Netlify/DeployButton/DeployButton.tsx, packages/app/src/app/pages/Sandbox/Editor/Workspace/items/GitHub/CreateRepo/CreateRepo.tsx, packages/app/src/app/pages/common/Modals/DeploymentModal/index.js, packages/app/src/app/store/providers/Api.js, packages/app/src/embed/components/Content/index.tsx, packages/app/src/embed/index.js, packages/common/src/components/Navigation/index.tsx, packages/common/src/utils/analytics.ts, packages/homepage/src/screens/home/Animation/Title.js
Events added:
- `DevTools - Open Pane` (pane: pane.id)
- `DevTools - Move Pane` (pane: pane.id) (this one is called when moving a pane)
- `GitHub Import Wizard - Open Sandbox Clicked`
- `Deploy Clicked` (provider: 'netlify' | 'zeit')
- `Export to GitHub Clicked`
- `Non-Patron Server Sandbox Limit Reached`
- `Patron Server Sandbox Limit Reached`
- `Embed Interaction` (for every click in the embed, excluding preview)
- `Navigation - Create Sandbox Clicked` (click create sandbox in navigation of all static pages (homepage, docs, explore, blog))
- `Homepage - Open X Clicked` (template: templateName)
Also added the utm properties and the blacklist for VSCode.
=> Implement events

packages/app/src/app/pages/common/ErrorBoundary/CodeSadbox/CodeSadbox.tsx, packages/app/src/app/pages/common/ErrorBoundary/CodeSadbox/buildCrashReport.ts, packages/app/src/app/pages/index.tsx
Updated the crash report template to include the current URL so as to make it easier to hunt down where crashes are occurring. Also updated the template copy to make it more explicit that the user should use the template to write up a crash report.
When running the client locally, the `/codesadbox` route will now be available to make it easier to test changes to the error boundary components. This route is removed in production builds.
=> ✨ Add URL to Crash Report, Add CodeSadbox route in Development

.circleci/config.yml, .eslintrc, package.json, packages/app/package.json, packages/app/src/app/pages/index.tsx, packages/common/package.json, packages/deps/package.json, packages/dynamic-pages/package.json, packages/executors/package.json, packages/homepage/package.json, packages/node-services/package.json, packages/notifications/package.json, packages/notifications/src/component/Toast.tsx, packages/notifications/src/component/Toasts.tsx, standalone-packages/sse-loading-screen/package.json, standalone-packages/sse-loading-screen/yarn.lock, yarn.lock
This greatly simplifies our build setup, recursive dependencies
can go wrong very fast.
This:
- Reduces dependency builds from 1:39 to 0:35!
- Allows us to just run `yarn build:dev` for all dependencies
- Uses Lerna to find the most efficient way to build dependencies (parallelizes when possible)
- Removes dependency of common from notification, common needs notification as well and this resulted in a loop. Yarn especially found this hard, because it kept installing both versions, even older versions, because of the loop.
- Simplifies the dependency graph of `sse-loading-screen`, which should solve the `now` deploy issue.
- Reduces the size of node_modules with another `90mb`. Faster CI builds!
=> Make notifications not depend on common

packages/app/src/embed/components/File/index.js, packages/app/src/embed/components/Files/index.js
Enhancement in `Embed` sidebar
Fixes #2342 
All folders are open by default
Makes folders collapsable in the sidebar.
Demo: [staging](https://pr2370.build.csb.dev/embed/currying-violet-cvgmq?fontsize=14&module=%2Fpublic%2Fanother%2Fjust-messing.js)
By default, the folder containing the open file is open.
Manually test the embed 😅 
(tested with nested directories as well)
Nested folders don't remember their open states. Not sure if that's something we should fix here.
=> embed: make folders collapsable

packages/common/src/templates/template.ts
Development bug, not production bug 🤷‍♀ 
View options for React sandboxes are immutable, even though they are mutated in embed.
(introduced here: [#2252](https://github.com/codesandbox/codesandbox-client/pull/2252/commits/14c9111bf4ee88050a49f790de247e1cf65e2b32#diff-f304719feae663f65f8b7f1ae8a2ecc5R208))
Keep the options mutable. See story below
~~WoRkS oN My mAChiNe~~ Have tested that it doesn't break in dev mode anymore.
----
How embed options work: 
1. We load a config for view options from [templates](https://github.com/codesandbox/codesandbox-client/tree/master/packages/common/src/templates)
2. We manipulate this config based on the URL parameters of the embed url. There are only a [few of these](https://github.com/codesandbox/codesandbox-client/blob/master/packa …
=> Fix: React embed breaks with expanddevtools (only in dev mode)

packages/app/src/embed/components/Content/index.tsx
Fixes #2338, expects https://github.com/codesandbox/codesandbox-client/pull/2377 to be merged.
Embed does not respect `expanddevtools` flag. 
You can see this problem in server sandboxes which have the [console open by default](https://github.com/codesandbox/codesandbox-client/blob/master/packages/common/src/templates/template.ts#L71-L83), `expanddevtools=0` does not override that.
Demo: [embed/node?expanddevtools=0](https://codesandbox.io/embed/node?expanddevtools=0)
Embed uses the default open state from sandbox template (open for server templates), but let's the user override it with the `expanddevtools` flag
Demo: [staging/embed/node?expanddevtools=0](https://pr2378.build.csb.dev/embed/node?expanddevtools=0)
- [NA] Documentation (It's already documented, but doesn't work as …
=> [Fix] Embed: expandDevTools flag should override template default

packages/app/src/app/pages/common/Modals/PreferencesModal/Experiments/index.tsx
Master's build failing = all future builds are failing. Fixed.
> Absolute imports should come before relative imports  import/first
I'm not saying this rule is silly, but it's not super wise either 😋
=> Make eslint happy in app

packages/app/src/app/components/CodeEditor/Monaco/event-to-transform.js, packages/app/src/app/components/CodeEditor/VSCode/index.tsx
It seems like the one remaining issue with live is different carriage returns. We would already normalize CRLF to LF, but sometimes this would lead to transformations to the transforms and would cause some miscommunication between the server and the client. With this change we start accepting CRLF again, and the server knows how to handle it this time (Elixir apparently reads `\r\n` as 1 byte).
People don't have an issue with CRLF normally when using Live, but whenever they paste code with double carriage returns, the editor used to act up. This time it's fixed! Hopefully we can do some real testing tomorrow to see if everything works properly.
=> Fix carriage returns with live

packages/homepage/content/users.json
Added a transparent square logo in PNG format instead of older, skewed version.
Small update to website logo
=> Replaced skewed logo image

packages/app/src/app/components/Preview/DevTools/index.tsx
Fixes https://github.com/codesandbox/codesandbox-client/issues/2317
The devtools panel can be resized to a height can go beyond the size of it's container, which makes the `>` console part go under the screen (see gif)
The devtools panel stops at the `maxHeight` which is the height of it's container. (See deployed version)
- [NA] Added myself to contributors table
=> Devtools: Add max limit for height

packages/app/src/app/pages/common/Modals/SelectSandboxModal/Sandbox/elements.js
Bug Fix
While Changing the showcase sandbox, the date is cropped because of box sizing. Check the below screenshot: 
Added CSS to fix it. Check screenshot below: 
Tested Locally
=> fix: box-sizing for Select Sandbox Modal

packages/app/src/app/pages/Dashboard/Content/CreateNewSandbox/NewSandboxModal/MyTemplates/MyTemplates.tsx
Not a Bug but can be treated as UX Enhancement.  ( I am not sure if this was intentional )
If the user doesn't have templates and go to `/s` route he sees a blink of 3 templates loading box which is not visible for a long time. You can check the gif:
Fixed the logic to not show loader. Check gif below:
Tested Locally
=> fix: templates custom loading on new sandbox modal

packages/app/src/app/overmind/actions.ts, packages/app/src/app/overmind/effects/api/index.ts, packages/app/src/app/overmind/factories.ts, packages/app/src/app/overmind/namespaces/dashboard/actions.ts, packages/app/src/app/overmind/namespaces/editor/actions.ts, packages/app/src/app/overmind/namespaces/editor/internalActions.ts, standalone-packages/vscode-textmate/package-lock.json
This PR allows us to give a body to the `fork` call to the server, this way if you as a team create a sandbox we automatically assign the sandbox to the team. There was also some logic with `refetchSandboxInfo` that didn't set `editor.isLoading` to `false`, so added that too. Lastly I extracted our logic to join a live session as a team so we can reuse it in multiple places.
=> Fix creating a sandbox in overmind from dashboard as a team

packages/app/config/build.js, packages/app/src/app/components/CodeEditor/Monaco/workers/linter/index.js, packages/app/src/app/index.html, packages/app/src/app/vscode/extensionHostWorker/common/global.ts, packages/app/src/embed/index.html, packages/app/src/sandbox/eval/npm/fetch-npm-module.ts, packages/app/src/sandbox/eval/transpilers/babel/worker/babel-worker.js, packages/app/src/sandbox/eval/transpilers/babel/worker/index.js, packages/app/src/sandbox/eval/transpilers/sass/worker/index.js, packages/app/src/sandbox/index.html, standalone-packages/codesandbox-browserfs/src/core/backends.ts, standalone-packages/monaco-typescript/src/tsWorker.ts
Whenever we try to download dynamic files in a worker we need to write the
downloaded files to the filesystem. The reason for this is that we have a
separate fs in the worker that's synced eagerly (because when we need to execute
files in the worker we can only retrieve the files synchronously). We used to
save the files to the WorkerFS, the WorkerFS is responsible for downloading the
files from the main thread. But this FS would get confused by also writing to it
from the worker, and then get out of sync.
I now wrapped the WorkerFS with an OverlayFS so that writes are written on top of
the FS, but not to the FS. I had to bump our browserfs version for this.
=> Fix babel warning when downloading dynamic files in worker

packages/app/src/sandbox/eval/transpilers/babel/worker/babel-worker.js
Merged after https://github.com/codesandbox/codesandbox-client/pull/2464
TODO: 
Fixes #1935
The current behavior is the find the plugin from the list of resolved modules. This works really well for files that are in the dependency path of either
1. entry file of the project
2. entry file of the dependency
`babel` allows you to omit `babel-plugin-` while added it to babel config. So, if you add the `react` plugin, we will try to find `react` but fallback to `babel-plugin-react` or `@babel/react` based on the babel version.
This works for 99% of babel plugins because the entry file of the plugin itself can be used.
Example: [`babel-plugin-jsx`](https://www.npmjs.com/package/babel-plugin-jsx) resolves to it's [`index.js`](https://unpkg.com/babel-plugin-jsx@1.2.0/index.js)
Buuuut, you can …
=> Download missing plugins from error

packages/app/src/app/overmind/namespaces/editor/internalActions.ts
`executor.updateFiles` uses `module.savedCode` for sending changes, which was not set yet when we called it. I now moved `updateFiles` to after the `savedCode` field is set.
=> Fix container file updating

packages/app/src/app/pages/Dashboard/Sidebar/index.js
Fix
#2482 
#2496
#2487
#2484
#2497
#2495
#2505
We check if `me` node exists and also use an empty array as default teams
=> Prevent crash on team items

packages/homepage/src/templates/_docs.elements.js, packages/homepage/src/templates/_job.elements.js, packages/homepage/src/templates/_post.elements.js, packages/homepage/src/templates/docs.js, packages/homepage/src/templates/job.js, packages/homepage/src/templates/post.js
This is the follow-up of #2420, where I've make the `docs` template a function component and put all styles in their own `.elements` file.
- `docs` is a class component
- most styles are in the templates themselves
- `docs` is a function component
- all styles are in their own `.elements` file.
Check if the pages still look the same
=> Cleanup homepage templates

packages/app/src/app/components/ContextMenu/index.tsx
Bugfix
When the transition ends the height and width is `auto`, because of this we don't have the menu measurements
#2501
This is a quick fix, I think this requires a better refactor of `ContextMenu`
before:
after:
=> show popover

packages/app/src/app/overmind/actions.ts
As requested by @christianalfoni in https://github.com/codesandbox/codesandbox-client/pull/2532#discussion_r328996362
Not sure if I should extract the new `ModalName` type into `@codesandbox/common` so I just kept it in `actions.ts` for now.
=> Restrict modal opened action

packages/app/src/app/pages/Sandbox/Editor/Workspace/Project/Frozen/Frozen.tsx
fix
When you turn off the forzen behavior of custom templates, you can't turn on again
You can switch the freeze state
Before:
After:
=> toggle freeze state on customTemplates

packages/app/src/app/overmind/actions.ts, packages/app/src/app/pages/common/ErrorBoundary/CodeSadbox/CodeSadbox.tsx, packages/app/src/app/pages/common/ErrorBoundary/CodeSadbox/buildCrashReport.ts
Small refactor to make the switch to Overmind.
Removed the title from the generated crash report, which will now require users to enter their own in order to be able to submit the report. Hopefully this makes crash reports more descriptive. Crash Reports now include the proper label automatically when they are generated.
@christianalfoni there appears to be an issue with Overmind in this component, as isLoggedIn returns false even when the user is in fact logged in (test this by running locally and navigating to http://localhost:3000/codesadbox from another page). Not quite sure how to solve this one, so I'd appreciate it if you can investigate! Probably has something to do with the error boundary.
=> 🔨 Switch CodeSadbox to useOvermind, Remove title, add label to Report

packages/sandbox-hooks/url-listeners.js
Nothing. Just ESLint fixes in url-listeners.js
=> fix eslint issues in url-listeners

packages/app/src/app/overmind/effects/api/index.ts, packages/app/src/app/overmind/effects/live/index.ts, packages/app/src/app/overmind/effects/utils/sandbox.ts
The sandbox transform was not called for a sandbox that was received from a live
session, this adds it
=> Fix joining live session

packages/app/src/app/pages/Dashboard/Content/SandboxCard/index.tsx, packages/app/src/app/pages/Dashboard/Content/SandboxGrid/index.js, packages/app/src/app/pages/Dashboard/queries.js
Normally we've loaded the cached screenshot of a sandbox in the dashboard,
this change ensures that we try to download a new version of a screenshot
if the sandboxcard has been in the screen long enough and we know that the
screenshot is outdated.
=> Make sure to load the last screenshot in the dashboard

packages/app/src/app/overmind/effects/api/index.ts, packages/app/src/app/overmind/effects/utils/sandbox.ts
In 4297f1da027a1912a61a7e0708b2e29af70a9c3c we've introduced new fields to module and directory, but we never changed the existing calls that get these from the API. Because of this, live sessions stopped working and uploading files. I now went through all times that we actually retrieve modules and directories from the API and made sure to add the transform, this is a quick fix but we might want to revisit this later as this feels a bit fragile. We either need to update the typings on what we receive from the API or do something else.
This is also related to #2620.
=> Add transforms for modules and directories

packages/app/src/app/pages/index.tsx
`app/pages/index.tsx` was using `inject` and `hooksObserver` from `app/componentConnectors`
uses `useOvermind` from `app/overmind`
Opened the homepage, /s/new page
ran `yarn lint` and `yarn typecheck`
=> 🔨 Refactored 🧠 Overmind Hacktober | app/pages/index.tsx : refactor to replace Cerebral with Overmind

packages/app/src/app/pages/CLI/index.tsx
This is part of the requested refactor for hacktoberfest mentioned in #2621.
@Saeris @christianalfoni 
Previously it was utilizing `inject` and `hooksObserver` from `app/componentConnectors`.
#2621 
Prefers `useOvermind` over `inject` and other small stylistic choices mentioned in #2621 
- `yarn:lint`: There were several linting errors, but none relevant to the scope of this PR
- `yarn:test`: Ran successfully
I was unable to add the 🔨 Refactor, 🧠 Overmind, or Hacktoberfest labels.
=> 🔨 Refactored app/pages/CLI/index.tsx

packages/app/package.json, packages/app/src/app/pages/Curator/index.js, packages/app/src/app/pages/Dashboard/Content/SandboxGrid/index.js, packages/app/src/app/pages/common/Modals/SelectSandboxModal/Sandbox/index.js, packages/app/tsconfig.check.json, yarn.lock
Fix
The sandbox dates (`insertedAt`, `updatedAt`, `deletedAt`) is received with format `2019-09-19 11:29:27.280934` this format now allow parsed with the right timezone
#2465 
There are two changes
1. Add `date-fns` to `app` scope
2. use [date-fns-tz](https://date-fns.org/v2.2.1/docs/Time-Zones) to parse the dates as utc dates and then `formatDistanceToNow` can parsed with the user time zone
*Before:*
*After*
=> show right time zone

packages/app/src/app/pages/Sandbox/Editor/Header/Header.tsx, packages/app/src/app/pages/Sandbox/Editor/Header/types.ts
`/Sandbox/Editor/Header/Header.tsx` was using `inject` and `hooksObserver` from `app/componentConnectors`
uses `useOvermind` from `app/overmind`
Opened the homepage, changed sandbox name
ran `yarn lint` and `yarn typecheck`
=> 🔨 Refactored 🧠 Overmind Hacktober | /Sandbox/Editor/Header/Header.tsx  : refactor to replace Cerebral with Overmind

packages/app/src/app/pages/Sandbox/Editor/Workspace/items/Files/index.js, packages/app/src/app/pages/Sandbox/Editor/Workspace/items/NotOwnedSandboxInfo/NotOwnedSandboxInfo.tsx, packages/app/src/app/pages/Search/Filters/index.js, packages/common/src/templates/icons.ts, packages/common/src/templates/iconsDark.ts, packages/common/src/templates/iconsLight.ts
Fixes here:
* Renames template to environment in search
* 404 was fixed in the dashboard of algolia
* Remove Dependencies from static template
* changes the Parcel Icon to be the JS Icon
=> Assorted Fixes

.all-contributorsrc, CONTRIBUTING.md, README.md, package.json, yarn.lock
[`v6.0.0`](https://github.com/all-contributors/all-contributors-cli/releases/tag/v6.0.0) (which is [used](https://github.com/all-contributors/all-contributors-bot/blob/455134d55738dc29d1baf7cd761e0b5cfe19314e/package.json#L27) by the `all-contributors-bot`) introduced the HTML-based format instead of the Markdown one.
Markdown-based format of contributors-table
HTML-based format of contributors-table
Check that `README` isn't changed
=> Update all-contributors-cli dependency so it's compatible with all-contributors-bot

packages/app/src/app/pages/common/Modals/Changelog/Dashboard/index.tsx, standalone-packages/vscode-textmate/package-lock.json
Refactor code for hacktoberfest [#2621](https://github.com/codesandbox/codesandbox-client/issues/2621)
@Saeris @christianalfoni @SaraVieira 
`/app/pages/common/Modals/Changelog/Dashboard/index.js` was using `inject` and `observer` from `app/componentConnectors`
uses `useOvermind` from `app/overmind` and `js` file converted to `tsx` file
ran `yarn lint` and `yarn typecheck`
I can't add labels to the PR
=> 🔨 Refactored 🧠 Overmind Hacktober | /app/pages/common/Modals/Changelog/Dashboard/index.js

packages/app/src/app/components/Preview/DevTools/Console/index.tsx, packages/app/src/app/components/Preview/DevTools/index.tsx
Before we would clear the counter of a devtool (unread count) whenever the devtools opens, also for problems and tests. It only makes sense to do this for the console though, so I moved this logic from the base devtools to the console devtools.
Tested:
- Open console and verify that counter doesn't go up on console.log
- Close console and verify that counter goes up on console.log
- Open console and verify that counter resets
- Open Problems and verify that counter stays the same
I'm talking about these counters:
=> Change behaviour of devtools counter

packages/app/src/app/components/Preview/DevTools/Tabs/elements.ts, packages/app/src/app/pages/Sandbox/Editor/Content/index.js
Bugfix
if you open a few browser tabs, you can access all of them
1. Create a gatsby sandbox
2. Add a lot of graphiQL tabs
3. Try to access all browser tabs
=> fix handle browser tabs overflow 

packages/app/src/app/overmind/namespaces/live/liveMessageOperators.ts
Fix #2719
We send a notification about user entering the session even if it's turned off in notifications. Seems like the check was missing from `onUserEnter` (it's present in `onUserLeft`)
It might be worth looking at other notifications as well. 
Could not test this on local (can't start live session on local), will test on staging
=> Live: Don't send userEnter notification if notifications are turned off

packages/app/src/app/pages/common/Modals/SearchDependenciesModal/index.js
🔨 Refactored, 🧠 Overmind, Hacktober | Refactor SearchDependenciesModal which now uses useOvermind
@Saeris @christianalfoni @SaraVieira 
`app/pages/common/Modals/SearchDependenciesModal/index.js` was using `inject` and `hookObserver` from `app/componentConnectors`
Uses `useOvermind` hook from `app/overmind`
1. Checked whether the functionality is working or not by opening add dependency modal in sandbox
2. Ran `yarn lint`
3. Ran `yarn test`
=> 🔨 Refactored, 🧠 Overmind, Hacktober | Refactor SearchDependenciesModal which now uses useOvermind

packages/app/src/app/pages/Sandbox/Editor/Workspace/items/Deployment/Netlify/SiteInfo/Actions/VisitSiteButton/VisitSiteButton.tsx
`VisitSiteButton.tsx` was using `inject` and `hooksObserver` from `app/componentConnectors`
uses `useOvermind` hook from `app/overmind`
1. Deployed app on local using `yarn start`.
2. From sandbox workspace deployed `https://csb-ooxu7.netlify.com` using `Netlify beta`.
In this process verified the link text `Building...` and then `Visit`.
3. Checked functionality of `Visit` and it was working fine.
4. Ran `yarn lint`, `yarn test` & `yarn typecheck` successfully.
=> 🔨 Refactored 🧠 Overmind Hacktober | VisitSiteButton.tsx : refactor to replace Cerebral with Overmind

packages/app/src/app/pages/common/UserMenu/Menu/elements.tsx, packages/common/src/templates/icons.ts, packages/common/src/templates/iconsDark.ts, packages/common/src/templates/iconsLight.ts
Fix some typings
- `packages/app/src/app/pages/common/UserMenu/Menu/elements.tsx`:
- `props` of `ItemA`, `ItemButton` & `ItemLink` have type `any`
- `packages/common/src/templates/icons.ts`, `packages/common/src/templates/iconsDark.ts` & `packages/common/src/templates/iconsLight.ts`
- return-type is set manually
- `packages/app/src/app/pages/common/UserMenu/Menu/elements.tsx`:
- `props` of `ItemA`, `ItemButton` & `ItemLink` are invoked correctly
- `packages/common/src/templates/icons.ts`, `packages/common/src/templates/iconsDark.ts` & `packages/common/src/templates/iconsLight.ts`
- return-type is invoked
N/A
=> Fix typings

packages/app/src/app/overmind/internalActions.ts, packages/app/src/app/pages/DevAuth/elements.ts, packages/app/src/app/pages/DevAuth/index.tsx, packages/app/src/app/pages/index.tsx
Before it wouldn't be possible to sign in a dev environment on `localhost` without copying over the `jwt`. This allows you to actually do it.
Instead of the normal flow we open a new path (only for dev) called `/auth/dev`. This popup prompts you to open `codesandbox.io/cli/login`, which will generate a token we can use to sign in. If you give this token we will do the API call to do get the `jwt` to return that.
This way we can test the sign in flow in localhost!
I tested this with my own account.
=> Add dev auth for localhost

packages/common/src/templates/template.ts
Bug Fix
React Devtools are shown on every template. 
`Reason`: When manipulating `REACT_VIEWS` it also updates `CLIENT_VIEWS` because of same reference ( nested object ) thus we see react devtools on every template. 
Check this vue template: 
Fixed the same reference issue.
1. Open Angular, Vue and few other templates for checking
2. Open react templates to check if devtools show up
=> fix: devtool constant value reference

package.json, testpr-script.js, yarn.lock
Allows you to easily test a PR:
Note the number of the PR, in this example: `2787`
In the root of client run: `yarn test:pr 2787`
It will automatically checkout the PR and update and build the deps. This is just to ensure the environment is correct related to testing.
If you want to make changes you can do so by:
- Just push the automatically created branch to Github as normal
- Create a new PR, but choose the existing PR (2787) as the source
- This creates a PR on the repo of the contributor and the contributor has to merge in this change, so write a comment on the original PR pointing to what needs to be merged in
I think this creates a really good collaborative feeling for the contributor. We are helping them helping us, instead of overriding what they are doing.
=> add script to test prs

packages/app/src/app/pages/Sandbox/Editor/Workspace/Project/Project.tsx
Fixes #2621 
\app\src\app\pages\Sandbox\Editor\Workspace\Project\Project.tsx was using Cerebral
\app\src\app\pages\Sandbox\Editor\Workspace\Project\Project.tsx now uses Overmind
1. Replaced inject and hooksObserver with useOvermind
2. yarn test
3. yarn lint
=> 🔨 Refactor, 🧠 Overmind, Hacktoberfest - \app\src\app\pages\Sandbox\Editor\Workspace\Project\Project.tsx

packages/app/src/app/components/Alert/Alert.tsx
The typings of the Alert component didn't support eg. `<span>aa</span>` according to the typings, but it works in the component and is used this way in some places. This adds it as an option.
=> Add react elements support for the alert component

packages/app/src/app/pages/Search/index.js
Refactor `/app/pages/Search/index.js` #2621 @Saeris @christianalfoni
It was using cerebral for state management
It uses Overmind for state management with help of useOvermind hook
1. yarn lint
2. yarn typecheck
3. yarn test
=> refactor: /app/pages/Search/index.js  🔨 Refactor, 🧠 Overmind 

packages/app/config/build.js, packages/app/src/app/components/CodeEditor/Monaco/workers/linter/index.js, packages/app/src/app/index.html, packages/app/src/app/overmind/effects/api/index.ts, packages/app/src/app/overmind/effects/api/types.ts, packages/app/src/app/overmind/effects/live/index.ts, packages/app/src/app/overmind/effects/moduleRecover.ts, packages/app/src/app/overmind/effects/utils/sandbox.ts, packages/app/src/app/overmind/namespaces/editor/actions.ts, packages/app/src/app/overmind/namespaces/editor/internalActions.ts, packages/app/src/app/vscode/extensionHostWorker/common/global.ts, packages/app/src/embed/index.html, packages/app/src/sandbox/eval/transpilers/babel/worker/index.js, packages/app/src/sandbox/eval/transpilers/sass/worker/index.js, packages/app/src/sandbox/index.html, packages/common/src/types/index.ts, standalone-packages/codesandbox-browserfs/src/backend/CodeSandboxEditorFS.ts, standalone-packages/monaco-typescript/src/tsWorker.ts
`savedCode` can be `null` whenever `savedCode === code`. However, we often get values this way: `savedCode || code || ''`. This doesn't work when `savedCode` is `''`, and `code` is a filled string. I'm not sure if this has caused many bugs before, but this definitely can cause inconsistencies. This change adds explicit checks.
I also created specific types for the API, also updated some existing types to use `null` instead of `undefined` (elixir doesn't know what undefined is). We need to look out for cases where properties are added to sandbox which are not included in the API, this can cause performance problems (all components using the sandbox update). This is an attempt at making that more clear, but maybe we should just put the whole API response inside the API typings and then make …
=> Appreciate property of savedCode more

packages/app/src/app/overmind/actions.ts, packages/app/src/app/pages/Sandbox/Editor/Workspace/Dependencies/AddVersion/index.tsx, packages/app/src/app/pages/Sandbox/Editor/Workspace/Dependencies/index.tsx
`app/pages/Sandbox/Editor/Workspace/Dependencies/AddVersion/index.js` was using Cerebral
`AddVersion` now uses `overmind` hook from the new state management tool, Overmind.
1. Replaced inject and hooksObserver with useOvermind
2. Convert `AddVersion` class component to functional component.
3. Add `searchDependencies` to the list of values the `ModalName` type can take in `app/overmind/actions.ts`
4. Use named export in `AddVersion` and update `pages/Sandbox/Editor/Workspace/Dependencies/index.tsx` accordingly.
5. Ran `yarn test`
6. Ran `yarn lint`
=> 🔨 Refactor, 🧠 Overmind | pages/Sandbox/Editor/Workspace/Dependencies/AddVersion/index.js

packages/app/src/app/pages/Sandbox/Editor/Workspace/items/ConfigurationFiles/elements.ts, packages/app/src/app/pages/Sandbox/Editor/Workspace/items/ConfigurationFiles/index.tsx, packages/common/src/types/index.ts
`/app/pages/Sandbox/Editor/Workspace/items/ConfigurationFiles/index.js` was using `Cerebral`
`/app/pages/Sandbox/Editor/Workspace/items/ConfigurationFiles/index.tsx` now using `Overmind`
1. Replaced `inject` and `observer` with `useOvermind`
2. Converted `js` files to `ts` and `tsx`
3. Added some missing types!
`files.moduleCreated()` also expected `directoryShortid` to be a `string` or `null`
4. Ran `yarn test`
5. Ran `yarn lint`
6. Ran `yarn typecheck`
=> 🔨 Refactor, 🧠 Overmind | /app/pages/Sandbox/Editor/Workspace/items/ConfigurationFiles/index.js

packages/app/src/app/pages/common/Modals/MoveSandboxFolderModal/index.js
🔨 Refactored, 🧠 Overmind, Hacktober | Refactor MoveSandboxFolderModal to use overmind
@Saeris @christianalfoni @SaraVieira
`app/pages/common/Modals/MoveSandboxFolderModal/index.js` was using `inject` and `hookObserver` from `app/componentConnectors` and also it was a class component with no lifecycle methods
Refactored `MoveSandboxFolderModal` to FC and replaced `inject`, `hookObserver` with `useOvermind`
1. Checked whether the folder is changed as expected by opening the modal when clicked on the label before the name of the sandbox.
2. Ran `yarn lint`
3. Ran `yarn test`
=> 🔨 Refactored, 🧠 Overmind, Hacktober | Refactor MoveSandboxFolderModal to use overmind

packages/app/src/app/pages/Dashboard/Sidebar/TemplateItem/TemplateItem.tsx
@Saeris @christianalfoni @SaraVieira
`/app/pages/Dashboard/Sidebar/TemplateItem/TemplateItem.tsx` was using inject and observer from app/componentConnectors
No reference to `signals` or `store` from inject and removed the dependencies.
ran `yarn lint` and `yarn typecheck`
=> 🔨 Refactored 🧠 Overmind Hacktober | /app/pages/Dashboard/Sidebar/TemplateItem/TemplateItem.tsx : refactor to remove Cerebral

packages/app/src/app/pages/common/UserMenu/Menu/index.tsx
Add an item to user menu to go to search, it was pretty hard to find initially:
=> Add Search to user menu

packages/app/package.json, packages/app/src/app/pages/Dashboard/Sidebar/TemplateItem/TemplateItem.tsx, packages/app/src/app/pages/common/ErrorBoundary/ErrorBoundary.tsx, yarn.lock
@Saeris @christianalfoni 
This PR adds `@types/react-router-dom` to `app` repo in order to get correct `react-router-dom` components typing.
Which is necessary to convert current `react-router-dom` components usage in `js` files to `ts` files, such as: `app/src/app/pages/Dashboard/Content/routes/PathedSandboxes/Navigation/elements.js`
Currently there is no typing for all `react-router-dom` components, so there is no type checking for `props` assigned to them.
Also `withRouter()` hoc, can take any components no matter if it expects `RouteComponentProps` or not.
This PR will introduce `react-router-dom` type checking for its usage.
And `withRouter()` hoc would expect component explicitly expects `RouteComponentProps`.
PS: I am not aware of why some of the component is wrapped in …
=> Chore: Add react-router-dom typing

packages/common/src/components/Preference/index.tsx
@Saeris @christianalfoni 
Fix bug where the props variants are not in sync with actual individual `Preference` component props, which needs to be fixed in order to refactor different `styled-components` styling `Preference` to `tsx` files.
eg. `src/app/pages/common/Modals/PreferencesModal/elements.js`
Current `*Preference` props types are redefined in `packages/common/src/components/Preference/index.tsx` which are not in sync with actual `*Preference` components props.
Using different `Props` from actual `*Preference` component, and refactor `Preference` to be a `React.FC` without `children` prop.
1. yarn test
2. yarn lint
3. yarn typecheck
=> Fix <Preference /> component props typing

packages/app/src/app/pages/common/Modals/DeleteProfileSandboxModal/index.tsx, packages/app/src/app/pages/common/Modals/index.js
=> 🔨 Switch DeleteProfileSandboxModal to use useOvermind

packages/app/src/app/pages/Sandbox/Editor/Workspace/Project/Keywords.tsx
Changing from types to Interface for Component Props for #2621 @Saeris @christianalfoni 
The component props were using type system to handle props and its data types
The component props use interface to handle props and its data type
yarn test
yarn lint
yarn typecheck
yarn start, go to Dashboard, drag things no error## Checklist
- [ x] Documentation
- [ x] Testing 
- [ x] Ready to be merged
- [ x] Added myself to contributors table
=> 🔨 Refactor, 🧠 Overmind Hactoberfest | Refactor /app/pages/Sandbox/Editor/Workspace/Project/Keywords.tsx to use interface instead of types

packages/app/src/app/pages/Dashboard/Sidebar/TrashItem/index.tsx
`/app/pages/Dashboard/Sidebar/TrashItem/index.js` was using `Cerebral`
**I think the `Cerebral` usage was unnecessary, (please correct me if I'm wrong) so I removed it.** Then convert the file to `typescript` and added needed types.
1. Manually tested it to check that it still works
2. `yarn test`
3. `yarn lint`
4. `yarn typecheck`
=> 🔨 Refactor /app/pages/Dashboard/Sidebar/TrashItem/index.js (Remove Cerebral)

packages/app/src/app/pages/common/Modals/FeedbackModal/Feedback.tsx, packages/app/src/app/pages/common/Modals/FeedbackModal/elements.ts, packages/app/src/app/pages/common/Modals/FeedbackModal/index.tsx
=> 🔨 Switch FeedbackModal to use useOvermind

packages/app/src/app/pages/common/Modals/PreferencesModal/EditorPageSettings/EditorSettings/index.tsx
This is a refactor related to #2621
@Saeris  @christianalfoni 
EditorSettings component was using inject and hooksObserver from app/componentConnectors.
- Refactored to use useOvermind from app/overmind
- Changed extension of the file from .js to .tsx
1. Run yarn test
2. Run yarn lint
3. Run yarn typecheck
=> 🔨 Refactor, 🧠 Overmind Hactoberfest | Refactor app/pages/common/Modals/PreferencesModal/EditorPageSettings/EditorSettings/index.js to use Overmind

packages/app/src/embed/components/Header/elements.js, packages/app/src/embed/components/Header/index.js
Master: The liked heart turns white on hover, which is a strange feedback for the liked state. 
This PR: The heart stays red in liked state. It does turn white (from grey) in unliked state.
=> Embed - remove hover feedback for liked heart

packages/homepage/content/docs/2-importing.md
Small docs update to include `codesandboxer-fs` as a way to upload files (I think this is realistically more useful than the `react-codesandboxer` docs beneath it)
Quick note on this: the fragmentation of tools is weird here, dating back to legacy stuff on `codesandboxer` being built out mostly independently of codesandbox itself more as an extension. It seems like it would make sense to make the `codesandbox` CLI itself work for both directories and files, to avoid recommending two different installs, but this was a quick fix to at least document this capability.
=> add codesandboxer-fs docs

packages/app/src/app/pages/Dashboard/Content/routes/PathedSandboxes/index.js
Fixed type error reported in #2777 
@Saeris @CompuIves 
No safe check for undefined `data.me`
Added a safe-check for the same
1. Step A
2. Step B
3. Step C
=> fix #2777: added safecheck for undefined data.me

packages/app/src/app/overmind/onInitialize.ts
fix
#2822
Possibly related
#2911 #2836
1. Create a React TS sandbox
2. Fork sandbox
3. Save file or add new dependency
=> Fix typescript error

packages/common/package.json
This lets `yarn test` work on Windows (without installing something like `win-node-env`).
Fix to test script to let tests run on Windows .
Running `yarn test` returns an error:
> @codesandbox/common@1.0.8 test C:\repos\open-source\codesandbox-client\packages\common        
> NODE_ENV=test jest                                                                            
lerna ERR! npm run test stderr:                                                                 
'NODE_ENV' is not recognized as an internal or external command,                                
operable program or batch file.    
Tests run successfully on Windows!
1. Ran `yarn test` and verified successful output.
2. Ran `yarn start` to verify app still runs.
=> Use cross-env to run tests

packages/app/src/app/pages/Sandbox/Editor/Workspace/Chat/index.js, packages/app/src/app/pages/Sandbox/Editor/Workspace/Chat/index.tsx, packages/common/src/types/index.ts
Changing `Chat` component to use Typescript and Overmind as part of #2621 @Saeris @christianalfoni
`Chat` component uses `inject` and `observer` and does not benefit from types.
`Chat` component uses `useOvermind` and Typescript.
1. `yarn lint`
2. `yarn test`
Wasn't able to open the component locally, so no manual testing unfortunately.
I ran into some issues with Typescript, also it would be great to have someone take a look at the class-to-functional-component change - in particular, I'm not 100% sure about my ref implementation. 
I'll mark the pain points in code additionally.
=> 🔨 Refactor, 🧠 Overmind Hactoberfest | Refactor /app/pages/Sandbox/Editor/Workspace/Chat/index.js to use Overmind and Typescript

packages/app/src/app/pages/CliInstructions/index.tsx, packages/app/src/app/pages/index.tsx
@Saeris @christianalfoni 
`packages/app/src/app/pages/CliInstructions/index.tsx` was using `inject` and `hooksObserver` from `app/componentConnectors`
uses `useOvermind` from `app/overmind`
run `yarn test`, `yarn typecheck` and through `lint-staged` also tried to run the app with `yarn start`
=> 🔨 Refactored 🧠 Overmind Hacktober | /app/pages/CliInstructions/index.tsx : refactor to replace Cerebral with Overmind

packages/app/src/app/pages/Sandbox/Editor/Workspace/Project/Project.tsx, packages/app/src/app/pages/Sandbox/Editor/Workspace/items/GitHub/Git/Git.tsx, packages/common/src/components/GithubBadge/index.stories.tsx, packages/common/src/components/GithubBadge/index.tsx, packages/homepage/src/screens/explore/SandboxModal.js
For imported direct commits we will show the first 7 characters of the `commitSha`, so the short `commitSha`.
Makes this:
Show as this:
=> Improve showing of commit sha

packages/app/package.json, packages/app/src/sandbox/compile.ts, packages/app/src/sandbox/eval/npm/fetch-npm-module.ts, packages/app/src/sandbox/npm/fetch-dependencies.ts, packages/app/src/sandbox/npm/index.ts, packages/app/src/sandbox/version-resolving/index.ts, packages/app/src/sandbox/version-resolving/merge-dependency.ts, packages/app/src/sandbox/version-resolving/resolutions.ts, packages/app/src/sandbox/version-resolving/resolve-dependency.ts, packages/common/src/templates/template.ts
This adds support for the `resolutions` field in `package.json`, more info of this is here: https://yarnpkg.com/lang/en/docs/selective-version-resolutions/.
A sandbox that should start working with this: https://codesandbox.io/s/vr435. This makes it so that `@test-library/react` will resolve the CI version of `@test-library/dom` instead of the npm version using these resolutions:
```
"resolutions": {
"@testing-library/react/@testing-library/dom": "https://pkg.csb.dev/testing-library/dom-testing-library/commit/5603c87b/@testing-library/dom"
}
```
=> Add support for version resolution

packages/app/src/app/pages/common/Modals/ShareModal/getCode.js, packages/homepage/content/docs/2-embedding.md
After @garethx' PR for dev.to (https://github.com/thepracticaldev/dev.to/pull/4575), I figured it might be nice to update the embed docs to be in line with the actual implementation too, so embeds are less error-prone out there.
Embed docs aren't in line with actual implementation
Embed docs are in line with actual implementation
1. Go to the [embed docs](https://pr2923.build.csb.dev/docs/embedding)
- [N/A] Added myself to contributors table
=> Update embed docs to be in line with actual implementation

packages/app/src/app/pages/Patron/PricingModal/PricingChoice/ChangeSubscription/index.tsx
This is part of the requested refactor for hacktoberfest mentioned in #2621.
Previously it was utilizing inject and hooksObserver from app/componentConnectors.
#2621
Prefers useOvermind over inject
* yarn:lint: There were several linting errors, but none relevant to the scope of this PR
* yarn:test: Ran successfully
=> Refactored 🧠 Overmind Hacktober | patron/subscription: /app/pages/Patron/PricingModal/PricingChoice/ChangeSubscription/index.ts

packages/app/src/app/pages/Profile/Showcase/SandboxInfo/index.js, packages/app/src/app/pages/Profile/Showcase/index.js
Improvement. Not sure if this was intentional as the like button doesn't work but I guess its better to not show like in Editor at the top.
Like button visible in showcase even when the user is logged out.
Show like button only when logged in, like in editor.
- Tested this page locally
=> fix: show like button on showcase title when the user is logged in

packages/app/src/embed/components/Sidebar/SandboxInfo/index.js
Improvment
In embed, we show `id` as a fallback if the title is not defined
Show `alias` as a fallback. Not sure if this makes sense but for consistency between app and embed it will make sense. As on app, the title is set to alias by default.
1. Local testing
=> embed: show alias instead of id as fallback title

packages/app/src/app/pages/common/Modals/PreferencesModal/Appearance/index.tsx, packages/app/src/app/pages/common/Modals/PreferencesModal/elements.js, packages/app/src/app/pages/common/Modals/ShareModal/elements.js, packages/common/src/components/Preference/PreferenceDropdown.tsx, packages/common/src/components/Preference/PreferenceKeybinding/index.tsx, packages/common/src/components/Preference/PreferenceNumber.tsx, packages/common/src/components/Preference/PreferenceSwitch.tsx, packages/common/src/components/Preference/PreferenceText.tsx, packages/common/src/components/Preference/elements.ts, packages/common/src/components/Preference/index.stories.tsx, packages/common/src/components/Preference/index.test.tsx, packages/common/src/components/Preference/index.tsx, packages/common/src/templates/configuration/elements.ts
Updated the props of `Preference` and it's child components and also refactored the child components to `FunctionComponent`s.
Follow-up of #2861
- `Preference`'s child components are `ClassComponent`s
- `Preference`'s child components export their props separately so they can be used by `Preference`
- `Preference`'s child components are `FunctionComponent`s
- `Preference`'s child components don't export their props separately and `Preference` derives the props of his child components by using the [`ComponentProps` generic](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/8e0fa6fc55e715ccd9ee1656ba4ce2106067fbf9/types/react/index.d.ts#L777-L782)
- [N/A] Documentation
- [N/A] Added myself to contributors table
=> Fix Preference's types

packages/app/src/app/pages/Sandbox/Editor/Workspace/Dependencies/VersionEntry/index.tsx
=> Fix scoped packages rendering in version entry view

packages/app/src/app/overmind/actions.ts, packages/app/src/app/overmind/effects/api/index.ts, packages/app/src/app/overmind/factories.ts, packages/app/src/app/overmind/internalActions.ts, packages/common/src/types/index.ts
With the move to Overmind we forgot to port over our userFeedbackSurvey behaviour from Cerebral. This puts it back in.
Tested the flow by removing the `if` check and confirming that the notification asking about the survey would pop up. Then verified that the modal opened with the typeform.
=> Add back user feedback survey behaviour

.all-contributorsrc, README.md, packages/app/src/app/pages/common/Modals/PreferencesModal/Experiments/index.tsx
changing module to use typescript #2621 
1. Step A
2. Step B
3. Step C
- [x ] Ready to be merged
=>  :hammer: Refactor, 🧠 Overmind and hacktoberfest | changes done for app/pages/common/Modals/PreferencesModal/Experiments/index.tsx

packages/app/src/sandbox/eval/transpilers/babel/worker/babel-worker.js
With this change we do preset downloading in the babel worker, exactly how we do it with plugins right now.
Makes https://codesandbox.io/s/los71 work.
=> Enable babel preset downloading

packages/app/src/app/pages/Dashboard/Content/SandboxCard/index.tsx
Screenshots don't get updated when a sandbox updates. For example, when you have two sandboxes next to eachother in the dashboard, and the first sandbox gets deleted, then the second sandbox gets the screenshot of the first sandbox. This is because our memoized state is not updated all the time. This makes that possible.
=> Fix showing screenshot in the dashboard

packages/app/src/embed/components/Content/index.tsx, packages/common/src/components/Preview/index.tsx
Allows for disabling our preview animation, which is pretty slow in the editor (it was built for the embed).
=> Allow for disabling the preview screenshot

packages/app/src/app/pages/Sandbox/Editor/Workspace/Dependencies/AddFont/index.js, packages/app/src/app/pages/Sandbox/Editor/Workspace/Dependencies/index.tsx
Enhancement
Disable button and update the button message:
1. Visual test
2. The button is disabled so repeated fonts don't get added
Also on another note. Sometimes the dropdown doesn't show up for typeface and when there is an advertisement it pops below and goes out of the screen. Any idea on this? I am happy to help on this issue as well :)
=> fix(ux): disable button for already added fonts

packages/app/src/app/pages/common/Modals/ShareModal/index.js
One line change = fun line change
Goes well with https://github.com/codesandbox/codesandbox-client/pull/2941
By default, we show navigation bar in the embed. It's useful for sandboxes with multiple routes
That default hasn't aged well, majority of sandboxes don't have routes.
Ideally, we'd like to keep the navigation hidden unless an explicit flag asks for it. Example: `showNavigation=true`.
But that would change the behavior of existing embeds aka 🚨 backward breaking change 🚨
We can however, set `hideNavigation=1` for every new embed in the share sheet. This adds some fluff to the url but maintains backward compatibility.
=> Embed: Change default of hideNavigation to true (with backward compatibility)

packages/app/src/app/overmind/effects/zeit.ts
Bug fix. Closes #2486, closes #2357.
In some ocasions, we are sending two `package.json` files.
We are comparing the correct property (`file` instead of `name`) and adding some typings to reduce the change of bugs on ZEIT's effects file.
1. Fork [this sandbox](https://codesandbox.io/s/nodenow-mdjn4);
2. Try to deploy it to ZEIT Now;
3. Verify that the deploy is successful.
When I added the typings, I noticed that we were trying to access a default property (`type` from `nowDefaults`) that had no value. Should we add something there?
=> fix(deployments): use correct property to compare filename

packages/app/src/app/pages/Profile/Showcase/SandboxInfo/elements.ts, packages/app/src/app/pages/Profile/Showcase/SandboxInfo/index.tsx, packages/app/src/app/pages/Profile/Showcase/index.tsx
=> Fix SandboxInfo

packages/homepage/content/docs/8-ci.md
=> Fix typo in CI doc

packages/app/src/embed/components/App/index.js
Bug Fix
When in `Embed` you dislike ( removing the current like ) the like counter does `-2` i.e if number of likes were `1` it goes to `-1`.
Reason: 
For instant feedback, the like is updated when we click heart button and on receiving the response we do `-1` which causes inconsistency. I have used the response from Backend to reflect on state.
Consistent behavior
1. Tested Locally by replicating the bug
Great work guys on the new embed design. Looks really awesome!!! 🔥 💯
=> fix(embed): likes counter on dislike shows inconsistent value

packages/app/src/app/components/CodeEditor/VSCode/index.tsx, packages/app/src/app/overmind/namespaces/editor/internalActions.ts, packages/app/src/app/overmind/namespaces/live/liveMessageOperators.ts, standalone-packages/codesandbox-browserfs/src/backend/CodeSandboxEditorFS.ts
Upon saving a file it is automatically emptied by the other user. This is because the other user applies `savedCode = undefined` (because we read `data.savedCode` instead of `data.module.savedCode`), which in the `fs` then is seen as empty code. It sends that back as return.
=> Fix live empty files

packages/app/src/app/overmind/factories.ts, packages/app/src/app/pages/common/Modals/StorageManagementModal/AddFileToSandboxButton/elements.js, packages/app/src/app/pages/common/Modals/StorageManagementModal/AddFileToSandboxButton/index.js, packages/app/src/app/pages/common/Modals/StorageManagementModal/FilesList/index.js, packages/app/src/app/pages/common/Modals/StorageManagementModal/index.tsx
Bug fix. Closes #3077.
I noticed a few issues on the Storage Management modal:
1. If you select two files, unselect one of them and press to delete, we send the id for both files because we are not filtering which files have `{ [id]: true }`;
2. If you try to delete a file outside the editor, it fails because we try to access `state.editor.currentSandbox.owned` without checking for `currentSandbox` first;
3. If you open the modal outside the editor, the buttons to add files to the project are enabled.
1. We are only sending the current selected files;
2. We are checking for `currentSandbox` before trying to read `currentSandbox.owned`;
3. We are disabling the button and tooltips for adding files to the project when the modal is opened outside the editor.
1. Open the modal outside the …
=> fix(storage-management): fix behavior outside of a sandbox context

packages/app/src/sandbox/eval/tests/jest-lite.ts, packages/common/package.json, yarn.lock
Bug fix. Closes #502, closes #1744, closes #1997.
On Firefox and Safari, you can get an `Unexpected frame by generating stack` error. I believe this error was a false positive because it was removed on the version 1.1.2 of `error-polyfill`.
The error is thrown and the expected behaviour on the three linked issues happen.
1. Open the sandboxes on the linked issues;
2. Verify that the expected behaviour in all of them happen on Chrome, Firefox and Safari.
=> fix(tests): update error-polyfill to fix unexpected frame error

packages/app/src/app/pages/common/Modals/PreferencesModal/CodeFormatting/Prettier/index.tsx, packages/app/src/app/pages/common/Modals/PreferencesModal/CodeFormatting/elements.ts, packages/app/src/app/pages/common/Modals/PreferencesModal/CodeFormatting/index.tsx
Follow-up of #2759
- Export `Prettier` by a named export  instead of a `default export`
- Type `Prettier`'s `bindValue` function
=> 🔨 Switch CodeFormatting to use useOvermind

packages/app/src/app/overmind/namespaces/preferences/actions.ts, packages/app/src/app/pages/common/Modals/PreferencesModal/Badges/index.tsx
Follow-up of #2760
- Change `setBadgeVisibility`'s signature to get its argument types directly from `Badge` instead of hardcoding them
- Just use `badges.length` instead of an extra `badgesCount` variable
- Simplify `Badge`'s `onClick` prop a bit
=> 🔨 Switch Badges to use useOvermind

packages/app/src/app/overmind/namespaces/dashboard/actions.ts, packages/app/src/app/pages/Dashboard/Content/CreateNewSandbox/elements.ts, packages/app/src/app/pages/Dashboard/Content/CreateNewSandbox/index.tsx, packages/app/src/app/pages/Dashboard/Content/routes/PathedSandboxes/index.js, packages/app/src/app/pages/Dashboard/Content/routes/RecentSandboxes/index.tsx
Follow-up of #2720
- Make `CreateNewSandbox` a `FunctionComponent` (instead of `SFC`, since it's [deprecated](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/f13238a5d2086cd87f3209704f8897f7f701d957/types/react/index.d.ts#L497-L503)) and improve it's `Props` type
- Cleanup `CreateNewSandbox` a bit (`Spring`'s `from` & `to` prop + the way `mostUsedSandboxComponent` is created)
- Export `CreateNewSandbox` by a named export  instead of a `default export`
=> 🔨 Switch CreateNewSandbox to use useOvermind

packages/homepage/src/screens/home/NPMFeature/index.js
Minor text update
The current text has missing spaces between words and has absent letters in some words
Add spacing between words. Add missing letters in words.
=> Fix spacing in homepage text

packages/app/src/app/components/Preview/DevTools/Tests/TestSummary/elements.ts
Bug fix. Closes #3002.
The sync's icon opacity doesn't change regardless of the `watching` state.
It changes as expected. I used the [documented styled-components hack to override higher specificity](https://www.styled-components.com/docs/faqs#how-can-i-override-styles-with-higher-specificity) applied by the `Actions` component targeting `svg` tags.
1. Visit [this sandbox](https://codesandbox.io/s/formation-javascript-avance-vnsp4);
2. Toggle file watching for tests;
3. Verify that the opacity changes as expected.
=> fix(tests): apply correct opacity to sync icon when watching tests

packages/app/src/app/overmind/effects/zip/create-zip/index.ts
Feature. Closes #488.
Lock files are ignored. (Is there any reason for this behavior?)
They are included in the zip file.
1. Open any sandbox;
2. Click to export it.
3. Verify that the lock file is included on the zip file.
If there is a reason to ignore these files, please close the issue.
=> feat(download): export lock files when downloading sandbox

packages/app/src/app/overmind/namespaces/deployment/actions.ts
Bug fix. Closes #3019.
We are displaying a generic error message when a request to ZEIT Now fails.
According to [ZEIT Now's API documentation](https://zeit.co/docs/api#errors), every error contains the same structure, always with a `message` property. We are now trying to access this property from the error but displaying the generic error as a fallback.
1. Fork [this sandbox](https://codesandbox.io/s/share-server-xvwzh);
2. Try to deploy it to ZEIT Now;
3. Verify that the error from the API is displayed.
There are other issues related to deployment regarding duplicate `package.json` files.
I'll try to solve them with another PR later.
=> fix(deployments): display error messages from ZEIT Now

packages/app/src/app/overmind/namespaces/files/internalActions.ts, packages/app/src/app/pages/Sandbox/Editor/Workspace/Files/DirectoryEntry/DirectoryEntryModal/index.tsx, packages/app/src/app/pages/Sandbox/Editor/Workspace/Files/DirectoryEntry/Entry/EditIcons/index.js, packages/app/src/app/pages/Sandbox/Editor/Workspace/Files/DirectoryEntry/Entry/index.tsx, packages/app/src/app/pages/Sandbox/Editor/Workspace/Files/DirectoryEntry/index.js, packages/app/src/app/store/modules/files/actions.js, packages/common/src/components/Button/elements.ts
Feature. Closes #2796.
There is no clear way to discard changes on modules.
Just like in VSCode's Git tab, there is an undo icon to discard changes on each file. It requires confirmation to proceed.
1. Open any sandbox;
2. Modify any file inside it;
3. Verify that an undo icon appear when you hover the file on explorer;
4. Click on the undo icon;
5. Verify that a modal pops up to confirm the action;
6. Cancel it and verify that nothing changes;
7. Confirm it and verify that the changes are gone.
There are some other changes within this PR:
- Modified the `Button`'s CSS, which closes #2733;
- Fixed the message when there is only one file recovered;
- Created one component to handle the modals to the explorer actions.
=> feat(explorer): improve discard changes functionality

packages/app/src/app/overmind/namespaces/editor/actions.ts
Fixes https://sentry.io/organizations/codesandbox/issues/1333824380/?project=155188&query=first-release%3APROD-1573738286-c05030adf.
The module itself is not crucial, if it doesn't exist we also don't need to set the error array to length 0.
=> Ignore error where an error is thrown when a module is not found

packages/app/src/app/overmind/effects/live/index.ts, packages/app/src/app/overmind/effects/vscode/SandboxFsSync/index.ts, packages/app/src/app/overmind/effects/vscode/index.ts, packages/app/src/app/overmind/namespaces/editor/actions.ts, packages/app/src/app/overmind/namespaces/live/actions.ts, packages/app/src/app/overmind/namespaces/live/internalActions.ts, packages/app/src/app/overmind/namespaces/live/liveMessageOperators.ts, packages/app/src/app/overmind/utils/sandbox.ts
Some extra fixes:
1. Change the syncing logic to only sync on change
2. We didn't sync if you join a sandbox with a live session as owner (`/s/:id`), I moved the syncing to live initialize to make sure that it always happens
3. We now debounce the selection updates when typing.
=> QOL improvements

packages/app/src/app/components/SandboxList/SandboxList.tsx
Improvement
Currently the fallback in Showcase page is `id`
Use the common method to get the name from sandbox
Local Testing and checking the value 
There is only one component where we are not getting the title correct and it is in `common/Modals/SelectSandboxModal`. The values are fetched from `/api/users/username/` and I am not sure how to fix it. Any help in this is appreciated :)
Thanks & sorry for this small change.
=> fix: title for showcase page

packages/app/src/app/pages/common/Modals/PreferencesModal/Appearance/EditorTheme/elements.ts, packages/app/src/app/pages/common/Modals/PreferencesModal/Appearance/EditorTheme/index.tsx, packages/app/src/app/pages/common/Modals/PreferencesModal/Appearance/elements.ts, packages/app/src/app/pages/common/Modals/PreferencesModal/Appearance/index.tsx, packages/common/src/components/Preference/PreferenceText/elements.ts, packages/common/src/components/Preference/PreferenceText/index.tsx
Follow-up of #2806
- Extract `EditorTheme` into its own component
=> 🔨 Switch Appearance to use useOvermind

packages/app/src/app/pages/Patron/index.tsx, packages/app/src/app/pages/Sandbox/Editor/Header/Header.tsx
Logic: 
```js
// not logged in, go to pro
if (!isLoggedIn) {
location.href = '/pro';
}
// don't send them away before authentication
if (hasLoadedApp && user) {
if (
!user.subscription || // if no subscription, get pro
user.subscription.plan !== 'patron' // if subscription but not patron, go to pro
) {
location.href = '/pro';
}
}
```
=> Add checks for patron redirect + remove badge from editor

packages/common/src/components/Preview/index.tsx
When changing urls with "pushState" / "history" it does a refresh now. This PR fixes that. Tested using history and location. Location does full refresh, as it should, while history just changes the url.
This issue might have been introduced realted to `vscodeeffects` as some changes was necessary related to "smooth" forking.
=> fix preview reload on history changes

packages/app/src/sandbox/eval/transpilers/svelte/svelte-worker.js
Fix. Closes #3094. 
Svelte replaced `magic-string` with `code-red` on version `3.13.0` and with this, CodeSandbox can't compile Svelte components anymore because it relies on `toUrl` to [generate inline sourcemaps](https://github.com/codesandbox/codesandbox-client/blob/master/packages/app/src/sandbox/eval/transpilers/svelte/svelte-worker.js#L143).
I've added a fallback function to generate the source maps like [`magic-string` does](https://github.com/Rich-Harris/magic-string/blob/master/src/SourceMap.js#L27).
I've opened [a PR](https://github.com/Rich-Harris/code-red/pull/22) to add this method to `code-red` but I'm not sure if it's the right approach or will even get merged. However, if we want to output sourcemaps, we'd need this because since 3.13.0, Svelte is "broken" on this matter. …
=> fix(svelte): add fallback toUrl method to generate sourcemaps

packages/app/src/app/pages/common/Modals/PreferencesModal/EditorPageSettings/EditorSettings/index.tsx
It is easy to miss the comment that a browser refresh is necessary for VIM to be enabled/disabled. Also it is not really VIM being enabled, it is the extension itself being enabled or not. You control its enabled/disabled state from the command palette
=> Improve experience of enabling VIM

packages/app/src/app/overmind/namespaces/editor/actions.ts, packages/app/src/app/pages/Sandbox/Editor/Header/Buttons/LikeButton/LikeButton.tsx, packages/app/src/app/pages/common/LikeHeart/MaybeTooltip.tsx, packages/app/src/app/pages/common/LikeHeart/index.tsx
Resubmission of #2855
Follow-up of #2635
- Change `likeSandboxToggled`'s signature to accept a `string` instead of `{ id: string }`, because it only has 1 argument
- Extract `MaybeTooltip` into a separate file
- Improve `LikeHeart`'s props type
=> 🔨 Switch LikeHeart to use useOvermind

packages/app/src/app/overmind/namespaces/deployment/actions.ts, packages/app/src/app/pages/Sandbox/Editor/Workspace/items/Deployment/Zeit/Deploys/Actions/AliasDeploymentButton/AliasDeploymentButton.tsx
Resubmission of #2844
Follow-up of #2742
- Change `aliasDeployment`'s signature to accept a `string` instead of `{ id: string }`, because it only has 1 argument
=> 🔨 Switch AliasDeploymentButton to use useOvermind

packages/app/src/app/pages/common/Modals/NetlifyLogs/elements.ts, packages/app/src/app/pages/common/Modals/NetlifyLogs/index.tsx, packages/app/src/app/pages/common/Modals/index.tsx
Follow-up of #2727
- Cleanup `useEffect` call
- Export `NetlifyLogs` by a named export  instead of a `default export`
=> 🔨 Switch NetlifyLogs to use useOvermind

packages/app/src/app/pages/Sandbox/SignOutNoticeModal/elements.ts, packages/app/src/app/pages/Sandbox/SignOutNoticeModal/index.tsx
Follow-up of #2655
- Make `SignOutNoticeModal` a `FunctionComponent`
I think this component (`SignOutNoticeModal`) can be deleted tho, since it's not used anymore? 🤔
=> 🔨 Switch SignOutNoticeModal to use useOvermind

packages/app/src/app/pages/CliInstructions/index.tsx
=> 🔨 Switch CLIInstructions to use useOvermind

packages/app/src/app/pages/CLI/Prompt/elements.ts, packages/app/src/app/pages/CLI/Prompt/index.tsx, packages/app/src/app/pages/CLI/index.tsx, packages/app/src/app/pages/index.tsx
Resubmission of #2848
Follow-up of #2623
- Move `overmind` subscriptions as close as possible to the components itself instead of passing it through
- Use a `ref` for `TokenInput`'s `onClick` instead of using the `MouseEvent`'s `target`
- Export `CLI` by a named export  instead of a `default export`
=> 🔨 Switch CLI to use useOvermind

packages/app/src/app/components/DelayedAnimation.ts, packages/app/src/app/overmind/namespaces/explore/actions.ts, packages/app/src/app/pages/Curator/elements.ts, packages/app/src/app/pages/Curator/index.tsx, packages/app/src/app/pages/Sandbox/Editor/Header/Buttons/PickButton/PickButton.tsx, packages/app/src/app/pages/index.tsx, packages/common/src/types/index.ts
Follow-up of #2864
- Make `DelayedAnimation`'s `delay` prop really optional
- Change `popularSandboxesMounted`'s signature to accept a `string` instead of `{ date: string }`, because it only has 1 argument
- Change `pickSandboxModal`'s signature to get its argument types directly from `PickedSandboxDetails` instead of hardcoding them
- Export `Curator` by a named export  instead of a `default export`
=> 🔨 Switch Curator to use useOvermind

packages/app/src/app/overmind/namespaces/patron/actions.ts, packages/app/src/app/pages/Patron/PricingModal/PricingChoice/ChangeSubscription/elements.ts, packages/app/src/app/pages/Patron/PricingModal/PricingChoice/ChangeSubscription/index.tsx, packages/app/src/app/pages/Patron/PricingModal/PricingChoice/index.tsx, packages/common/src/types/index.ts
Follow-up of #2654
- Change `updateSubscriptionClicked`'s signature to accept a `string` instead of `{ coupon: string }`, because it only has 1 argument
- Move `overmind` subscriptions as close as possible to the components itself instead of passing it through
- Type `StripeInput`'s `onChange` prop
- Type `LinkButton`'s `onClick` prop
=> 🔨 Switch ChangeSubscription to use useOvermind

packages/app/src/app/pages/NewSandbox/elements.ts, packages/app/src/app/pages/NewSandbox/index.tsx
=> 🔨 Switch NewSandbox to use useOvermind

packages/app/src/app/overmind/namespaces/dashboard/actions.ts, packages/app/src/app/pages/Dashboard/Content/routes/Templates/Mine/index.tsx
Feature.
To delete a template, the user needs to open it first.
There is a new option to delete a template from the dashboard.
1. Create a template if you don't have any;
2. To go Dashboard > My templates;
3. Right-click a template and select `Delete Template`;
4. Verify that the template is removed and the dashboard is updated.
The new action is very similar to `workspace.deleteTemplate` but without pulling data from the `state` and without updating the (opened) sandbox. Should I refactor and reuse that? I wouldn't like to but it's up to you.
=> feat(dashboard): add option to delete template

packages/app/src/app/overmind/namespaces/live/actions.ts, packages/app/src/app/pages/Sandbox/Editor/Workspace/items/Live/index.tsx
Follow-up of #2663
- Change `createLiveClicked`'s signature to accept a `string` instead of `{ sandboxId: string }`, because it only has 1 argument
- Change `onChatEnabledChange`'s signature to accept a `boolean` instead of `{ enabled: boolean }`, because it only has 1 argument
- Remove unnecessary use of a `Fragment` (`<></>`)
=> 🔨 Switch Live to use useOvermind

packages/app/src/app/pages/Sandbox/Editor/Workspace/items/NotOwnedSandboxInfo/NotOwnedSandboxInfo.tsx
In the future we'd have a modal saying you need to sign in to bookmark templates.
=> Fix Bookmark button for non-signed in users by removing it

packages/app/src/app/overmind/internalActions.ts, packages/app/src/app/overmind/namespaces/editor/internalActions.ts, packages/app/src/app/overmind/namespaces/server/actions.ts
Now we still do a smooth fork, but we fire up the executor on the forked sandbox and we refresh the preview so that we see the container fires up :)
=> do smooth forking, but restart executor and refresh preview

packages/codesandbox-api/src/protocol/protocol.ts
**How?**
It looks like in `protocol.ts` we need to send
different params to `postMessage` if the `target`
is a `Worker`...
There's probably a more polymorphic way to handle
all of this, but this commit implements a quick
and dirty function which returns a default value
if an error is thrown (i.e. a "SecurityError" in this case)
**References:**
- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Property_access_denied
- https://gitlab.com/gitlab-org/gitlab/issues/27144#note_258460537
Fixes https://github.com/codesandbox/codesandbox-client/issues/3173
It doesn't work in a xorigin iframe 😞 
It works now 😄 
1. Make the change
2. Rebuild the assets necessary for self-hosted code sandbox
3. Start a simple web server with built assets
=> Fix access to constructor on xorigin object

packages/app/src/app/overmind/namespaces/editor/internalActions.ts, packages/app/src/app/overmind/namespaces/workspace/actions.ts
Fixes #3175
When renaming a sandbox users would get an error saying "alias has already been taken", which is thrown because we send an alias that has been taken in the payload.
I thought to resolve this by conditionally adding title, description and alias to the payload based on whether they were changed, but there was another issue that arose from this.
After a fork we don't set the `project` fields to the forked sandbox, so we always think that the alias changed when changing the name of a sandbox. I updated this too.
=> Fix renaming forked sandboxes

packages/app/src/app/pages/Dashboard/Content/routes/PathedSandboxes/Navigation/NavigationLink.tsx, packages/app/src/app/pages/Dashboard/Content/routes/PathedSandboxes/Navigation/elements.ts, packages/app/src/app/pages/Dashboard/Content/routes/PathedSandboxes/Navigation/index.tsx
Reverts the dashboard navigation PR to fix styling and functionality. In prod it looks like this:
It's supposed to look like this:
This also makes dragging and dropping sandboxes on the folder names in the navigation work again.
I reverted the files to JS, then started to add type definitions.
=> Fix dashboard navigation

packages/common/src/components/ProgressButton/elements.ts
This was annoying
It was like this
Position relative keeps it in place
=> fix fork button

packages/app/src/app/components/Preview/DevTools/React-Devtools/elements.ts, packages/common/src/templates/helpers/react-template.ts, packages/common/src/templates/react-ts.ts, packages/common/src/templates/react.ts, packages/common/src/templates/template.ts
Code Improvment
The devtools will open in anything that has react with some pretty shady code even though it doesn't work in server sandboxes
Create a React Template where I extend from to add to react and react-ts
Also remove inpespect button with css as it does not work as mentioned in the beggining
1. Opened React Template
2. Open React + TS
3. Open several others to make sure it wasn't there
=> Improve React DevTools Implementation

packages/app/src/app/overmind/namespaces/live/actions.ts, packages/app/src/app/pages/Sandbox/index.tsx, packages/app/src/app/pages/index.tsx
Tested opening up the page, though think @CompuIves should check live and routing behaviour here, as I am a bit unsure
=> refactored sandbox page to overmind

packages/app/src/app/components/CreateNewSandbox/CreateSandbox/Explore/Explore.tsx
Text update.
Explore Templates was confusing to people, while we have been communicating Template Universe.
Communicate Template Universe in create sandbox modal.
Not tested and unsure if I edited the correct span. AMA and mea culpa.
Idem.
=> Rename Explore Templates to Template Universe

.imgbotconfig
This PR is in preparation of adding [`imgbot`](https://imgbot.net).
Like @SaraVieira [suggested](https://github.com/codesandbox/codesandbox-client/pull/3137#issuecomment-562973518), I ignored the `test_snapshots` like described in https://imgbot.net/docs/#ignoring-files
@CompuIves After merging in this PR, you only need to add the bot to this repo (or just the whole organization) and the bot will automatically create PRs like #3137
=> Prepare imgbot and ignore image_snapshots

packages/common/src/types/index.ts
After doing some profiling on our API calls (especially forking and showing sandboxes) I found out that the majority of the time is spent on rendering the author of a sandbox. This is because for the author we do some expensive computations, like counting the total fork count and like count, but also rendering up to 5 sandboxes for the top sandboxes.
I think this is unnecessary for the `author` field, so I propose with this PR to remove a bunch of fields from `sandbox.author` so that we can have much faster API calls. I think we will really shave ~50% response time when doing this change.
=> Update user type, increase API perf

packages/app/src/app/pages/Sandbox/Editor/Workspace/items/NotOwnedSandboxInfo/elements.ts
Better for SEO, now shows like this (the same):
=> Make description an h2

packages/app/package.json, packages/common/package.json, yarn.lock
Part of the work to add an official tailwind template: https://codesandbox.io/s/tailwind-css-playground-kkkzc
=> upgrade template-icons to 1.1.0 for tailwind

packages/app/package.json, packages/app/src/app/pages/Sandbox/Editor/Workspace/Project/SandboxConfig/TemplateConfig/index.tsx, standalone-packages/vscode-textmate/package-lock.json, yarn.lock
Since DefinitelyTyped/DefinitelyTyped#40894 is merged, we can now add `@types/react-color` again (like I first did in #3119).
=> Add react-color types

packages/common/src/components/Preview/index.tsx
It is super annoying in development that clearing the console causes Chrome to loose its insight into objects that are logged out, even though "prevent clearing log" is set in the chrome devtools. This should fix it.
=> Prevent clearing logs in development

packages/app/src/app/pages/Sandbox/Editor/Workspace/Files/DirectoryEntry/Entry/EntryTitleInput/index.tsx, packages/app/src/app/pages/Sandbox/Editor/Workspace/Files/DirectoryEntry/validateTitle.js
Bug Fix
- Chrome autocomplete shows up
- Typing `a` or `A` gives an error
- Added more special characters ( Not sure if it is needed )
- On putting, whitespaces error is not shown
- Disable chrome autocomplete
- Fixed regex for special characters
- Whitespace checks
1. Tested locally by checking all condition
=> fix: new directory input validation

packages/app/src/app/overmind/internalActions.ts, packages/common/src/templates/parcel.ts
Fixes #3262
Tested by opening that sandbox, and /s/vanilla to see if anything changed.
The problem was that we didn't reassign entries with the concat.
=> Fix default opened files in parcel

packages/app/package.json, packages/app/src/sandbox/eval/presets/create-react-app/v3.ts, packages/app/src/sandbox/eval/transpilers/babel/worker/babel-worker.js, yarn.lock
Fixes #3260
Add `@babel/plugin-proposal-nullish-coalescing-operator` to CRA. I decided not to make it a dynamic import so that the CRA sandboxes load more quickly.
Tested this by testing null coalescing. The editor complains, but I'll handle that in another update.
=> Add coalescing plugin to CRA v3

packages/app/src/app/overmind/namespaces/files/actions.ts
We now show the right error for uploaded files if the file is larger than 7MB.
=> Fix upload error

packages/app/src/app/pages/Search/Filters/index.js
Fixes typo in the environment sub-header on the search page
=> Fix typo on search page

packages/components/.storybook/decorators/LayoutDecorator.tsx, packages/components/.storybook/decorators/index.ts, packages/components/src/components/Grid/grid.stories.tsx, packages/components/src/components/Grid/index.tsx, packages/components/src/components/Stack/index.tsx, packages/components/src/components/Stack/stack.stories.tsx
Grid + Stack
Built on top of https://github.com/codesandbox/codesandbox-client/pull/3269
=> Layout components

packages/common/src/design-language/typography.ts, packages/components/.storybook/decorators/LayoutDecorator.tsx, packages/components/src/components/Collapsible/index.tsx, packages/components/src/components/Element/element.stories.tsx, packages/components/src/components/Element/index.tsx, packages/components/src/components/Example/index.tsx, packages/components/src/components/Grid/index.tsx, packages/components/src/components/Stack/index.tsx, packages/components/src/components/Stack/stack.stories.tsx, packages/components/src/stories/decorators/ThemeDecorator.tsx, packages/components/src/stories/decorators/index.ts
Changes in this PR:
1. Add missing fontsizes based on figma files
2. Make layout decorator highlight top level component as well
3. Implement `Element` component which provides margin props
4. Use Element as the base for other library components
=> components: Element

packages/common/src/design-language/typography.ts, packages/components/.storybook/decorators/LayoutDecorator.tsx, packages/components/src/components/Collapsible/index.tsx, packages/components/src/components/Element/element.stories.tsx, packages/components/src/components/Element/index.tsx, packages/components/src/components/Example/index.tsx, packages/components/src/components/Grid/index.tsx, packages/components/src/components/Stack/index.tsx, packages/components/src/components/Stack/stack.stories.tsx, packages/components/src/components/Text/index.tsx, packages/components/src/components/Text/text.stories.tsx, packages/components/src/stories/decorators/ThemeDecorator.tsx, packages/components/src/stories/decorators/index.ts, packages/components/src/utils/polyfill-theme.ts
Built on top of https://github.com/codesandbox/codesandbox-client/pull/3287 (this PR contains those changes)
the `Text` component is a reusable atom which inherits our base `Element` and has 3 variants for body, muted and danger styles
New token added: `mutedForeground` - this is another design token that vscode does n't have, but our UI does. we can probably use [`descriptionForeground`](https://code.visualstudio.com/api/references/theme-color#base-colors), but we would still polyfill it.
=> components: Text

packages/components/src/components/Collapsible/index.stories.tsx, packages/components/src/components/Collapsible/index.tsx
Using Text inside Collapsible instead of creating new elements.
The stories are especially interesting.
=> components: use Text in Collapsible

packages/app/src/app/pages/Search/index.tsx
Landing on search page results from a Google search is a poor experience, and Google is struggling to crawl the search pages properly resulting in some weird search results. This change prevents Google from indexing and crawling this page.
https://pr3293.build.csb.dev/search lgtm!
=> Add noindex to search page

packages/app/src/app/overmind/namespaces/editor/actions.ts, packages/app/src/app/pages/Sandbox/Editor/Content/Preview/index.tsx
Follow-up of #2638
- Change `previewActionReceived`'s signature to accept `any ` instead of `{ action: any }`, because it only has 1 argument
- use `ServerContainerStatus` enum instead of string values
=> 🔨 Switch Preview to use useOvermind

packages/components/src/components/Textarea/index.stories.tsx, packages/components/src/components/Textarea/index.tsx
3 hours, 3 lines. such is the life of a developer
new prop `autosize` - resizes based on the content
=> components: autosize for textarea

packages/app/src/app/overmind/namespaces/workspace/actions.ts
Adding a tag with `#` doesn't really make sense, and it breaks removing tags. So this removes the `#` from the tag when adding it.
=> Remove # from tags

packages/app/src/app/pages/common/Modals/ForkServerModal/elements.ts, packages/app/src/app/pages/common/Modals/ForkServerModal/index.tsx
=> 🔨 Switch ForkServerModal to use useOvermind

packages/app/src/app/pages/common/Modals/SearchDependenciesModal.tsx, packages/app/src/app/pages/common/Modals/index.tsx
Follow-up of #2747
- Make `SearchDependenciesModal` a `FunctionComponent`
- Export `SearchDependenciesModal` by a named export  instead of a `default export`
=> 🔨 Switch SearchDependenciesModal to use useOvermind

packages/app/src/app/overmind/namespaces/profile/actions.ts, packages/app/src/app/pages/Profile/elements.ts, packages/app/src/app/pages/Profile/index.tsx, packages/app/src/app/pages/index.tsx
Follow-up of #2729
- Change `profileMounted`'s signature to accept a `string` instead of `{ username: string }`, because it only has 1 argument
- Fix `Profile`'s props by using `react-router-dom`'s `RouteComponentProps` generic instead of hardcoding it
- Export `Profile` by a named export  instead of a `default export`
=> 🔨 Switch Profile to use useOvermind

packages/app/scripts/sentry-create-release.js, packages/app/src/app/index.js, packages/common/package.json, packages/common/src/utils/analytics/sentry.ts, yarn.lock
We still get 100s of thousands of errors from users that are running an old version of CodeSandbox. This makes sure that we only get errors from latest versions, and that we ignore all the errors from previous versions.
=> Move sentry to a new, clean project

packages/app/src/app/overmind/namespaces/editor/actions.ts, packages/app/src/app/pages/Sandbox/index.tsx
...and maybe other errors, as well?
This PR changes this GitHub import error message:
into this:
=> Make GitHub import errors more descriptive

packages/app/src/app/overmind/effects/live/index.ts, packages/app/src/app/overmind/effects/utils/index.ts, packages/app/src/app/overmind/internalActions.ts, packages/app/src/app/overmind/namespaces/files/actions.ts
We currently send updates for optimistic modules to the server, which the server cannot process. With this change we don't send updates for optimistic modules, and once we get the confirmation that the module has been created we send the whole module.
=> Only send updates to non-optimistic modules in live

packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Explorer/Dependencies/Dependency/index.tsx, packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Explorer/Files/DirectoryEntry/Entry/index.tsx, packages/components/src/components/Select/index.tsx, packages/components/src/components/Text/index.tsx
bad: 
1. buttons dont have enough click space
2. long version numbers overlap with name
3. select box doesnt have padding for caret
good:
=> Sidebar - fix dependencies overlap

packages/app/src/app/overmind/effects/live/index.ts, packages/app/src/app/overmind/factories.ts, packages/app/src/app/overmind/namespaces/editor/actions.ts, packages/app/src/app/overmind/namespaces/editor/internalActions.ts, packages/app/src/app/overmind/namespaces/editor/state.ts, packages/app/src/app/overmind/namespaces/files/actions.ts, packages/app/src/app/overmind/namespaces/workspace/actions.ts, packages/app/src/app/overmind/utils/items.ts, packages/common/src/types/index.ts, packages/common/src/utils/permission.test.ts, packages/common/src/utils/permission.ts
This allows users to change properties of a sandbox if they're the owner.
They can change the title, description, things like env variables. Everything
except the code, in which we'll autofork.
The goal of this is to answer to the multiple feature requests related to using
a git sandbox. While the best solution would be to invent a permission model,
we're not there yet and I'm not sure when we'll get it. So this seems like a good
intermediate solution instead.
=> Add ownership to GitHub sandboxes

packages/app/src/app/components/GitProgress/index.ts, packages/app/src/app/components/GitProgress/index.tsx, packages/app/src/app/pages/common/Modals/PRModal/elements.ts, packages/app/src/app/pages/common/Modals/PRModal/index.tsx, packages/app/src/app/pages/common/Modals/index.tsx
Follow-up of #2755 & #2803
- Fix `GitProgress`' `result` prop type
- Inline `PRModal`'s `result` instead of having an extra variable
- Export `PRModal` by a named export  instead of a `default export`
=> 🔨 Switch PRModal to use useOvermind

packages/app/src/app/pages/Sandbox/Editor/Navigation/elements.ts
This will make the focus of the navigation this background color instead of the outline. I think this looks a bit cleaner and will give an improvement in perceived speed.
=> Change the focus of the navigationitem of the new sidebar

packages/app/src/app/pages/Profile/Showcase/LoadingSandbox.tsx, packages/app/src/app/pages/Profile/Showcase/NoSandboxAvailable.tsx, packages/app/src/app/pages/Profile/Showcase/SandboxInfo/elements.ts, packages/app/src/app/pages/Profile/Showcase/SandboxInfo/index.tsx, packages/app/src/app/pages/Profile/Showcase/elements.js, packages/app/src/app/pages/Profile/Showcase/elements.ts, packages/app/src/app/pages/Profile/Showcase/index.tsx
Follow-up of #2766 & #2967
- Move `overmind` subscriptions as close as possible to the components itself instead of passing it through
- Extract `LoadingSandbox` & `NoSandboxAvailable` out of `Showcase`
=> 🔨 Switch Profile/Showcase to use useOvermind

packages/app/src/app/pages/Sandbox/Editor/Header/Actions.tsx, packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/GitHub/GithubLogin.tsx, packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/ProjectInfo/EditSummary.tsx, packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Server/VarForm.tsx, packages/common/src/theme/__snapshots__/theme.test.ts.snap, packages/common/src/themes/codesandbox.json, packages/components/src/components/Button/index.tsx
=> Danny's final feedback

packages/app/src/app/pages/Sandbox/Editor/Workspace/Files/DirectoryEntry/index.tsx
Bug fix
Delete Modal only shows up when the directory is open. Closes: #3528 
Modal is shown on the collapsed state as well.
1. Tested Delete Directory & files using edit icons
2. Delete using context menu
=> fix: show delete modal in collapsed state

packages/components/src/components/Input/index.tsx
These elements have a fixed height and are centered with flex. `line-height: 1` makes the font not have any additional height beyond its baseline
=> Center text inside Input, Select, Textarea

packages/app/src/app/pages/Sandbox/Editor/Header/Actions.tsx
🎵He was a 26px
She was a 32px
Can I make it any more obvious?
🎸Added both to header
They didn't align properly
What more can I say?
```diff
<Avatar
user={user}
+   css={{ size: '26px' })
/>
```
side note: this is surfacing a need for avatar sizes in the future based on the context its used
=> Match avatar and button size in header

packages/app/src/app/overmind/effects/vscode/index.ts, packages/app/src/app/overmind/namespaces/editor/actions.ts, packages/app/src/app/overmind/namespaces/preferences/actions.ts, packages/app/src/app/pages/common/Modals/PreferencesModal/Experiments/ContainerLSP.tsx, packages/common/src/types/index.ts, packages/common/src/utils/feature-flags.ts
For the feature flag for the container we don't use the localStorage, but a database property. We need to do this to determine which sandboxes have the experimental feature enabled. It turns out that our implementation of localStorage vars is half done, which is quite bad.
This PR changes the LSP feature flag to use the user, but there is still one API call missing. We need to do a POST `/api/v1/users/current` with body:
```
{
"user": {
"experiments": {
"container_lsp" boolean
}
}
}
```
To update the setting. Preferably we'd have an overmind action for this. Can anyone @codesandbox/frontend pick this up and finish this PR? I can't do it until tomorrow.
=> Fix feature flag for container lsp

packages/app/src/app/components/Preview/DevTools/Terminal/Shell/Term.tsx, packages/app/src/app/components/Preview/DevTools/Terminal/terminal-theme.ts, packages/common/src/themes/codesandbox-black.js
not a big fan of the implementation, it's a weird mix of old and new theming methods
=> Terminal: convert object to dot notation

packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Deployment/Zeit.tsx
bug:
fix:
```
- <Button css={{ width: 50 }}>
+ <Button css={{ width: 'auto' }}>
```
hard coded widths are always trouble 🙃
=> sign in button should width: auto

packages/notifications/package.json, yarn.lock
Notifications uses a different major version of styled-components which means there are 2 version on the page, which is not really useful (theme clashes, bundlesize, etc.)
Downgraded to 4.x in notifications
⚠️ Not sure if we depend on any v5 features in notifications 🤔
=> sync styled version in notifications

packages/app/src/app/pages/Dashboard/queries.ts
Bug - It looks more like a backend bug, but removing `teamId=null` from request body fixes it for the moment.
1. Tested by recovering multiple sandboxes
=> fix: recover sandbox request body

packages/app/src/app/overmind/effects/vscode/initializers.ts
This was removed in https://github.com/codesandbox/codesandbox-client/pull/3616 (by accident?) 
bringing it back
=> Bring back theme preference initialiser

packages/app/config/webpack.common.js, packages/app/config/webpack.dev.js
sourcemaps has been broken in dev. Now they work and is scoped to `src/app`, meaning it looks like this:
So all references that are **not** `app.js`, is actual references to the app. In this case `factories.ts` and `index.tsx`:
The rest is just libraries and stuff where we do not really care about the sourcemaps. Which should also make the dev flow build faster.
=> improves sourcemaps

packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Explorer/Dependencies/Dependency/index.tsx
this bug was introduced last week in a different bug fix :)
=> Fix dependency picker hidden behind text

packages/app/src/app/overmind/effects/fakeGql/comments/mutations.ts, packages/app/src/app/overmind/namespaces/editor/actions.ts, packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Comments/Dialog/Markdown.tsx, packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Comments/Dialog/Reply.tsx, packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Comments/Dialog/index.tsx
Adds ability to edit both comments and replies in the dialog
=> Add edit to comments

packages/app/src/app/components/CodeEditor/CodeMirror/index.js
This is a performance fix for codemirror, if we spam the resize operation of codemirror (which is expensive because of `getClientBoundingRect`) the embed will be slow. With this we debounce the call with 30ms.
=> Debounce the resizer of codemirror

packages/common/src/themes/codesandbox-black.js
=> Black theme - change blue highlights to match editor

packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Comments/Comment.tsx, packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Comments/Dialog/Reply.tsx, packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Comments/Dialog/index.tsx, packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Comments/index.tsx, packages/app/src/app/pages/Sandbox/Editor/index.tsx, packages/components/src/components/Icon/index.stories.tsx, packages/components/src/components/Icon/index.tsx
Discussed this one with Danny and realised that our icons can't be on the 4pt scale
Example:
The button that contains both these icons is the same size - 26x26, but the icons inside them have to be adjusted based how they look next to each other
Because of that, they can't always be 16. or even be on the 8/12/16 scale we have. We need more granular control of them
The ones in the image are 14x14 and 10x10 to look _optically aligned._ (both inside a 26x26 button)
Notes for future: It would be cool to optically align icons in the library so that there are less scenarios in which we need to optically align them. This can't be abstracted away fully because optical alignment depends on the context/neighbouring icons, so we'll always need this escape hatch 🙃
=> Fix: Icons cant be on scale

packages/app/src/embed/components/Sidebar/Dependencies/elements.js, packages/app/src/embed/components/Sidebar/Dependencies/index.js, packages/app/src/embed/components/Sidebar/SandboxInfo/elements.ts, packages/app/src/embed/components/Sidebar/SandboxInfo/index.tsx, packages/app/src/embed/components/Sidebar/elements.js, packages/app/src/embed/components/Sidebar/index.js
=> Semantic changes to prepare for embed seo

packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Explorer/Files/DirectoryEntry/Entry/index.tsx
To differentiate between hover and selected state in file tree - we only change foreground color to signal hover
=> Don't use list.hover for file tree

packages/app/src/app/pages/Sandbox/Editor/Header/icons.tsx
Fixed miss alignment in Share Icon.
#UX #UI
=> Fixed miss alignment in Share Icon

packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Explorer/Files/DirectoryEntry/Entry/index.tsx, packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/NotOwnedSandboxInfo/Summary.tsx, packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/ProjectInfo/Summary.tsx, packages/components/src/components/Avatar/index.tsx, packages/components/src/components/Text/index.tsx
Use maxWidth liberally
Haven't solved dependencies yet, that needs a change in structure to work (different PR)
=> Handle long names in the sidebar

packages/app/src/app/overmind/effects/live/index.ts, packages/app/src/app/overmind/namespaces/editor/internalActions.ts, packages/app/src/app/overmind/namespaces/live/internalActions.ts
We had some side effects that were still running when we were forking a sandbox, this resets them.
=> Reset live counters on sandbox change

packages/app/src/app/overmind/namespaces/comments/state.ts, packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Comments/Comment.tsx, packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Comments/index.tsx
=> Add times and move file name

packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Comments/components/MultiComment.tsx, packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Comments/index.tsx
=> style multi comments

packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Comments/Dialog/Reply.tsx, packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Comments/Dialog/index.tsx, packages/components/src/components/SkeletonText/index.tsx, packages/components/src/components/SkeletonText/skeleton-text.stories.tsx, packages/components/src/components/ThemeProvider/index.tsx, packages/components/src/index.ts
=> Dialog: Replies loader

packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/ProjectInfo/TemplateConfig.tsx
closes #3703
On selecting an icon from template icon popup, the popup doesn't close.
Currently it can be closed with outside click.
Close template icon popup after selection the icon.
The testing was done visually.
1. Go to `Template Info`
2. Click on `Template Icon` and select any icon.
3. It should close the popup.
=> fix(template-icon): close popup on selecting the icon

packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Comments/Dialog/Code.tsx
=> make code font dm

packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Comments/Dialog/index.tsx
motivation: animations are imperative, the reply animations has multiple steps in it. with our current implementations, there were multiple bugs that kept cropping up because of the declarative/imperative translation.
Rewrote the animations with a better (more explicit) transition for logic.
TODO: check for state changes in replies and decide animations for them
=> Reply animation refactor

packages/app/src/app/constants.ts, packages/app/src/app/overmind/effects/browser.ts, packages/app/src/app/overmind/namespaces/comments/actions.ts, packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Comments/Dialog/Reply.tsx, packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Comments/Dialog/index.tsx
When a comment is selected: There is 4 tasks that fight for dominance:
1. fetching replies and setting them in state
2. dialog opening animation
3. skeleton animation
4. getting the line for code comment
We can make some small changes to reduce this collision, one of those is to delay the skeleton animation (3) until the dialog has fully animated
=> Dialog performance - delay skeleton animation

packages/app/src/app/overmind/effects/router.ts, packages/app/src/app/overmind/effects/vscode/index.ts, packages/app/src/app/overmind/namespaces/editor/actions.ts, packages/app/src/app/overmind/namespaces/live/actions.ts, packages/app/src/app/overmind/onInitialize.ts, packages/app/src/app/pages/Sandbox/Editor/index.tsx, packages/app/src/app/pages/Sandbox/index.tsx
With this change, we put the currently opened file and selection in the URL (`?file=...&selection=...`). When you share the link with others (or just refresh) you will directly go back to that file and select the same code. 
I tested it with several combinations of files and selections. Also made sure that you scroll to the location of the selection when you open it.
=> Persist selection and file in the url for loading later

packages/common/src/themes/codesandbox-black.js
Fixes https://github.com/codesandbox/codesandbox-client/issues/3824
left: production
middle: this PR
right: over correction?
=> CSB Black - bump up the contrast for line numbers

packages/components/src/components/SkeletonText/index.tsx
Oh boy, the replies skeleton wasn't actually themed until now. It was always black.
```diff
- const themeType = props.theme.type;
+ const themeType = props.theme.vscodeTheme.type;
```
=> Comments: Now the reply skeleton is actually themed

packages/app/src/app/pages/Sandbox/Editor/Skeleton/elements.ts
Bug Fix
When we select theme `red` and load the editor, the app breaks because skeleton is using `Color` package and `Color('#ff000033')` throws an error. 
Fixes the color access with opacity.
Screen Recording: https://www.loom.com/share/c56684ce70834e91a8ec822b80061e8d 
1. Locally tested with red theme
=> fix: skeleton with color having opacity

packages/common/src/components/Preview/index.tsx
Allow to use the [WebHID API](https://wicg.github.io/webhid/)
As per [Feature Policy](https://wicg.github.io/webhid/#feature-policy) to use the WebHID API (available behind a `chrome://flags` in Chrome) the sandbox iframe needs to allow `hid`. 
Currently the WebHID API can't be used anymore because it introduced a feature policy that isn't in the allowed list of the iframe. 
Currently broken sandboxes: 
* [Keyboard Backlight Control](https://codesandbox.io/s/webhid-demo-keyboard-backlight-qlq95)
* [Ambient Light Sensor](https://codesandbox.io/s/webhid-demo-ambient-light-sensor-ix382)
The WebHID API would work inside a sandbox
=> add hid feature policy to iframe

packages/homepage/content/docs/2-tests.md
docs
link address is incorrect
https://codesandbox.io/docs/(/docs/environment)
now the link is going to the correct destination
https://codesandbox.io/docs/environment
1. Updated document
=> Correct link in test documents

packages/app/config/webpack.prod.js, packages/app/src/sandbox/eval/utils/get-dependency-name.test.ts, packages/app/src/sandbox/eval/utils/get-dependency-name.ts, packages/app/src/sandbox/npm/fetch-dependencies.ts
This sped up downloading dependencies 2-5x, even in some cases it takes 1s instead of 60s!
Fixes #3782
Fixes #3811
=> Download dependencies seperately and merge in bundler

packages/app/src/app/pages/Sandbox/SearchDependencies/DependencyHit/elements.js, packages/app/src/app/pages/Sandbox/SearchDependencies/RawAutoComplete/elements.js, packages/app/src/app/pages/Sandbox/SearchDependencies/dependencies.js, packages/app/src/app/pages/Search/search.ts, packages/app/src/app/pages/common/Modals/index.tsx
Bug fix #3796
On changing to light theme `Add dependencies` modal doesn't pick up the `light` theme
On Changing to `light` or `dark` theme appropriate colors are added to `Add dependencies` modal
The testing was done visually.
1. Select any `light` or `dark` theme from `Color Theme` under `Preferences`
2. Click on `Add dependency` in `Explorer tab`
3.  Appropriate colors are added to `Add dependencies` modal
Light Theme
Dark Theme
=> 3796 fix dependencies modal theme

packages/app/src/sandbox/eval/manager.ts, packages/app/src/sandbox/eval/tests/jest-lite.ts, packages/app/src/sandbox/eval/transpiled-module.ts
When we change the globals of a file, we need to throw away the cache of that file when we re-evaluate. We didn't do this, and because of that the global of `document` and `window` was re-used between two test runs, even though the globals had changed.
Fixes #3505
=> Don't reuse cache of a module if there are new globals

packages/app/src/app/pages/Dashboard/Content/SandboxCard/index.tsx
Enhancement
We cannot get/copy the sandbox link from the dashboard. Usecase: I wanted to share a link of old codesandbox so I searched on the dashboard and had to open the sandbox to get the link.
Add an option to copy the link directly from Context Menu.
Locally tested 4-5 sandboxes link by copying the link from the above option.
=> feat: add copy sandbox link option on Sandbox Card

packages/app/src/app/overmind/namespaces/editor/actions.ts, packages/app/src/app/overmind/namespaces/editor/state.ts, packages/app/src/app/pages/Sandbox/index.tsx
Shows the actual error from the backend when we can't open a sandbox
Also removes the login option because we know the error is that the backend cannot process the repo
Always shows error 422
Errors, amazing 
1. Open a github repo with a lot of modules or without a package.json
=> Show actual errors in sandbox error

packages/app/src/app/pages/Dashboard/Content/SandboxCard/index.tsx, packages/app/src/app/pages/Dashboard/Content/routes/Templates/OwnedTemplates/OwnedTemplates.tsx
Feature 🌈 
Currently, we don't have a copy link option in the context menu
Add option to copy link
1. Locally verified the copied link
=> feat: add template copy link

packages/app/src/app/overmind/effects/vscode/initializers.ts
Issue:
When you are abroad and/or your browser is configured in another language TS will go bananas and use another language to show errors even though all the rest of the errors are in English.
It's a weird experience that I could see on my wife's computer. All her computer is in English but the moment firefox was in Spanish you would get two different languages showing up in the errors.
All of the UI is in English and more commonly than not this is a mistake or a travel issue where people have some setting in the browser misconfigured.
Not to mention that Dank Mono does not support cyrlic so things get WEIRD
This sets all TS errors to be in English always so no more weird things like this happen
Closes #1870
Closes #3676
Closes #3923
=> Make TS errors english

packages/app/src/app/pages/NewDashboard/Components/SandboxCard/index.tsx, packages/app/src/app/pages/NewDashboard/Content/index.tsx, packages/app/src/app/pages/NewDashboard/Content/routes/StartSandboxes/index.tsx, packages/app/src/app/pages/NewDashboard/Content/routes/Templates/index.tsx, packages/app/src/app/pages/NewDashboard/Sidebar/index.tsx, packages/app/src/app/pages/NewDashboard/index.tsx, packages/app/src/app/pages/NewDashboard/queries.ts, packages/app/src/app/pages/NewSandbox/index.tsx, packages/components/src/components/Link/index.tsx
=> add skeleton to templates and start

.circleci/config.yml
We crossed our open source limit of 35,000 snapshots per month
Short term fix: Commenting out the test from circleCI so that we can uncomment it back at the start of new billing cycle in 9 days
Suggestion for long term fix: We should only run visual tests after checking if there are changes to packages/components. Right now, we're running them for every change in the app which running out of our quota faster
=> Disable visual tests for the month

packages/common/src/components/Preview/index.tsx
Fix #3757 
`hash` change in the `url` doesn't trigger a page reload in the Iframe
dispatch `refresh` to manually to trigger `reload` in Iframe
1. Fork -> https://codesandbox.io/s/sinuous-router-g2eud
2. Click on any route Eg: `Bob's Profile` which changes the url in the address bar to `/#users/bob`
3. Then click on `Reload` icon in the `Browser` Tab.
4. It should reload the Iframe.
=> Fix refresh for hash based URL in Preview

packages/app/src/app/pages/Sandbox/Editor/Header/CollaboratorHeads/CollaboratorHeads.tsx
Fixes this state:
To only show that button if there are 2 or more extra users.
=> Disallow showing one live user under "More" button

packages/app/src/app/pages/NewDashboard/Sidebar/index.tsx
Haven't done the alignment yet because wasn't sure how we want it
CSB-111
=> Add menu for switching accounts

packages/homepage/content/docs/3-deployment.md
- Zeit just rebranded to Vercel and this PR changes the deployment guidelines to deployment for gridsome
Old Product Name
New Product Name
=> [FIX] switch zeit now to Vercel Now for codesandbox deployment

packages/app/package.json, packages/app/src/app/pages/NewDashboard/Components/SandboxCard/Menu.tsx, packages/app/src/app/pages/NewDashboard/Components/SandboxCard/index.tsx, packages/app/src/app/pages/NewDashboard/Components/SandboxItem/Menu.tsx, packages/app/src/app/pages/NewDashboard/Components/SandboxItem/index.tsx, packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Comments/Comment.tsx, packages/common/src/components/Button/index.tsx, packages/components/src/components/Menu/index.tsx, yarn.lock
Closes CSB-142
- updated @types/react-router-dom to match react-router-dom version
- Move isMenuClicked logic to components and use it in card and comments
- use useHistory api instead of withRouter
- rename `template` prop to `isTemplate` to convey intent
- ignore incorrect types for common/components/button
Notes for reviewer - 
updates router types which failed the check in [one place](https://github.com/codesandbox/codesandbox-client/pull/4020/files#r417830423)
=> dashboard: Make card clickable

README.md, packages/app/src/app/components/SocialInfo/SocialInfo.tsx, packages/app/src/app/overmind/effects/vscode/Workbench.ts, packages/app/src/app/pages/Sandbox/Editor/Workspace/SSEDownNotice/SSEDownNotice.tsx, packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/ProjectInfo/Delete.tsx, packages/common/src/components/Footer.tsx, packages/homepage/src/components/Footer/index.js
We're moving discussions over to GitHub from Spectrum so we no longer want to direct folks to Spectrum. This PR removes links to Spectrum where there's currently already a link to GitHub, or replaces a link to Spectrum with one to GitHub Discussions where there isn't.
Checked all instances apart from see down notice (as I don't know how to force it to appear, and the SocialInfo component, as I couldn't work out where that's displayed - but the code looks ok.
=> Remove/replace Spectrum links with GitHub Discussions

packages/app/src/app/pages/Sandbox/Editor/index.tsx
Enhancement
When we copy the text from the status bar present in Editor we also get a comma in between version and commitSha. Like this 
`Version: ,ac5b1e45c`
Avoid Comma
1. Locally copied version
2. Tested the react behavior here: https://codesandbox.io/s/goofy-solomon-nq9bm?file=/src/App.js
`Question` Can anyone explain to me how this is happening. Is React tracking explicitly if a string is passed it keeps as a string ( this is expected ) but when we declare a variable it tracks as an array ( Not able to understand this :/ )
=> fix: version copied from editor status bar

packages/app/src/app/pages/Dashboard/Sidebar/SandboxesItem/FolderEntry/index.tsx
Bug Fix
After deleting the folder in the dashboard, the view is not updated.
Ref: https://www.loom.com/share/e4c2b3be5fa54e38ac7e3b17cc5210f1
Update view after deleting
Ref: https://www.loom.com/share/33fc94ee6bdf49bab1a733938f5e9f81
1. Locally tested by deleting folders
=> fix: update view after deleting folder in dashboard

standalone-packages/sandpack/README.md
Docs update that fixes #2306. Sandpack is used by Gitlab and CodeSanbox in production, so I think is stable enough.
=> Sandpack is ready to be used, fixes #2306

packages/app/src/app/overmind/internalActions.ts, packages/app/src/app/overmind/onInitialize.ts, packages/homepage/src/components/Toast/index.js
Follow-up of #3815 
- Use early return
- Cleanup Privacy toast
=> Privacy policy followup

.circleci/config.yml
Since `create-docker-image` already requires `build-prod`, it's not necessary anymore that `deploy-to-production` requires it
=> Simplify master build

packages/app/src/app/components/CodeEditor/VSCode/index.tsx
Switching files was noticably slow, with this change it's almost instant. The reason for this was a `React.useEffect` that would execute for every time we switch a file, and this would cause VSCode to do a layout update. With this change file switching is instant.
=> Greatly improve file switching performance

packages/app/src/app/components/CodeEditor/VSCode/index.tsx, packages/app/src/app/pages/Sandbox/Editor/Workspace/Files/DirectoryEntry/DirectoryChildren/index.tsx, packages/app/src/app/pages/Sandbox/Editor/Workspace/Files/DirectoryEntry/index.tsx, packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Explorer/Files/DirectoryEntry/DirectoryChildren/index.tsx, packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Explorer/Files/DirectoryEntry/index.tsx
Spreads are expensive, and it seems like we were doing it for all our folders. This removes the spreads.
It seems like we weren't using siblings at all anymore, even not in spreads and checks.
I tested this by opening and closing files/directories.
=> Remove unnecessary calculations for rendering files

packages/app/src/app/overmind/actions.ts, packages/app/src/app/overmind/effects/git/export-to-github.ts, packages/app/src/app/overmind/effects/zeit.ts, packages/app/src/app/overmind/namespaces/deployment/actions.ts, packages/app/src/app/overmind/namespaces/deployment/internalActions.ts, packages/app/src/app/pages/Sandbox/Editor/Workspace/items/Deployment/Deployment.tsx, packages/app/src/app/pages/Sandbox/Editor/Workspace/items/Deployment/Zeit/DeployButton/DeployButton.tsx, packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Deployment/NotLoggedIn.tsx, packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Deployment/NotOwner.tsx, packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Deployment/Zeit.tsx, packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Deployment/index.tsx, packages/app/src/app/pages/common/Modals/DeploymentModal/index.tsx, packages/app/src/app/pages/common/ZeitIntegration/index.tsx, packages/common/src/templates/configuration/now/index.ts, packages/common/src/templates/template.ts, packages/components/src/components/Integration/index.stories.tsx, packages/homepage/src/pages/company/index.js, packages/homepage/src/pages/ide/index.js, packages/homepage/src/pages/pricing/index.js
Refactor. ZEIT has rebranded to Vercel.
We're displaying deployment to ZEIT Now yet.
We are displaying deployment to Vercel. Only texts in the app were changed, code still refers to it as `zeit`. Blog posts and announcements were not updated too.
N/A
=> refactor(deployment): rename ZEIT Now to Vercel

packages/app/src/app/components/CreateNewSandbox/CreateSandbox/SearchBox/SearchBox.tsx, packages/app/src/app/components/CreateNewSandbox/CreateSandbox/TemplateList/TemplateList.tsx
Bug fix. Closes #4073.
Keyboard events when the search input is focused are "swallowed" by the `useKey` hooks.
Keyboard events fired from the search input are not handled by the `useKey` hooks.
1. Type something in the search input on the create modal;
2. Press the arrow keys and verify that the interaction is kept inside the input;
3. Press `Esc` to blur from the search input;
4. Press the arrow keys and verify that it navigates through the list.
=> fix(create): react to keyboard events when search input is focused

packages/components/package.json
As suggested by @siddharthkp in #3955:
> Suggestion for long term fix: We should only run visual tests after checking if there are changes to `packages/components`. Right now, we're running them for every change in the app which running out of our quota faster
=> chore: Only run Chromatic when files are changed

packages/app/src/app/pages/common/Modals/ShareModal/getCode.ts, packages/common/src/components/Preview/index.tsx, packages/homepage/src/screens/home/explore/index.js, standalone-packages/react-sandpack/src/components/SandpackProvider/SandpackProvider.tsx
Adds 'xr-spatial-tracking' to allowed attributes in preview iframe
Can't use webxr in preview
Can use webxr in preview
=> Add xr-spatial-tracking support to preview

packages/app/src/app/components/CreateNewSandbox/CreateSandbox/New/index.tsx
=> Fix padding in what's new

packages/app/src/app/overmind/effects/vercel.ts, packages/app/src/app/overmind/namespaces/deployment/actions.ts, packages/common/src/types/index.ts
**Problem**: 
When you tried to deploy a project to vercel, if you had env variables these were never actually sent to vercel so everything failed
**Now**:
If you have env vars in your now.json file and have the same in environment variables these will be sent to vercel so you can deploy and these secrets will be added to your account
Example sandbox id: https://pr4169.build.csb.dev/s/cool-northcutt-ud4wr
Add an env variable called: NEXT_HELLO_CSB with any value and then go to the deployed site at `api/people/test` and magic!
=> Send env vars to vercel as secrets

package.json, packages/app/src/app/overmind/effects/vscode/index.ts, yarn.lock
Eslint stopped working in the worker after upgrading to `babel-eslint` 1.1.0. It seems like a dynamic require is added to resolve `eslint` files directly, which is not available in the web worker yet (https://github.com/babel/babel-eslint/pull/794). 
I also saw that the linter worker was started twice, now we start it once. 
Fixes https://sentry.io/organizations/codesandbox/issues/1697777972/?project=2071895&query=is%3Aunresolved&statsPeriod=14d
Fixes https://sentry.io/organizations/codesandbox/issues/1697778867/?project=2071895&query=is%3Aunresolved&statsPeriod=14d
=> Fix eslint

packages/app/src/app/pages/Sandbox/Editor/Workspace/index.tsx
Fixes #3766
Fixes #3221
Fixes #3982
Fixes #3975
Fixes #3964
Fixes #4258
Fixes #4254
Fixes #4235
Fixes #4229
Fixes #4227
Fixes #4199
Fixes #4177
Fixes #4153
Fixes #4139
Fixes #4108
Fixes #3561
Fixes #3624
And probably some more. When someone clicks on the sidebar icon when loading a sandbox, or they navigate between sandboxes, it crashes because `currentSandbox` can now be null
=> Don't allow the sidebar to render if currentSandbox is not available

packages/sandbox-hooks/url-listeners.js
This should fix hash routing in vue router v4 (https://n2qq4.csb.app/#/)
Clicking on any link changes the url but does not trigger the click event
Triggers the click event on the anchors
1. Go to https://n2qq4.csb.app/#/
2. Click on Go to Foo
There might be a better way to check if an element is inside of a Vue app, but I couldn't find anything better for Vue 3. Maybe @yyx990803 knows a better way
=> fix: check for vue router v4

packages/app/package.json, packages/app/src/sandbox/eval/manager.ts, packages/app/src/sandbox/eval/npm/fetch-npm-module.ts, packages/app/src/sandbox/eval/transpilers/babel/check.ts, packages/app/src/sandbox/eval/transpilers/babel/index.ts, packages/app/src/sandbox/eval/transpilers/babel/worker/dynamic-download.ts, packages/app/src/sandbox/eval/utils/is-es-module.test.ts, packages/app/src/sandbox/eval/utils/resolve-utils.ts, yarn.lock
Apparently some npm packages refer to a file using `"module":` field but the file doesn't exist. We recently changed to resolving `module` by default because of the exact reason, but on the `main` field (`main` field was referring to a file that doesn't exist).
This is tricky, and unfortunately it's allowed to refer to files that don't exist. The only solution for this is by introducing a separate check that verifies if the file exists, and if it doesn't fall back to `main`. It's a performance hit (as we have to do this during file resolving, which happens on the main thread), but I don't see another way.
Fixes #4276
Fixes #4275
=> Add a fallback to commonjs if esmodule is not found

packages/app/src/app/overmind/effects/vercel.ts
Issue: Now we set the public flag in vercel deployments always to true because back in the day that was a requirement for free accounts and the default
that is long gone
Fixes email support issue
=> make deployments be whatever the person sends

packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Explorer/Dependencies/Dependency/index.tsx
=> Fix dependency name overflow

packages/app/src/sandbox/eval/transpilers/babel/convert-esmodule/__snapshots__/index.test.ts.snap, packages/app/src/sandbox/eval/transpilers/babel/convert-esmodule/index.test.ts, packages/app/src/sandbox/eval/transpilers/babel/convert-esmodule/index.ts, packages/app/src/sandbox/eval/utils/is-es-module.test.ts
If there's an esm file that defines `exports`, we first need to rename that variable as it's a reserved keyword in the world of commonjs.
Fixes https://github.com/codesandbox/codesandbox-client/discussions/4273.
Fixes #4292
=> Fix esmodule conversion of files with reserved export keywords

packages/app/src/sandbox/eval/transpilers/babel/convert-esmodule/__snapshots__/index.test.ts.snap, packages/app/src/sandbox/eval/transpilers/babel/convert-esmodule/index.test.ts, packages/app/src/sandbox/eval/transpilers/babel/convert-esmodule/index.ts, packages/app/src/sandbox/eval/transpilers/babel/convert-esmodule/utils.ts
We used to do
```
const a = interopRequireDefault(require('a')).default
a()
```
Now it will be
```
const $csb_a = require('a');
const a = interopRequireDefault($csb_a);
a.default()
```
In case `default` has been changed (often in case of cyclic dependencies).
=> Fix how we transpile esmodule default

packages/components/src/components/Textarea/index.tsx
Even thought autosize is an optional prop, it was always autosizing. Removed that bug.
=> Components: Textarea optional autosize

packages/app/src/app/overmind/namespaces/live/liveMessageOperators.ts
Codesandbox is live by default, so this message is just confusing, as noted from a user showing us git flow issues. We also have an indication at the top showing who else is in the session now.
=> remove live notification

packages/app/config/build.js, packages/app/package.json, standalone-packages/vscode-textmate/package-lock.json, standalone-packages/vscode-textmate/package.json, standalone-packages/vscode-textmate/src/onigLibs.ts, standalone-packages/vscode-textmate/tsconfig.json, yarn.lock
Thanks to the work from https://github.com/microsoft/vscode/pull/95958, we can use a new oniguruma library that results in 2-3x faster syntax highlighting.
=> Use new, faster oniguruma wasm library

packages/app/src/app/overmind/actions.ts, packages/app/src/app/overmind/namespaces/comments/actions.ts, packages/app/src/app/overmind/namespaces/live/internalActions.ts
This fixes issue with comments not being transposed when refreshing and changes has been made before comments are fetched.
I also fixed an issue where moving a sandbox to teams did not show the comments indicator. The reason was because we do not copy feature flags when refetching sandbox info. We do now 😄
=> Commentsfix

packages/app/src/sandbox/eval/transpilers/babel/convert-esmodule/__snapshots__/index.test.ts.snap, packages/app/src/sandbox/eval/transpilers/babel/convert-esmodule/index.test.ts, packages/app/src/sandbox/eval/transpilers/babel/convert-esmodule/index.ts
Fixes #4355
```js
import a from './b';
a()
```
will become
```js
const a = interopRequireDefault(require('b'));
(0, a.default)()
```
The tricky thing is that we also do it for this case, will it break things?
```js
import a from './b';
const c = a;
```
```js
const a = interopRequireDefault(require('b'));
const c = (0, a.default)
```
=> Fix how we call imported esmodules

packages/app/src/sandbox/eval/utils/is-es-module.test.ts
The test isn't consistent in the time it takes. So, sometimes it fails in unrelated PRs
Increasing the threshold from 5ms to 10ms so that we can still catch regressions but it has more room in CI
=> Increase test threshold

packages/homepage/src/components/Navigation/index.js, packages/homepage/src/components/layout.js
Some strange behavior on the homepage adding an extra border on the <motion.div>
Could not figure out what it is, fixed it with margin -1px offset (Hack).
At least it looks better now but we need to fix this later ( on my list) 
Fixed-mobile layout: 
Fixed missing border on other page
=> Black Lives Matter.: Fixed mobile and styling on none homepage

packages/app/package.json, packages/app/src/app/overmind/effects/live/index.ts, packages/homepage/package.json, yarn.lock
If there was a timeout (10s) of a message the promise would never resolve or reject. This makes sure that it does that. I also raised the timeout of sending an operation to 45s.
Finally I made the reconnect logic for the socket more robust, will now only stop trying if we're getting 401 (unauthorized) responses.
=> Fix live timeouts

packages/components/src/components/Text/index.tsx, packages/components/src/components/Text/text.stories.tsx
Text inherits line height from the parent, this means it can pick up smaller line heights all the way up from html/body which isn't meant for this component.
Adding a default line height which can be overwritten on demand
Fixes CSB-267
Fixes CSB-268
This went way better than expected!
2 places need work, creating a issue for that
before and after:
in the share modal: before and after:
=> Components: add default line height of normal to Text

packages/app/src/app/overmind/effects/vscode/SandboxFsSync/index.ts
This fixes issue where we grab `@types/` even though the package includes types. Tested with `react` and `react-textarea-autosize`... React grabs it from @types and even though react-textarea-autosize has a @types package it uses its internal typing, cause it is there
=> only download definitelytype if no types included

packages/components/src/components/Tooltip/index.tsx
Tooltips should be on a higher plane than overlays and menus
=> Components: Fix tooltip zindex

packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Explorer/Files/DirectoryEntry/index.tsx
Fixes #4366, but not the root problem. Should also benefit in performance, `find` can be very expensive.
=> Use title from props to render directory

packages/app/src/app/overmind/effects/api/index.ts, packages/app/src/app/overmind/effects/vscode/SandboxFsSync/index.ts, packages/app/src/app/overmind/namespaces/editor/actions.ts
This handles two things:
1. When you use a TAG we add the actual version that tag represents (The same behaviour as when we do not add any specific version, we add the specific latest version)
2. A dependency can no longer override the types of the main package, if it is installed as an explicit package
=> install specific version when using tags

packages/app/src/app/components/CreateNewSandbox/CreateSandbox/Import/Import.tsx, packages/app/src/app/pages/GitHub/index.tsx
A button with `to` isn't a Link. @SaraVieira could you check whether this happens on other places? I think it started happening after the cleanup
=> Fix importing sandbox

packages/app/src/app/overmind/effects/vscode/SandboxFsSync/index.ts
This ensure we get the latest version looking at ETAG, instead of keeping it cached:
```ts
// Download a resource with cache busting when dealing with a
// properly configured server that will send the correct ETag
// and Date headers and properly handle If-Modified-Since and
// If-None-Match request headers, therefore we can rely on the
// validation to guarantee a fresh response.
fetch("some.json", {cache: "no-cache"})
.then(function(response) { /* consume the response */ });
```
=> fix caching of typings

packages/app/src/sandbox/eval/transpilers/babel/worker/babel-worker.js
Babel got to the `import()` statements first!
Fixes #4470
=> Make sure to run dynamic imports before other plugins

packages/components/src/themes/codesandbox-black.ts
I always had trouble seeing the matching bracket borders in CSB Black, this changes it to make them more apparent by using the default border.
=> Make bracket matches more apparent in CSB Black

standalone-packages/sandpack/src/manager/index.ts, standalone-packages/sandpack/typings/types.d.ts
Added additional useful properties to Preview Manager such as managerState, status, getManagerTranspilerContext, errors. These things are available in react-sandpack, so it might be good to have these things here also.
Currently, the above mentioned properties are not available in the Preview Manager.
The above mentioned properties are added along with the existing properties. These changes have no conflict to the existing behavior
1. After the adding the above properties, taken build of the sandpack package and tested it in the local environment in a new test project.
2. Also, checked it in the local application where I have been already using the sandpack without changes.
- [x ] Testing 
- [ x] Ready to be merged
=> Additional properties added to Preview Manager

packages/app/src/sandbox/eval/presets/angular-cli/index.ts, packages/common/src/templates/angular.ts, packages/common/src/templates/configuration/tsconfig/index.ts
This adds custom `tsconfig.json` support for Angular, and changes the default config to output `es2015` by default.
Fixes #1543
=> Support tsconfig configuraton in Angular template

packages/app/src/sandbox/eval/transpilers/sass/index.ts, packages/app/src/sandbox/eval/transpilers/sass/worker/sass-worker.js, packages/app/src/sandbox/eval/transpilers/sass/worker/utils/imports.ts
Related to #1543.
Our sass-loader requires a round-trip from the worker thread to the main thread to check if a file exists, because the file should live on the main thread. Because of this it can take long to resolve a single file, since we need to use the node resolver (which checks ~20 paths) before finding the right result. Because 99% of the time, the file is relative to the requester, we now check that first before using the node resolver. This results in 99% of the cases that we only need to do 1 roundtrip, instead of 20, and thus in faster Sass compiling.
=> Optimize resolving of sass files

packages/app/src/sandbox/eval/transpilers/babel/convert-esmodule/__snapshots__/index.test.ts.snap, packages/app/src/sandbox/eval/transpilers/babel/convert-esmodule/generator.ts, packages/app/src/sandbox/eval/transpilers/babel/convert-esmodule/index.test.ts
Our esmodule converter printed an ast of:
```
c = (10.0, + +(15))
```
to
```
c = (10.0, ++(15))
```
which is wrong, this fixes it.
Fixes #4476
Also opened a PR here to fix upstream: https://github.com/davidbonnet/astring/pull/315.
=> Fix printing a double UnaryExpression

packages/app/src/app/pages/NewDashboard/Content/routes/Settings/components/index.tsx
Make the card a bit larger.
This change will impact all cards' height.
I can change to only do this when on the Community Plan if necessary
- [N/A] Documentation
- [N/A] Added myself to contributors table
=> Update Card component's height on User Settings

packages/app/src/sandbox/eval/presets/dojo/transpilers/style.js
Bug Fix
As described in #4305, styles for dojo widgets are currently not loading. There is an existing check to defer to an existing
js file for `.m.css` files, but at some point something changed and now those `.js` files are not in the list of transpiled modules when this check is performed.
Closes #4305
Now for `.m.css` dependencies in `node_modules` the corresponding js dependency is explicitly resolved.
1. Run the sandbox in the linked issue with master, and you can see the discrepancies from the deployed example
2. Run the sandbox [with this branch](https://pr4548.build.csb.dev/s/github/pereibex/dojo-create-sample) and the styles will be fixed
=> Add missing js modules for dojo styles

packages/homepage/content/docs/7-environment.md
Related to https://github.com/vuejs/vue-cli/pull/5681
=> add env variable to sse docs

packages/app/src/sandbox/eval/presets/svelte/index.js
Adds support for (scss) in svelte templates
To test use this example: https://codesandbox.io/s/agitated-snow-u0y0z?file=/App.svelte
=> add sass and css support to svelte

packages/app/src/app/pages/Sandbox/index.tsx
We have a mobile redirect to send users from `s/new` to `embed/new` and this was also triggering when users were trying to go to `/s`
=> remove redirect if user is trying to go to /s

packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Explorer/Files/DirectoryEntry/Entry/EditIcons/index.js
React throws a removeChild error when this is rendered:
```
<>
{false && <div />
</>
```
because the contents are empty, as I understood from here: https://stackoverflow.com/questions/54880669/react-domexception-failed-to-execute-removechild-on-node-the-node-to-be-re.
This seems to happen sometimes in the explorer, and this change fixes that.
=> Fix removeChild error in Explorer

packages/app/src/app/overmind/effects/vscode/Workbench.ts
Fixes https://github.com/codesandbox/codesandbox-client/issues/4575
document.documentElement.requestFullscreen() doesn't work on safari, you have to use document.documentElement.webkitRequestFullscreen()
=> Fix toggle full screen on safari

packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/GitHub/index.tsx
We were checking for `git`, but not using the `git` property from that same object.
Fixes #4581
=> Fix a bug where forkedTemplateSandbox.git is undefined

packages/app/src/app/pages/NewDashboard/Components/Selection/DragPreview.tsx
showing a counter of 1 doesn't convey any information. We should remove it to keep it minimal
on the flip side, it does give a hint that you can select multiple. Leaving this for @DannyRuchtie and @CompuIves's input
=> Dashboard - only show counter for multiple items

packages/app/src/app/overmind/namespaces/git/actions.ts, packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/GitHub/index.tsx, packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/GitHub/utils/getConflictsText.tsx
The following issues has been adressed: 
- The Git Extractor has a new version. When dealing with sync of multiple commits we got the commit SHA of the oldest commit, causing your sandbox to be in sync... but still out of sync because of wrong commit SHA
- When dealing with syncing of `base` on a PR, we gave a filepath missing `/` on the commit... so it did not update correctly, causing a bit of havoc really
- Fixed updating git changes after doing a sync
- Fixed reloading the source sandbox after dealing with a sync
- Improved conflict resolution to also check content, also some comments to understand it better
- Fixed margin when having multiple conflicts
- Improved some text related to not necessarily being deleted by the user
- Moved the "conflict" event to trigger correctly
Please …
=> fixes several issues with github flow

packages/app/src/app/components/CodeEditor/elements.ts, packages/app/src/app/pages/Sandbox/Editor/Content/EditorToast.tsx
The configuration indicator was overlaying the search. Since we can not put it underneath (as the search is inside VSCode) I decided to put it bottom right instead.
=> fix search

packages/app/src/app/overmind/internalActions.ts
Fixes #4661
Real edge case; happens when `sandbox.modules == []`
=> Fix module being undefined

packages/app/src/app/pages/common/Modals/MoveSandboxFolderModal/DirectoryPicker/SandboxesItem/FolderEntry/elements.ts, packages/app/src/app/pages/common/Modals/MoveSandboxFolderModal/DirectoryPicker/SandboxesItem/FolderEntry/index.tsx, packages/app/src/app/pages/common/Modals/MoveSandboxFolderModal/DirectoryPicker/SandboxesItem/index.tsx
Because we're in a transition period to workspaces it's not possible to move sandboxes to "All Sandboxes" in personal workspaces due to technical limitations. This adds a message to the modal to let the user know.
Temporary fix for #4629
=> Add a warning for unsupported functionality in move modal

packages/app/src/app/overmind/namespaces/dashboard/actions.ts, packages/app/src/app/pages/Dashboard/Components/Selection/ContextMenu.tsx, packages/app/src/app/pages/Dashboard/Components/Selection/ContextMenus/ContainerMenu.tsx, packages/app/src/app/pages/Dashboard/Content/routes/All/useFilteredItems.ts, packages/app/src/app/pages/Dashboard/Sidebar/index.tsx
1. Keep `/` path in collections when it is present (teams)
```diff
state.dashboard.allCollections = collectionsByLevel.filter(
-  c => c.id && c.name
+  c => c.id
);
```
2. Don't show `/` in explorer view or in show it twice in sidebar
=> Fix: Bring back create sandbox menu when All workspace exists

packages/app/src/sandbox/compile.ts
Whenever a CRA without React dependency requires an HTML file, which and that one requires a JS file, top-level event listeners don't catch on.
That's because the compiler sets `body.innerHTML` after the JS has been loaded. This PR is a quick fix, but I will investigate tomorrow if this is the best fix, and if it fixes all cases.
Refer: https://codesandbox.io/s/vibrant-herschel-puilg?file=/public/index.html
=> Don't set sandbox HTML if there's an HTML module

packages/app/src/app/pages/common/Modals/MoveSandboxFolderModal/DirectoryPicker/SandboxesItem/FolderEntry/index.tsx, packages/app/src/app/pages/common/Modals/MoveSandboxFolderModal/DirectoryPicker/SandboxesItem/index.tsx, packages/components/src/components/Tooltip/index.tsx
I wonder what you think of this @siddharthkp. With this change we don't render the tooltip if `label` is `null`.
=> Don't render a tooltip if the label is null

packages/app/src/embed/components/App/index.js, packages/common/src/utils/platform.ts
Sometimes Safari on iPhone would crash if there were multiple embeds on the same page. I think the same could happen on Android. With this we add a default, which prevents crashes if multiple embeds are on the same page.
=> Enable run on click by default for Android and IOS

packages/app/src/app/overmind/factories.ts, packages/app/src/app/overmind/internalActions.ts
I noticed after sign in we wouldn't show all teams, and that's because we have a flow that is duplicated, and we only added it to one flow. I merged both flows into one function now.
=> Merge user initialization into one function

packages/sandbox-hooks/url-listeners.js
I do not think we should `stopPropagation` here, cause this stops the event bubbling up. It is the `preventDefault` we want to prevent the browser to trigger the link.
Let me know if there is some reason we want to actually stop the click event.
Fixes: https://github.com/codesandbox/codesandbox-client/issues/4523
=> should still propagate hyperlink clicks

packages/app/src/app/pages/Sandbox/Editor/Header/ForkButton/ForkButton.tsx
It's not a good long-term fix. I think we shouldn't render the component if we haven't fetched the teams yet.
=> Quickfix teamId being undefined

.github/workflows/stale.yml
=> make stale bot friendlier

packages/app/src/app/pages/common/Modals/PreferencesModal/EditorPageSettings/EditorSettings.tsx
Look behind expressions are now supported on FF
https://caniuse.com/#feat=js-regexp-lookbehind
=> add vim to FF

packages/app/src/sandbox/eval/transpilers/babel/convert-esmodule/__snapshots__/index.test.ts.snap, packages/app/src/sandbox/eval/transpilers/babel/convert-esmodule/generator.ts, packages/app/src/sandbox/eval/transpilers/babel/convert-esmodule/index.test.ts
=> Fix printing unary statement with -(--i)

.all-contributorsrc, README.md, packages/app/src/app/overmind/effects/zip/create-zip/index.ts, packages/app/src/app/utils/inject-resources-for-export.ts, packages/app/src/sandbox/external-resources.ts
Feature requested on issue #2268 
External resources are not included inside `public/index.html` when you export the project as a ZIP file, so users have to manually fix that issue after exporting.
External resources are included inside `<head>` tag.
1. Create a project and add 1 or 2 external resources. Example: https://codesandbox.io/s/reverent-cookies-kdldf
2. Export the project as a ZIP file and run it.
3. External resources are now there so the project works as it did on codesandbox.
=> Include external resources when exporting ZIP

packages/app/src/sandbox/npm/index.ts
Fixes #4853
Unfortunately there was a bug with our packager that allowed it to save `{ error: '' }` to the cache if there was an error. This bug has been fixed in the packager, but there is still an existing cache, which is why we need to fall back to our dynamic fetching if we see that the object has an error.
=> Fix loading prebundled dependencies that have {error: string}

packages/app/src/app/pages/Sandbox/Editor/Workspace/Files/DirectoryEntry/index.tsx, packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Explorer/Files/DirectoryEntry/index.tsx, packages/common/src/sandbox/modules.ts
This PR makes it so that you can upload whole folders using the "Upload files" buttons on the sidebar using the new https://caniuse.com/#feat=input-file-directory that is supported in most browsers
In others, it just won't let you select a folder
closes #1981
=> Accept folders in upload files button

packages/app/src/app/overmind/effects/vercel.ts
Related: https://github.com/codesandbox/static-template/pull/160#issuecomment-688544291
=> Fix Static Deployments in Vercel

packages/app/src/app/overmind/namespaces/git/actions.ts, packages/common/src/types/index.ts
This deals with binary files on both public and private repos. Also dealing with syncing up from "source" where the sandbox is on a PR branch, where it actually creates a commit out of the binary file to be "merged" in.
This depends on PR in `git-extractor`
=> Deal with binary files

packages/app/src/app/components/TeamAvatar/TeamAvatar.tsx, packages/app/src/app/pages/Profile2/LikedSandboxes.tsx, packages/app/src/app/pages/Profile2/ProfileCard.tsx, packages/app/src/app/pages/Profile2/SandboxCard.tsx, packages/app/src/app/pages/Profile2/ShowcaseSandbox.tsx, packages/app/src/app/pages/Profile2/index.tsx
- full width profile
- open in new tab with modifier
- grid for teams
- fix liked sandboxes grid
- fixes aspect ratio for team avatar
=> WIP Profiles: fix a bunch of tiny issues

packages/common/src/components/Preference/PreferenceNumber.tsx, packages/common/src/components/Preference/index.tsx, packages/common/src/templates/configuration/sandbox/ui.tsx
Enhancement
Currently, the input width is small and we cannot see the full port number. 
https://www.loom.com/share/83c2ac809c5d4903997110bbaec82011
1. Updated the styling props. We do have style prop used in Input but it wasn't passed from parent.
https://www.loom.com/share/4b1eeccaf5f642818c3db1bc07e54bb4
1. Tested the UI of Sandbox Config and added max and min values to make sure the number is fully visible.
=> fix: input width for port in sandbox config

packages/app/src/embed/components/SplitPane/elements.js
Bug Fix
If we select `previewwindow=tests` the splitpane resizer appears vertically.
https://www.loom.com/share/cb108505dfbd4a23bbb1c5343fcc6fec
Make the resizer horizontal. 
https://www.loom.com/share/40e7c5e5d62e488b85fbc3251a2b83fc
1. Tested embed with previewwindow=tests
2. Tested normal embeds
=> fix(embed): tests splitpane resizer position

packages/app/src/app/pages/Dashboard/Components/Selection/ContextMenus/SandboxMenu.tsx
The server still returns `teamId === null` on sandboxes in a personal workspace for backwards compatibility reasons. That breaks our check on workspace, and makes it seem like the user has no access to the sandbox.
Here we check for `teamId === null` to also make sure that you're an owner. Because the server only responds with `teamId = null` if it's in *your* personal workspace.
=> Fix permissions on personal workspace sandboxes

packages/app/src/app/pages/Sandbox/SearchDependencies/Dependency.tsx
Bug fix
We have sorted versions in version selector which by defaults shows the newest release [ first value ] in most cases. But when we select and add the dependency we push the latest tag in API. Check line here: https://github.com/codesandbox/codesandbox-client/blob/master/packages/app/src/app/pages/Sandbox/SearchDependencies/index.tsx#L20
https://www.loom.com/share/fc794bba8ee2403c8cde304c806fdc23
Show the latest version for the dependency by default. 
https://www.loom.com/share/bc0500fa4507436da06e7698634974fd
Is there any easy way to debug or visualize overmind state?  I am usually checking through hooks context value which becomes difficult to check all values in the nested object. Thanks 👋
=> fix(dependencies): show latest version on Dependency

packages/app/package.json, packages/app/src/embed/components/Actions/index.js, packages/app/src/embed/components/Content/index.tsx, packages/app/src/embed/components/SplitPane/index.js
Bug fix #4924
Open Sandbox link does not respect initialpath and always loads the preview on the base path, even though the person is seeing the initialpath one.
initialpath param is added (if present) to the Open Sandbox link so it opens on the correct page
1. Step A
Ran `yarn start` and tested with and without initialpath changed by the user
2. Step B
3. Step C
=> Respect initialpath in embed "Open Sandbox" link

packages/app/src/app/pages/Sandbox/SearchDependencies/SearchBox.tsx
There was a user with an issue where it broke because next.focus was not a function
sent over DM on twitter
=> fix edge case

standalone-packages/browser-jsdom/index.js
You don't wanna know how deep I had to go
Updating it JSDom does not fix it because its a dependency that uses it and that dependency is supposed to run in node
closes #4303
Example
https://pr4935.build.csb.dev/s/n9m2w9q8x0?file=/index.test.js
=> Fix Tests on Firefox

.eslintrc, packages/app/src/app/overmind/namespaces/files/internalActions.ts
Right now when you upload a json file with emojis or any other non-utf-8 characters it shows gibberish
This fixes that by using atob in a different way
closes #1248
=> Fix encoding on json files

packages/app/src/sandbox/eval/presets/create-react-app/v3.ts, packages/sandpack-core/src/manager.ts, packages/sandpack-core/src/npm/dynamic/fetch-npm-module.ts, packages/sandpack-core/src/utils/extensions.ts
We should prefer `mjs` over `js`. This changes that.
Fixes #4958
=> Fix default extensions for sandpack (prefer mjs)

packages/app/src/app/components/Preview/DevTools/Tabs/index.tsx, packages/app/src/app/components/Preview/DevTools/index.tsx
It was impossible to move bottom devtools to the top part, because of an undefined value in track. This fixes that by moving the track to where we know view is defined.
Tested moving tabs from top to bottom, other way around and in same row.
=> Fix moving tab to top in devtools
