- packages/app/src/app/pages/NewDashboard/Components/Selection/ContextMenu.tsx
- packages/app/src/app/pages/NewDashboard/Content/routes/Deleted/index.tsx
> show correct menu items in deleted sandboxes

- packages/app/package.json
- packages/app/src/app/pages/NewDashboard/Components/Folder/FolderCard.tsx
- packages/app/src/app/pages/NewDashboard/Components/Folder/FolderListItem.tsx
- packages/app/src/app/pages/NewDashboard/Components/Sandbox/SandboxCard.tsx
- packages/app/src/app/pages/NewDashboard/Components/Sandbox/SandboxListItem.tsx
- packages/app/src/app/pages/NewDashboard/Components/Sandbox/TemplateIcon.tsx
- packages/app/src/app/pages/NewDashboard/Components/Sandbox/index.tsx
- packages/app/src/app/pages/NewDashboard/Components/Selection/index.tsx
- packages/app/src/app/pages/NewDashboard/Content/routes/All/index.tsx
- packages/app/src/app/pages/NewDashboard/Sidebar/index.tsx
- packages/components/src/components/Button/index.tsx
- yarn.lock
Fixes CSB-284
Fixes CSB-283
Fixes CSB-281
Fixes CSB-264
Fixes CSB-291
Fixes CSB-222
> WIP: Dashboard polish 8

- packages/app/src/app/overmind/namespaces/dashboard/actions.ts
- packages/app/src/app/overmind/namespaces/dashboard/state.ts
- packages/app/src/app/pages/NewDashboard/Components/Filters/SortOptions/index.tsx
- packages/app/src/app/pages/NewDashboard/Content/index.tsx
- packages/app/src/app/pages/NewDashboard/Content/routes/All/index.tsx
- packages/app/src/app/pages/NewDashboard/Content/routes/All/useFilteredItems.ts
- packages/app/src/app/pages/NewDashboard/Content/routes/Deleted/index.tsx
- packages/app/src/app/pages/NewDashboard/Content/routes/Drafts/index.tsx
- packages/app/src/app/pages/NewDashboard/Content/routes/Recent/index.tsx
- packages/app/src/app/pages/NewDashboard/Content/routes/Search/index.tsx
- packages/app/src/app/pages/NewDashboard/Content/routes/Settings/Invite.tsx
- packages/app/src/app/pages/NewDashboard/Content/routes/Settings/NewTeam.tsx
- packages/app/src/app/pages/NewDashboard/Content/routes/Settings/TeamSettings.tsx
- packages/app/src/app/pages/NewDashboard/Content/routes/Settings/UserSettings.tsx
- packages/app/src/app/pages/NewDashboard/Content/routes/StartSandboxes/index.tsx
- packages/app/src/app/pages/NewDashboard/Content/routes/Templates/index.tsx
Also adds a title to all routes
closes CSB-295
closes CSB-273
closes CSB-276
closes CSB-278
closes CSB-275
closes CSB-274
closes CSB-293
> Fix ordering and filtering issues

- packages/app/src/app/pages/NewDashboard/Components/Header/index.tsx
- packages/app/src/app/pages/NewDashboard/Components/VariableGrid/index.tsx
- packages/app/src/app/pages/NewDashboard/Content/routes/All/index.tsx
- packages/app/src/app/pages/NewDashboard/Content/routes/Deleted/index.tsx
- packages/app/src/app/pages/NewDashboard/Content/routes/Drafts/index.tsx
- packages/app/src/app/pages/NewDashboard/Content/routes/Home/index.tsx
- packages/app/src/app/pages/NewDashboard/Content/routes/Recent/index.tsx
- packages/app/src/app/pages/NewDashboard/Content/routes/Search/index.tsx
- packages/app/src/app/pages/NewDashboard/Content/routes/Templates/index.tsx
> WIP: Dashboard polish 10

- .all-contributorsrc
- README.md
- packages/app/src/app/pages/common/Modals/DeploymentModal/index.tsx
- packages/app/src/app/pages/common/Modals/index.tsx
- packages/app/src/app/pages/common/VercelIntegration/index.tsx
Bug fix for #4343
https://github.com/codesandbox/codesandbox-client/issues/4343
1. Click 'Deploy with Vercel' and verify padding:
- [ x] Testing 
- [ x] Ready to be merged
- [ x] Added myself to contributors table
> fix padding on icon in deployment modal (#4343)

- packages/homepage/src/components/layout.js
Added a banner up top on the home page
> make simple banner

- packages/components/package.json
- packages/components/src/components/Menu/index.tsx
- packages/components/src/components/Menu/reach-menu.fork.tsx
- packages/components/tsconfig.json
- yarn.lock
Upgrade all Reach UI dependencies + Fork menu-button and bring it into `@codesandbox/components` to use it for multiple use cases (example: #4373)
> Upgrade reach menu + add fork

- packages/app/src/app/pages/Sandbox/Editor/Workspace/Files/index.tsx
> show upload icon on private sandboxes

- packages/app/src/app/pages/NewDashboard/Components/Sandbox/SandboxCard.tsx
- packages/app/src/app/pages/NewDashboard/Components/Sandbox/SandboxListItem.tsx
- packages/app/src/app/pages/NewDashboard/Components/Selection/ContextMenu.tsx
- packages/app/src/app/pages/NewDashboard/Components/Selection/index.tsx
> WIP Dashboard: Scroll to sandbox in folder

- packages/app/src/sandbox/eval/transpilers/babel/convert-esmodule/__snapshots__/index.test.ts.snap
- packages/app/src/sandbox/eval/transpilers/babel/convert-esmodule/utils.ts
> Rename our get function to $csbGet in defineProperty

- packages/app/src/app/pages/NewDashboard/Components/Sandbox/SandboxCard.tsx
- packages/app/src/app/pages/NewDashboard/Components/Sandbox/SandboxListItem.tsx
- packages/app/src/app/pages/NewDashboard/Components/Sandbox/index.tsx
- packages/app/src/app/pages/NewDashboard/Components/Selection/ContextMenu.tsx
- packages/app/src/app/pages/NewDashboard/Components/Selection/index.tsx
- packages/app/src/app/pages/NewDashboard/Sidebar/ContextMenu.tsx
- packages/app/src/app/pages/NewDashboard/Sidebar/index.tsx
> WIP Dashboard: Add menu + actions for folders in sidebar

- packages/app/src/app/pages/NewDashboard/Components/Selection/index.tsx
- packages/app/src/app/pages/NewDashboard/Content/routes/All/index.tsx
- packages/app/src/app/pages/NewDashboard/Content/routes/Deleted/index.tsx
- packages/app/src/app/pages/NewDashboard/Content/routes/Drafts/index.tsx
- packages/app/src/app/pages/NewDashboard/Content/routes/Home/index.tsx
- packages/app/src/app/pages/NewDashboard/Content/routes/Recent/index.tsx
- packages/app/src/app/pages/NewDashboard/Content/routes/Search/index.tsx
- packages/app/src/app/pages/NewDashboard/Content/routes/Templates/index.tsx
> WIP Dashboard: sync items between VariableGrid and Selection

- packages/app/src/app/pages/NewDashboard/Components/Selection/DragPreview.tsx
> WIP Dashboard: make small thumbnail follow cursor

- packages/app/src/app/pages/NewDashboard/Components/Folder/index.tsx
- packages/app/src/app/pages/NewDashboard/Components/Sandbox/index.tsx
- packages/app/src/app/pages/NewDashboard/Components/Selection/ContextMenu.tsx
- packages/app/src/app/pages/NewDashboard/Sidebar/ContextMenu.tsx
- packages/app/src/app/pages/NewDashboard/Sidebar/index.tsx
Fixes CSB-202
```
track('Dashboard2 - Recent template forked', { source: 'Home' });
track('Dashboard2 - Recent sandbox opened', { source: 'Home' });
track('Dashboard2 - Change workspace');
track('Dashboard2 - Create Folder', { source: 'Grid' });
track('Dashboard2 - Rename Folder', { source: 'Grid' });
track('Dashboard2 - Delete folder', { source: 'Grid' });
track('Dashboard2 - Create Folder', { source: 'Sidebar' });
track('Dashboard2 - Rename Folder', { source: 'Sidebar' });
track('Dashboard2 - Delete folder', { source: 'Sidebar' });
track('Dashboard2 - Rename sandbox');
```
> WIP Dashboard - Analytics

- packages/app/src/app/pages/NewDashboard/Sidebar/index.tsx
Fixes CSB-194
HOVER_THRESHOLD = name === 'All sandboxes' ? 0 : 500; // ms
> WIP Dashboard: toggle sub folders on drag hover

- packages/app/src/app/pages/NewDashboard/Content/routes/Search/index.tsx
Fixes CSB-311
Thanks to @SaraVieira
> WIP Dashboard: reduce number of requests in search

- packages/app/src/app/pages/NewDashboard/Components/Filters/FilterOptions/index.tsx
- packages/app/src/app/pages/NewDashboard/Components/Selection/index.tsx
- packages/app/src/app/pages/NewDashboard/Sidebar/index.tsx
- packages/app/src/app/pages/NewDashboard/index.tsx
- packages/components/package.json
- packages/components/src/components/SkipNav/index.tsx
- packages/components/src/components/ThemeProvider/index.tsx
- packages/components/src/index.ts
- yarn.lock
Add skip to content Fixes CSB-176
Enter to pick folder in sidebar
Open menu on the correct sandbox
Add reach tags to stop warnings
Use defaultChecked for warning
> WIP: Dashboard polish 17

- packages/app/src/app/components/Overlay/Overlay.tsx
- packages/app/src/app/pages/Dashboard/Navigation/index.tsx
- packages/app/src/app/pages/NewDashboard/Header/Notifications/Filters.tsx
- packages/app/src/app/pages/NewDashboard/Header/Notifications/index.tsx
- packages/app/src/app/pages/NewDashboard/Header/Notifications/notifications/Menu.tsx
- packages/app/src/app/pages/NewDashboard/Header/Notifications/notifications/SandboxInvitation.tsx
- packages/app/src/app/pages/NewDashboard/Header/Notifications/notifications/TeamAccepted.tsx
- packages/app/src/app/pages/NewDashboard/Header/Notifications/notifications/TeamInvite.tsx
- packages/app/src/app/pages/NewDashboard/Header/index.tsx
- packages/app/src/app/pages/Sandbox/Editor/Header/Collaborators/Collaborators.tsx
- packages/common/src/utils/short-distance.ts
https://linear.app/codesandbox/issue/CSB-351/fix-design-bugs-in-notififications
all but close on outisde click fixes
>  fix design bugs in notififications

- packages/app/src/app/pages/NewDashboard/Content/utils.ts
- packages/app/src/app/pages/NewDashboard/Sidebar/TeamAvatar.tsx
- packages/app/src/app/pages/NewDashboard/Sidebar/index.tsx
- packages/components/src/design-language/colors.ts
> WIP Dashboard: workspace menu redesign

- packages/app/src/app/pages/NewDashboard/Components/Sandbox/SandboxCard.tsx
- packages/app/src/app/pages/NewDashboard/Components/Sandbox/SandboxListItem.tsx
- packages/app/src/app/pages/NewDashboard/Components/Sandbox/index.tsx
- packages/components/src/components/Icon/icons.tsx
> dashboard-redesigned-sandbox

- packages/app/src/app/pages/NewDashboard/Components/Sandbox/index.tsx
- packages/app/src/app/pages/NewDashboard/Components/Selection/ContextMenu.tsx
- packages/app/src/app/pages/NewDashboard/Components/Selection/index.tsx
- packages/app/src/app/pages/NewDashboard/Components/VariableGrid/index.tsx
- packages/app/src/app/pages/NewDashboard/Content/routes/All/index.tsx
- packages/app/src/app/pages/NewDashboard/Sidebar/index.tsx
> WIP: Dashboard polish 18

- packages/app/src/app/overmind/effects/live/clients.test.ts
- packages/app/src/app/overmind/effects/live/clients.ts
- packages/app/src/app/overmind/effects/live/index.ts
Prepares the client to handle missing operations which the server will now notify about
> resync method for OT client

- packages/app/src/app/overmind/namespaces/dashboard/actions.ts
- packages/app/src/app/pages/NewDashboard/Components/Folder/FolderCard.tsx
- packages/app/src/app/pages/NewDashboard/Components/Folder/index.tsx
- packages/app/src/app/pages/NewDashboard/Components/Sandbox/SandboxCard.tsx
- packages/app/src/app/pages/NewDashboard/Components/Sandbox/index.tsx
- packages/app/src/app/pages/NewDashboard/Components/Selection/DragPreview.tsx
- packages/app/src/app/pages/NewDashboard/Components/Selection/index.tsx
- packages/app/src/app/pages/NewDashboard/Components/VariableGrid/index.tsx
- packages/app/src/app/pages/NewDashboard/Content/routes/Home/index.tsx
- packages/app/src/app/pages/NewDashboard/Content/routes/Settings/Invite.tsx
- packages/app/src/app/pages/NewDashboard/Content/routes/Settings/NewTeam.tsx
- packages/app/src/app/pages/NewDashboard/Content/routes/Settings/TeamSettings.tsx
- packages/app/src/app/pages/NewDashboard/Sidebar/ContextMenu.tsx
- packages/app/src/app/pages/NewDashboard/Sidebar/index.tsx
Fixes CSB-356
Fixes CSB-355
Fixes CSB-310
Fixes CSB-270
Fixes CSB-255
Fixes CSB-247
Smoother drag preview
Replace team with workspace in copy
> WIP: Dashboard Polish

- packages/app/src/app/pages/NewDashboard/Components/Folder/index.tsx
- packages/app/src/app/pages/NewDashboard/Components/Sandbox/SandboxCard.tsx
- packages/app/src/app/pages/NewDashboard/Components/Sandbox/SandboxListItem.tsx
- packages/app/src/app/pages/NewDashboard/Components/Sandbox/index.tsx
- packages/app/src/app/pages/NewDashboard/Components/Selection/ContextMenu.tsx
- packages/app/src/app/pages/NewDashboard/Components/Selection/index.tsx
- packages/app/src/app/pages/NewDashboard/Sidebar/index.tsx
> WIP: Dashboard polish 19

- packages/app/src/app/pages/NewDashboard/Components/Filters/FilterOptions/index.tsx
- packages/app/src/sandbox/eval/utils/is-es-module.test.ts
The issue with using defaultChecked is that it doesn't update checkboxes when select all was clicked
Adding checked fixes it
> Fix Weird behaviour or environment filters (new dahsboard)

- packages/app/src/app/pages/NewDashboard/Components/Selection/ContextMenu.tsx
- packages/app/src/app/pages/NewDashboard/Sidebar/ContextMenu.tsx
- packages/components/src/components/Menu/index.tsx
- packages/components/src/components/Menu/menu.stories.tsx
- packages/components/src/components/Menu/reach-menu.fork.tsx
> Dashboard: Accessible context menu

- packages/app/src/app/components/CreateNewSandbox/CreateSandbox/TemplateList/TemplateList.tsx
> add fallback if template.sandbox.is null

- packages/app/src/app/components/Preview/DevTools/Terminal/Shell/index.tsx
This is one is the weirdest ives
closes #4037
> check if function before running

- packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/NotOwnedSandboxInfo/BookmarkTemplateButton/index.tsx
> return if no customTemplate

- packages/app/src/app/pages/Sandbox/Editor/Header/Actions.tsx
> fix edge cases when experiments is null

- packages/app/src/app/components/Preview/DevTools/index.tsx
> check that get views is an object

- packages/app/src/app/components/CreateNewSandbox/CreateSandbox/elements.ts
Fixes that weird issue Gareth and a couple more people have but I can't reproduce for the life of me
shown here
https://twitter.com/BisvarupMukher1/status/1274394317314916352
> fix weird scroll issue

- packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/GitHub/CreateRepo.tsx
- packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/GitHub/index.tsx
Brings back "create repo on Github" on existing github sandboxes
> put back exports

- packages/components/src/components/Button/index.tsx
Followup of #4451
Would this just work? I'm not sure if it breaks anything.
> Make Button a Link if it has `to` prop

- packages/app/src/app/components/TeamAvatar/TeamAvatar.tsx
- packages/app/src/app/components/TeamAvatar/index.ts
- packages/app/src/app/graphql/introspection-result.ts
- packages/app/src/app/graphql/types.ts
- packages/app/src/app/overmind/actions.ts
- packages/app/src/app/overmind/effects/gql/dashboard/fragments.ts
- packages/app/src/app/overmind/effects/gql/dashboard/queries.ts
- packages/app/src/app/overmind/factories.ts
- packages/app/src/app/overmind/namespaces/dashboard/actions.ts
- packages/app/src/app/overmind/namespaces/dashboard/state.ts
- packages/app/src/app/overmind/state.ts
- packages/app/src/app/pages/NewDashboard/Components/Sandbox/SandboxCard.tsx
- packages/app/src/app/pages/NewDashboard/Components/Sandbox/SandboxListItem.tsx
- packages/app/src/app/pages/NewDashboard/Components/Sandbox/index.tsx
- packages/app/src/app/pages/NewDashboard/Components/Sandbox/types.ts
- packages/app/src/app/pages/NewDashboard/Components/Selection/index.tsx
- packages/app/src/app/pages/NewDashboard/Content/routes/All/index.tsx
- packages/app/src/app/pages/NewDashboard/Content/routes/Deleted/index.tsx
- packages/app/src/app/pages/NewDashboard/Content/routes/Settings/Invite.tsx
- packages/app/src/app/pages/NewDashboard/Content/routes/Settings/TeamSettings.tsx
- packages/app/src/app/pages/NewDashboard/Content/routes/Settings/index.tsx
- packages/app/src/app/pages/NewDashboard/Content/routes/Templates/index.tsx
- packages/app/src/app/pages/NewDashboard/Sidebar/index.tsx
- packages/app/src/app/pages/common/Modals/TeamInviteModal/index.tsx
- packages/components/src/components/Button/index.tsx
- packages/components/src/components/ThemeProvider/index.tsx
- packages/components/src/components/Tooltip/index.tsx
The commit titles describe pretty well what has changed!
> Dashboard Improvements

- packages/app/src/app/overmind/namespaces/dashboard/actions.ts
- packages/app/src/app/overmind/namespaces/dashboard/utilts.ts
- packages/app/src/app/pages/NewDashboard/Components/Breadcrumbs/index.tsx
- packages/app/src/app/pages/NewDashboard/Components/EmptyScreen/index.tsx
- packages/app/src/app/pages/NewDashboard/Components/Folder/FolderCard.tsx
- packages/app/src/app/pages/NewDashboard/Components/Header/index.tsx
- packages/app/src/app/pages/NewDashboard/Components/Selection/index.tsx
- packages/app/src/app/pages/NewDashboard/Components/VariableGrid/index.tsx
- packages/app/src/app/pages/NewDashboard/Content/routes/All/index.tsx
- packages/app/src/app/pages/NewDashboard/Content/routes/All/useFilteredItems.ts
- packages/app/src/app/pages/NewDashboard/Content/routes/Search/index.tsx
- packages/app/src/app/pages/NewDashboard/Header/index.tsx
- packages/app/src/app/pages/NewDashboard/Sidebar/ContextMenu.tsx
- packages/app/src/app/pages/NewDashboard/Sidebar/index.tsx
- packages/app/src/app/pages/NewDashboard/types.ts
> Dashboard Improvements #3 

- packages/chrome-extension/content.js
This PR fixes the browser extension to the new GH UI
> fix browser extension

- packages/app/src/app/overmind/effects/vscode/Workbench.ts
- packages/app/src/app/overmind/namespaces/editor/actions.ts
CMD + SHIFT + R = reload preview
> add preview reload with shortcut

- packages/app/src/app/pages/Dashboard/index.tsx
- packages/app/src/app/pages/Live/index.tsx
- packages/app/src/app/pages/common/ErrorBoundary/CodeSadbox/CodeSadbox.tsx
- packages/app/src/app/pages/common/SignInButton/index.tsx
Fixes #4478
We started using new buttons in the header, but not all pages actually have the new theme provider.
> Import ThemeProvider in old dashboard

- packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/ProjectInfo/Privacy.tsx
fixes https://twitter.com/davidyarham/status/1277634547568594946
> fix small typo

- packages/homepage/src/utils/useAccordion.js
doen't append to the URL no more
> fix faq issues

- packages/app/src/app/components/Notifications/notifications/Comment.tsx
- packages/app/src/app/components/Notifications/notifications/Mention.tsx
- packages/app/src/app/components/Notifications/notifications/SandboxInvitation.tsx
This makes the transition from comment to resource really fast.
> Use history.push for notification links

- packages/app/src/app/overmind/effects/api/index.ts
- packages/app/src/app/overmind/namespaces/git/actions.ts
- packages/app/src/app/overmind/namespaces/git/state.ts
- packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/GitHub/index.tsx
This PR adds a step where the user says it wants to contribute back and then we will sync with Github
> Add sync step in gitflow

- packages/app/src/app/pages/common/Modals/ShareModal/getCode.ts
- packages/common/src/components/Preview/index.tsx
- packages/homepage/content/docs/2-embedding.md
- packages/homepage/content/docs/2-importing.md
- packages/homepage/content/docs/2-tests.md
- packages/homepage/content/docs/5-secrets.md
- packages/homepage/src/screens/home/explore/index.js
- standalone-packages/react-sandpack/src/components/SandpackProvider/SandpackProvider.tsx
> Remove autoplay from the iframe sandbox property

- packages/app/src/app/overmind/effects/vscode/SandboxFsSync/utils.ts
- packages/app/src/app/overmind/namespaces/files/actions.ts
- packages/app/src/app/overmind/namespaces/files/internalActions.ts
- packages/app/src/app/overmind/namespaces/live/liveMessageOperators.ts
> Properly update all files when updating folder path

- packages/app/src/app/overmind/effects/vscode/LinterWorker/index.js
Removes this rule from eslint, discussed on twitter here 
https://twitter.com/AdamRackis/status/1282758047807438851?s=20
> remove "no-loop-func" rule

- packages/app/src/app/pages/Sandbox/SearchDependencies/RawAutoComplete/index.js
> check that parts is defined

- packages/app/src/app/overmind/namespaces/editor/actions.ts
closes edge case described in #4561 
closes #4561 
closes #4534
> don't replace url unless a new url exists

- packages/app/src/app/overmind/factories.ts
Fixes https://sentry.io/organizations/codesandbox/issues/1749766173/events/7322c54aad16416890ed064411bd10e6/?project=2071895&query=is%3Aunresolved&statsPeriod=14d
> Fix closing a modal that's already closed

- packages/app/src/app/pages/NewDashboard/Components/Selection/ContextMenus/SandboxMenu.tsx
> do not show privacy buttons if not pro

- packages/app/src/app/components/TeamAvatar/TeamAvatar.tsx
- packages/app/src/app/pages/NewDashboard/Components/VariableGrid/index.tsx
- packages/app/src/app/pages/NewDashboard/Content/routes/Settings/TeamSettings.tsx
- packages/app/src/app/pages/NewDashboard/Content/routes/Settings/UserSettings.tsx
- packages/app/src/app/pages/Sandbox/Editor/Header/WorkspaceDashboardIcon/WorkspaceDashboardIcon.tsx
Dashboard:
1. make section headers 500 font weight
2. Vertically align show more with the header
3. Align grid in settings page to header
4. Increase margin of last item to make space at the end
Editor
1. make workspace avatar the size as other avatar
2. make back button solid on hover
> Dashboard feedback 1

- packages/homepage/src/pages/docs/start.js
> Fixed the placeholder to show correcly on mobile

- packages/app/src/app/pages/Profile2/index.tsx
- packages/app/src/app/pages/index.tsx
In the spirit of continuous deployment, started an empty page as base for work: /u2/drcmda
> WIP: create a new route for profiles v2

- packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/ProjectInfo/Delete.tsx
red/error feedback on hover and focus
> Sidebar: Delete button should have red hover feedback

- packages/app/src/sandbox/index.js
- packages/codesandbox-api/src/dispatcher/index.ts
- standalone-packages/react-sandpack/.storybook/webpack.config.js
- standalone-packages/react-sandpack/package.json
- standalone-packages/react-sandpack/stories/InTheWild.js
- standalone-packages/react-sandpack/yarn.lock
- standalone-packages/sandpack/package.json
- standalone-packages/sandpack/src/manager/index.ts
Fixes https://github.com/codesandbox/codesandbox-client/discussions/4631
> Add support for multiple managers in one context

- packages/app/src/app/components/CreateNewSandbox/CreateSandbox/Create/Create.tsx
- packages/app/src/app/components/CreateNewSandbox/CreateSandbox/Create/elements.ts
- packages/app/src/app/components/CreateNewSandbox/CreateSandbox/CreateSandbox.tsx
- packages/app/src/app/components/CreateNewSandbox/CreateSandbox/CreateSandboxModal.tsx
- packages/app/src/app/components/CreateNewSandbox/CreateSandbox/Import/elements.ts
- packages/app/src/app/components/CreateNewSandbox/CreateSandbox/TemplateList/TemplateList.tsx
- packages/app/src/app/components/CreateNewSandbox/CreateSandbox/elements.ts
- packages/app/src/app/components/Modal/index.js
- packages/app/src/app/pages/Sandbox/Editor/index.tsx
- packages/app/src/app/pages/Sandbox/index.tsx
- packages/app/src/app/pages/common/UserMenu/elements.ts
- packages/common/src/components/Scrollable/elements.ts
Makes the create sandbox modal responsive hiding a lot of things to let users create a sandbox on mobile
> responsive new sandbox

- packages/app/src/app/overmind/actions.ts
- packages/app/src/app/overmind/internalActions.ts
- packages/app/src/app/overmind/namespaces/live/actions.ts
- packages/app/src/app/pages/Live/index.tsx
- packages/app/src/app/pages/SignUp/index.tsx
closes #4646
closes #4645 
closes #4639
> fix login if not in modal

- packages/app/src/app/pages/Dashboard/Components/Repo/RepoCard.tsx
- packages/app/src/app/pages/Dashboard/Components/Repo/RepoListItem.tsx
- packages/app/src/app/pages/Dashboard/Components/Selection/ContextMenu.tsx
We can't really do anything with them so no actions should be there
> remove actions from repo folders

- packages/app/src/app/pages/Dashboard/Components/Selection/ContextMenus/ContainerMenu.tsx
- packages/app/src/app/pages/Dashboard/Components/Selection/index.tsx
1. Don't show `Create new sandbox` in menu on All sandboxes screen
2. Turn renaming off when dragging
> Dashboard: Fix bugs reported by andras

- packages/app/src/app/pages/Dashboard/Components/VariableGrid/index.tsx
- packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/ConfigurationFiles/index.tsx
Updates weight of titles in the dashboard and padding in one of the screens in the editor
> update padding and text weight

- packages/app/src/app/overmind/actions.ts
- packages/app/src/app/overmind/internalActions.ts
Makes the provider for login mandatory to make sure what happened yesterday does not happen again
> make provider mandatory

- packages/app/src/app/overmind/namespaces/editor/actions.ts
- packages/app/src/app/overmind/namespaces/git/actions.ts
Fixes issue with creating a new repo, the UI hangs... not anymore 😄
> fix create repo

- packages/app/src/app/overmind/namespaces/git/actions.ts
> fix loading issue

- packages/app/src/app/overmind/namespaces/git/actions.ts
> GitHub improv

- packages/app/src/app/overmind/factories.ts
> fix modals bug

- packages/app/src/app/pages/common/Modals/MoveSandboxFolderModal/DirectoryPicker/SandboxesItem/FolderEntry/CreateFolderEntry.tsx
- packages/app/src/app/pages/common/Modals/MoveSandboxFolderModal/DirectoryPicker/SandboxesItem/FolderEntry/index.tsx
- packages/app/src/app/pages/common/Modals/MoveSandboxFolderModal/DirectoryPicker/SandboxesItem/index.tsx
Tested renaming, creating, deleting and selecting folders in personal and team workspace.
> Fix selecting & creating folders in move modal

- packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Explorer/ExternalResources/index.tsx
> fix overflow issue in external dependencies

- packages/app/src/app/components/Markdown/Link.tsx
closes #4690
An empty link broke the website, wow javascript ah?
> fix markdown crash on info

- packages/app/src/app/overmind/namespaces/dashboard/actions.ts
- packages/app/src/app/pages/Dashboard/Components/Selection/ContextMenus/MultiItemMenu.tsx
- packages/app/src/app/pages/Dashboard/Components/Selection/ContextMenus/SandboxMenu.tsx
> Allow changing privacy of multiple sandboxes

- packages/homepage/content/changelog/index.js
> update whats new tab

- packages/homepage/content/changelog/index.js
Added 3.9.2 in whats new section
 Features
- Dashboard - team members management|
- Add freezing/unfreezing in the dashboard
- Update Algolia info to use our new index
- Allow changing privacy of multiple sandboxes
- Add support for fetching gists
- Additional properties added to Preview Manager
by JohnPremKumar  https://github.com/codesandbox/codesandbox-client/pull/4535
- Add missing js modules for dojo styles 
By maier49 https://github.com/codesandbox/codesandbox-client/pull/4548
Fix
- Merge user initialisation into one function 
- Propagate hyperlink clicks
- Update overmind to lates
- Notify auth on commit
- Fix markdown crash on info
- Fix overflow issue in external dependencies
> updated whats new

- .github/workflows/stale.yml
Runs everyday at 12:00 am
https://github.com/actions/stale
https://github.com/nodejs/node-core-utils/blob/master/.github/workflows/stale.yml
This one seems to work on bigger projects
Thank you @codebytere
> add stale gh action

- packages/app/src/app/components/CreateNewSandbox/CreateSandbox/New/index.tsx
- packages/homepage/content/changelog/3-9-2/index.md
- packages/homepage/content/changelog/index.js
> Changelog 392

- packages/chrome-extension/popup.css
- packages/chrome-extension/popup.html
> Extension Dark Mode issue - Fixed

- packages/app/src/app/pages/Dashboard/Components/Folder/CreateFolder.tsx
- packages/app/src/app/pages/Dashboard/Components/Folder/FolderCard.tsx
- packages/app/src/app/pages/Dashboard/Components/Folder/FolderListItem.tsx
- packages/app/src/app/pages/Dashboard/Components/Folder/index.tsx
- packages/app/src/app/pages/Dashboard/Sidebar/ContextMenu.tsx
- packages/app/src/app/pages/Dashboard/Sidebar/constants.ts
- packages/app/src/app/pages/Dashboard/Sidebar/index.tsx
Enhancement
Currently, we can create and update the folder name to be empty or name with only spaces.
Add validation to avoid empty name.
1. Tested create a folder through sidebar and folder UI.
2. Rename Folder name flow
> fix: add validation for empty folder

- packages/app/src/app/components/SignInModal.tsx
- packages/app/src/app/pages/index.tsx
Enhancement
Seeing lag in sign in Modal animation. This happens because of routes component re-rendering due to hooks change present in `src/app/pages/index.tsx`.
https://www.loom.com/share/5973551e773249cc98ef232959b89db1
Placed the hooks in the `SignInModal` which prevents re-rendering of Routes Component.
https://www.loom.com/share/7d1077db197546aeb2169159238b072a
1. Checked results after profiling 
2. Tested sign in modals
> fix: signin modal animation lag 

- packages/app/src/app/components/TeamAvatar/TeamAvatar.tsx
- packages/app/src/app/overmind/actions.ts
- packages/app/src/app/pages/Sandbox/Editor/Header/Collaborators/CollaboratorList.tsx
- packages/common/src/types/index.ts
> Fix showing personal workspace in the share sheet

- packages/app/src/app/components/CreateNewSandbox/CreateSandbox/Import/Import.tsx
- packages/app/src/app/overmind/namespaces/editor/actions.ts
- packages/app/src/app/overmind/namespaces/git/actions.ts
Gives specific error when trying to import a private repo without being logged in:
> deal with not signed on private repos

- packages/app/src/app/pages/Dashboard/Content/routes/Repositories/useFilteredItems.ts
> do null check in repo sandbxoes

- packages/app/src/app/overmind/actions.ts
- packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Explorer/Dependencies/AddDependency.tsx
- packages/app/src/app/pages/Sandbox/SearchDependencies/index.tsx
> Depenency modal fix

- packages/app/src/app/pages/Sandbox/SearchDependencies/Dependency.tsx
Bug Fix
Dependency modal shows the wrong selected version, as we don't have the defaultValue set in.
https://www.loom.com/share/219635b740a8468f922cda956ffb580f
https://www.loom.com/share/0e4014ff3e2f448dba075b0bb329f522
Great work guys on the new improved UI 💯
> fix(dependencies): preserve selected version after new search

- packages/app/src/app/overmind/namespaces/dashboard/actions.ts
- packages/app/src/app/pages/Dashboard/Content/routes/Settings/TeamSettings.tsx
Incorrect label in settings as spotted by @lbogdan 
!!! I only changed the label name and not the function name !!!
> Fixed label

- CONTRIBUTING.md
- package.json
- yarn.lock
Contributing guide update
We dont have info about how to debug state in overmind.
Add relevant info
`Note:` I have added the dependency of `overmind-devtools` as `start:overmind` uses it.
> chore: add overmind info in contributing guide

- packages/app/src/app/components/Markdown/Code.tsx
- packages/app/src/app/components/TeamAvatar/TeamAvatar.tsx
- packages/app/src/app/pages/Dashboard/Components/Folder/index.tsx
- packages/app/src/app/pages/Dashboard/Sidebar/ContextMenu.tsx
- packages/app/src/app/pages/Patron/PricingModal/PricingChoice/ThankYou/index.tsx
- packages/app/src/app/pages/Profile2/ProfileCard.tsx
- packages/app/src/app/pages/Sandbox/Editor/Header/Actions.tsx
- packages/app/src/app/pages/Sandbox/Editor/Header/Collaborators/Collaborators.tsx
- packages/app/src/app/pages/Sandbox/Editor/Header/SandboxName/index.tsx
- packages/app/src/app/pages/Sandbox/Editor/Navigation/Navigation.tsx
- packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Comments/Dialog/index.tsx
- packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Explorer/Dependencies/AddDependency.tsx
- packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Explorer/index.tsx
- packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/GitHub/index.tsx
- packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Live/LiveNow/User.tsx
- packages/app/src/app/pages/common/LikeHeart/MaybeTooltip.tsx
- packages/app/src/app/pages/common/Modals/MoveSandboxFolderModal/DirectoryPicker/TeamsPicker/index.tsx
- packages/common/src/components/flex/index.stories.tsx
- packages/components/src/components/Menu/reach-menu.fork.tsx
- packages/components/src/components/SkipNav/index.tsx
- packages/components/src/components/Textarea/index.tsx
- packages/homepage/src/templates/_docs.elements.js
- packages/homepage/src/templates/docs.js
So this error happens when fragments render with no children and react doesn't like that.
I went through all the Fragments we have and fix all the ones that can possibly render null
This will close all those issues
closes #4643
closes #4735
closes #4692
closes #4663
closes #4934
closes #4909
closes #4932
closes #4947
> Fix " Failed to execute 'removeChild' on 'Node'" errors

- packages/app/src/app/pages/Profile/Header/UserInfo/ProfileInfo/index.tsx
- packages/common/src/types/index.ts
Do not show a link to GitHub if there is no GitHub
> Remove Profile link to GitHub if the user signed up with Google

- packages/app/src/sandbox/status-screen/loading-screen.html
Fixes a typo in dow**n**loading.
N/A
N/A
N/A
> Corrects typo.

- packages/app/src/app/overmind/namespaces/workspace/actions.ts
- packages/app/src/app/pages/Sandbox/SearchDependencies/Dependency.tsx
Enhancement
Currently, we don't show the installed version 
https://www.loom.com/share/89a6d6fbbbf1415c9c63f5c222916f23
> feat(dependencies): show installed version on dependency modal

- packages/app/src/app/overmind/effects/vscode/LinterWorker/index.js
For TS files there needs to be a different check, based on https://stackoverflow.com/questions/63818415/react-was-used-before-it-was-defined.
> Fix 'React is used before defined' in TS files

- packages/app/src/sandbox/eval/transpilers/babel/convert-esmodule/__snapshots__/index.test.ts.snap
- packages/app/src/sandbox/eval/transpilers/babel/convert-esmodule/index.test.ts
- packages/app/src/sandbox/eval/transpilers/babel/convert-esmodule/index.ts
Star exports shouldn't have any special ordering.
> Fix star export order

- packages/app/src/app/overmind/namespaces/patron/actions.ts
Also tested to make sure it works!
> Add a survey for people that cancel Pro

- packages/app/src/app/overmind/effects/live/index.ts
The client requests for every socket reconnect a new token
This happens every 100ms at the start, and sometimes
the server hasn't responded before retrying, which causes a big
spam for the server. This change makes sure that we only request
a new token when we're sure that the existing request has finished.
> Make the client cache a jwt token to prevent spamming the server

- packages/app/src/app/pages/Profile2/Header.tsx
- packages/app/src/app/pages/Profile2/ProfileCard.tsx
- packages/app/src/app/pages/Profile2/index.tsx
- packages/components/src/components/Stats/index.tsx
add 404 page if user not found
hide stats that are not available
Fix header height
add github username to social links
> Profile: Polish no. 1

- packages/homepage/content/features/collaboration/index.md
- packages/homepage/content/features/devrel/index.md
- packages/homepage/content/features/learning/index.md
- packages/homepage/content/features/onboarding/index.md
- packages/homepage/content/features/prototyping/index.md
- packages/homepage/content/features/team/index.md
Update copy to reflect workspace terminology instead of teams
> Update copy - teams -> workspaces

- packages/app/src/app/pages/Dashboard/Components/Selection/ContextMenu.tsx
Fixes https://github.com/codesandbox/codesandbox-client/issues/4991#issuecomment-707155794
> check actual items available

- packages/app/src/app/pages/Profile2/ProfileCard.tsx
> Profiles - add delete button for social links

- packages/app/src/app/overmind/namespaces/profile/actions.ts
> Profiles - add tracking for new profiles

- packages/app/src/app/overmind/effects/vercel.ts
- packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/ConfigurationFiles/index.tsx
- packages/app/src/app/utils/get-type.ts
- packages/common/src/templates/configuration/now/index.ts
- packages/common/src/templates/template.ts
- packages/components/src/examples/configuration-sidebar.stories.tsx
> change now.json to vercel.json

- packages/sandpack-core/package.json
- packages/sandpack-core/src/cache.ts
- yarn.lock
Brave breaks with some shields because there is no indexdb
closes #5097
> Fix emebeds when browser doesn't allow cookies

- packages/app/src/app/components/CreateNewSandbox/CreateSandbox/CreateSandbox.tsx
- packages/app/src/app/components/CreateNewSandbox/CreateSandbox/Icons/BackIcon.tsx
- packages/app/src/app/components/CreateNewSandbox/CreateSandbox/Icons/index.ts
- packages/app/src/app/components/CreateNewSandbox/CreateSandbox/elements.ts
Right now when you land on this page there is no way to leave so this PR adds a button for the dashboard
> add back to dashboard on Create Sandbox Modal

- packages/app/src/app/pages/Dashboard/Components/Selection/ContextMenus/SandboxMenu.tsx
Bug Fix
Seeing multiple dividers at the bottom in the context menu. 
Conditionally add the dividers
1. Open context menu in official templates and in personal sandbox
> fix(sandbox-card): conditionally add menu dividers in context menu

- packages/app/src/app/pages/Sandbox/Editor/Content/Preview/ResponsiveWrapper/index.tsx
> Use Polyfill for ResizeObserver

- packages/app/src/sandbox/eval/transpilers/babel/worker/plugins/babel-plugin-rename-imports.js
> Fix dynamic imports on Babel 6

- packages/common/src/components/Preview/Navigator/index.tsx
- packages/common/src/components/Preview/index.tsx
Will not work
More info here:
https://github.com/niklasvh/html2canvas
> disable preview comments in sse

- packages/common/src/components/Preview/index.tsx
I tested in:
- Chrome: Will block any downloads done automatically
- Firefox and Brave:  Will show you a download button and not download automatically
- SaFari: will show a massive warning asking you if you wish to download that
If put on page load no website will download files automatically
Not added automatically to embedded since that is in control of the user
closes #4739
> add alow-downloads to the iframe

- packages/app/src/app/components/Markdown/index.tsx
> fix quote styling in comments

- packages/app/src/app/pages/Sandbox/GitHubError.tsx
- packages/app/src/app/pages/Sandbox/index.tsx
It used to only show error and now it shows that you are not signed in
> Add Error if not logged and importing GH repo

- packages/app/src/app/pages/Dashboard/Content/routes/Search/index.tsx
- packages/app/src/app/pages/Dashboard/Content/routes/Search/searchItems.ts
- packages/sandbox-hooks/screenshot.js
> Add folders to the dashboard search

- packages/common/src/components/Preview/Navigator/index.tsx
> comments in see

- packages/sandbox-hooks/screenshot.js
Fixes issue where cross origin is not activated on actual cross origin images
> fix origin handling

- packages/app/src/app/overmind/effects/browser.ts
- packages/app/src/app/overmind/namespaces/preview/actions.ts
- packages/app/src/app/overmind/onInitialize.ts
- packages/chrome-extension/background.js
- packages/chrome-extension/content.js
- packages/chrome-extension/manifest.json
This is ready to be merged as it does not affect any existing code. We can test the extension locally to see how well it works first
> Extension screenshot

- packages/app/src/app/pages/Profile2/ProfileCard.tsx
- packages/app/src/app/pages/Profile2/index.tsx
The global routing and nested routing in profiles do not play well together. Removed the nested routing, it's not really needed.
> Bugfix: remove nested router from profiles

- packages/app/src/sandbox/eval/transpilers/babel/convert-esmodule/__snapshots__/index.test.ts.snap
- packages/app/src/sandbox/eval/transpilers/babel/convert-esmodule/index.test.ts
- packages/app/src/sandbox/eval/transpilers/babel/convert-esmodule/index.ts
> Fix imports with spaces

- packages/app/src/app/overmind/effects/browserExtension.ts
- packages/app/src/app/overmind/effects/preview.ts
- packages/app/src/app/overmind/namespaces/preview/actions.ts
- packages/app/src/app/pages/Sandbox/Editor/Content/Preview/ResponsiveWrapper/PreviewCommentWrapper.tsx
- packages/app/src/app/pages/Sandbox/Editor/Content/Preview/index.tsx
- packages/chrome-extension/manifest.json
Since we use a shortcut now, we have to ensure when used that you are actually allowed to create the screenshot. Also include some fixes that was broken in the other broken PR which caused code not to work correctly
> detect ability to actually take preview screenshot

- packages/app/src/app/pages/Sandbox/Editor/Content/Preview/ResponsiveWrapper/PreviewCommentWrapper.tsx
Okay, lets try this last thing
> last try, omg

- packages/app/src/app/overmind/effects/vscode/extensionHostWorker/common/fs.ts
> Update TypeScript for extensions

- packages/app/src/app/pages/Sandbox/Editor/Content/Preview/ResponsiveWrapper/PreviewCommentWrapper.tsx
- packages/chrome-extension/content.js
- packages/sandbox-hooks/screenshot.js
- Fix device pixel ratio in extension
- When document has scrollTop, we take that into account on HTML2Canvas
- Show cursor as bubble during creation of comment
> Extension screenshot9

- packages/common/src/components/SandboxCard/fixtures.ts
- packages/common/src/templates/helpers/is-server.ts
- packages/common/src/templates/index.ts
- packages/common/src/templates/quasar.ts
Naming wasn't consistent so issues were happening
To be merged with backend
closes #5256
> fix quasar imports

- packages/app/src/app/pages/Sandbox/Editor/Workspace/SgnInBanner.tsx
- packages/app/src/app/pages/Sandbox/Editor/Workspace/SignInBanner.tsx
- packages/app/src/app/pages/Sandbox/Editor/Workspace/elements.ts
- packages/app/src/app/pages/Sandbox/Editor/Workspace/index.tsx
Side banner for when user is not signed in
> first version of side banner

- packages/app/src/app/pages/common/Modals/MoveSandboxFolderModal/index.tsx
- packages/app/src/app/pages/index.tsx
- packages/common/src/templates/vue.ts
Moves check upper in the code to avoid new race condition
> Move sandbox fix update

- packages/app/src/app/pages/Sandbox/Editor/Workspace/index.tsx
> fix styling bug related to signin banner

- packages/components/src/components/Switch/index.tsx
- packages/components/src/components/Switch/switch.stories.tsx
disabled styleeees with `data-disabled`
> Components: Add styles for disabled switch

- packages/app/src/app/pages/Dashboard/Content/routes/Settings/TeamSettings/WorkspaceSettings.tsx
We'll need to bring back a third card when you can update payment details. Till then, I added an empty div to keep it to 2 cards
> Remove pilot promotion if you are in pilot

- packages/app/src/app/pages/Dashboard/Content/routes/Settings/components/PermissionSettings.tsx
> Dashboard settings: keep names consistent in dashboard

- packages/app/src/app/pages/Dashboard/Components/Selection/ContextMenus/SandboxMenu.tsx
- packages/app/src/app/pages/Dashboard/Content/routes/Settings/components/PermissionSettings.tsx
> Fix cannot read joinedPilot of undefined

- packages/app/src/app/pages/Profile2/AllSandboxes.tsx
Repro: https://codesandbox.io/u/oskarabc
Fix: http://pr5330.build.csb.dev/u/oskarabc
> Profiles: User has featured sandboxes but everything is unlisted

- packages/homepage/src/components/Navigation/MobileNav.js
Will add avatar of the user on the homepage
> Add user avatar to Mobile Homepage Header

- packages/app/src/app/components/CreateNewSandbox/CreateSandbox/TemplateList/TemplateList.tsx
Another place where using the translation of chrome with the tooltip breaks the app
closes #5348
> Use new tooltip to avoid crash

- packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Comments/components/MultiComment.tsx
> Fix crash on comments

- packages/app/src/sandbox/eval/transpilers/babel/worker/babel-worker.js
- packages/app/src/sandbox/eval/transpilers/babel/worker/utils/error-mock.ts
> Fix Vue 3 on Firefox

- packages/homepage/content/docs/2-api.md
- packages/homepage/content/docs/2-importing.md
Adds How to Create folders in the Define API and also adds headings
Related: https://github.com/codesandbox/codesandbox-client/discussions/5368
> Adds How to Create folders in the Define API and also adds headings

- packages/common/src/utils/supports-new-react-transform.ts
Making PR to test since my local dev seems broken because of websockets
closes #5407
> Fix React transform not found in newer version of react

- packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Explorer/Dependencies/AddDependency.tsx
- packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Explorer/Dependencies/useKeys.ts
- packages/app/src/app/pages/Sandbox/SearchDependencies/Dependency.tsx
Example: https://www.npmjs.com/package/react-jquery
closes #5033
> Fix issue where a user tries to install a dependency that has no versions

- packages/app/src/app/overmind/namespaces/live/internalActions.ts
> Fix edge case where changedModuleShortids is null

- packages/app/src/app/pages/Sandbox/Editor/Header/SignInAd.tsx
- packages/app/src/app/pages/Sandbox/Editor/utils/get-vscode-theme.js
Updates with a differnt design 
When approved will add the 3 minute timeout back
> Update sign in banner design

- packages/app/scripts/start.js
- packages/app/src/app/overmind/effects/browser.ts
- packages/app/src/app/pages/Sandbox/Editor/Content/Preview/index.tsx
Right now the install banner is showing in all browsers.
This shows it in chromium browsers that can install the extension
> only show install extension banner in chromium browsers

- packages/app/src/app/overmind/namespaces/editor/state.ts
> Fix crash by wrapping JSON.parse in a try...catch

- packages/app/src/app/pages/TeamInvitation/TeamInvitation.tsx
We also seemed to have an issue where sometimes pages did not recognize login and I think it had to do with the function only being called one
> Show user friendly error if we have issues fetching team token

- packages/app/src/app/overmind/effects/api/index.ts
- packages/app/src/app/overmind/namespaces/git/actions.ts
- packages/app/src/app/pages/common/Modals/NotFoundBranchModal/index.tsx
- packages/app/src/app/pages/common/Modals/index.tsx
> Redirect user if branch is gone

- packages/homepage/src/pages/pricing/_cards.js
> Add checkmarks to cards in pricing

- packages/app/src/sandbox/eval/presets/vue-cli/index.ts
- packages/app/src/sandbox/eval/presets/vue-cli/v3.ts
This shaves off 500kb from the sandbox bundle size.
> Greatly reduce initial bundle size of sandbox

- packages/homepage/src/pages/jobs/index.js
> added Senior Designer

- packages/app/src/app/pages/Dashboard/Components/Selection/ContextMenus/SandboxMenu.tsx
- packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/ProjectInfo/Permissions.tsx
All pro users have this feature
- Sandbox menu
- IDE
> Bugfix: Remove team pro check for sandbox permissions

- packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Explorer/Files/DirectoryEntry/Entry/index.tsx
- packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Explorer/Files/DirectoryEntry/index.tsx
Enhancement
File tree is skipped when using tab.
https://www.loom.com/share/fa2183f780464d51b1d79d4d49a7a79c
1. Tested by traversing through tab
I am not 100% sure whether the proposed changes are correct but will like to get right direction in order to achieve the correct keyboard accessibility.
> add keyboard traversing in file tree

- packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Search/components/Result.tsx
- packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Search/index.tsx
> fix padding & double border on search screen

- standalone-packages/sandpack/src/utils/generate-package-json.ts
Enhancement
If entry key is not defined the log says to add dependencies
Fix logs
Need help on how to test this. But imo this should work.
> fix(sandpack): error logs for invalid sandbox info

- packages/app/src/sandbox/eval/transpilers/babel/worker/utils/error-mock.ts
> Fix Vue in Safari

- packages/homepage/content/docs/2-custom-npm-registry.md
We were still talking about the waitlist, this updates it!
> Update notice for private npm registries

- packages/app/src/sandbox/eval/utils/is-es-module.ts
Allows us to detect minified esmodules.
Fixes #5519
> Improve esmodule detection

- packages/app/src/sandbox/eval/transpilers/babel/convert-esmodule/__snapshots__/index.test.ts.snap
- packages/app/src/sandbox/eval/transpilers/babel/convert-esmodule/index.test.ts
- packages/app/src/sandbox/eval/transpilers/babel/convert-esmodule/index.ts
> Fix export ordering when re-exporting an import

- packages/sandpack-core/src/npm/merge-dependency.ts
This allows a dependency to be merged even if the entries don't match,
with the requirement that the existing dependencies has no entries. That
way we know for sure that no other dependency is calling into it.
> Optimize merging dependencies with no entries

- packages/app/src/app/overmind/namespaces/dashboard/actions.ts
- packages/app/src/app/pages/Dashboard/Components/CommunitySandbox/CommunitySandboxCard.tsx
- packages/app/src/app/pages/Dashboard/Components/CommunitySandbox/index.tsx
- packages/app/src/app/pages/Dashboard/Components/CommunitySandbox/types.ts
Managed likes for community search which plays well with Likes by me
Built on top of https://github.com/codesandbox/codesandbox-client/pull/5548
> Likes for community search

- packages/app/src/sandbox/eval/presets/parcel/index.ts
Adds postcss and sass to parcel preset
Fixes #5516 
No PostCSS, modules cannot be imported in css
Everything works 🎉
1. Step A
2. Step B
3. Step C
> add sass and postcss to parcel preset

- packages/app/package.json
- packages/app/scripts/start.js
- yarn.lock
Bug fix in the dev start script of the main app
iFrame crashes and keeps re-connecting to a websocket that is always redirected to an html file.
Redirects to the actual endpoint instead of frame.html
1. Step A
2. Step B
3. Step C
> Fix the dev server proxy for sandbox iFrame

- .all-contributorsrc
- README.md
- packages/app/src/app/pages/common/Modals/ShareModal/index.tsx
Hey there! 👋
I was just exploring the codebase and decided to contribute by closing one of the issues :)
Thanks for making Codesandbox!
feature
Closes #5650
1. Embed url field works in the same way Editor url does
> Add Embed url to ShareModal

- packages/app/package.json
- packages/common/package.json
- packages/common/src/utils/is-babel-7.ts
- yarn.lock
Fixes https://github.com/codesandbox/sandpack/issues/41
> Fix Svelte 3 HMR and Babel/runtime issues

- packages/app/src/banner.js
> Real time fishy

- packages/app/src/sandbox/compile.ts
- packages/app/src/sandbox/html-writer.ts
Hotfix for vue 3 template strings in html file
> HOTFIX: Vue 3 Webpack template tags

- packages/app/src/sandbox/compile.ts
- packages/app/src/sandbox/html-writer.test.ts
- packages/app/src/sandbox/html-writer.ts
This PR should improve further on the html hydration
Still wanna test this a bit more on staging
> HTML hydrating improvements

- packages/app/src/sandbox/compile.ts
> Trying to fix #5712

- packages/app/src/app/pages/Dashboard/Components/CommunitySandbox/CommunitySandboxCard.tsx
- packages/app/src/app/pages/Dashboard/Content/routes/Discover/index.tsx
- make them always longer than wider
- longer shadow on the stats
- make likes tabular-nums so that updates aren't janky
> Discover: A little polish for featured sandboxes

- packages/app/src/app/overmind/namespaces/profile/actions.ts
Reported via feedback: https://app.frontapp.com/open/msg_iaq37k6
> Profiles bug fix: Delete sandboxes from state without reloading sandboxes

- packages/app/src/app/overmind/namespaces/editor/actions.ts
There is currently a race condition with the like button that if you can click twice or more before the api response comes in the button increments or decrements for the amount of clicks. Caused by slow internet, slow api, very fast clicking, ...
Fixes #5711
> Fix race condition with like button

- packages/components/src/components/Menu/index.tsx
Bug fix
Keyboard navigation does not work. details in #5766
1. Step A
2. Step B
3. Step C
- [N/A] Documentation
closes #5766
> fix(components): context menu keyboard navigation

- packages/app/src/app/pages/Sandbox/Editor/Header/SandboxName/index.tsx
Basically, I just bring out the component from the render, which was causing multiples rerendering that was leading to losing the focus positions.
> refactor(sandboxname): avoid rerender

- packages/homepage/src/pages/jobs/index.js
Removed the visual designer from the jobs page
> Removed the visual designer

- packages/homepage/src/pages/jobs/index.js
- packages/homepage/src/pages/podcasts/codesandbox-podcast.js
- packages/homepage/src/pages/podcasts/index.js
- packages/homepage/src/pages/podcasts/version-one.js
Removed designer + removed no follow for podcasts
> Removed designer + removed no follow 

- packages/sandpack-core/src/npm/__snapshots__/dependencies-to-query.test.ts.snap
- packages/sandpack-core/src/npm/dependencies-to-query.test.ts
- packages/sandpack-core/src/npm/dependencies-to-query.ts
- packages/sandpack-core/src/npm/index.ts
- packages/sandpack-core/src/npm/preloaded/fetch-dependencies.ts
Currently we pass the entire semver version to packager, this PR changes that to remove metadata from the semver.
Fixes #5768
> Remove semver metadata before fetching packager result

- packages/homepage/src/pages/jobs/index.js
Loads the open offers in Recruitee dynamically, so we don't have to manually keep it in sync.
> Fetch the jobs for Recruitee dynamically

- packages/app/package.json
- packages/sandpack-core/src/npm/dynamic/fetch-protocols/index.ts
- packages/sandpack-core/src/npm/dynamic/fetch-protocols/jsdelivr/jsdelivr-gh.test.ts
- packages/sandpack-core/src/npm/dynamic/fetch-protocols/jsdelivr/jsdelivr-gh.ts
- packages/sandpack-core/src/npm/dynamic/fetch-protocols/tar.test.ts
- packages/sandpack-core/src/npm/dynamic/fetch-protocols/tar.ts
- packages/sandpack-core/src/npm/dynamic/resolve-dependency.test.ts
- yarn.lock
Also supports branch names in gh provider, adds tests and improves overall reliability of tar and jsdelivr-gh checks
Closes #5725
> improve tar protocol and jsdelivr-gh to support branch names

- docker/Dockerfile
Adding zsh and vim for when us server bods work on the client
> Add zsh & vim to Dockerfile 😇

- packages/app/src/app/overmind/namespaces/git/actions.ts
- packages/app/src/app/overmind/namespaces/git/utils.ts
- packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/GitHub/CreateRepo.tsx
- packages/components/src/examples/configuration-sidebar.stories.tsx
- packages/homepage/content/articles/team-pro/index.md
- packages/homepage/content/changelog/3-9-0/index.md
- packages/homepage/content/docs/1-x-faqs.md
- packages/homepage/content/docs/2-api.md
- packages/homepage/content/docs/2-importing.md
- packages/homepage/content/podcasts/version-one/1/transcript.md
- packages/homepage/src/pages/enterprise/index.js
- packages/homepage/src/pages/feedback/index.js
- packages/homepage/src/pages/ide/index.js
- packages/homepage/src/pages/knowledge-sharing/index.js
- packages/homepage/src/pages/personal/index.js
- packages/homepage/src/pages/prototyping/index.js
- packages/homepage/src/pages/team/index.js
- standalone-packages/vscode-extensions/out/extensions/ngryman.codesandbox-theme-0.0.1/.vsixmanifest
- standalone-packages/vscode-extensions/out/extensions/ngryman.codesandbox-theme-0.0.1/README.md
> Documentation cleanup

- packages/app/src/app/overmind/effects/deployment/vercel.ts
- packages/app/src/app/overmind/namespaces/deployment/actions.ts
- packages/app/src/app/pages/common/Modals/DeploymentModal/index.tsx
Able to deploy to production and preview from codesandbox.
> Vercel production/preview deployments

- packages/sandpack-core/src/npm/dynamic/fetch-protocols/csb.ts
- packages/sandpack-core/src/npm/dynamic/resolve-dependency.ts
- packages/sandpack-core/src/npm/merge-dependency.ts
Fixes an issue with codesandbox CI deps and probably any other remote deps
Fixes #5823
> Fix issues with remote dependencies and remote transient dependencies

- packages/app/src/app/pages/Dashboard/Content/routes/Discover/index.tsx
> Discover: user selection: none

- packages/app/src/app/overmind/namespaces/editor/actions.ts
- packages/app/src/app/pages/Dashboard/Content/routes/Settings/components/Alert.tsx
- packages/app/src/app/pages/Dashboard/Content/routes/Settings/components/PermissionSettings.tsx
- packages/app/src/app/pages/Pro/pages/WorkspacePlanSelection.tsx
- packages/app/src/app/pages/Sandbox/Editor/Header/Actions.tsx
- packages/app/src/app/pages/Sandbox/Editor/Header/Collaborators/Collaborator.tsx
- packages/app/src/app/pages/common/Modals/NetlifyLogs/index.tsx
| Tested | Where | Event name |
| :-: | :- | :- |
| ⛔️  | Vertical more option (3 dots) | Editor - Click More Menu |  
| ⛔️  | Pricing page link under share sandbox | Editor - Share sandbox Pricing link | 
| ⛔️  | Upgrade Pro under the workspace | Dashboard - Workspace Settings Pro link |
| ⛔️  | Every like icon | Sandbox - Like & Sandbox - Undo Like | 
| ⛔️  | Deployment Modal | Editor - Open Netlify Site |
| ⛔️  | Pro page - switching plan | Pro - Set billing interval |
| ⛔️  | Pro page - change workspace switcher | Pro - Change Workspace |
> feat(tracking): editor more menu event

- packages/app/src/app/overmind/namespaces/editor/actions.ts
- packages/app/src/app/pages/Dashboard/Components/CommunitySandbox/index.tsx
Related to https://github.com/codesandbox/codesandbox-client/pull/5860
> feat(tracking): like in the dashboard

- packages/sandpack-core/src/npm/dynamic/resolve-dependency.ts
Fixes: #5863
See #5863 - Dependency resolution for aliased packages was recently broken.
When a dependency uses a npm alias, the package is resolved.
1. Set up the project locally.
2. Copied and pasted the package.json and index.js files from a broken example (https://codesandbox.io/s/carbon-quickstart-xzkbp?file=/public/index.html:1607-1627) and reproduced the issue.
3. Made my changes to the code
4. Rebuilt the project and confirmed that it now works as expected, i.e. the sandbox works correctly and has no errors regarding trying to fetch the aliased package from any registry.
Hopefully this is ok, feel free to contact me on Github with any questions!
> fix: check for package alias when resolving dependencies

- packages/app/src/app/pages/Dashboard/Components/CommunitySandbox/CommunitySandboxCard.tsx
- packages/app/src/app/pages/Dashboard/Components/CommunitySandbox/index.tsx
- packages/app/src/app/pages/Dashboard/Components/CommunitySandbox/types.ts
- packages/app/src/app/pages/Dashboard/Content/routes/Discover/index.tsx
> Discover: Polish based on feedback

- packages/app/src/sandbox/eval/transpilers/sass/worker/resolver.js
- packages/app/src/sandbox/eval/transpilers/sass/worker/sass-worker.js
This PR includes some small tweaks to the sass transformer
> Small improvements to sass transformer

- packages/app/src/app/pages/Dashboard/Components/Selection/ContextMenu.tsx
> Dashboard/ContextMenu: fix undefined check.

- packages/app/src/sandbox/eval/index.ts
- packages/app/src/sandbox/eval/transpilers/babel/ast/convert-esmodule.test.ts
- packages/app/src/sandbox/eval/transpilers/babel/ast/convert-esmodule.ts
- packages/app/src/sandbox/eval/transpilers/babel/index.ts
- packages/common/src/templates/esmodule-react.ts
- packages/common/src/templates/index.ts
- packages/sandpack-core/src/preset/preset.ts
Steps done:
1. Template added to `common`
2. Template -> preset conversion in `Sandpack`
3. Add template to template list on `server`
---
Todo:
1. Manually update the template of a sandbox
> Add an experimental esm template for React

- packages/app/package.json
- packages/homepage/package.json
- yarn.lock
This is an attempt to fix the "Failed to fetch error" reported [here](https://sentry.io/organizations/codesandbox/discover/results/?display=previous&field=title&field=release&field=environment&field=user.display&field=timestamp&name=TypeError%3A+Failed+to+fetch&project=2071895&query=issue.id%3A1483083484&sort=-timestamp&statsPeriod=90d&widths=-1&widths=-1&widths=-1&widths=-1&widths=-1) and fixed [here](https://github.com/codesandbox/ab-testing-framework/commit/8b142ed075801096a014ddad9f0f875c75fed073)
> fix(ab-framework): handle fetch error

- packages/app/src/app/pages/Dashboard/Content/routes/Settings/Invite.tsx
- packages/app/src/app/pages/Dashboard/Header/index.tsx
Add new "Invite members" button on the dashboard page only for valid workspaces.
@tromika I added the following event in the button: `Dashboard - Invite members`
> feat(dashboard): add invite members link

- packages/app/src/app/pages/Dashboard/Content/routes/Settings/Invite.tsx
- packages/app/src/app/pages/Dashboard/Header/index.tsx
Reverts codesandbox/codesandbox-client#5882
> Revert "feat(dashboard): add invite members link"

- packages/app/src/app/pages/Dashboard/Sidebar/index.tsx
> Add badge component and prop to sidebar menu

- packages/common/src/utils/dependencies.ts
We used to use jsdelivr for resolving a tag to an absolute version, but
it turns out that jsdelivr caches the result. This is unintended
behavior, because when a tag updates people will see different results
based on their browser cache. This PR makes us default to unpkg instead,
which has a better caching mechanism.
> Fix tag fetching

- packages/app/config/webpack.prod.js
- packages/sandpack-core/src/npm/dynamic/fetch-protocols/npm-registry.ts
Testing this out because for some reason sandbox api responses are cached in the service worker?!
> Remove service worker rule

- packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Explorer/Files/DirectoryEntry/DirectoryChildren/ModuleEntry.tsx
- packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Explorer/Files/DirectoryEntry/Entry/index.tsx
Add `copy esmodule url` to context menu
> Add copy esmodule url to context menu

- packages/app/config/build.js
- packages/app/config/webpack.prod.js
- packages/app/scripts/copy-assets.js
- packages/app/src/app/index.html
- packages/app/src/app/overmind/effects/vscode/constants.ts
- packages/app/src/app/overmind/effects/vscode/initializers.ts
- packages/app/src/app/overmind/effects/vscode/metadata.ts
This disables the auto save, in order to fix bugs around it, as there are a lot of users making complaints that their changes are suddenly gone.
> fix(editor): disable auto save

- packages/app/src/sandbox/eval/transpilers/babel/ast/__snapshots__/convert-esmodule.test.ts.snap
- packages/app/src/sandbox/eval/transpilers/babel/ast/convert-esmodule.ts
This fixes an issue where invalid variable names can get generated from filepaths in the convert-esmodule script
> exclude invalid characters from variables

- packages/homepage/src/screens/home/hero/Content.js
Related to GRO-1
Change the middle CTA wording on the hp.
| A | B |
| - | - |
| ![image](https://user-images.githubusercontent.com/540472/127684919-b0434fb6-10fa-4897-b692-0e8c1ab591ab.png) | ![image](https://user-images.githubusercontent.com/540472/127684888-fdef7a91-a2b0-4545-8c04-65706eebafaa.png) |
> feat(homepage): wording experiment

- packages/homepage/src/components/Footer/index.js
3 Jobs listed, modified the code accordingly. 
https://github.com/codesandbox/codesandbox-client/issues/6011
1. Step A
2. Step B
3. Step C
> Fixes #6011

- packages/sandpack-core/src/manager.ts
Fixes a bug with esmodule sandboxes where asset paths aren't rewritten to the resolved url
Redirects don't influence module path
Redirects change the module path
> fix: Rewrite paths if esmodule url is a redirect

- packages/app/src/app/overmind/actions.ts
- packages/app/src/app/overmind/internalActions.ts
- packages/app/src/app/overmind/state.ts
- packages/app/src/app/pages/Sandbox/Editor/Header/Actions.tsx
- packages/app/src/app/pages/SignIn/Modal.tsx
**Missing production experiment**
> Anon users get signin modal at fork/create sandbox

- packages/app/src/sandbox/eval/transpilers/vue/v2/loader.ts
- packages/app/src/sandbox/eval/transpilers/vue/v2/style-loader/loader.ts
Adds more typings for the vue loaders
> chore: Type some more vue loaders

- packages/app/src/sandbox/eval/transpilers/svgr/transpiler.js
Added the default config of svgr, kinda broke the logic with this
> add default config for svgr back

- packages/homepage/src/components/Navigation/index.js
**Missing production experiment**
> feat(homepage): hide link headers

- packages/common/src/templates/quasar.ts
Update on Quasar's docs website URL
Has old URL
Has correct URL
1. Step A
2. Step B
3. Step C
> fix: update url in quasar.ts

- packages/common/src/utils/dependencies.test.ts
- packages/common/src/utils/dependencies.ts
If a version is absolute we don't need to do an additional resolve, this PR returns early in case of absolute versions.
> performance: Don't fetch version for absolute versions

- packages/app/src/sandbox/eval/presets/create-react-app/v1.ts
- packages/app/src/sandbox/eval/transpilers/babel/index.ts
- packages/app/src/sandbox/eval/transpilers/babel/worker/babel-worker.js
- packages/app/src/sandbox/eval/transpilers/babel/worker/dynamic-download.ts
- packages/app/src/sandbox/eval/transpilers/babel/worker/evaluate.js
- packages/app/src/sandbox/eval/transpilers/babel/worker/utils/resolvePatch.ts
- packages/sandpack-core/src/manager.ts
- packages/sandpack-core/src/resolver/fixture/node_modules/simple/package.json
- packages/sandpack-core/src/resolver/fixture/node_modules/solid-js/package.json
- packages/sandpack-core/src/resolver/resolver.test.ts
- packages/sandpack-core/src/resolver/resolver.ts
- Add cjs to react preset v1
- Fix some more issues in babel plugin/preset installer
- Support more complex exports fields
Closes #6288
> fix: Resolver bugfixes

- packages/app/src/app/overmind/namespaces/files/actions.ts
- packages/app/src/app/overmind/namespaces/server/actions.ts
- packages/app/src/app/pages/Sandbox/Editor/Content/Preview/index.tsx
- packages/common/src/utils/url-generator.ts
This just breaks down between forks.
> Don't hardcode url in preview for sse

- packages/sandpack-core/src/resolver/fixture/tsconfig.json
- packages/sandpack-core/src/resolver/utils/tsconfig.ts
Went a bit too fast and forgot paths and baseUrl is part of compilerOptions...
> fix: tsconfig format in resolver

- packages/common/src/templates/icons.ts
we forgot one more thing - load remix icon when we detect `remix` template!
> load right icon for remix template

- packages/homepage/src/screens/home/anywhere/index.js
Link update. 
Currently links to the general blog page
Now links to the correct article for users to learn about play.js
1. Step A
2. Step B
3. Step C
> hotfix: Update play.js link on homepage

- packages/app/src/sandbox/eval/index.ts
> re-enable experimental esmodule resolution

- packages/app/src/sandbox/eval/transpilers/postcss/index.ts
Need to test more if this breaks sandboxes.
> Don't download postcss if it's not needed

- packages/app/src/sandbox/eval/presets/angular-cli/index.ts
Use Babel 7 for angular
Fixes #6334
> fix: Use Babel 7 for angular cli template

- packages/sandpack-core/src/npm/dynamic/fetch-npm-module.ts
Only create new combined metas for new metas coming in. Not the most beautiful code though... I have to run!
> Improve performance of fetching metas

- packages/homepage/src/components/Footer/index.js
Add Sandpack to the footer on the homepage.
> add sandpack to footer on the hp

- packages/app/src/sandbox/eval/tests/jest-lite.ts
- packages/sandpack-core/src/runner/eval.ts
Fixes #6257
Verified that the linked sandbox works again!
> Fix test globals

- packages/app/src/app/pages/VSCodeAuth/Prompt/index.tsx
> Tweak sign-in

- packages/homepage/src/pages/company/index.js
Updated presskit with new logo
> new presskit

- packages/app/src/app/overmind/effects/vscode/extensionHostWorker/common/fs.ts
> upgrade typescript in editor to 4.5

- packages/homepage/src/config/hiring.js
Update the hiring number from 2 to 4
> Update hiring number

- packages/app/src/app/pages/Dashboard/Content/routes/Settings/Invite.tsx
- packages/app/src/app/pages/Dashboard/Content/routes/Settings/TeamSettings/WorkspaceSettings.tsx
Team Pro permissions:
- Admin can invite users as Admin, Editor, Viewer permissions - Editor by default
- Editor users can invite users as Viewer permissions - Viewer by default
- Viewer users can't invite any other user to teams.
> fix: set level team permissions

- packages/app/src/sandbox/eval/presets/create-react-app/index.ts
- packages/app/src/sandbox/eval/presets/create-react-app/utils.ts
- packages/app/src/sandbox/eval/transpilers/react-refresh/refresh-transpiler.ts
Cleanup/simplify the react refresh logic and remove old `cleanUsingUnmount` logic
> React refresh cleanup & improvements

- packages/app/src/sandbox/eval/transpilers/sass/worker/resolver.ts
- packages/common/src/utils/path.ts
fix: issue with extensions of sass
Closes CSB-4001
> fix: issue with extensions of sass

- packages/sandpack-core/src/manager.ts
> chore: Tweak verify tree

- packages/app/src/sandbox/eval/index.ts
- packages/app/src/sandbox/eval/presets/solid/index.ts
- packages/common/src/templates/configuration/babelrc/index.ts
- packages/common/src/templates/icons.ts
- packages/common/src/templates/index.ts
- packages/common/src/templates/solid.ts
- packages/template-icons/src/SolidIcon.tsx
- packages/template-icons/src/index.ts
> feat: add solid preset

- packages/app/src/sandbox/eval/presets/solid/index.ts
- packages/common/src/templates/configuration/babelrc/index.ts
- packages/common/src/templates/configuration/tsconfig/index.ts
Fixes some issues with the solid template
> fix: Some issues with solid template

- packages/app/integration-tests/tests/sandboxes.test.js
- Increase timeout for integration tests
- Make it easier to change timeouts (use a simple const)
> Integration test tweaks and increase timeout

- package.json
- packages/app/package.json
- packages/app/src/app/overmind/effects/live/index.ts
- packages/app/src/app/overmind/effects/vscode/Linter.ts
- packages/app/src/app/overmind/effects/vscode/extensionHostWorker/common/fs.ts
- packages/app/src/app/overmind/effects/vscode/extensionHostWorker/common/global.ts
- packages/app/src/app/pages/Dashboard/Components/Folder/CreateFolder.tsx
- packages/app/src/embed/components/Content/Monaco/mode.ts
- packages/app/src/sandbox/codesandbox-overlay/index.ts
- packages/app/src/sandbox/eval/tests/jest-lite.ts
- packages/codesandbox-api/package.json
- packages/common/package.json
- packages/components/package.json
- packages/executors/package.json
- packages/node-services/package.json
- packages/react-embed/package.json
- yarn.lock
Reverts codesandbox/codesandbox-client#6672
> Revert "fix: ESLint typescript Template Literal Types"

- package.json
- packages/app/package.json
- packages/app/src/app/overmind/effects/live/index.ts
- packages/app/src/app/overmind/effects/vscode/Linter.ts
- packages/app/src/app/overmind/effects/vscode/extensionHostWorker/common/fs.ts
- packages/app/src/app/overmind/effects/vscode/extensionHostWorker/common/global.ts
- packages/app/src/app/pages/Dashboard/Components/Folder/CreateFolder.tsx
- packages/app/src/embed/components/Content/Monaco/mode.ts
- packages/app/src/sandbox/codesandbox-overlay/index.ts
- packages/app/src/sandbox/eval/tests/jest-lite.ts
- packages/codesandbox-api/package.json
- packages/common/package.json
- packages/components/package.json
- packages/executors/package.json
- packages/node-services/package.json
- packages/react-embed/package.json
- yarn.lock
Second attempt at #6672 
Still have to figure out what actually went wrong so please don't merge this yet
Closes https://github.com/codesandbox/codesandbox-client/issues/6630
> fix: ESLint typescript Template Literal Types

- packages/app/src/app/overmind/effects/vscode/SandboxFsSync/index.ts
Resolve version before fetching typings
Closes #6701
> fix: Resolve version before fetching typings

- packages/app/src/app/pages/Sandbox/Editor/FixedSignInBanner.tsx
- packages/app/src/app/pages/Sandbox/Editor/Header/Collaborators/Collaborators.tsx
- packages/app/src/app/pages/Sandbox/OnBoarding/index.tsx
- packages/homepage/src/components/Navigation/index.js
> Remove experiments (A/B tests)

- .all-contributorsrc
- README.md
- packages/homepage/content/docs/1-x-faqs.md
Fix FAQ Docs: Update default Node version in container sandbox
Container sandboxes run Node v10.20.1 (LTS) by default.
Container sandboxes run Node v14.18.1 (LTS) by default.
1. yarn test
2. yarn lint
> docs: Update default Node version in container sandbox

- packages/app/src/app/overmind/namespaces/git/actions.ts
- packages/common/src/utils/url-generator.ts
Closes [CSB-5126](https://linear.app/codesandbox/issue/CSB-5091/implement-graphql-code-generator-on-web-projects)
> feat(git export): redirect to projects

- packages/sandpack-core/src/npm/dynamic/fetch-protocols/npm-registry.ts
> feat(sandpack): allow consume proxy to retrieve private packages

- packages/homepage/src/pages/pricing/_plans.js
> fix(pricing): npm private package only for teams

- packages/homepage/src/pages/pricing/_plans.js
> fix(pricing): table header background

- packages/common/src/utils/analytics/sentry.ts
> fix(sentry): ignore editor errors

- packages/sandpack-core/src/npm/dynamic/fetch-protocols/npm-registry.ts
> fix(sandpack): do not set default value for credentials

- packages/app/src/app/overmind/namespaces/git/actions.ts
> chore: learn about sandbox imports

- packages/app/src/app/pages/Dashboard/Content/routes/Home/index.tsx
- packages/app/src/app/pages/Dashboard/Sidebar/index.tsx
- yarn.lock
With adding params we would like to measure the number of redirects from the sidebar and the banner separately.
1. Step A
2. Step B
3. Step C
> chore(dashboard): add params to track redirect source to Projects

- packages/app/src/app/components/CreateNewSandbox/CreateSandbox/Import/Import.tsx
- packages/common/src/utils/url-generator.ts
Try to redirect users who would like to import a GH repo to Projects while keeping the option to use repository sandboxes.
1. Step A
2. Step B
3. Step C
> Add Projects redirect to the Import Projects screen

- packages/app/src/app/components/CreateNewSandbox/CreateSandbox/Import/Import.tsx
> chore(dashboard): highlight VSCode support on the import projects screen

- packages/app/src/app/overmind/actions.ts
- packages/app/src/app/overmind/effects/index.ts
- packages/app/src/app/overmind/effects/moduleRecover.ts
- packages/app/src/app/overmind/namespaces/editor/actions.ts
- packages/app/src/app/overmind/namespaces/editor/internalActions.ts
- packages/app/src/app/overmind/namespaces/editor/state.ts
- packages/app/src/app/overmind/namespaces/files/actions.ts
- packages/app/src/app/overmind/namespaces/files/internalActions.ts
- packages/app/src/app/overmind/namespaces/live/internalActions.ts
- packages/app/src/app/pages/common/Modals/RecoverFilesModal/index.tsx
- packages/app/src/app/pages/common/Modals/index.tsx
Reverts #5903 (Link [here](https://github.com/codesandbox/codesandbox-client/pull/5903/) since it doesnt want to autolink??)
This adds back the non-live collaboration code recovery logic that was removed last year.
Not sure what the best way to test this is?
1. Step A
2. Step B
3. Step C
> CSB-5451 -- re-add module recovery logic

- packages/app/src/app/pages/Dashboard/Components/Folder/FolderCard.tsx
- packages/app/src/app/pages/Dashboard/Components/Sandbox/NewSandbox.tsx
- packages/app/src/app/pages/Dashboard/Components/Sandbox/SandboxCard.tsx
- Folder Card
- Sandbox Card
- New Sandbox Card
Color backgrounds will be applied in another PR
> feat(new-design): Card Layout

- packages/app/src/app/pages/Dashboard/Components/CommunitySandbox/CommunitySandboxCard.tsx
- packages/app/src/app/pages/Dashboard/Components/EmptyScreen/index.tsx
- packages/app/src/app/pages/Dashboard/Components/Folder/FolderCard.tsx
- packages/app/src/app/pages/Dashboard/Components/Repo/ImportRepo.tsx
- packages/app/src/app/pages/Dashboard/Components/Repo/RepoCard.tsx
- packages/app/src/app/pages/Dashboard/Components/Sandbox/NewMasterSandbox.tsx
- packages/app/src/app/pages/Dashboard/Components/Sandbox/NewSandbox.tsx
- packages/app/src/app/pages/Dashboard/Components/Sandbox/SandboxCard.tsx
- packages/components/src/themes/codesandbox-black.ts
- Hover
- Repo Cards
- Alignment adjustments 
- Empty states
> feat(new-design): Cards iteration 2

- packages/app/src/app/pages/Dashboard/Components/VariableGrid/index.tsx
> feat(new-style): Change grid gutter

- packages/components/src/components/Switch/index.tsx
- packages/components/src/themes/codesandbox-black.ts
- packages/components/src/utils/polyfill-theme.ts
> feat(new-style): Toggle Color

- packages/app/src/app/pages/Dashboard/Header/index.tsx
- packages/app/src/app/pages/Profile/Header.tsx
- packages/app/src/app/pages/Sandbox/Editor/Header/Actions.tsx
- packages/components/src/themes/codesandbox-black.ts
**Dashboard**
- Change logo size
**Editor**
- Adjust 'Create New' button
**Profile page**
- Change logo size
- Change background color
- Change search input width
- Adjust 'Create New' button
> Facelift: Header style fixes

- packages/app/src/app/components/CreateNewSandbox/CreateSandbox/CreateSandbox.tsx
- packages/app/src/app/components/CreateNewSandbox/CreateSandbox/FromTemplate.tsx
- packages/app/src/app/components/CreateNewSandbox/CreateSandbox/elements.ts
Closes XTD-62
Closes XTD-63
Mostly functional, little styles.
> feat(from-template): Add fields to create screen

- packages/app/src/app/components/SandboxList/DeleteSandboxButton/index.tsx
- packages/app/src/app/pages/Dashboard/Components/Branch/BranchCard.tsx
- packages/app/src/app/pages/Dashboard/Components/Branch/BranchListItem.tsx
- packages/app/src/app/pages/Dashboard/Components/Branch/index.tsx
- packages/app/src/app/pages/Dashboard/Components/Branch/types.ts
- packages/app/src/app/pages/Dashboard/Components/Folder/FolderCard.tsx
- packages/app/src/app/pages/Dashboard/Components/Repo/ImportRepo.tsx
- packages/app/src/app/pages/Dashboard/Components/Repo/RepoCard.tsx
- packages/app/src/app/pages/Dashboard/Components/Repository/index.tsx
- packages/app/src/app/pages/Dashboard/Components/Sandbox/NewMasterSandbox.tsx
- packages/app/src/app/pages/Dashboard/Components/Sandbox/NewSandbox.tsx
- packages/app/src/app/pages/Dashboard/Components/Sandbox/SandboxCard.tsx
- packages/app/src/app/pages/Dashboard/Components/Sandbox/SandboxListItem.tsx
- packages/app/src/app/pages/Dashboard/Components/Sandbox/index.tsx
- packages/app/src/app/pages/Dashboard/Components/Sandbox/types.ts
- packages/app/src/app/pages/Dashboard/Components/Selection/ContextMenu.tsx
- packages/app/src/app/pages/Dashboard/Components/Selection/ContextMenus/BranchMenu.tsx
- packages/app/src/app/pages/Dashboard/Components/Selection/ContextMenus/FolderMenu.tsx
- packages/app/src/app/pages/Dashboard/Components/Selection/ContextMenus/SandboxMenu.tsx
- packages/app/src/app/pages/Dashboard/Components/Selection/DragPreview.tsx
- packages/app/src/app/pages/Dashboard/Components/Selection/index.tsx
- packages/app/src/app/pages/Dashboard/Content/routes/Recent/index.tsx
- packages/app/src/app/pages/Dashboard/Sidebar/ContextMenu.tsx
- packages/app/src/app/pages/Dashboard/Sidebar/index.tsx
- packages/app/src/app/pages/Profile/ContextMenu.tsx
- packages/app/src/app/pages/common/Modals/DeleteProfileSandboxModal/index.tsx
- packages/app/src/app/pages/common/Modals/DeleteSandboxModal/index.tsx
- packages/app/src/app/pages/common/Modals/MoveSandboxFolderModal/DirectoryPicker/SandboxesItem/FolderEntry/index.tsx
Doesn't quite close the ticket yet, because originally I wanted to implement the context menu. However, that proved to be more complicated then I thought, so I'm opening a new PR later for that.
In this PR I:
* Aligned all cards with paddings and text alignments
* Updated the default/hover/focus/selection style
* Increased the speed of the interactions (hover, focus)
also fixed XTD-164
> facelift: dashboard cards interaction

- packages/app/src/app/pages/Dashboard/Components/Repo/RepoCard.tsx
- packages/app/src/app/pages/Dashboard/Components/Repo/RepoListItem.tsx
- packages/app/src/app/pages/Dashboard/Components/Repository/index.tsx
Closes XTD-184 and XTD-186
- Synced sandbox card and list view: Change icon and add 'synced' tag
- Repository card and list view: Change icon and adjust paddings
> Facelift: Card reviews

- packages/app/src/app/components/TeamAvatar/TeamAvatar.tsx
- packages/app/src/app/components/WorkspaceSelect/WorkspaceSelect.tsx
- packages/app/src/app/pages/Dashboard/Components/Selection/index.tsx
- packages/app/src/app/pages/Dashboard/Content/routes/Settings/index.tsx
- packages/app/src/app/pages/Dashboard/Header/index.tsx
- packages/app/src/app/pages/Dashboard/Sidebar/index.tsx
- packages/app/src/app/pages/Dashboard/index.tsx
- packages/components/src/components/List/index.tsx
General type and padding adjustment of sidebar and header itens
(before)
(after)
> Facelift: Header and Sidebar UI review

- packages/app/src/app/pages/Dashboard/Components/VariableGrid/index.tsx
- packages/app/src/app/pages/Dashboard/Content/routes/SyncedSandboxes/index.tsx
- packages/app/src/app/pages/Dashboard/types.ts
> chore: remove import repo from synced sandboxes

- packages/app/src/app/components/CreateNewSandbox/CreateSandbox/Import/Import.tsx
- packages/app/src/app/components/CreateNewSandbox/CreateSandbox/Import/useImportAndRedirect.tsx
- packages/app/src/app/components/CreateNewSandbox/CreateSandbox/utils/api.ts
If the user has write access to the repository, import and open the editor. Else, continue to step 2.
> feat(dashboard): import and redirect if user has write access

- packages/app/package.json
- packages/app/src/app/components/CreateNewSandbox/CreateSandbox/CreateSandbox.tsx
- packages/app/src/app/components/CreateNewSandbox/CreateSandbox/Import/FromRepo.tsx
- packages/app/src/app/components/CreateNewSandbox/CreateSandbox/Import/useForkAndRedirect.ts
- packages/app/src/app/components/CreateNewSandbox/CreateSandbox/Import/useGithubOrganizations.ts
- packages/app/src/app/components/CreateNewSandbox/CreateSandbox/Import/useValidateRepoDestination.ts
- packages/app/src/app/components/CreateNewSandbox/CreateSandbox/Import/utils.ts
- packages/app/src/app/components/CreateNewSandbox/CreateSandbox/utils/api.ts
- packages/app/src/app/components/CreateNewSandbox/queries.ts
- packages/app/src/app/graphql/types.ts
- yarn.lock
- Adds validation to the destination: valid owner (organization) and repo (name) combination.
- Fetches the user's authorized GitHub organizations.
- Attempts to match the closest org to the current team name.
- Fork, import and redirect users to the editor.
> feat(dashboard): fork repositories from github

- packages/app/src/app/overmind/namespaces/dashboard/actions.ts
- packages/app/src/app/overmind/namespaces/dashboard/utils.ts
Fixes XTD-244, where the two subsequent calls where ordering the repos differently
> fix: sort repos by name

- packages/app/src/app/components/CreateNewSandbox/CreateSandbox/CreateSandbox.tsx
- packages/app/src/app/components/CreateNewSandbox/CreateSandbox/FromTemplate.tsx
- packages/app/src/app/components/CreateNewSandbox/CreateSandbox/Import/Import.tsx
- packages/app/src/app/components/CreateNewSandbox/CreateSandbox/TemplateCard.tsx
- packages/app/src/app/components/CreateNewSandbox/CreateSandbox/elements.ts
> Style adjusments to New modal

- packages/app/src/app/pages/Dashboard/Components/Sandbox/index.tsx
Use an `anchor` tag instead of a `Link` from `react-router` to render the v2 sandboxes on the recent page. Since the editor is another application, we need a full refresh on the page.
Loom for evidence: https://www.loom.com/share/22f05b23b47845e49b1c6bbf147dbf88
> fix(dashboard): cloud sandboxes redirects on recent page

- packages/app/src/app/overmind/effects/api/apiFactory.ts
- packages/app/src/app/overmind/effects/api/index.ts
- packages/app/src/app/overmind/namespaces/dashboard/actions.ts
- packages/app/src/app/overmind/namespaces/dashboard/state.ts
- packages/app/src/app/pages/Dashboard/Components/Branch/BranchCard.tsx
- packages/app/src/app/pages/Dashboard/Components/Branch/BranchListItem.tsx
- packages/app/src/app/pages/Dashboard/Components/Branch/index.tsx
- packages/app/src/app/pages/Dashboard/Components/Branch/types.ts
- packages/app/src/app/pages/Dashboard/Components/Repository/RepositoryCard.tsx
- packages/app/src/app/pages/Dashboard/Components/Repository/RepositoryListItem.tsx
- packages/app/src/app/pages/Dashboard/Components/Repository/index.tsx
- packages/app/src/app/pages/Dashboard/Components/Repository/types.ts
- packages/app/src/app/pages/Dashboard/Components/Selection/ContextMenu.tsx
- packages/app/src/app/pages/Dashboard/Components/Selection/ContextMenus/BranchMenu.tsx
- packages/app/src/app/pages/Dashboard/Components/Selection/ContextMenus/RepositoryMenu.tsx
- packages/components/src/components/Menu/index.tsx
Allows users to remove branches and repositories from CodeSandbox through the dashboard interface.
|Repository|Branch|
|:-:|:-:|
|![Screen Shot 2022-10-10 at 16 36 36](https://user-images.githubusercontent.com/24959348/194940202-bb868aa4-9b2e-42d7-900a-d869fec83cb9.png)|![Screen Shot 2022-10-10 at 16 36 56](https://user-images.githubusercontent.com/24959348/194940251-3e17db13-64aa-452a-b67e-b90958174c2f.png)|
Repositories are unlinked from the current team.
Branches are removed from the repository but not deleted on GitHub.
Demo: https://www.loom.com/share/51ec5eb3db2d4fcd9458940e51418a7f
> feat(dashboard): remove from codesandbox

- packages/app/src/app/pages/common/Modals/NewTeamModal/TeamInfo.tsx
- packages/app/src/app/pages/common/Modals/NewTeamModal/TeamMembers.tsx
- packages/app/src/app/pages/common/Modals/NewTeamModal/TeamSubscription.tsx
- packages/app/src/app/pages/common/Modals/NewTeamModal/index.tsx
- packages/app/src/app/pages/common/Modals/index.tsx
Placeholder steps so we can handle: create team -> add members -> subscription.
https://www.loom.com/share/cfc6305db3924f479c23523267ef9df7
> feat(dashboard): team creation steps

- packages/homepage/content/articles/building-accessible-apps-with-speed-using-chakra-ui/index.md
Update a few links on the blog post for improved accessibility.
1. Step A
2. Step B
3. Step C
> Fix some links on the Chakra UI blog post

- packages/app/src/app/hooks/useCreateCheckout.ts
- packages/app/src/app/pages/common/Modals/NewTeamModal/TeamSubscription.tsx
- packages/app/src/app/pages/common/Modals/NewTeamModal/index.tsx
Redirect to the dashboard home page for the created team on the following occasions:
- Dismissing the modal after the first step.
- Successful sign-up on Stripe.
- Cancellation of the checkout.
> fix(trial): redirect to the dashboard home page for the created team

- packages/app/src/app/graphql/types.ts
- packages/app/src/app/overmind/effects/gql/dashboard/fragments.ts
- packages/app/src/app/overmind/namespaces/dashboard/actions.ts
- packages/app/src/app/pages/Dashboard/Components/Branch/index.tsx
- packages/app/src/app/pages/Dashboard/Components/Selection/ContextMenu.tsx
- packages/app/src/app/pages/Dashboard/Components/Selection/ContextMenus/BranchMenu.tsx
- packages/app/src/app/pages/Dashboard/Components/Selection/ContextMenus/RepositoryMenu.tsx
- Rename 'Remove from CodeSandbox' to 'Remove branch from CodeSandbox'
- Hide this option if the branch is the default
- Update the action to handle the state when removing contribution branches
- Add 'Remove repository from CodeSandbox'
- Hide this option if the branch is a contribution branch
- Update the action to handle the state when removing the repository from the recent page
- Rename 'Remove from CodeSandbox' to 'Remove repository from CodeSandbox'
> feat(dashboard): branch and repository removal

- packages/app/src/app/pages/Dashboard/Content/routes/Settings/TeamSettings/ManageSubscription/index.tsx
Handles subscription status `TRIALING`.
1. Open `dashboard/settings` with a team in trial mode.
2. See the correct card if you are the admin of said team.
> fix(dashboard): subscription management on user/team settings

- packages/app/src/app/pages/SignIn/Onboarding.tsx
Update usage options during the sign-up:
> chore(sign-up): update usage options

- packages/app/src/app/components/WorkspaceSelect/WorkspaceSelect.tsx
- packages/app/src/app/overmind/actions.ts
- packages/app/src/app/pages/Dashboard/Components/TemplatesRow/TemplatesRow.tsx
- packages/app/src/app/pages/common/Modals/NewTeamModal/TeamInfo.tsx
- packages/app/src/app/pages/common/Modals/NewTeamModal/TeamMembers.tsx
- packages/app/src/app/pages/common/Modals/NewTeamModal/TeamSubscription.tsx
- packages/app/src/app/pages/common/Modals/NewTeamModal/index.tsx
Adds analytics according to the [list](https://www.notion.so/codesandbox-app/Trials-for-new-sign-ups-6238a25dfd244124bc38cfb420dc1189#5f75e569e18441de8920dfe497b03cf7) of what we want to track.
> feat(trial): tracking

- packages/homepage/src/pages/pricing/_intro.js
- packages/homepage/src/pages/pricing/_plans.js
Small update to the wording of editor seats on the Pricing page.
1. Step A
2. Step B
3. Step C
> Update wording of editor seats

- packages/app/src/app/pages/SignIn/Onboarding.tsx
Event tracking for the account creation and onboarding steps
no tracking for account creation
tracking for each of the steps in the form - I'm interested to know if there is a drop off rate for user filling out the four fields
none
> adds tracking to onboarding

- packages/app/src/app/index.js
> Allow for CMD+W or CTRL+W closing when in PWA mode

- packages/app/src/app/pages/Dashboard/Components/CommunitySandbox/index.tsx
Bug Fix 
Clicking on the More actions button redirects to the editor page (Not sure if this was intended behavior though)
Prevent redirection
1. Tested locally with Discover page and home page
> fix(discover): stop event propagation in context menu for sandbox card

- packages/app/src/app/pages/Dashboard/Components/Folder/index.tsx
- packages/app/src/app/pages/Dashboard/Components/Sandbox/index.tsx
- packages/app/src/app/pages/Dashboard/Components/Selection/index.tsx
Add tracking to gain insights in how often drag and drop is used.
> chore(dashboard): Track drag start

- packages/app/src/app/utils/dateTime.test.ts
- packages/app/src/app/utils/dateTime.ts
Silly mistake earlier, aided by not having strict types :( 
Closes #7119
> fix: proper date constructor

- packages/app/src/app/components/StripeMessages/PaymentPending.tsx
- packages/app/src/app/components/StripeMessages/index.tsx
- packages/app/src/app/hooks/useCreateCustomerPortal.ts
- packages/app/src/app/pages/Dashboard/Content/routes/Settings/TeamSettings/ManageSubscription/stripe.tsx
- packages/app/src/app/pages/Dashboard/Content/routes/Settings/UserSettings/ManageSubscription/Stripe.tsx
- packages/app/src/app/pages/Dashboard/Sidebar/BottomMessages/TrialExpiring.tsx
- packages/app/src/app/pages/Dashboard/index.tsx
- packages/app/src/app/pages/Pro/Upgrade.tsx
- packages/app/src/app/pages/Sandbox/Editor/index.tsx
- packages/components/src/components/MessageStripe/MessageStripe.tsx
- yarn.lock
- Updates the customer portal hook args to accept return paths.
- Adds the stripe message to the pages if the subscription status is unpaid.
🚨 The screenshots below were taken with the conditional disabled.
|Editor page|
|:-:|
|![7sil2k-3000 preview csb app_s_broken-fast-9yls2p](https://user-images.githubusercontent.com/24959348/201243282-b005b918-70b9-49d9-8ae6-af8466bc286f.png)|
|Dashboard page|
|:-:|
|![7sil2k-3000 preview csb app_dashboard_repositories_workspace=b5123bcc-da66-446f-88e2-5b89c9c37d27](https://user-images.githubusercontent.com/24959348/201243332-e9f04c73-0308-48b6-a0c8-9e7bddc1cc24.png)|
N/A.
(I do miss Leva so much)
> feat(subscriptions): unpaid message 

- packages/app/src/app/pages/Dashboard/Components/Selection/index.tsx
Add tracking to the drop after dragging. Added parameter to see if the dropped item or items are dropped in the same place.
> chore(dashboard): Track drop

- packages/app/src/app/pages/Dashboard/Content/routes/Repositories/index.tsx
- packages/app/src/app/pages/Dashboard/Content/routes/Sandboxes/index.tsx
- packages/app/src/app/pages/Dashboard/Content/routes/Settings/TeamSettings/ManageSubscription/upgrade.tsx
- packages/app/src/app/pages/Dashboard/Content/routes/Settings/TeamSettings/RegistrySettings.tsx
- packages/app/src/app/pages/Dashboard/Content/routes/Settings/components/Alert.tsx
- packages/app/src/app/pages/Dashboard/Content/routes/Settings/components/PermissionSettings.tsx
Redirects users directly to the stripe checkout in the following:
- Repositories page
- Sandboxes page
- Settings page:
- General
- Registry
- Permissions
> feat(subscriptions): reduce steps to checkout

- packages/app/src/app/pages/Dashboard/Components/Selection/ContextMenus/SandboxMenu.tsx
Trying to centralize the subscription checks.
> chore(dashboard): use hasActiveSubscription from subscription hook

- packages/app/src/app/graphql/types.ts
- packages/app/src/app/overmind/effects/gql/dashboard/fragments.ts
- packages/app/src/app/pages/Dashboard/Sidebar/BottomMessages/TrialExpiring.tsx
- packages/app/src/app/pages/Dashboard/Sidebar/index.tsx
Reverts codesandbox/codesandbox-client#7143
> Revert "fix(end-of-trial): show different message if trial has been canceled"

- packages/app/src/app/graphql/types.ts
- packages/app/src/app/overmind/effects/gql/dashboard/fragments.ts
- packages/app/src/app/pages/Dashboard/Sidebar/BottomMessages/TrialExpiring.tsx
- packages/app/src/app/pages/Dashboard/Sidebar/index.tsx
Was merged once in master, should be merged in 287 first
> feat(end-of-trial): show different message when trial expires

- packages/app/src/app/components/CreateSandbox/TemplateCard.tsx
As title says, anonymous users cannot fork, so it's better to see the running template.
Haven't tested this yet, but I trust the code because of its simplicity.
> feat: as anonymous user, open template instead of trying fork

- packages/app/src/app/pages/Dashboard/Components/UpgradeBanner/UpgradeBanner.tsx
- packages/app/src/app/pages/Dashboard/Content/routes/Repositories/index.tsx
- packages/app/src/app/pages/Dashboard/Content/routes/Sandboxes/index.tsx
- packages/app/src/app/pages/Dashboard/Content/routes/Settings/TeamSettings/ManageSubscription/index.tsx
- packages/app/src/app/pages/Dashboard/Content/routes/Settings/TeamSettings/ManageSubscription/stripe.tsx
- packages/app/src/app/pages/Dashboard/Sidebar/BottomMessages/AdminStartTrial.tsx
- packages/app/src/app/pages/Dashboard/Sidebar/BottomMessages/AdminUpgradeToTeamPro.tsx
- packages/app/src/app/pages/Dashboard/Sidebar/BottomMessages/TrialExpiring.tsx
- packages/app/src/app/pages/Dashboard/Sidebar/BottomMessages/UpgradeToPersonalPro.tsx
Track events for the upgrade, start trial and learn more actions.
> feat(subscription): Track actions

- packages/app/src/app/pages/Dashboard/Components/UpgradeBanner/UpgradeBanner.tsx
Not sure if we want this, but I think that this is what someone is looking for when they want to learn more about the upgrade. Opened this PR in case we want it.
> chore: change "Learn More" link to go to pricing page

- packages/app/package.json
- packages/app/src/embed/components/App/index.js
- yarn.lock
Add `?sandpack=experimental` to an embed URL iframe in order to render a Sandpack instance instead of the usual embed layout
> Embed: Experimental Sandpack layout

- packages/app/src/app/components/CreateSandbox/CreateSandbox.tsx
- packages/app/src/app/components/CreateSandbox/Import/Import.tsx
- packages/app/src/app/components/CreateSandbox/Import/importLimits.tsx
- packages/app/src/app/components/CreateSandbox/SearchResults/SearchResultList.tsx
- packages/app/src/app/components/CreateSandbox/SearchResults/SearchResults.tsx
- packages/app/src/app/components/CreateSandbox/TemplateCard.tsx
- packages/app/src/app/components/CreateSandbox/TemplateCategoryList.tsx
- packages/app/src/app/components/CreateSandbox/elements.ts
- packages/app/src/app/components/CreateSandbox/stripes.tsx
- packages/app/src/app/constants.ts
- packages/app/src/app/hooks/useSubscription.ts
- packages/app/src/app/pages/Dashboard/Components/Selection/ContextMenus/MultiItemMenu.tsx
- packages/app/src/app/pages/Dashboard/Components/Selection/ContextMenus/SandboxMenu.tsx
- packages/app/src/app/pages/Dashboard/Components/Selection/index.tsx
- packages/app/src/app/pages/Dashboard/Components/TemplatesRow/TemplatesRow.tsx
- packages/app/src/app/pages/Dashboard/Components/UpgradeBanner/UpgradeBanner.tsx
- packages/app/src/app/pages/Dashboard/Content/routes/Repositories/index.tsx
- packages/app/src/app/pages/Dashboard/Content/routes/Sandboxes/index.tsx
https://www.youtube.com/watch?v=ucX9hVCQT_U
> feat(limitations): sandbox and repository limitations

- packages/app/src/app/pages/Dashboard/Components/UpgradeBanner/UpgradeBanner.tsx
- packages/components/src/components/Banner/Banner.tsx
Changes to color, padding and copy.
[Old version]
**[New version]**
> UI Review: Style and Text Fixes to Upgrade Banner

- packages/app/src/app/pages/common/Modals/NewTeamModal/TeamSubscription.tsx
- packages/app/src/app/pages/common/Modals/NewTeamModal/index.tsx
- packages/app/src/app/pages/common/Modals/index.tsx
> chore: tweak pro feature list

- packages/app/src/app/pages/Dashboard/Content/routes/Settings/TeamSettings/WorkspaceSettings.tsx
Pilot teams aren't paying teams.
> fix(subscription): hide organization upgrade cta if team is pilot

- packages/app/src/app/overmind/namespaces/dashboard/types.ts
- packages/app/src/app/pages/Dashboard/Components/EmptyScreen/index.tsx
- packages/app/src/app/pages/Dashboard/Components/Folder/CreateFolder.tsx
- packages/app/src/app/pages/Dashboard/Components/Folder/index.tsx
- packages/app/src/app/pages/Dashboard/Components/Sandbox/SandboxListItem.tsx
- packages/app/src/app/pages/Dashboard/Components/Sandbox/index.tsx
- packages/app/src/app/pages/Dashboard/Components/Selection/ContextMenus/FolderMenu.tsx
- packages/app/src/app/pages/Dashboard/Components/Selection/ContextMenus/MultiItemMenu.tsx
- packages/app/src/app/pages/Dashboard/Components/Selection/ContextMenus/SandboxMenu.tsx
- packages/app/src/app/pages/Dashboard/Components/Selection/index.tsx
- packages/app/src/app/pages/Dashboard/Components/VariableGrid/index.tsx
- packages/app/src/app/pages/Dashboard/Content/index.tsx
- packages/app/src/app/pages/Dashboard/Content/routes/Deleted/index.tsx
- packages/app/src/app/pages/Dashboard/Sidebar/ContextMenu.tsx
- packages/app/src/app/pages/Dashboard/Sidebar/index.tsx
- packages/app/src/app/pages/Dashboard/Sidebar/utils.tsx
- packages/app/src/app/pages/Profile/ContextMenu.tsx
- packages/app/src/app/pages/common/Modals/DeleteProfileSandboxModal/index.tsx
- packages/app/src/app/pages/common/Modals/DeleteSandboxModal/index.tsx
- packages/app/src/app/pages/common/Modals/MoveSandboxFolderModal/DirectoryPicker/SandboxesItem/FolderEntry/index.tsx
- packages/common/src/utils/url-generator/dashboard.ts
> chore: revert archive to delete

- packages/app/src/app/pages/Dashboard/Content/routes/Settings/TeamSettings/ManageSubscription/index.tsx
- packages/app/src/app/pages/Dashboard/Content/routes/Settings/TeamSettings/ManageSubscription/upgrade.tsx
- packages/app/src/app/pages/Dashboard/Content/routes/Settings/TeamSettings/RegistryForm.tsx
- packages/app/src/app/pages/Dashboard/Content/routes/Settings/TeamSettings/RegistrySettings.tsx
- packages/app/src/app/pages/Dashboard/Content/routes/Settings/TeamSettings/WorkspaceSettings.tsx
- packages/app/src/app/pages/Dashboard/Content/routes/Settings/UserSettings/ManageSubscription/Upgrade.tsx
- packages/app/src/app/pages/Dashboard/Content/routes/Settings/UserSettings/WorkspaceSettings.tsx
- packages/app/src/app/pages/Dashboard/Content/routes/Settings/components/PermissionSettings.tsx
- packages/app/src/app/pages/common/Modals/DeleteWorkspace/index.tsx
**Change font weight of titles to Regular
Adjust text case of CTAS**
[Old]
[New]
**Change highlight to 'Team Pro' only on upgrade notification for Registry and Permissions screen**
[Old]
[New]
> UI Review: Change font-weight of titles in Team settings modules

- packages/app/src/app/overmind/namespaces/dashboard/actions.ts
Adds tracking if sandbox is moved to a different team.
> feat(tracking): Sandbox is moved to different team

- packages/app/src/app/pages/Dashboard/Components/Branch/BranchCard.tsx
- packages/app/src/app/pages/Dashboard/Components/Branch/BranchListItem.tsx
- packages/app/src/app/pages/Dashboard/Components/Branch/index.tsx
- packages/app/src/app/pages/Dashboard/Components/Branch/types.ts
- packages/app/src/app/pages/Dashboard/Components/Repository/RepositoryCard.tsx
- packages/app/src/app/pages/Dashboard/Components/Repository/RepositoryListItem.tsx
- packages/app/src/app/pages/Dashboard/Components/Repository/index.tsx
- packages/app/src/app/pages/Dashboard/Components/Repository/types.ts
- packages/app/src/app/pages/Dashboard/Components/Sandbox/NewMasterSandbox.tsx
- packages/app/src/app/pages/Dashboard/Components/Sandbox/SandboxCard.tsx
- packages/app/src/app/pages/Dashboard/Components/Sandbox/SandboxListItem.tsx
- packages/app/src/app/pages/Dashboard/Components/Sandbox/index.tsx
- packages/app/src/app/pages/Dashboard/Components/Sandbox/types.ts
- packages/app/src/app/pages/Dashboard/Components/Selection/ContextMenus/RepositoryMenu.tsx
- packages/app/src/app/pages/Dashboard/Components/Selection/ContextMenus/SandboxMenu.tsx
- packages/app/src/app/pages/Dashboard/Components/SyncedSandbox/SyncedSandboxListItem.tsx
- packages/app/src/app/pages/Dashboard/Components/SyncedSandbox/index.tsx
This will create some conflicts with #7198 but I will solve them there after merging this.
PR is just find and replace, no logic change
Closes XTD-420
> chore: replace view only with restricted

- packages/app/src/app/components/CreateSandbox/Import/importLimits.tsx
- packages/app/src/app/components/CreateSandbox/stripes.tsx
- packages/app/src/app/pages/Dashboard/Content/routes/Settings/TeamSettings/ManageSubscription/upgrade.tsx
- packages/app/src/app/pages/Dashboard/Content/routes/Settings/TeamSettings/RegistrySettings.tsx
- packages/app/src/app/pages/Dashboard/Content/routes/Settings/TeamSettings/WorkspaceSettings.tsx
- packages/app/src/app/pages/Dashboard/Content/routes/Settings/components/PermissionSettings.tsx
- packages/app/src/app/pages/Dashboard/Sidebar/BottomMessages/AdminUpgradeToTeamPro.tsx
- packages/app/src/app/pages/Dashboard/Sidebar/BottomMessages/UpgradeToPersonalPro.tsx
- packages/app/src/app/pages/Sandbox/Editor/Header/Collaborators/Collaborator.tsx
The goal is to understand where the users are redirected to the /pro page.
1. Step A
2. Step B
3. Step C
> chore: add source to links that point to the pro page

- packages/app/src/app/pages/Dashboard/Content/routes/Deleted/index.tsx
- packages/app/src/app/pages/Dashboard/Content/routes/Liked/index.tsx
- packages/app/src/app/pages/Dashboard/Content/routes/MyContributions/index.tsx
- packages/app/src/app/pages/Dashboard/Content/routes/Recent/index.tsx
- packages/app/src/app/pages/Dashboard/Content/routes/Repositories/index.tsx
- packages/app/src/app/pages/Dashboard/Content/routes/Sandboxes/index.tsx
- packages/app/src/app/pages/Dashboard/Content/routes/Settings/TeamSettings/TeamSettings.tsx
- packages/app/src/app/pages/Dashboard/Content/routes/Settings/UserSettings/index.tsx
- packages/app/src/app/pages/Dashboard/Content/routes/Shared/index.tsx
- packages/app/src/app/pages/Dashboard/Content/routes/SyncedSandboxes/index.tsx
- packages/app/src/app/pages/Dashboard/Content/routes/Templates/index.tsx
Changed the title of pages in the dashboard to better reflect the active page.
> feat(dashboard): Update dashboard page titles

- packages/components/src/components/CreateCard/CreateCard.stories.tsx
- packages/components/src/components/CreateCard/CreateCard.tsx
- packages/components/src/components/CreateCard/index.tsx
Creates a new generic `CreateCard` that receives an icon, a label and extends props from the `Stack`. It's placed in the components section to make visual testing easier with Storybook since this component will be integrated on an upcoming task.
> feat(dashboard/components): CreateCard

- packages/app/src/app/components/CreateSandbox/TemplateCard.tsx
- packages/app/src/app/components/CreateSandbox/elements.ts
- packages/app/src/app/pages/Dashboard/Components/Header/index.tsx
- packages/app/src/app/pages/Dashboard/Content/routes/Sandboxes/EmptyState.tsx
- packages/app/src/app/pages/Dashboard/Content/routes/Sandboxes/MaxSandboxesBanner.tsx
- packages/app/src/app/pages/Dashboard/Content/routes/Sandboxes/RestrictionsBanner.tsx
- packages/app/src/app/pages/Dashboard/Content/routes/Sandboxes/index.tsx
- packages/components/src/components/CreateCard/CreateCard.tsx
- packages/components/src/index.ts
There's a bit of code duplication at the moment. I want to pick up another task to see what can be abstracted into a template and what's better left as is.
> feat(sandboxes): update empty state

- packages/app/src/app/pages/Dashboard/Content/routes/Deleted/index.tsx
Updates the UI when there are no recently deleted items:
> feat(dashboard/deleted): update empty state

- packages/app/src/app/graphql/types.ts
- packages/app/src/app/overmind/effects/gql/dashboard/queries.ts
- packages/app/src/app/overmind/namespaces/dashboard/actions.ts
- packages/app/src/app/overmind/namespaces/dashboard/state.ts
- packages/app/src/app/pages/Dashboard/Components/EmptyPage/index.tsx
- packages/app/src/app/pages/Dashboard/Content/routes/Liked/EmptyLikes.tsx
- packages/app/src/app/pages/Dashboard/Content/routes/Liked/index.tsx
Needs to be tested against production because there are no curated collections in staging:
> feat(dashboard/likes): update empty page

- packages/app/src/app/pages/Dashboard/Components/TemplatesRow/TemplatesRow.tsx
- packages/app/src/app/pages/Dashboard/Content/routes/Drafts/EmptyDrafts.tsx
- packages/app/src/app/pages/Dashboard/Content/routes/MyContributions/EmptyContributions.tsx
- packages/app/src/app/pages/Dashboard/Content/routes/Recent/DocumentationRow.tsx
- packages/app/src/app/pages/Dashboard/Content/routes/Recent/EmptyRecent.tsx
- packages/app/src/app/pages/Dashboard/Content/routes/Repositories/EmptyRepositories.tsx
- packages/app/src/app/pages/Dashboard/Content/routes/Sandboxes/EmptySandboxes.tsx
- packages/app/src/app/pages/Dashboard/Content/routes/Shared/index.tsx
- Adds events to match this table on Notion: https://www.notion.so/codesandbox-app/Dashboard-Onboarding-888d5e7f16684175abc1c67995e5f07d#adc9614b198b41f8bc5e56b342a99bd5
- Adds utm source parameter to URLs.
> feat(tracking): updates events + utm tracking

- packages/app/src/app/components/CreateSandbox/TemplateCard.tsx
- packages/app/src/app/pages/Dashboard/Components/CommunitySandbox/types.ts
- packages/app/src/app/pages/Dashboard/Components/Selection/DragPreview.tsx
- packages/common/src/utils/getTemplateIcon.ts
Worked together with Lena on this one.
> chore: reduce template icon and text in create sandbox modal

- packages/app/src/app/pages/Dashboard/Content/routes/Recent/EmptyRecent.tsx
Removes intro video from first row.
> recent: remove "getting started with codesandbox" from first row

- packages/app/src/app/pages/Dashboard/Content/routes/MyContributions/EmptyContributions.tsx
- packages/app/src/app/pages/Dashboard/Content/routes/Recent/DocumentationRow.tsx
- packages/app/src/app/pages/Dashboard/Content/routes/Recent/EmptyRecent.tsx
- packages/app/src/app/pages/Dashboard/Content/routes/Recent/OpenSourceRow.tsx
- packages/app/src/app/pages/Dashboard/Content/routes/Repositories/EmptyRepositories.tsx
- packages/app/src/app/pages/Dashboard/Content/routes/Shared/index.tsx
- packages/app/src/app/pages/Dashboard/Content/utils.ts
Adds the following row if the workspace is personal and there are no recent branches, sandboxes, etc.
> feat(dashboard): creates OpenSourceRow

- packages/app/src/app/components/CreateSandbox/TemplateCard.tsx
- packages/app/src/app/components/CreateSandbox/elements.ts
- packages/components/src/components/CreateCard/CreateCard.tsx
- packages/components/src/components/ExternalCard/elements.ts
- Changes background color of cards:
- Fixes the typography of template cards:
> fix(cards): adjust UI

- packages/app/src/app/pages/Dashboard/Components/Branch/BranchCard.tsx
- packages/app/src/app/pages/Dashboard/Components/Repository/RepositoryCard.tsx
- packages/app/src/app/pages/Dashboard/Components/VariableGrid/index.tsx
- packages/app/src/app/pages/Dashboard/Components/shared/ActionCard.tsx
- packages/app/src/app/pages/Dashboard/Components/shared/StyledCard.tsx
- packages/components/src/components/InteractiveOverlay/InteractiveOverlay.stories.tsx
- packages/components/src/components/InteractiveOverlay/InteractiveOverlay.tsx
Check out the components in Storybook. Also changed implementations of the `InteractiveOverlay` in the different cards, so make sure to check those out too.
> feat(InteractiveOverlay): update Item and add Button and Link children

- packages/app/src/app/components/CreateSandbox/CreateSandbox.tsx
Learn how many times people use the template search to see if we should improve it.
> chore: track template search

- packages/app/src/app/constants.ts
- packages/app/src/app/pages/common/Modals/SubscriptionCancellation/SubscriptionCancellation.tsx
Part of XTD-593.
Update reference to free disk space after [change](https://github.com/codesandbox/codesandbox-server/pull/1229) 
https://linear.app/codesandbox/issue/XTD-593/update-pricing-info-to-reflect-new-disk-limits
shows 4GB on `/pro` page and cancellation modal
verified change in preview
> Update free disk space

- packages/app/src/app/pages/Dashboard/Components/Carousel/Carousel.tsx
- packages/app/src/app/pages/Dashboard/Components/EmptyPage/index.tsx
- packages/app/src/app/pages/Dashboard/Content/routes/Recent/DocumentationRow.tsx
- packages/app/src/app/pages/Dashboard/Content/routes/Recent/EmptyRecent.tsx
- packages/app/src/app/pages/Dashboard/Content/routes/Recent/InstructionsRow.tsx
- packages/app/src/app/pages/Dashboard/Content/routes/Recent/OpenSourceRow.tsx
- packages/app/src/app/pages/Dashboard/Content/routes/Recent/RecentContent.tsx
|Before|
|:-:|
|![codesandbox stream_dashboard_recent_workspace=cab9e635-ec49-4c82-806c-c521babd3a6c](https://user-images.githubusercontent.com/24959348/215398137-c0803eda-2bfd-4e3c-87f3-9ca56b3b00ef.png)|
|After|
|:-:|
|![localhost_3000_dashboard_recent_workspace=cab9e635-ec49-4c82-806c-c521babd3a6c](https://user-images.githubusercontent.com/24959348/215398074-95640e76-7882-4e77-9792-d45d97701d3e.png)|
Adds "carousel" to the dashboard recent page.
> feat(dashboard): make content scroll horizontally

- packages/app/src/app/components/CreateSandbox/CreateSandboxModal.tsx
Reverts codesandbox/codesandbox-client#7376
> Revert "fix(dashboard): Only close modal when modal is open"

- packages/app/src/app/overmind/actions.ts
- packages/app/src/app/overmind/internalActions.ts
- packages/app/src/app/overmind/namespaces/git/actions.ts
- packages/app/src/app/overmind/utils/auth.ts
- packages/app/src/app/pages/SignIn/ChooseProvider.tsx
- packages/app/src/app/pages/SignIn/components/DuplicateAccount.tsx
This PR is needed to unblock further work in: https://github.com/codesandbox/codesandbox-client/pull/7385
- Adjusts the function signature to improve consistency.
- Handles opening `.stream` to test the GitHub flow in development mode.
> feat: update provider auth

- packages/app/src/app/components/StripeMessages/UpgradeSSEToV2.tsx
> chore: adjust copy

- packages/app/src/app/pages/Pro/Upgrade.tsx
Undo the previous CTA text change
> fix(pro): CTA text for personal

- packages/app/src/app/pages/Pro/Upgrade.tsx
Change pricing to reflect the actual pricing in Stripe.
> fix(pricing): Reflect true pricing

- packages/app/src/app/pages/Dashboard/index.tsx
> chore: re-run build

- packages/app/src/app/hooks/useWorkspaceSubscription.ts
- packages/app/src/app/overmind/actions.ts
- packages/app/src/app/overmind/modals.ts
- packages/app/src/app/overmind/namespaces/editor/internalActions.ts
- packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Live/NotLive/Owner.tsx
- packages/app/src/app/pages/common/Modals/GenericAlertModal/index.tsx
- packages/app/src/app/pages/common/Modals/LiveSessionConfirm/index.tsx
- packages/app/src/app/pages/common/Modals/index.tsx
When a user clicks on "Go live" and the current workspace does not have a pro subscription, shows a notice that the feature will be restricted to pro users soon. I've also disabled automatically initializing the live session.
codesandbox-john1 (credentials in 1Password) can be used to test this.
> feat(editor/live): feature notice

- packages/app/src/app/pages/Dashboard/Content/routes/Recent/DocumentationRow.tsx
I re-ordered the videos to better highlight our git flow.
1. Step A
2. Step B
3. Step C
> feat(dashboard): reorder onboarding videos

- packages/app/src/app/overmind/internalActions.ts
- packages/app/src/app/pages/Sandbox/OnBoarding/index.tsx
Always set the onboarding to `false` on sign-up.
> feat(editor): hide onboarding for new users

- packages/app/src/app/pages/common/Modals/LiveSessionConfirm/index.tsx
> feat(live): Update date to pro feature

- packages/app/src/app/pages/Dashboard/Components/UpgradeBanner/UpgradeBanner.tsx
> feat(live): Replace privacy settings with live sessions pro perk in banner

- packages/app/src/app/overmind/effects/api/apiFactory.ts
- packages/app/src/app/overmind/effects/api/index.ts
- packages/app/src/app/overmind/namespaces/pro/actions.ts
- packages/app/src/app/overmind/namespaces/pro/state.ts
- packages/app/src/app/overmind/namespaces/pro/types.ts
- packages/app/src/app/pages/Pro/Upgrade.tsx
- packages/app/src/app/pages/common/Modals/MemberPaymentConfirmation/index.tsx
- packages/app/src/app/utils/currency.ts
- packages/homepage/src/pages/pricing/_utils.js
- packages/homepage/src/pages/pricing/index.js
Made the pricing on the Pro page dynamic so it updates automatically when we update it.
> feat(pricing): Use dynamic pricing fetched from stripe on pro page

- packages/app/src/app/hooks/useCreateCheckout.ts
- packages/app/src/app/hooks/useWorkspaceSubscription.ts
- packages/app/src/app/pages/Dashboard/Components/NewTeamModal/TeamSubscription.tsx
- packages/app/src/app/pages/Dashboard/Components/TeamSubscriptionOptions/TeamSubscriptionOptions.tsx
- packages/app/src/app/pages/Dashboard/Content/routes/Settings/TeamSettings/ManageSubscription/upgrade.tsx
- packages/app/src/app/pages/Dashboard/Content/routes/Settings/TeamSettings/WorkspaceSettings.tsx
- packages/app/src/app/pages/Dashboard/Sidebar/BottomMessages/AdminStartTrial.tsx
- packages/app/src/app/pages/Pro/Upgrade.tsx
- packages/app/src/app/pages/Pro/components/SubscriptionCard.tsx
- packages/app/src/app/pages/Pro/legacy-pages/WorkspacePlanSelection.tsx
- packages/components/src/components/ComboButton/ComboButton.tsx
Closes [XTD-696](https://linear.app/codesandbox/issue/XTD-696/release-0-allow-admin-to-open-stripe-to-check-out-on-annual).
Updates the workspace settings UI to allow free teams to go through the checkout process and purchase seats on yearly subscriptions.
https://user-images.githubusercontent.com/24959348/221274141-a0301700-5320-4fff-9c10-e1e9a3bf8fa0.mov
Updates the new team creation to include more subscription options:
Updates the `/pro` page to show subscription options:
2. Visit a team that does not have an active subscription
3. Go to the settings
4. Click on the caret in the upgrade card
5. Select "Custom upgrade"
6. The UI in Stripe should allow to select the quantity of seats to purchase
> feat(subscriptions): enable annual subscriptions

- packages/app/src/app/components/CreateSandbox/Import/SuggestedRepositories.tsx
Closes XTD-731
https://user-images.githubusercontent.com/7533849/221875497-2f2471b8-4fa1-4db1-91cd-1834af7f638e.mov
> feat(import): update suggested private repository action when on a free tier

- packages/app/src/app/pages/Dashboard/index.tsx
Allows opening the create new modal on the import tab by passing a search param.
https://user-images.githubusercontent.com/24959348/221967756-8f8a3627-4e0c-432f-a028-05be189f7bef.mov
1. Visit https://k9kls0-3000.preview.csb.app/dashboard/recent?import_repo=true
- If you are not signed in, it'll take you to `/signin` and you can use the dev sign-in flow as expected.
2. The dashboard will load in your personal team and the create new modal will open on the import tab.
Alternatively, you can visit https://k9kls0-3000.preview.csb.app/dashboard/recent?workspace={WORKSPACE_ID}&import_repo=true. The flow will be the same as the above but the dashboard will load in the specified team and the import suggestions will be based on the github organization that matches the closest to the workspace.
> feat(dashboard): adds support to "import_repo" search param

- packages/app/src/app/components/CreateSandbox/Import/SuggestedRepositories.tsx
We had to update the import through an action rather than a URL.
> fix(import): Update to the new way of importing

- packages/app/src/app/components/CreateSandbox/Import/AccountSelect.tsx
- packages/app/src/app/components/CreateSandbox/Import/SuggestedRepositories.tsx
> Update SuggestedRepos and AccountSelector styles 

- packages/app/config/babel.prod.js
- packages/app/config/webpack.common.js
- packages/app/config/webpack.prod.js
> chore: Remove ie11 from babel config

- packages/app/src/app/pages/Pro/Upgrade.tsx
- packages/app/src/app/pages/Pro/components/UpsellTeamProCard.tsx
> fix(pro): typo anually to annually

- packages/app/src/app/components/CreateSandbox/Import/SuggestedRepositories.tsx
- packages/app/src/app/components/CreateSandbox/Import/useGitHubAccountRepositories.ts
Closes XTD-714.
If the suggested repo has been imported into the current team, don't show it on the suggestions.
https://user-images.githubusercontent.com/24959348/223808170-e9d36dfb-9fe8-4521-ae61-0cb1bd8accd9.mov
Already imported repos were part of the suggestions. 
If a repo has already been imported, it doesn't get listed in the suggestions.
1. Open the create new modal and go to the "Import from GitHub tab"
2. Your suggested repos should appear
3. Select one of the suggested repos (it will try to open the editor and 404 because it's a different codebase)
4. Go back to the create new modal
5. Just imported repo shouldn't be listed as suggestion
> feat(import): remove already imported repos from suggestions 

- packages/app/package.json
- packages/app/src/app/components/Debug/Debug.tsx
- packages/app/src/app/components/Debug/index.ts
- packages/app/src/app/hooks/useWorkspaceSubscription.ts
- packages/app/src/app/pages/Dashboard/index.tsx
- yarn.lock
Closes XTD-794.
Since we upgraded to Node 16, we shouldn't have problems installing Leva. The tool will help us mock test scenarios more easily.
https://user-images.githubusercontent.com/24959348/224812871-6de7b3cf-e66d-40cb-8719-16ada66b9d8e.mov
1. Launch the preview
2. Open the dashboard
3. Set `CSB_DEBUG` to `true` 
4. Reload the page
5. Controls should appear at the left bottom of the screen
> feat: leva setup

- packages/app/src/app/components/CreateSandbox/Import/AccountSelect.tsx
- packages/app/src/app/components/CreateSandbox/Import/AuthorizeForSuggested.tsx
- packages/app/src/app/components/CreateSandbox/Import/FromRepo.tsx
- packages/app/src/app/components/CreateSandbox/Import/SuggestedRepositories.tsx
- packages/app/src/app/components/CreateSandbox/Import/utils.ts
- packages/app/src/app/hooks/useGitHubAccountRepositories.ts
- packages/app/src/app/hooks/useGithubOrganizations.ts
- packages/app/src/app/pages/Dashboard/Content/routes/Repositories/EmptyRepositories.tsx
- packages/app/src/app/utils/fuzzyMatchGithubToCsb.ts
Adds suggested repositories to the empty repositories page. Also moves a bunch of files to shared folders.
https://user-images.githubusercontent.com/7533849/224970841-bae45af4-e159-4693-b98a-2a7e079d4e47.mov
> feat(import): Suggest repositories to import on empty repositories page

- packages/app/src/app/components/CreateSandbox/Import/SuggestedRepositories.tsx
Closes XTD-808.
https://user-images.githubusercontent.com/24959348/225953712-d3fa9907-be44-478a-9138-5733b966b7c0.mov
https://user-images.githubusercontent.com/24959348/225955208-59b8a561-1465-47ca-b2fe-0f9149d8895c.mov
1. Visit https://nqqsyr-3000.csb.app/s
2. Select "Import from GitHub"
3. Go through the "Sign in"
4. "There was a problem getting your repositories" error doesn't happen
> fix(suggested repos): do not query if there's no team id

- packages/app/package.json
- packages/app/src/app/components/Debug/Debug.tsx
- packages/app/src/app/components/Debug/index.ts
- packages/app/src/app/hooks/useWorkspaceSubscription.ts
- packages/app/src/app/pages/Dashboard/index.tsx
- packages/app/src/app/pages/index.tsx
- yarn.lock
It adds back: https://github.com/codesandbox/codesandbox-client/pull/7503
And fixes the panel showing in production because `useControls` instance will render the panel even if we return early in the `Debug`, we need to explicitly set its value to `hidden` based on local storage or environment.
> fix: leva setup

- packages/app/src/app/components/CreateSandbox/Import/SuggestedRepositories.tsx
- packages/app/src/app/components/CreateSandbox/queries.ts
- packages/app/src/app/graphql/types.ts
`pushedAt` better reflects the recency of changes made to a repo.
> feat(import): use pushedAt instead of updatedAt in suggested repositories

- packages/app/config/webpack.prod.js
Tweak service worker for less network usage
> chore: Tweak service worker for less network usage

- packages/app/src/sandbox/compile.ts
- packages/app/src/sandbox/eval/transpilers/babel/ast/convert-esmodule.ts
- packages/app/src/sandbox/eval/transpilers/babel/worker/babel-worker.ts
- packages/sandpack-core/src/preset/preset.ts
> chore: cleanup babel worker

- packages/app/src/app/hooks/useWorkspaceLimits.ts
- packages/app/src/app/hooks/useWorkspaceSubscription.ts
- packages/app/src/app/overmind/actions.ts
- packages/app/src/app/pages/Dashboard/Content/routes/Settings/TeamSettings/WorkspaceSettings.tsx
- packages/app/src/app/pages/Dashboard/Content/routes/Settings/components/InviteMember.tsx
- packages/app/src/app/pages/Dashboard/Content/routes/Settings/components/MemberList.tsx
- packages/app/src/app/pages/common/Modals/EditorSeatsUpgrade/index.tsx
- packages/app/src/app/pages/common/Modals/index.tsx
- Adds leva controls to the workspace limits:
- Adds a modal informing that users need to upgrade if their workspace has reached the maximum amount of editors.
Currently, we don't show the option to add more editors if the limit has been reached.
- "Editor" option is enabled in the invite member input:
https://user-images.githubusercontent.com/24959348/227354320-98f88148-d818-4b4e-94a0-2be52179766a.mov
- "Make user an admin" option is enabled in the member actions menu:
https://user-images.githubusercontent.com/24959348/227354425-f0fb7211-a25d-42e1-bbc2-ef32c7a0b929.mov
When accessing the preview, you can set `CSB_DEBUG` to `true` in the local storage. This will show the panel and you can tweak the test scenario as shown in the video below: …
> feat(settings): upsell team pro when trying to add more editors

- packages/app/src/app/overmind/effects/deployment/vercel.ts
- packages/app/src/app/overmind/namespaces/deployment/actions.ts
- packages/app/src/app/overmind/namespaces/deployment/state.ts
- packages/app/src/app/pages/common/Modals/DeploymentModal/index.tsx
- packages/common/src/types/index.ts
Started out by changing the Vercel user endpoint to the latest version, but found that there is a lot of stuff we're not using. This PR doesn't get rid of all of it, but I was able to remove a bunch of unused code and update a few more endpoints in the time left I wanted to spend on this.
This can be tested on stream by deploying (v1) sandboxes to Vercel via the UI. Let me know if you need help getting a Sandbox template to fork and deploy.
> fix(vercel): Update vercel user endpoint

- packages/app/package.json
- packages/sandbox-hooks/package.json
- yarn.lock
This reverts commit 35619b6135a85377a488765b95c1866cef6483f7.
Closes #7566
Closes #7565
Closes #7563
Closes #7560
> fix(console): Don't crash when logging dates

- packages/app/src/app/components/LoseFeatures/LoseFeatures.tsx
- packages/app/src/app/constants.ts
- packages/app/src/app/pages/Dashboard/Components/UpgradeBanner/UpgradeBanner.tsx
Reverts codesandbox/codesandbox-client#7540
> Revert "Remove VM boost for pro - text only"

- packages/app/src/app/pages/Dashboard/Content/routes/Recent/DocumentationRow.tsx
Replaces wrong video link with correct one
[ticket](https://linear.app/codesandbox/issue/PC-786/update-wrong-video-link-on-the-recent-dashboard-page)
1. Step A
2. Step B
3. Step C
> Replace link with correct video

- packages/app/src/app/pages/SignIn/Onboarding.tsx
A nullable field is now _actually_ null sometimes, and it is causing errors. This handles the null.
1. Step A
2. Step B
3. Step C
> Handle null pendingUser.name

- packages/app/src/app/utils/fuzzyMatchGithubToCsb.ts
Fixes https://github.com/codesandbox/codesandbox-client/issues/7615
> fix: check on github org

- packages/app/src/app/components/CreateSandbox/CreateSandbox.tsx
- packages/app/src/app/components/CreateSandbox/Import/Import.tsx
- packages/app/src/app/components/CreateSandbox/ImportSandbox/ImportSandbox.tsx
- packages/app/src/app/components/CreateSandbox/ImportSandbox/index.ts
- packages/app/src/app/components/CreateSandbox/SearchBox/SearchBox.tsx
- packages/app/src/app/pages/Dashboard/Components/Repository/stripes.tsx
- packages/app/src/app/pages/Dashboard/Content/routes/Recent/RecentContent.tsx
- packages/app/src/app/pages/Dashboard/Content/routes/Repositories/index.tsx
This adds the ability to import synced templates into CodeSandbox. Documentation is included.
> feat(CreateSandbox): Allow importing synced templates 

- packages/app/src/app/components/Notifications/Content.tsx
- packages/app/src/app/components/Notifications/Filters.tsx
- packages/app/src/app/components/Notifications/notifications/PullRequestReviewRequest.tsx
- packages/app/src/app/components/Notifications/types.ts
Adds a new notification type, for when someone requests your review on a branch that has been imported into one of your CSB teams.
To test this, sign into this branch (stream) and ask someone to request a review from you on `test-sandbox`
(Note: currently the API does not yet send these notifications because it is a) not yet deployed b) behind a feature flag but that shouldn't impact the mergeability of this)
You don't get a notification.
You will get a notification 🎉 
I couldn't find any existing tests for the notifications, but lmk where I can find them and I'll try adding some.
> PC-957 --  PR review request notification

- packages/app/src/app/components/LoseFeatures/LoseFeatures.tsx
- packages/app/src/app/constants.ts
- packages/app/src/app/pages/Dashboard/Components/UpgradeBanner/UpgradeBanner.tsx
> feat(constants): add AI tool label to feature list in dashboard

- packages/sandpack-core/src/manager.ts
Closes https://github.com/codesandbox/sandpack/issues/944
> fix: hard reload on module removal

- packages/app/src/app/pages/common/Modals/SubscriptionCancellation/SubscriptionCancellation.tsx
- packages/app/src/app/pages/common/Modals/index.tsx
This way we'll get a better sense of what we should improve to make CodeSandbox a better experience.
> chore: add cancellation survey

- packages/app/src/app/overmind/internalActions.ts
- packages/app/src/app/overmind/namespaces/dashboard/actions.ts
Reverts codesandbox/codesandbox-client#7797
> Revert "feat(dashboard): add error handling to getTeams action"

- packages/app/src/app/components/Notifications/Content.tsx
- packages/app/src/app/components/Notifications/notifications/TeamInviteRequest.tsx
- packages/app/src/app/components/Notifications/types.ts
- packages/common/src/utils/url-generator.ts
Adds an in-browser notification for when someone requests to join a team.
1. Step A
2. Step B
3. Step C
> Add TeamInviteRequest notification

- .codesandbox/Dockerfile
- .codesandbox/features.json
- .codesandbox/workspace.json
Uses new Docker setup and forces vue tsserver to not run
> perf: optimize settings for codesandbox environment

- packages/app/src/app/constants.ts
- packages/app/src/app/pages/Dashboard/Content/routes/Settings/TeamSettings/WorkspaceSettings.tsx
- packages/app/src/app/pages/Pro/Create.tsx
- packages/app/src/app/pages/Pro/Upgrade.tsx
- packages/app/src/app/pages/Pro/legacy-pages/WorkspacePlanSelection.tsx
> chore: replace organization contact link

- packages/app/src/app/components/CreateSandbox/SearchResults/SearchResults.tsx
Since all our official templates are now git based.
> fix(templates): remove git requirement

- packages/app/package.json
- packages/app/src/app/components/Preview/DevTools/Console/index.tsx
- packages/sandbox-hooks/console/index.js
- packages/sandbox-hooks/package.json
- yarn.lock
This version of `console-feed` crashes the app multiple times.
> Revert "refactor: update console-feed package to csb-console-feed

- packages/app/src/app/overmind/effects/vscode/extensionHostWorker/common/fs.ts
> chore: update typescript to v5.2.2

- packages/app/src/app/overmind/effects/zip/create-zip/index.ts
This ensures that we don't accidentally add dependencies to a package.json when we create a zip, if they're already defined on the other side (e.g. devDependency vs dependency).
> fix(zip): only add dependencies that are not already in the package.json

- .circleci/config.yml
- packages/app/src/app/overmind/effects/live/index.ts
- packages/app/src/app/overmind/effects/vscode/LinterWorker/package.json
- packages/app/src/app/overmind/effects/vscode/LinterWorker/yarn.lock
- standalone-packages/sse-loading-screen/yarn.lock
- test
create a PR for staging deploy
> staging deploy

- catalog-info.yaml
Add catalog info for backstage
> fix: add catalog info

- packages/common/src/templates/constants/files.ts
Added '.devcontainer' to the list of hidden directories in files.ts
> feat: Add hidden directory

- packages/common/src/templates/constants/files.ts
Add .eslintrc.json to the HIDDEN_FILES array in files.ts
> feat: Add support for .eslintrc.json file

- packages/app/src/app/components/Create/hooks/useFeaturedTemplates.ts
Added react (vite + ts) and python templates, removed react-new-devbox template.
1. Step A
2. Step B
3. Step C
> feat: Updated featured templates

- packages/app/src/app/constants.ts
- packages/app/src/app/pages/Dashboard/Components/UpgradeBanner/UpgradeBanner.tsx
- packages/app/src/app/pages/Dashboard/Content/routes/Settings/UserSettings/ManageSubscription/Upgrade.tsx
- packages/app/src/app/pages/Dashboard/Content/routes/Settings/components/PermissionSettings.tsx
> style: Update AI tool access labels and permissions

- packages/app/src/app/pages/Dashboard/Sidebar/NestableRowItem.tsx
- packages/app/src/app/pages/Dashboard/Sidebar/RowItem.tsx
Update gap from 2 to 1 in NestableRowItem. Update width from 40px to 36px with padding in RowItem.
Before
After
> feat: Update gap and width in Sidebar components

- packages/app/src/app/hooks/useBetaSandboxEditor.ts
- packages/app/src/app/hooks/usePersistedState.ts
- packages/app/src/app/pages/common/Modals/PreferencesModal/Experiments/BetaSandboxEditor.tsx
> fix: decouple experimental flag from feedback form

- packages/app/src/sandbox/index.html
- packages/sandbox-hooks/console/index.js
Temporarily load both V1 and V2 preview protocol in sandbox-hooks console.
> feat: Load V2 Preview Protocol

- packages/app/src/app/components/WorkspaceSetup/StepHeader.tsx
- packages/app/src/app/components/WorkspaceSetup/steps/Create.tsx
- packages/app/src/app/components/WorkspaceSetup/steps/PlanOptions.tsx
- packages/app/src/app/components/WorkspaceSetup/steps/Plans.tsx
Updated spacing, width, and labels in WorkspaceSetup components
Small visual and UI copy tweaks to Workspace Setup screens
Checked the changes in the preview in CSB
> feat: Workspace setup UI tweaks

- packages/app/src/app/components/StripeMessages/SandboxLimitation.tsx
- packages/app/src/app/components/StripeMessages/index.tsx
- packages/app/src/app/hooks/useWorkspaceLimits.ts
- packages/app/src/app/pages/Dashboard/index.tsx
- packages/app/src/app/pages/Sandbox/Editor/index.tsx
- packages/components/src/components/Button/index.tsx
- packages/components/src/components/IconButton/index.tsx
- packages/components/src/components/MessageStripe/MessageStripe.tsx
> feat: Add sandbox limitation banner

- Dockerfile
Update docker nginx base image.
> Update docker nginx

- packages/app/src/app/overmind/namespaces/dashboard/actions.ts
- packages/app/src/app/pages/Dashboard/Content/routes/Recent/RecentContent.tsx
- packages/app/src/app/pages/Dashboard/Content/routes/Recent/RecentHeader.tsx
Useful feature for the dashboard?
> feat: quick access to create new branches for the common repositories

- packages/app/src/app/components/WorkspaceSetup/Summary.tsx
- packages/app/src/app/components/WorkspaceSetup/steps/PlanOptions.tsx
- packages/app/src/app/components/WorkspaceSetup/steps/Plans.tsx
A few different fixes:
- spending limit of $0 allowed
- always show spending limit in the summary
- only redirect from flow when upgrading and non-admin
> fix: minor fixes on checkout

- packages/app/src/app/components/UBBBetaWelcomeBanner.tsx
- packages/common/src/utils/url-generator/dashboard.ts
> fix: add members info in welcome banner

- packages/app/src/app/components/Create/CreateBox.tsx
- packages/app/src/app/components/Create/CreateBox/CreateBoxForm.tsx
> fix: better signaling for drafts in create modal

- packages/app/src/app/pages/Dashboard/Components/UpgradeBanner/UpgradeBanner.tsx
> fix: remove 404 link to docs

- packages/app/src/app/components/Create/CreateBox.tsx
- packages/app/src/app/components/Create/CreateBox/CreateBoxForm.tsx
> feat: add support for selecting folder when creating box

- packages/app/src/app/components/WorkspaceSetup/steps/FAQ.tsx
- packages/app/src/app/components/WorkspaceSetup/steps/Plans.tsx
- packages/app/src/app/constants.ts
- Add FAQ section
- Update constant.ts with the latest changes on Pricing page
Closes PC-1683
> fix(upgrade): design tweaks

- packages/app/src/app/components/UBBBetaWelcomeBanner.tsx
> chore: update content on ubb banner

- packages/app/src/app/overmind/namespaces/dashboard/actions.ts
My bad, didn't test this at the previous release
> fix: logic for deleted page

- packages/app/src/app/components/StripeMessages/RestrictedSandboxes.tsx
- packages/app/src/app/pages/Dashboard/Content/routes/Recent/RecentContent.tsx
- packages/app/src/app/pages/Dashboard/Content/routes/Recent/RecentHeader.tsx
- packages/app/src/app/pages/Dashboard/Content/routes/Recent/index.tsx
- packages/app/src/app/pages/Dashboard/Content/routes/Sandboxes/index.tsx
Also added tracking to the banner (cc @tromika)
> feat: add sandbox banner on recent page

- packages/app/src/app/components/Create/CreateBox.tsx
- packages/app/src/app/components/Create/CreateBox/CreateBoxForm.tsx
- packages/app/src/app/components/Create/elements.tsx
- packages/app/src/app/components/StripeMessages/DraftsLimit.tsx
- packages/app/src/app/graphql/types.ts
- packages/app/src/app/hooks/useWorkspaceLimits.ts
- packages/app/src/app/overmind/effects/gql/dashboard/fragments.ts
- packages/app/src/app/overmind/namespaces/dashboard/actions.ts
- packages/app/src/app/overmind/namespaces/editor/actions.ts
- packages/app/src/app/pages/Dashboard/Components/Selection/ContextMenus/ContainerMenu.tsx
- packages/app/src/app/pages/Dashboard/Content/routes/Drafts/index.tsx
- packages/app/src/app/pages/Dashboard/Content/routes/Recent/RecentHeader.tsx
- packages/app/src/app/pages/Dashboard/Content/routes/Sandboxes/index.tsx
- packages/app/src/app/pages/Dashboard/Content/routes/Templates/index.tsx
Drafts
Drafts limit
Sandbox limit
> feat: add draft limit for free workspaces

- packages/app/src/app/components/WorkspaceSelect/WorkspaceSelect.tsx
- packages/app/src/app/components/WorkspaceSetup/Summary.tsx
- packages/app/src/app/components/WorkspaceSetup/steps/Addons.tsx
- packages/app/src/app/components/WorkspaceSetup/steps/ChangePlan.tsx
- packages/app/src/app/components/WorkspaceSetup/steps/Create.tsx
- packages/app/src/app/pages/WorkspaceFlows/CreateWorkspace.tsx
- packages/app/src/app/pages/WorkspaceFlows/UpgradeWorkspace.tsx
> fix: improve tracking on create workspace and checkout

- packages/app/src/app/pages/Dashboard/Components/Sandbox/SandboxCard.tsx
- packages/app/src/app/pages/Dashboard/Components/Sandbox/index.tsx
- packages/app/src/app/pages/Dashboard/Content/routes/Recent/RecentContent.tsx
Small PR to add the title attribute on the sandbox card (helps with long names) and to cleanup unused code
> fix: title attr when hovering sandbox card

- packages/app/src/app/components/WorkspaceSelect/WorkspaceSelect.tsx
Forgot to account for friend of csb in the filter there
> fix: allow moving into friend of csb workspaces

- packages/app/src/app/components/Create/CreateBox.tsx
- packages/app/src/app/components/Create/GenericCreate.tsx
- packages/app/src/app/components/Create/ImportRepository.tsx
- packages/app/src/app/components/Integration/DetailInfo/elements.ts
- packages/app/src/app/components/Integration/elements.ts
- packages/app/src/app/components/Modal/index.js
- packages/app/src/app/components/Notifications/Content.tsx
- packages/app/src/app/overmind/namespaces/dashboard/actions.ts
- packages/app/src/app/pages/Dashboard/Content/routes/Recent/RecentContent.tsx
- packages/app/src/app/pages/Dashboard/Sidebar/constants.ts
- packages/app/src/app/pages/Dashboard/Sidebar/index.tsx
- packages/app/src/app/pages/Dashboard/index.tsx
- packages/app/src/app/pages/common/Modals/PreferencesModal/Integrations/GitHubPermissions.tsx
- packages/app/src/app/pages/common/Modals/PreferencesModal/SideNavigation.tsx
- packages/app/src/app/pages/common/Modals/TeamInviteModal/index.tsx
Some general styling and alignment fixes
Preferences modal window simplified (integrations tab)
Close button added for all modal windows consistently
> style: different improvements on modal windows and overall layout

- packages/app/src/app/pages/common/Modals/PreferencesModal/Experiments/BetaSandboxEditor.tsx
Change title from 'Sandbox beta editor' to 'Unified Platform Editor' and change tooltip from 'Use beta editor' to 'Use Unified Platform Editor'
> style: Changing experiments modal title and tooltip to reflect current terminology

- packages/app/src/app/components/StripeMessages/PaymentPending.tsx
- packages/app/src/app/graphql/types.ts
- packages/app/src/app/pages/Dashboard/index.tsx
- packages/app/src/app/pages/Sandbox/Editor/index.tsx
> feat: add handling for subscription status IncompleteExpired

- packages/app/src/app/components/Create/hooks/useFeaturedTemplates.ts
Make the Postgres template more features to get a better sense if people like to see more full-stack templates.
> feat: add postgres as featured template

- packages/app/src/app/components/Create/CreateBox/CreateBoxForm.tsx
- packages/app/src/app/components/WorkspaceSelect/WorkspaceSelect.tsx
- packages/app/src/app/pages/Dashboard/Components/Breadcrumbs/index.tsx
- packages/app/src/app/pages/Dashboard/Components/Header/index.tsx
- packages/app/src/app/pages/Dashboard/Components/Selection/index.tsx
- packages/app/src/app/pages/Dashboard/Content/routes/Drafts/index.tsx
- packages/app/src/app/pages/Dashboard/Content/routes/Recent/RecentContent.tsx
- packages/app/src/app/pages/Dashboard/Sidebar/ExpandableReposRowItem.tsx
- packages/app/src/app/pages/Dashboard/Sidebar/NestableRowItem.tsx
- packages/app/src/app/pages/Dashboard/Sidebar/RowItem.tsx
- packages/app/src/app/pages/Dashboard/Sidebar/index.tsx
- packages/app/src/app/pages/common/Modals/MoveSandboxFolderModal/DirectoryPicker/SandboxesItem/index.tsx
- packages/common/src/utils/url-generator/dashboard.ts
- packages/components/src/components/List/index.tsx
**Today**
**Proposal**
Closes PC-1747
Closes PC-1748
Other small improvements
- better alignment for folders in dropdown (create modal)
- auto-expand repositories if less then 5
> feat: reorder and rename siderbar items

- packages/app/package.json
- packages/app/src/app/hooks/useCookieConsent.ts
- packages/app/src/app/index.js
- packages/app/src/app/pages/index.tsx
- packages/app/src/app/utils/cookieConsent/cookieConsentConfig.ts
- packages/app/src/app/utils/cookieConsent/cookieConsentTheme.css
- packages/app/src/embed/index.js
- packages/common/src/utils/analytics/amplitude.ts
- packages/common/src/utils/analytics/index.ts
- yarn.lock
Same as: https://github.com/codesandbox/codesandbox-site/pull/404
> feat: add cookie consent

- packages/app/src/app/pages/Dashboard/Sidebar/RowItem.tsx
- packages/app/src/app/pages/Dashboard/Sidebar/index.tsx
> feat: Add upgrade option for free users in Dashboard Sidebar

- packages/app/src/app/pages/Dashboard/Sidebar/index.tsx
Add isTeamAdmin to useWorkspaceAuthorization hook in Sidebar component
> fix: show upgrade button only for admins 

- packages/sandpack-core/src/manager.ts
- packages/sandpack-core/src/npm/dynamic/fetch-npm-module.ts
- packages/sandpack-core/src/resolver/resolver.ts
Follow-up on #8387 this one fixes both the original issue and the regression
> fix: npm fetcher improvement + regression fix

- packages/app/src/app/components/Create/CreateBox.tsx
- packages/app/src/app/components/Create/CreateBox/TemplateInfo.tsx
- packages/app/src/app/components/Create/TemplateCard.tsx
- packages/app/src/app/components/Create/TemplateList.tsx
- packages/app/src/app/components/Create/hooks/useAllTemplates.ts
- packages/app/src/app/components/Create/hooks/useFeaturedTemplates.ts
- packages/app/src/app/components/Create/hooks/useOfficialTemplates.ts
- packages/app/src/app/components/Create/hooks/useTeamTemplates.ts
- packages/app/src/app/components/Create/utils/api.ts
- packages/app/src/app/components/Create/utils/types.ts
- packages/app/src/app/graphql/types.ts
- packages/app/src/app/overmind/actions.ts
- packages/app/src/app/overmind/effects/api/index.ts
- packages/app/src/app/overmind/effects/gql/dashboard/queries.ts
- packages/app/src/app/overmind/state.ts
- packages/app/src/app/pages/Dashboard/index.tsx
- packages/app/src/app/pages/common/Modals/index.tsx
In order to test this, try and sandbox/devbox id in the following queries:
/dashboard/recent?create_devbox=devbox-id
/dashboard/recent?create_sandbox=sandbox-id
> feat: add param for prefill sandbox template

- packages/app/src/app/components/Notifications/index.tsx
- packages/app/src/app/components/WorkspaceSelect/WorkspaceSelect.tsx
- packages/app/src/app/pages/Dashboard/Components/Selection/index.tsx
- packages/app/src/app/pages/Dashboard/Content/routes/Recent/RecentContent.tsx
- packages/app/src/app/pages/Dashboard/Content/routes/Recent/RecentHeader.tsx
- packages/app/src/app/pages/Dashboard/Content/routes/Search/searchItems.ts
- packages/app/src/app/pages/Dashboard/Header/index.tsx
- packages/app/src/app/pages/Dashboard/Sidebar/index.tsx
- packages/app/src/app/pages/common/UserMenu/index.tsx
- packages/components/src/components/Button/index.tsx
> feat: topbar redesign

- packages/app/src/app/components/WorkspaceSetup/Layout.tsx
- packages/app/src/app/components/WorkspaceSetup/StepHeader.tsx
- packages/app/src/app/components/WorkspaceSetup/steps/Addons.tsx
- packages/app/src/app/components/WorkspaceSetup/steps/ChangePlan.tsx
- packages/app/src/app/components/WorkspaceSetup/steps/Finalize.tsx
- packages/app/src/app/components/WorkspaceSetup/steps/Payment.tsx
- packages/app/src/app/components/WorkspaceSetup/steps/Plans.tsx
- packages/app/src/app/components/WorkspaceSetup/steps/SelectWorkspace.tsx
- packages/app/src/app/components/WorkspaceSetup/steps/SpendingLimit.tsx
- Fix an issue on the Select Workspace step
- Add a workspace caption on every step 
Closes PC-1778
> feat: Add workspaceId prop to StepHeader component

- packages/app/src/app/components/Create/CreateBox/CreateBoxForm.tsx
This didn't work:
1. Set privacy to public or unlisted
2. Try set folder to "Drafts"
It would not set the folder to drafts, and this fixes that :)
> fix: setting folder to drafts with privacy 2

- packages/app/src/app/components/Notifications/index.tsx
The condition was accidentally flipped in prod
> fix: notification bubble

- packages/app/src/app/components/WorkspaceSetup/steps/Plans.tsx
Fixes https://github.com/codesandbox/codesandbox-client/issues/8424
> fix: update links on pricing page

- packages/app/src/app/components/Create/ImportRepository/steps/StartFromTemplate.tsx
Before (temporary screen)
After (using the templates tagged with `starter`)
> feat: use starter templates for create repo

- packages/app/src/app/pages/Dashboard/Sidebar/index.tsx
> fix: show usage only for ubb

- packages/app/src/app/components/Create/TemplateCard.tsx
- packages/app/src/app/components/Create/utils/constants.ts
> feat: add codeium in featured templates

- packages/app/src/app/pages/Dashboard/Components/Selection/ContextMenus/SandboxMenu.tsx
> fix: don't allow moving templates in folders

- packages/sandbox-hooks/console/index.js
Closes https://github.com/codesandbox/sandpack/issues/1068
Closes https://github.com/codesandbox/sandpack/issues/1091
> fix(sandpack): avoid loading preview protocol outside preview domain

- packages/app/src/sandbox/compile.ts
- packages/sandpack-core/src/npm/index.ts
Send Sandpack messages about the progress of the dependency download.
> feat(sandpack): send dependency progress

- packages/app/src/app/components/Create/CreateBox.tsx
- packages/app/src/app/components/Create/CreateBox/CreateBoxForm.tsx
- packages/app/src/app/components/Create/ImportRepository.tsx
- packages/app/src/app/components/Create/SearchBox/SearchBox.tsx
- packages/app/src/app/components/Create/SearchBox/elements.ts
- packages/app/src/app/components/Create/TemplateCard.tsx
- packages/app/src/app/components/Create/TemplateFilter.tsx
- packages/app/src/app/components/Create/TemplateList.tsx
- packages/app/src/app/components/Create/elements.tsx
- packages/app/src/app/components/Create/utils/api.ts
- packages/app/src/app/overmind/internalActions.ts
- packages/components/src/components/Badge/index.tsx
> feat: new template picker

- packages/app/src/app/utils/fuzzyMatchGithubToCsb.ts
Found the event. I put it in the wrong list
> remove unused event

- packages/sandpack-core/src/npm/dynamic/resolve-dependency.ts
I noticed we try to resolve absolute versions for absolute versions, that's a bit backwards because we already have the absolute version.
> perf: dont resolve semver if it's already absolute

- packages/app/src/app/constants.ts
- packages/app/src/app/pages/common/Modals/SurveyModal/index.tsx
Broken URLs replaced with new ones.
> fix: Typeform URLs

- packages/app/src/app/pages/VSCodeAuth/Prompt/index.tsx
Adds support for signing into Cursor
> feat: add support for signin in to cursor
