codesandbox/codesandbox-client

- packages/app/src/app/pages/common/Modals/MoveSandboxFolderModal/DirectoryPicker/SandboxesItem/index.tsx
The "Move Sandbox" model fetches collections (folders) for itself and caches that with the help of `Query from react-apollo`.
Problem: While using the dashboard, if you open the move modal through the context menu, it caches the collections at that point (in react-apollo's copy).
This means that when collections are updated in the dashboard (added or deleted in overmind state), it doesn't reflect in the move modal. The 2 states are out of sync and you see folders missing/or undeleted (as reported by @linqcan)
Ideal fix: Refactor Move modal from class component + react-apollo to hooks and overmind.
Hot/short fix (this one): Disable caching of collections in the Move modal using `fetchPolicy=network-only`. This means the Move modal always has the latest state of collections at the cost of …
> Avoid stale collections in Move Sandbox modal

- packages/app/src/app/overmind/effects/vscode/LinterWorker/index.js
Fixes issue with typescript and optional chaining: https://www.karltarvas.com/2020/04/07/typescript-no-unused-expressions.html
> fix optional chaining eslint

- packages/app/src/app/pages/Sandbox/Editor/Header/CollaboratorHeads/CollaboratorHeads.tsx
Fix a case where the collaborator heads don't update because `liveRoomInfo` doesn't update but `liveRoomInfo.users` does.
> Fix collaborator heads not updating

- packages/app/src/app/overmind/effects/vscode/LinterWorker/index.js
- packages/sandbox-hooks/url-listeners.js
Okay, 
So there is an issue with Vue not using `HashChangeEvent`, but rather `popState`: https://github.com/vuejs/vue-router/issues/1807. So this is actually not working in production now.
That means we have three approaches to solve this:
1. We detect if Vue is running
2. We detect if nothing is using a hash listener
3. We fire off both HashChange and popState in our `go` method
So my reasoning:
1. Having framework specific code in something as generic as `url-listeners` is not ideal
2. We would have to hack the browser API
3. If it works... most straightforward and least intrusive
Since router libraries will only listen to one of the events, I implemented 3. Tested with `vue-router` and `react-router-dom`. 
We do not need the intercepting click here anymore, which fixes the original …
> Vue router fix

- packages/app/src/sandbox/eval/transpilers/babel/convert-esmodule/__snapshots__/index.test.ts.snap
- packages/app/src/sandbox/eval/transpilers/babel/convert-esmodule/index.test.ts
- packages/app/src/sandbox/eval/transpilers/babel/convert-esmodule/index.ts
- packages/app/src/sandbox/eval/transpilers/babel/convert-esmodule/syntax.ts
We hoist imports to the top, as that is how imports are treated. However, imports need to be below exports that are defined above them, this makes sure that happens.
Fixes https://github.com/tensorflow/tfjs/issues/3889
> Keep imports below converted exports

- packages/app/src/app/components/Notifications/notifications/SandboxInvitation.tsx
Now you can still open the sandbox of the invite, even if you've read it.
> Fix sandbox read notification click

- packages/common/src/utils/is-preact-10.ts
If no dependencies or devDependencies were present an error was shown in the console
> fix preact console error

- packages/common/src/themes/codesandbox-black.js
The warning squiggles were red, which made them look like errors. Now they are yellow to make them look like warnings.
> Make warning squiggles yellow

- packages/app/src/app/overmind/effects/live/index.ts
This makes sure that we don't spam the server when CodeSandbox returns a 503. It also adds more variability in connecting so not all users reconnect exactly at the same time.
> Don't spam the server when CodeSandbox returns 503

- packages/app/src/app/overmind/effects/vscode/LinterWorker/index.js
- yarn.lock
`vue` dependency version in `package.json` is usually a range (e.g. `^2.6.11`), but `semver.gte()` only supports plain versions. We should use `semver.gtr()`, which also supports ranges. 
Tested that this change configures the correct `eslint` rules for the sandbox's Vue.js version.
L.E. I added the `yarn.lock` changes to this PR as I get them consistently when running `yarn install`.
Fixes #4994
> Fix Vue.js version comparison

- packages/app/src/app/overmind/namespaces/profile/actions.ts
- packages/app/src/app/pages/Profile/Showcase/NoSandboxAvailable.tsx
Bug fix.
When a user goes to `/u/:username` and `username` doesn't exist, they get a blank page.
We show the `NotFound` component to the user when `getProfile` fails - regardless of the reason.
1. Visit `/u/aarthurdennerr` for example - [production link](https://codesandbox.io/u/aarthurdennerr);
1. Verify that we show the `NotFound` component instead of a blank page;
1. Visit `/u/arthurdenner` for example - [production link](https://codesandbox.io/u/arthurdenner);
1. Verify that we show that the user doesn't have a showcased sandbox yet.
- I've added two different `try/catch` because if `getProfile` fails, we show the `NotFound`, but if the `getSandbox` fails, we want to show the profile still. Are you okay with this behaviour or should we change it?
- I've changed the text when the user …
> fix(profile): redirect to NotFound page when profile request fails

- packages/app/src/app/overmind/internalActions.ts
This cannot be the case anymore, as the server lets the client know when a user is not signed in anymore using a cookie.
> Remove outdated session expired error message

- packages/app/src/app/pages/Sandbox/Editor/Content/EditorToast.tsx
The border radius will now be at the top left, instead of bottom left:
> Fix styling of the following name tag

- packages/app/src/app/pages/Profile/Showcase/NoSandboxAvailable.tsx
- packages/app/src/app/pages/common/Modals/SelectSandboxModal/index.tsx
Feature? It's a leftover from #4998 that I noticed today. 🤦🏽‍♂️ 
There is no way to select a sandbox to be showcased in case the user doesn't have one.
There is a button to select one sandbox to be showcased when the user doesn't have one.
1. Visit your profile;
1. Select a sandbox as showcased;
1. Verify that you're able to change the showcased sanbox;
1. Delete the showcased sandbox;
4. Verify that you're able to select a sandbox to be showcased.
> feat(profile): allow selection of showcased sandbox when none is selected

- .all-contributorsrc
- README.md
- packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Explorer/ExternalResources/google-fonts.ts
Feature (minor addition).
User can now add the Inter font as an external resource (via the Google Fonts picker).
1. Visit an existing sandbox;
2. Select _Inter_ via the Google Fonts picker;
3. Inter is successfully added as an external resource, and is functional as intended.
Inter was only added to Google Fonts on the 6th of March, so I presume it was unintentionally left out. But if, for whatever reason, you prefer not to include it – that's totally fine 😄
> feat: add Inter to google font picker

- packages/app/src/sandbox/eval/transpilers/babel/convert-esmodule/__snapshots__/index.test.ts.snap
- packages/app/src/sandbox/eval/transpilers/babel/convert-esmodule/index.test.ts
- packages/app/src/sandbox/eval/transpilers/babel/convert-esmodule/index.ts
`escope` was wrongly configured to not treat block scoped vars (`let`, `const`) as block-scoped. This fixes that issue.
> Fix resolving ES6 scopes in esconvert

- packages/homepage/content/docs/8-ci.md
Adds a note on how CI only works in private repos
> add public repo note in CI docs

- packages/app/src/app/pages/Dashboard/Components/Sandbox/SandboxCard.tsx
Moved Sandbox Thumbnail into a component.
Sandbox thumbnail logic:
0. Use template icon as starting point and fallback
1. Use `sandbox.screenshotUrl` if it can be successfully loaded (might not exist)
2. If `sandbox.screenshotOutdated`, lazily load latest screenshot. Switch when image is loaded.
FAQ: Why don't we directly load the latest screenshot?
Generating the latest screenshot takes a few seconds, so it's faster to use the cached `screenshotUrl` and then lazily fetch the latest one.
> Dashboard: Lazily update stale sandbox thumbnails

- packages/app/src/sandbox/compile.ts
> Make @babel/runtime dependency not pinned

- packages/app/src/sandbox/eval/transpilers/babel/convert-esmodule/index.ts
- packages/common/src/utils/dependencies.ts
Some files which have over 5.000 exports caused our generated to create a huge line of 
```
exports.a = exports.b = exports.c = exports.d = void 0;
```
This in itself is not a problem, but when another AST parser goes over this it will crash with a `Maximum call stack size exceeded`. It will be worth checking how other converters like TypeScript handles this.
Fixes #5022
> Fix large amount of exports causing stack size exceeded error

- packages/app/src/sandbox/eval/tests/jest-lite.test.js
- packages/app/src/sandbox/eval/tests/jest-lite.ts
- packages/sandpack-core/src/runner/eval.ts
Explanation (copied from code base):
```
/**
* In this function we actually set some globals on the global window. This is because there are modules out
* there that try to overwrite some globals that we try to set. For example, this code won't work:
*
* ```js
* const test = 5;
* ```
*
* if we add test to the scope in the function:
*
* ```ts
* function evaluate(test) {
*   const test = 5; // <- Error!
* }
* ```
*
* Because of this, we have to put these globals on the global window. The big disadvantage of this is that
* we cannot run these tests in parallel. If we would want to do that we could introduce the globals in separate
* scope (separate function) that wraps the inner function, like this:
*
* ```ts
* (function jestGlobals(test) {
*   (function evaluate() {
*     const test = 5; // …
> Fix jest globals

- .github/ISSUE_TEMPLATE/BUG.md
An update of the links to the Code of Conduct and Contributing Guidelines contained within the issue tracking template. Whilst not a massive change, it does ensure some consistency.
Currently, both the Code of Conduct and the Contributing Guidelines links point to documents held within the `electron` repository.
These links now correctly point to the `codesandbox` versions of these documents.
1. Create a new issue
2. Open the Contributing Guidelines link in a new tab; verify the document is the `codesandbox` version and not the `electron` version
3. Open the Code of Conduct link in a new tab; verify the document is the `codesandbox` version and not the `electron` version
> Update links within issue template

- packages/app/src/app/pages/common/Modals/ShareModal/index.tsx
Typo fix
Typo is fixed
This is a simple copy change, I haven't spin up the project for this
> Fix typo in a share modal copy

- packages/app/src/app/overmind/namespaces/editor/actions.ts
In live mode the preview would update automatically for the user, even if they disabled it. This fixes it/
> Honor live preview setting in live mode

- packages/app/src/app/overmind/namespaces/live/liveMessageOperators.ts
Whenever a third user would type, the cursor of the second user would become hidden. This fixes that.
> Fix new cursor of new user overwriting existing cursors

- packages/components/src/components/Tags/Tag.tsx
It was the only place where we use `react-icons` in `@codesandbox/components`, and it's not marked as a dependency. We'll have to check the test snapshot to see if it changes styling significantly.
> Remove dependency on react-icons in @csb/components

- packages/app/src/sandbox/status-screen/indicator-screen.html
- packages/app/src/sandbox/status-screen/loading-screen.html
- packages/app/src/sandbox/status-screen/run-on-click-screen.html
I noticed today that the bundler took a long while to load because it was downloading all Inter fonts. With this change we'll only download 2 specimen for in the bundler, and I think it will not block the loading of the loading screen.
> Move Inter loading to Google Fonts in Sandpack

- packages/app/src/app/pages/Dashboard/Content/routes/Settings/TeamSettings.tsx
Makes more apparent that you have an Invite URL by changing it from an icon on the left to a button:
this was it before:
> Move "Copy Invite URL" to button

- packages/app/src/app/pages/Sandbox/SearchDependencies/SearchBox.tsx
Accessiblity Issue
On an light theme, search box text is difficult to read.
Github Theme: 
Use theme colors. 
Github Light: 
Codesandbox Black:
1. Switched theme to light and opened dependency modal
> fix(dependency): add theme support on searchbox

- packages/components/src/components/Icon/index.tsx
We have `color` prop on Icon that isn't connected to theme. We don't use this anywhere in the app.
Suggested approach instead:
```jsx
<Icon name="github" css={{ color: 'blues.500' }} />
```
> Icon - remove redundant color prop

- packages/app/src/app/pages/Dashboard/Components/Selection/ContextMenus/SandboxMenu.tsx
Currently, to delete a template we let you do it if the template's team is null and this resulted in people having a button to delete recently used templates that had no team but also had no author id either
These are Github templates you cannot delete
This adds a check for that
closes #5026
> Add extra validation for showing delete template

- packages/sandpack-core/src/transpiler/transpilers/webpack/index.ts
This will make binary loaders from webpack (like `arraybuffer-loader`) work.
> Create binary before sending it to webpack loader

- packages/app/src/app/pages/Sandbox/SearchDependencies/Dependency.tsx
Sometimes when importing a sandbox the dependencies object in the package.json empty and that will crash when trying to see what version you have installed
closes #5120
> fall back to empty object if deps object does not exist

- docker/Dockerfile
- docker/run-docker.sh
- package.json
This will rather start the client process in a tmux session, which can be accessed from within VSCode. It is inserted behind the `start:dev_api`.
It does not matter if process is already running or not. If it is running the `start:dev_api` command will open the existing session. If not, it will start the process and open the tmux session.
To exit a tmux session you use `ctrl + b`
> allow access to process from within VSCode

- packages/app/src/app/overmind/namespaces/dashboard/state.ts
- packages/app/src/app/pages/Dashboard/Components/Filters/SortOptions/index.tsx
Adds the possibility to order sandboxes in the dashboard by views
> Add order by views on dashboard

- packages/app/src/sandbox/index.js
- packages/common/src/config/env.ts
- packages/common/src/types/global.d.ts
- [POC: Sandpack Service Worker to Resolve Relative Files](https://github.com/codesandbox/codesandbox-client/pull/5137)
- **[Step 1: Do not register webpack service worker in Sandpack](https://github.com/codesandbox/codesandbox-client/pull/5138)**
- [Step 2: Setup webpack build for sandpack service worker](https://github.com/souldzin/codesandbox-client/pull/1)
This will do undesirable caching, since the same host is used for various projects. Also, it will block us from using a service worker for handling relative resources.
- See the POC above for more context :smile:
Currently a service worker is always registered to optimize asset loading with caching. But! Since the same service worker can be used for multiple projects, this can be problematic. It will also conflict with using a …
> Step 1: Do not register webpack service worker in Sandpack

- packages/app/src/app/pages/Profile2/ShowcaseSandbox.tsx
We add an "Open sandbox" button on the showcased sandbox. Aaaaand we inject a "Open Sandbox" watermark/button on the server for non-pro users as an anti-phishing effort. Some users end up getting both of these 🤡 
Added a check for Pro users to avoid duplicate buttons + Moved delete to the top right so that it's not on top of the embed button
> Profile bugfix - Add pro check to avoid double watermark

- packages/app/src/app/pages/Profile2/AllSandboxes.tsx
For folks without showcased sandboxes or pinned sandboxes, the vertical alignment can look off. Fixed that.
> Profiles bug fix - Fix vertical alignment for new profiles

- packages/app/src/app/pages/Profile2/ProfileCard.tsx
Bug fix.
The following workflow breaks the app:
- Edit profile
- Cancel
- Edit profile
The `bio` is set to an empty string if `user.bio` is falsy (`null` in this case).
We can fix this in the `Textarea` component using `defaultValue ||  ''` as its initial state.
Let me know if you prefer this fix instead.
1. See current behaviour.
> fix(profile): apply default value to user bio on cancel

- packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Explorer/Files/DirectoryEntry/Entry/EditIcons/ErrorBoundary.tsx
- packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Explorer/Files/DirectoryEntry/Entry/EditIcons/index.js
- packages/common/src/components/Tooltip/index.tsx
It turns out this issue is when you have google translate on, and it's actively translating the page into another language
What I did is find the root cause and set a boundary around it. This doesn't really seem fixable unless we change to the new tooltips that are also more accessible, but that would require a rewrite of the explorer that is already supposed to happen.
This is not the perfect solution as it will still crash that part of the app, but not the page and the part of the app is pretty small.
Video shows before and after
closes #5243
closes #5001
closes #5015
closes #5058
closes #5070
closes #5061
closes #5086
closes #5190
closes #5134
closes #5194
closes #5192
> Fix remove child bug

- packages/app/src/app/overmind/namespaces/workspace/actions.ts
We already do this in dashboard, but not in editor. Copied the implementation
> Bugfix: Show error from the server for Always On in Editor

- packages/app/src/app/pages/Dashboard/Content/routes/AlwaysOn/index.tsx
Tweak to the info icon size, just saw this one and thought it would be a nice one to quickly pick up.
Old:
New:
> Adjust the size of the info icon in Always On

- package.json
- yarn.lock
Esquery changed their API (in 1.2 or 1.3) to become esmodules, so the
export is suddenly { default: {} }, which eslint doesn't expect. We have to
pin esquery to v1.0.1 for now, but in the long run we need to update eslint as
it seems that eslint fixed this in v7.
> Pin esquery to v1.0.1 to fix eslint

- packages/common/src/templates/vue.ts
The public file was not marked as an HTML entry so when changed it did not reflect on the preview
closes #5285
> add public/index.html as entry

- packages/app/src/app/pages/Dashboard/Content/routes/Settings/TeamSettings/WorkspaceSettings.tsx
```js
const created = team.users.find(user => user.id === team.creatorId);
```
^ This is empty when the creator is no longer part of team.
Nice to have: If `created` is empty, fetch the creator information from the public API
Fixes https://github.com/codesandbox/codesandbox-client/issues/5301
> Dashboard settings - dont show created by the person who left

- packages/app/src/app/pages/Pro/getExpiringDate.ts
- packages/app/src/app/pages/Pro/index.tsx
We had an issue that no matter if you had a monthly or yearly subscription on the expiring page we would always show yearly
This fixed that by checking and if it's monthly checks the day the user subscribed, the calendar month and adds one to it.
For example, someone who subscribed on the 12th of January would see:
On Monthly: 12 of Februray
On yearly: 12 January
> Fix date of expiring for monthly users

- packages/app/src/app/pages/Dashboard/Header/index.tsx
- packages/app/src/app/pages/Sandbox/Editor/Header/index.tsx
It turns out that we redirect within `create-react-app` but since the homepage is not in `create-react-app`, it doesn't work. We need to use an `a` tag to make the page opening go outside of the `create-react-app` framework.
> Fix redirect to /s from the dashboard when clicking the logo

- packages/common/src/components/SandboxCard/fixtures.ts
- packages/common/src/templates/docusaurus.ts
- packages/common/src/templates/helpers/is-server.ts
- packages/common/src/templates/icons.ts
- packages/common/src/templates/index.ts
- packages/homepage/content/docs/1-x-faqs.md
[NEEDS TO BE ADDED TO THE BACKEND BEFORE MERGE]
This adds all the stuff required in our code to get the new Docusaurus template up and going
closes #5135 
Also merge https://github.com/codesandbox/codesandbox-importers/pull/104
> Add Docusaurus official template

- packages/app/src/app/pages/Profile2/AllSandboxes.tsx
Hey 👋 
Bug Fix
When we close the `Upgrade to Pro` message on the Profile page it takes us to the `pro` pricing page. I am not sure if this is the intended behavior. Screen rec for the issue: 
https://www.loom.com/share/b23fe204f9c64455adea2859ff417196
To not redirect to the pricing page on clicking the close button.
https://www.loom.com/share/86d2f04677e543ac968cec403afb5939
1. Checked redirection with close button
2. Confirmed that clicking on banner still takes to the Pricing page
> fix(profile):prevent redirection on clicking close icon for upgrade banner

- packages/app/src/app/pages/Profile2/LikedSandboxes.tsx
Enhancement
Shows no messages but have active buttons as seen in below screenshot.
Shows no sandboxes message.
1. Tested with no liked sandboxes
2. Tested with Liked Sandboxes
____
Can we add a `.nvmrc` file?  Whenever opening a new session to run scripts, I need to manually use the node version for eg: `nvm use 10.22.1`
> fix(profile): show no sandboxes found message in Liked Sandboxes Page

- packages/common/src/utils/supports-new-react-transform.ts
This enables the new React transform for any React version, the reason behind this is that React doesn't require v17 to utilize the transform, eg. React v16 works too. The React team uses CodeSandbox CI to test, and their version is `0.0.0-abc` so it doesn't work for them all the time.
> Enable new React transform for every React version

- packages/app/src/sandbox/eval/presets/angular-cli/index.ts
- packages/app/src/sandbox/eval/presets/cxjs/index.ts
- packages/app/src/sandbox/eval/presets/dojo/index.ts
- packages/app/src/sandbox/eval/presets/vue-cli/v2.ts
- packages/app/src/sandbox/eval/presets/vue-cli/v3.ts
- packages/sandpack-core/src/preset/preset.test.ts
- packages/sandpack-core/src/preset/preset.ts
- yarn.lock
We now use transpilers for renaming `import` to `$csbImport` instead of string manipulation. 
Fixes #5079
> Stop using string manipulation for import renames

- packages/components/src/components/Menu/index.tsx
Issue was seen when you open context menu on sandbox cards that are located in the lower part of the screen while the dashboard is open.
Still not perfect, couldn't figure out how to position the reach menu component on top of the anchor. but at least the height is now computed based on the right height for the items (31px instead of 36px)
However, `React.Children` computes the dividers as well, hence we still have a slight offset, but at least it doesn't feel broken anymore) and depends on how many dividers the menu has.
We could make a fix by "meta" looking at the children and compute the dividers separately, but I wouldn't want to get a fragile implementation in the shared component.
> fix vertical position for context menu

- packages/app/src/app/components/CreateNewSandbox/CreateSandbox/SandboxCard/SandboxCard.tsx
- packages/app/src/app/components/CreateNewSandbox/CreateSandbox/SandboxCard/elements.ts
- packages/app/src/app/pages/Dashboard/Components/Sandbox/SandboxListItem.tsx
- packages/app/src/app/pages/Dashboard/index.tsx
- packages/common/package.json
- packages/common/src/theme/__snapshots__/theme.test.ts.snap
- packages/common/src/theme/breakpoints.ts
Dashboard - List View
- "Always-On" column replaced with a small green circle overlapping the sandbox image
- Sandbox name column wider
- Text overflow only when there's no room, removed fixed width
Sandbox templates list
- Text overflow only when there's no room, removed fixed width
- `title` attribute added so the full name is visible on hover (via browser default tooltip)
Breakpoints
- Found a 3px difference between sidebar toggle (770px) and main content going full width (767px)
> fix text truncate

- packages/common/src/utils/analytics/sentry.ts
This is related to the `Cannot convert undefined or null to object ` error and suggested here #5406 
Also removes chrome extensions disable in the code as that can be done in the UI as seen in the issue
> Disable timers in sentry

- packages/components/src/components/Menu/index.tsx
Background: Last week I solved one issue with the context menu rendering at a big offset on the dashboard, but it was still an approximation based on the number of menu items passed.
Problem with the current solution: computing based on the number of `children` does not work (eg: on profile page it still renders below the viewport) because a Fragment will be seen as a single child in the count.
Experimental solution:
- when a new menu is triggered with a change of position (x,y), the menu is set on visibility hidden and renders all its children
- on the next cycle, the ref should be set with the menu rendered and the height/width are taken from the DOM
Potential problems:
- Still a fragile solution, if for whatever reason the menu does not render on the first pass, the bounding rect …
> context menu position: ref + getBoundingClientRect

- packages/app/package.json
- packages/app/src/sandbox/compile.ts
- packages/app/src/sandbox/eval/presets/create-react-app/utils/reactPreset.ts
- packages/app/src/sandbox/eval/transpilers/react/refresh-transpiler.ts
- packages/sandpack-core/src/manager.ts
- packages/sandpack-core/src/transpiled-module/hmr.ts
- packages/sandpack-core/src/transpiled-module/transpiled-module.ts
- yarn.lock
This PR does three things:
1. It calls `module.hot.invalidate()` if the export structure of a module changes within React Refresh context
2. It adds `module.hot.invalidate` functionality 🙂 
3. Stops showing `Aw Snap` message on Sandpack
This will make React refreshes when exports change much more stable, and will in general improve the experience for Sandpack.
> Fix React Refresh boundary export changes

- packages/app/src/sandbox/eval/transpilers/babel/index.ts
- packages/app/src/sandbox/startup.js
Babel Worker is memory expensive. This will make sure that we only spawn a single worker in Sandpack, because Sandpack is usually rendered multiple times in a single window.
> Only create a single babel worker when in sandpack

- packages/common/src/utils/host.ts
This will ensure that the local Docker environment will work, as this env var is not set in that environment.
> Make host fallback to codesandbox.test

- packages/app/package.json
- packages/codesandbox-api/package.json
- packages/codesandbox-api/src/dispatcher/index.ts
- packages/common/package.json
- packages/components/package.json
- packages/executors/package.json
- packages/sandbox-hooks/package.json
- packages/sandpack-core/package.json
- packages/sse-hooks/package.json
- standalone-packages/sandpack/package.json
- standalone-packages/sandpack/yarn.lock
It turns out that if you open CodeSandbox from an external page,
window.opener will be set as well. We need to mark it as standalone
manually in this case.
Fixes https://github.com/codesandbox/codesandboxer/issues/72
> Do standalone check for all codesandbox.io domains

- packages/app/src/app/pages/common/Modals/AddPreset/index.tsx
Enhancement
We can create a custom preset with only spaces
Disable button if the name is empty.
1. Tested spaces
2. With valid name
3. No value
> fix: disable button on empty preset name

- packages/app/src/app/pages/Sandbox/Editor/Header/SandboxName/elements.ts
Closes #5490 
Text not visible in light themes
make text compatible to theme
1. Tried with different themes. 
**Night Owl Light:** 
**Github Light**
**Cobalt2**
**CSB Black**
___
Kind of naive question, but isnt it possible to do something like this?
```
background: ${props => props.theme['input.foreground']};
```
I was seeing a issue in editor while doing so.
> fix: theme support for sandbox name input

- packages/app/src/app/pages/common/Modals/ShareModal/index.tsx
- packages/app/src/embed/components/Sidebar/FileTree/elements.js
Bug Fix
File Tree ui for embed URLs in share modal shows distorted UI, the sizes of items are way too big. Check below screenshot: 
Fixed the UI to match embed file tree styles. 
https://www.loom.com/share/65d77f64bd0649a69416a04b1de9ed89
1. Tested on a large application with nested folders
2. Tested both embed UI and share modal UI.
> fix: module selection ui in share option

- packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Explorer/Files/DirectoryEntry/Entry/index.tsx
In this particular case `onClick` can be `undefined`, we should enable `strictNullChecks` to catch these cases at build time.
Related issue: https://sentry.io/organizations/codesandbox/issues/2233030390/?project=2071895&referrer=slack
> Add explicit check on onClick

- packages/app/src/app/overmind/namespaces/editor/actions.ts
- packages/common/src/types/index.ts
- packages/sandpack-core/src/npm/dynamic/fetch-protocols/npm-registry.ts
Apparently that's not always the case 😄
> Remove assumption that dist-tags is always set in npm manifest

- packages/app/config/webpack.prod.js
With private npm we need to ensure that we always get the latest API
response back, right now we cache /api/v1/npm_registry/... in the SW,
which sometimes makes private npm packages return old results.
> Remove SW caching of API urls in sandbox

- packages/app/src/sandbox/startup.js
Actually, if you load that url from `new.csb.app` it will load `new.csb.app/static/...`. This way we actually load the js from the root.
> Preload babel.min.js from root

- packages/app/src/app/pages/Dashboard/Sidebar/index.tsx
**Sidebar dashboard tweak**
It was just a pixel, but once you see it you can't unsee it
> fix(dashboard sidebar): align folder icon too all items of the menu

- packages/codesandbox-api/src/dispatcher/host.ts
Fixes #5575
SSE and standalone sandboxes were getting this error:
Because sse hooks doesn't override `process`.
> Fix console.log in SSE and static sandboxes

- packages/app/src/sandbox/eval/transpilers/babel/convert-esmodule/__snapshots__/index.test.ts.snap
- packages/app/src/sandbox/eval/transpilers/babel/convert-esmodule/index.test.ts
- packages/app/src/sandbox/eval/transpilers/babel/convert-esmodule/index.ts
Our esmodule converter for node_modules didn't take `export const [a, b] = c()` into account, with this change it does.
> Allow array exports

- packages/app/src/app/overmind/effects/deployment/githubPages.ts
PUBLIC_URL for GH Pages should always be lower cased.
> Always use lowecase username for public_url (CRA)

- packages/app/src/sandbox/eval/tests/jest-lite.ts
This is a fix for dispatching events in tests, however, we should find a
solution to mock all globals with the JSDOM equivalent for a longer term
solution.
Fixes #5605
> Add Event to the test globals

- packages/app/src/sandbox/eval/presets/vue-cli/index.ts
- packages/app/src/sandbox/eval/presets/vue-cli/v2.ts
- packages/app/src/sandbox/eval/transpilers/base64/index.ts
Bug fix with vue v2 svg imports #1664 
Closes #1664 
SVG Import returns svg content
SVG Import returns a data-url of the svg
1. Run the linked sandbox in the issue
2. It renders the svg properly 🎉
> Fix: svg imports in vue 2 should return a url

- packages/app/src/sandbox/eval/presets/create-react-app/utils/reactPreset.ts
- packages/app/src/sandbox/eval/transpilers/base64/mimes.json
Fixes #5424 
Returns content of markdown files
Returns url of markdown files
1. Open the example
> Use data-url for markdown assets in react preset

- packages/app/src/app/overmind/namespaces/git/actions.ts
I'd like your opinion on this @christianalfoni, I think this is better.
With this change we change where you get redirected to when you create a repo from the sandbox. Normally you would get redirected to the fork of the imported repo, with this change you directly go to the imported repo. I think this is important for a couple reasons:
1. When you import a repo, you'd expect to go to the sandbox linked to it
2. You can share this sandbox with others to contribute, and it stays up to date with GitHub
3. It's a bit less flaky, I've seen in support the fork going wrong sometimes for private sandboxes
4. People now still have the choice to fork when they go to the repo sandbox, but at least they know what the "root" sandbox is and we have a good explanation of it in the sidebar.
While …
> Redirect to sandbox Git page instead of forked sandbox on creation

- packages/app/src/app/index.html
This prevents the browser navigation (back & forward) on horizontally swipe into the code editor. There was a previous fix, however, it was only working in the Safari and Chrome browser, while Firefox users were still facing the problem (which is quite annoying).
Apparently, moving `overscroll-behavior-x` property to the `html` tag fixed it, without any downside for the other browsers that were working before.
Closes #5054
> fix(browser window): prevent back & forward navigation on horizontally swipe

- packages/app/src/app/graphql/types.ts
- packages/app/src/app/overmind/effects/api/index.ts
- packages/app/src/app/overmind/effects/gql/dashboard/mutations.ts
- packages/app/src/app/overmind/namespaces/profile/actions.ts
- packages/app/src/app/pages/Profile/ProfileCard.tsx
- packages/common/src/types/index.ts
Requires https://github.com/codesandbox/codesandbox-server/pull/315 to be merged and deployed first.
* Removes REST API call for updating profile (bio and social links)
* Makes use of new Graphql mutation `UpdateCurrentUser` to update profile info (username, display name, bio, social links)
* Alerts user with modal when changing username, so that they know they'll need to update their external links
See it in action: https://www.loom.com/share/813da73b839141a8a16f1cfde85e73b0
I think I did all the Graphql updating okay but let me know if I missed anything since this is my first time contributing to the client repo.
> Allow users to change username and display name

- packages/app/src/app/pages/Dashboard/Content/routes/Settings/TeamSettings/RegistryForm.tsx
- packages/app/src/app/pages/Dashboard/Content/routes/Settings/TeamSettings/RegistryPreset/Artifactory.tsx
- packages/app/src/app/pages/Dashboard/Content/routes/Settings/TeamSettings/RegistryPreset/Azure.tsx
- packages/app/src/app/pages/Dashboard/Content/routes/Settings/TeamSettings/RegistryPreset/Custom.tsx
- packages/app/src/app/pages/Dashboard/Content/routes/Settings/TeamSettings/RegistryPreset/GitHub.tsx
- packages/app/src/app/pages/Dashboard/Content/routes/Settings/TeamSettings/RegistryPreset/Npm.tsx
- packages/app/src/app/pages/Dashboard/Content/routes/Settings/TeamSettings/RegistryPreset/index.ts
This makes it far easier to set up an npm registry with Artifactory and Azure DevOps. It will give you exactly the form fields that the configuration wizard of the private npm requires you to fill in:
> Add custom npm registry form presets

- packages/common/src/sandbox/modules.ts
We used to return everything starting with the name of a directory in
`getModulesAndDirectoriesInDirectory`. This isn't right, because if you
have this:
- /app
- /app/index.js
- /app-components
`getModulesAndDirectoriesInDirectory(..., ..., '/app')` would also
include `/app-components`. Luckily we only do this client side, so when
someone deletes the folder `/app`, `/app-components` doesn't get
deleted. But it's confusing that the folder gets hidden. This fixes that.
I tested it by:
1. Creating 4 folders, 2 in the root and 2 in a subfolder
2. Deleting the subfolder
3. Verify that all folders in the subfolder are deleted, and other subfolder is still there.
> Don't delete files with similar name optimistically

- packages/app/src/app/pages/Dashboard/Sidebar/index.tsx
Addresses [this issue](https://www.notion.so/28294a4d1f924b20b73533ab5b8c2419?v=adac55ed225d4d48a19a0c73579a02d0&p=9b6dcc7be3154654804ecef4efb77fa3) from the big polish list 💅 
In the sidebar it was using the text `TeamAvatar` rather than the Google or Github photo in the personal workspace.
I've done a frontend fix to detect whether we're in the personal workspace, and if so, just use the `user.avatarUrl`.
However, I think there's something going wrong potentially with the server because for the personal `Team` that is created on sign up, it isn't pulling through the Github or Google URL from the `User` or `PendingUser`, so I'll have a look at fixing that as well.
Before ☹️
After 🎉
> Use user avatarUrl in sidebar if in personal workspace

- packages/app/src/app/overmind/utils/items.ts
Bug Fix: Currently not all icons are shown when loading
See video on polish list https://www.notion.so/28294a4d1f924b20b73533ab5b8c2419?v=adac55ed225d4d48a19a0c73579a02d0&p=a6e82222882c42389623726e9460cd45
Icons are missing in loading skeleton
All missing icons are now being displayed in the loading skeleton
> Fix missing editor icons in load state

- packages/app/src/app/pages/Dashboard/Content/routes/Discover/Curate.tsx
- packages/app/src/app/pages/Dashboard/Content/routes/Discover/index.tsx
> Bugfix: Discover collections should not shuffle on re-render

- packages/app/src/app/overmind/effects/api/index.ts
- packages/app/src/app/overmind/namespaces/editor/actions.ts
Relates https://github.com/codesandbox/codesandbox-server/issues/316 and https://github.com/codesandbox/codesandbox-server/pull/340
In order to allow users (who do not have personal pro) to import private repos into a team they are part of that does have team pro, we need to be able to tell what the active team is. This param was being sent in `forkSandbox` but not via the normal static Github URL import (`/s/github/user/repo`).
> Send active team id to server for github imports

- packages/app/src/embed/index.html
The font that we were loading in the embed wasn't actually loaded
because it wasn't included in the html. Now it is, so the character
width calculations of the embed should be fixed.
> Fix character width issues in embed

- packages/app/src/app/components/WorkspaceSelect/WorkspaceSelect.tsx
- packages/app/src/app/overmind/namespaces/dashboard/actions.ts
- packages/app/src/app/pages/Dashboard/Content/routes/Settings/TeamSettings/WorkspaceSettings.tsx
- packages/app/src/app/pages/Dashboard/Content/routes/Settings/UserSettings/WorkspaceSettings.tsx
- packages/components/src/components/Avatar/index.tsx
Allow user to change avatar in personal team workspace.
@siddharthkp @DannyRuchtie I think now I am conflicted because it would make sense to allow name and username edit here. But I don't think it should necessarily be moved out of the sidebar because that is historically where users could do that. Should we have it in both places? Or moved it all to personal workspace settings? Or only have avatar upload in personal workspace settings for now?
> Allow user to change avatar in personal team workspace

- packages/app/src/app/pages/Dashboard/Components/CommunitySandbox/CommunitySandboxCard.tsx
`author` can be `null`
```diff
- author.username && 
+ author?.username &&
```
> Fix: Handle anonymous author in discover page

- packages/app/src/app/pages/Sandbox/Editor/Header/SandboxName/elements.ts
- packages/app/src/app/pages/Sandbox/Editor/Header/SandboxName/index.tsx
It improves the transition between states on the Rename Sandbox component.
https://user-images.githubusercontent.com/4838076/117943778-67f0af80-b304-11eb-9ca6-cb4543043fa2.mov
https://user-images.githubusercontent.com/4838076/117943722-59a29380-b304-11eb-804c-a31848ec213c.mov
> fix(rename sandbox): refactor to turn its transition smoother

- packages/app/src/app/pages/Sandbox/Editor/Workspace/SignInBanner.tsx
Simply deleted z-index row because it didn't affect anything but caused bug #5751.
It's a fix of a bug that I've opened as #5751 issue.
Pop-up that's being rendered by right-clicking at bottom of workspace is behind of "Sign in" banner and affecting UX.
"Sign-in" banner doesn't have `zIndex: 999` in styles now and it implements right behavior. Right-click at the bottom of workspace as unauthorized user are not causing z-index bug anymore.
I didn't run locally whole project. I just made this:
1. Open Chrome devtools and look for React component name.
2. Clone repo and find this React component in code.
3. Delete zIndex: 999 row.
4. It was impossible to mismatch the component because of unique component name.
> Fix z-index bug #5751

- packages/common/src/components/Preview/index.tsx
- packages/homepage/content/docs/2-api.md
- packages/homepage/content/docs/2-embedding.md
- packages/homepage/content/docs/2-importing.md
- packages/homepage/content/docs/2-tests.md
- packages/homepage/content/docs/5-secrets.md
We already use [`gatsby-remark-embedder`](https://github.com/MichaelDeBoey/gatsby-remark-embedder) in some places, but we're not using it fully (yet).
> chore: use `gatsby-remark-embedder` fully to transform all embeds in docs

- packages/app/package.json
- yarn.lock
I added this for the remote development environments, but since we're not using them (yet), and one of its dependencies (`node-pty`) has issues installing on some environments, let's remove it for now.
Fixes #5808 .
> Remove stmux dev dependency for now.

- packages/app/src/app/overmind/effects/git/export-to-github.ts
- packages/app/src/app/overmind/effects/http.ts
Fixes https://github.com/codesandbox/codesandbox-server/issues/389
Fixes https://github.com/codesandbox/codesandbox-client/issues/4504
https://www.loom.com/share/025f51b436f44586b9b9469e7fe778e9
We weren't using `blobToBase64` in `export-to-github` so when the binary files were going to the git importer, it was sending the URL of the asset (like `https://rawcdn.githack.com/sbinlondon/csb-vue-test/669c16821bf80094ae68409afd690ed92fe9cc85/src/assets/logo.png`) rather than the base-64 encoded string it should have done.
The linter fussed at me for using an await in a loop so please let me know if we need to update this to a `Promise.all` or if it's ok to do `eslint-disable`.
Also still need to test and make sure that syncing files doesn't break it again/we are using `blobToBase64` everywhere …
> Use blobToBase64 when exporting to github

- packages/app/src/sandbox/compile.ts
- packages/app/src/sandbox/eval/presets/vue-cli/index.ts
- packages/app/src/sandbox/eval/transpilers/babel/worker/babel-worker.js
- packages/app/src/sandbox/eval/transpilers/babel/worker/utils/normalize-name.test.ts
- packages/app/src/sandbox/eval/transpilers/babel/worker/utils/normalize-name.ts
- packages/common/src/templates/configuration/babelrc/index.ts
Currently we use the vue-preset-env for babel, but as it needs to download all plugins (that are already in @babel/standalone), it slows down compilation quite significantly. This PR changes this behaviour to use as much of the pre-bundled and browser optimised transforms as possible.
Based on the preset that was used before https://github.com/vuejs/vue-cli/blob/dev/packages/%40vue/babel-preset-app/index.js
> Vue performance improvements

- packages/app/src/sandbox/eval/transpilers/sass/worker/sass-worker.js
Fixes resolution of sass modules if there's a `path` in the request
Fixes #4865
> Fix sass resolver

- packages/app/package.json
- packages/app/src/app/overmind/namespaces/editor/actions.ts
- packages/app/src/app/overmind/namespaces/editor/state.ts
- packages/app/src/app/pages/Sandbox/Editor/Header/SignInAd.tsx
- packages/app/src/app/pages/index.tsx
- packages/common/src/config/env.ts
- packages/homepage/gatsby-browser.js
- packages/homepage/package.json
- yarn.lock
This introduces the implementation of the AB framework across the apps (homepage and editor) in order to use the same user-id in both environments and it also persists the id from an anonymous user to a logged-in status.
We're going to ship an **A/A** test so that we'll able to make sure that Amplitude is getting the right values in the production, so then we'll be able to release a new one (A/B)
---
It also takes the opportunity to release a redesign for the sign-in banner at the very top in the editor, which is part of the next experiment.
> Feat/ab framework implementation + redesign sign banner

- packages/app/src/app/overmind/namespaces/editor/actions.ts
- packages/app/src/app/overmind/namespaces/editor/state.ts
- packages/app/src/app/pages/Sandbox/Editor/Header/SignInAd.tsx
Let's run our first experiement! 🚀 
---
This changes the trigger to show the sign-in ads on top of editor for anonymous users:
- A version: keep the same, runs after 3 minutos;
- B version: run after 3 changes in the editor;
> feat(ab experiment): change trigger to show sign-in ads in the editor

- packages/common/src/config/env.ts
You were absolutely right about the method to determine the env 😓
> fix(ab env): check the current host to determine the env

- packages/homepage/content/docs/2-custom-npm-registry.md
We had wrong documentation on whether we support a `.npmrc` file, that has now been corrected.
> Change message on `.npmrc` file

- packages/sandpack-core/src/runner/eval.ts
This PR changes the logic where we overwrite setImmediate with a custom version that did not behave correctly.
Mainly wondering why we ever implemented this? (we can optionally polyfill this with a correct implementation if we want to)
Fixes #5878
> Don't overwrite setImmediate

- packages/app/src/app/components/ContextMenu/elements.ts
- packages/app/src/app/components/ContextMenu/index.tsx
- packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Explorer/Files/DirectoryEntry/DirectoryChildren/ModuleEntry.tsx
- packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Explorer/Files/DirectoryEntry/Entry/index.tsx
Implements some final touches to the esmodule url context menu item.
- Only show the item for ts, tsx, js and jsx
- Use the new codesandbox hostname
- Add the new badge
> Tweaks to copy as ESModule url context menu item

- packages/common/src/utils/metrics.ts
- packages/sandpack-core/src/manager.ts
Gets rid of the resolver measure warnings and probably also fixes a memory leak as these measures are kept in memory if not resolved which can happen quite easily as there's no cleanup call
> Fix measure warnings

- packages/app/src/app/pages/Client/Prompt/index.tsx
Bug fix.
When a user signs into CodeSandbox via Google or GitHub and they land on `https://codesandbox.io/client/login`, the deeplink of the button contains a `null` nonce causing the authentication in play.js to fail.
This PR changes the logic slightly so the loading state is visible based on whether `authClient` is null or not. 
1. Open play.js
2. Tap on "Sign in"
3. In Safari "Sign in" with a Google/GitHub account.
4. Once the web authentication has finished quickly tap on "Open on play.js"
5. As a result play.js prompts an error letting the user know that the sign in process didn't succeed.
> Show loading state in `client/login` if authToken is null

- packages/app/src/embed/components/Actions/index.js
- packages/app/src/embed/index.js
- packages/app/src/embed/logo.svg
Related to GRO-11
| A | B |
| - | - |
| ![Screenshot 2021-07-21 at 11 27 54](https://user-images.githubusercontent.com/4838076/126474544-bb7657e4-4ab1-48f3-a0a1-97f973b0460c.png) | ![Screenshot 2021-07-21 at 11 28 25](https://user-images.githubusercontent.com/4838076/126474616-50d1446c-c95e-4ebe-9ab7-cb3d3b633764.png) |
It implements the AB framework in the embed application, and then it also introduces a new experiment to test different wording in the embed call to action.
- `embed-open-wording`: @tromika is this name correctly? 
- @tromika could you please create this experiment in the production mode, with the proper description?
> feat(embed): wording experiment

- packages/app/src/app/pages/Sandbox/Editor/Workspace/Files/DirectoryEntry/validateTitle.js
- packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Explorer/Files/DirectoryEntry/validateTitle.js
This removes the client side validation of the $ in files and folders,
which was not needed anyway.
> Allow the '$' sign in folders and files

- packages/app/src/sandbox/startup.js
Currently we're preloading Babel, but this throws a warning in chrome as we don't always use this script within a couple seconds, sometimes it's only used on a hot reload or not at all.
Throws a warning
No more warning
> fix: Use prefetch for Babel instead of preload

- packages/app/src/sandbox/compile.ts
- packages/sandpack-core/src/cache.ts
- packages/sandpack-core/src/manager.ts
- packages/sandpack-core/src/transpiled-module/transpiled-module.ts
Currently the manager types suggest id is always defined, which is not the case for react-sandpack. This is a copy from #6021 but instead of only checking this in consumeCache this fixes the manager types to reflect what the state is in react-sandpack as there's some other places where this could cause issues.
Closes #6021 
Manager has an id property that is typed as stirng
Manager has an id property that is typed as string, null or undefined
> fix(sandpack): Manager typings should reflect that id can be undefined in case of react-sandpack

- packages/homepage/src/components/Navigation/index.js
Update job application count in header navigation on main site so it matches with the footer and current amount of roles available.
The old one says "2".
Now it's a "3".
1. Just updated the number from "2" to "3", nothing too complex.
> Update job application count in header navigation on main site

- packages/sandpack-core/src/transpiled-module/utils/query-path.test.ts
- packages/sandpack-core/src/transpiled-module/utils/query-path.ts
Currently loading the module `https://jspm.dev/npm:shopify-buy@2.11.0!cjs` fails due to it having an explanation mark, which we also use to specify loaders in imports...
Should we consider replacing this `!` with something else like `|>` or something, to make it more explicit and less likely we conflict with an actual character someone might use?
Throws an error
Does not throw an error
> Fix issues with jspm and loader import syntax conflicts

- packages/app/src/app/overmind/effects/deployment/githubPages.ts
- packages/app/src/app/overmind/effects/deployment/netlify.ts
- packages/app/src/app/overmind/effects/live/index.ts
To improve server deploys, we're extending the socket jwt ttl on the server side, but
we need to also extend how long we cache it on the frontend, or all this is pointless.
[Note: requires the server changes to be deployed first!!]
Extend how long we cache JWTs for to improve server deploys
Everyone reconnects at the same time and the DB doesn't like that
1. Extend TTL
2. Restart server
3. Beautiful smooth reconnect
> extend socket jwt ttl timeout

- packages/app/src/sandbox/eval/transpilers/babel/ast/__snapshots__/rewrite-meta.test.ts.snap
- packages/app/src/sandbox/eval/transpilers/babel/ast/collect-dependencies.ts
- packages/app/src/sandbox/eval/transpilers/babel/ast/rewrite-meta.test.ts
- packages/app/src/sandbox/eval/transpilers/babel/ast/rewrite-meta.ts
- packages/app/src/sandbox/eval/transpilers/babel/index.ts
Before this PR we didn't touch import.meta which resulted in errors as `import.meta` is only allowed in ESModules.
We don't do anything with import.meta resulting in errors.
Now sandpack replaces `import.meta` with `$csb__import_meta` which we insert as a module-scoped variable if `import.meta` is used.
Wrote some basic unit tests and tried out this failing sandbox https://codesandbox.io/s/quizzical-cerf-2ph7r?file=/src/index.tsx
Closes CSB-858
> fix(sandpack): Rewrite import.meta to $csb__import_meta

- packages/app/src/app/pages/Dashboard/Content/index.tsx
> fix(dashboard beta): feature flag wrapper over the component instead of the route

- packages/sandpack-core/src/npm/dynamic/fetch-npm-module.ts
- packages/sandpack-core/src/npm/dynamic/resolve-dependency.ts
Fixes a bug with transient dependencies that are urls to globs/git repos/...
See https://codesandbox.io/s/summer-glade-ztrpm for an example
Bug report https://twitter.com/acdlite/status/1427001781012373505
We always try to fetch the version from unpkg for transient deps
We check if the transient dep is remote and fetch from remote source instead
> Use semver for remote transient deps

- packages/app/src/app/overmind/effects/vscode/Workbench.ts
- packages/app/src/app/pages/Sandbox/index.tsx
*The big bug*
**Reproduce**
- Launch the editor in any template or sandbox;
- Go to the dashboard page using a navigation link;
- Relaunch the editor through a sandbox link or creating a new one;
**Bugs**
- The command palette no longer open;
- The Github link is the same as the previous session, causing a lot of inconsistency;
**What might be causing it?**
As long as the editor is in the browser memory, there are many stale states, and probably a few methods have not been triggering again in the second launch.
**Possible solution?**
- Reset the states on unmount component;
- Identify which methods need to be retriggered or be cleaned;
**Temp fix**
There is a proposal of a temporary workaround, which consists of checking in the second launch if the editor has loaded; if so, reload the …
> fix(editor): refresh editor in the second launch

- packages/app/src/embed/components/Actions/index.js
| A | B |
| - | - |
| ![Screenshot 2021-07-21 at 11 27 54](https://user-images.githubusercontent.com/4838076/126474544-bb7657e4-4ab1-48f3-a0a1-97f973b0460c.png) | ![image](https://user-images.githubusercontent.com/540472/129922818-b83634da-7dfb-45ab-bee8-85ab04519e85.png) |
As per https://linear.app/codesandbox/issue/GRO-37/embed-cta-iteration-2-open-and-fork
Experiment to test out the Open and Fork wording for the CTA button in embeds
> feat(embed): wording experiment iteration 2 - open and fork

- packages/app/src/sandbox/eval/presets/custom/index.ts
- packages/app/src/sandbox/eval/presets/vue-cli/index.ts
- packages/sandpack-core/src/npm/dynamic/fetch-npm-module.ts
Currently we call `manager.resolveTranspiledModule` in `fetchNPMModule#resolvePath`, but we forgot to skip the ignored extensions which adds unnecessary lookup times/latency and might actually cause issues like #6046 
#6046 was actually a pretty nice edge-case, apparently the packaged used has a `package.json.js` file 🤯  , see https://unpkg.com/browse/vue-instantsearch@4.0.0-beta.1/dist/vue3/es/package.json.js
Fixes #6046
Closes CSB-998
Tries different file extensions for fully resolved filepaths
Does not try different file extensions if filepath is already fully resolved
> fix: don't add file extensions to resolved filepaths

- packages/app/src/sandbox/eval/transpilers/babel/index.ts
- packages/app/src/sandbox/eval/transpilers/babel/worker/dynamic-download.ts
- packages/app/src/sandbox/eval/transpilers/babel/worker/evaluate.js
- packages/app/src/sandbox/eval/transpilers/babel/worker/utils/resolvePatch.ts
- packages/app/src/sandbox/eval/transpilers/vue/v2/css-loader/get-modules.ts
- packages/app/src/sandbox/eval/transpilers/vue/v2/index.ts
- packages/app/src/sandbox/eval/transpilers/vue/v2/loader.js
- packages/app/src/sandbox/eval/transpilers/vue/v2/style-compiler/loader.ts
- packages/app/src/sandbox/eval/transpilers/vue/v2/style-loader/index.ts
- packages/app/src/sandbox/eval/transpilers/vue/v2/style-loader/loader.js
- packages/app/src/sandbox/eval/transpilers/vue/v2/template-compiler/index.ts
- packages/app/src/sandbox/eval/transpilers/vue/v2/template-compiler/loader.ts
- packages/app/src/sandbox/eval/transpilers/vue/v2/template-compiler/modules/transform-require.js
- packages/app/src/sandbox/eval/utils/resolve-utils.ts
- packages/sandpack-core/src/manager.ts
- packages/sandpack-core/src/npm/dynamic/fetch-npm-module.ts
- packages/sandpack-core/src/transpiled-module/transpiled-module.ts
- packages/sandpack-core/src/utils/resolve-utils.ts
- yarn.lock
More preparation work to replace the resolver, this PR resolves a bunch of "hidden" race conditions in the vue 2 transpiler and replaces the readFile and isFile utils with their gensync equivalent
This should be the last PR before the big one to replace the resolver
> fix: Fix a bunch of race conditions and replace fs with gensync equivalent

- packages/homepage/src/screens/home/hero/Content.js
| A | B |
| - | - |
| ![image](https://user-images.githubusercontent.com/540472/127684919-b0434fb6-10fa-4897-b692-0e8c1ab591ab.png) | ![image](https://user-images.githubusercontent.com/540472/130437197-613f0774-cd60-4ffc-9745-0c084dfdf120.png) |
As per https://linear.app/codesandbox/issue/GRO-38/cta-variants-on-the-homepage-iteration-2-start-coding, let's start an experiment to test the start coding wording in the middle CTA on the homepage.
> feat(homepage): start coding wording experiment

- .github/workflows/stale.yml
Community update
Issues go stale after 90 days, but that can get frustrating for issues that are still relevant.
Update the stale-bot messaging to highlight that the `no-stale` label can be used to prevent state-bot from running.
> update stale bot

- packages/app/src/app/overmind/effects/vscode/LinterWorker/index.js
Resolves https://github.com/codesandbox/codesandbox-client/issues/3401#issuecomment-812929720
[Reference](https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/FAQ.md#i-get-errors-from-the-no-undef-rule-about-global-variables-not-being-defined-even-though-there-are-no-typescript-errors)
> lint: disable no-undef for TS files

- package.json
- yarn.lock
Speeds up our pre-commit hook. Note we couldn't reach for the latest version of `lint-staged` because it requires Node 12+.
We use lint-staged to check js/ts files before committing. Checking all changes runs quite efficiently, but it's a bit slow when trying to commit only some of your local changes.
Same as before, but faster. Was 50+ seconds for a partially committed file. Now it's sub 10 seconds on my machine. 🚀
Ran locally.
> chore: bump lint-staged

- packages/common/src/utils/url-generator.ts
https://github.com/codesandbox/sandpack/tree/tree/main -> `github/codesandbox/tree/main`
https://github.com/codesandbox/sandpack/tree/main -> `github/codesandbox/main`
> fix(beta import): remove the tree keyword from url

- packages/app/integration-tests/tests/utils.js
- packages/sandpack-core/src/manager.ts
- packages/sandpack-core/src/preset/preset.ts
This PR changes the logic of transpilers in a preset to use a (private) map so we ensure full control over when and how transpilers are registered.
The good thing is that this de-duplicates duplicate transpiler registrations so should speedup code execution as well.
For some reason this fixed a case where transpilers dissapear, still not sure how this is even possible?
Fixes #6105
> fix: Use map for transpilers, this resolves an issue with transpilers dissapearing

- packages/app/src/sandbox/eval/transpilers/base64/index.ts
- packages/common/src/utils/is-url.ts
Binary files should simply return the uri, no need to base64 encode it especially not encoding the uri
> fix: Data uri binary files

- packages/sandpack-core/src/npm/dynamic/fetch-protocols/utils.ts
When JSDelivr fails (which I think it did more often recently), sandboxes take ages to load. This reduces the try count, because knowing JSDelivr, if it fails twice, it will most probably fail 3rd, 4th etc...
> Reduce retry count for jsdelivr if it fails to load

- packages/app/src/app/graphql/types.ts
- packages/app/src/app/overmind/effects/gql/dashboard/mutations.ts
- packages/app/src/app/overmind/namespaces/dashboard/actions.ts
- packages/app/src/app/pages/Dashboard/Content/routes/Settings/UserSettings/WorkspaceSettings.tsx
- packages/app/src/app/pages/common/Modals/UndoAccountDeletion/UndoDeletedConfirmation.tsx
- packages/app/src/app/pages/common/Modals/UndoAccountDeletion/index.tsx
- packages/app/src/app/pages/common/Modals/index.tsx
- packages/common/src/types/index.ts
Co-authored-by: JamesACS <james@codesandbox.io>
Users can now undo their request for account deletion without emailing us 🎉 
TO DO (but I am only a poor backend dev so I need help)
1. Step A
2. Step B
3. Step C
> Allow undoing account deletion

- packages/common/src/utils/dependencies.ts
Unpkg can sometimes take over 30s to load the version, which results in the bundler being _really_ slow. JSDelivr is more reliable for these kinds of things.
> Make sure we use jsdelivr for resolving absolute versions

- packages/sandpack-core/src/resolver/fixture/node_modules/@zendesk/laika/esm/laika.js
- packages/sandpack-core/src/resolver/fixture/node_modules/@zendesk/laika/package.json
- packages/sandpack-core/src/resolver/resolver.test.ts
- packages/sandpack-core/src/resolver/resolver.ts
Currently if an exports field contains an extension we keep adding the extension resulting in a path with the same extension multiple times... this PR fixes that by checking if the new addition to the string was the same as the end of the string.
It's not perfect but not sure how else to fix this without largely refactoring the resolver again...
Closes #6279
> Fix exports failing when they include an extension

- packages/app/src/sandbox/eval/transpilers/less/file-manager.ts
- packages/app/src/sandbox/eval/transpilers/less/less-worker.ts
- Fix less regex for node_modules
- Try to fetch module if it's not in mem-fs
Fixes #6295
> Improve less file manager to download missing dependencies and use regex properly

- packages/app/src/sandbox/compile.ts
- packages/app/src/sandbox/eval/presets/create-react-app/index.ts
- packages/common/src/components/Preview/index.tsx
- packages/sandpack-core/src/manager.ts
This implementation adds support for Sandpack using React DevTools as a dependency. It should not affect the current editor, as I'm also passing this parameter to load the ReactDevTools dependency.
> Sandpack: support react devtools

- packages/common/src/components/Preview/index.tsx
Accidentally reverted `allow-downloads` iframe feature in this [commit](https://github.com/codesandbox/codesandbox-client/commit/bb8176517289179b8375896870b37f0cb8c71cb6) that was introduced [here](https://github.com/codesandbox/codesandbox-client/pull/5163).
Activating it again.
> Allow-downloads in iframes

- packages/app/src/app/pages/common/Modals/ShareModal/getCode.ts
- packages/common/src/components/Preview/index.tsx
Bug fix
Closes #6399 
The pointer lock API can't be used in the preview iframe.
Allow users to create sandboxes that depend on the pointer being used as a control input, as is done in the React Three Fiber demo.
1. Nothing yet.
> Add `allow-pointer-lock` to preview iframe

- packages/sandpack-core/src/npm/dynamic/fetch-protocols/index.ts
- packages/sandpack-core/src/npm/dynamic/fetch-protocols/transformer.ts
Adds a proxy to a URL that has CORS headers when trying to fetch from the npm registry.
> Support downloading directly from the registry

- packages/sandpack-core/src/npm/dynamic/fetch-npm-module.ts
Fixes an infinite recursion between `getDependencyVersion` and `resolvePath` in fetch-npm-module
Sandbox to see this in action: https://codesandbox.io/s/yq0z0j (beware this will likely crash your browser-tab)
> fix: Resolver recursion in `getDependencyVersion`

- packages/sandpack-core/src/resolver/resolver.test.ts
- packages/sandpack-core/src/resolver/resolver.ts
> fix: wildcard exports adding an extension should not break dir/index

- packages/app/src/app/pages/SignIn/Modal.tsx
- Adds redirect to the Google provider;
- User replace API instead, in order to avoid the user back to the sign-in page;
> fix: redirect in the google provider

- packages/app/src/sandbox/eval/presets/vue-cli/index.ts
- packages/sandpack-core/src/transpiled-module/transpiled-module.ts
Transpile vue and the surrounding tree
Not transpiling surrounding tree
Closes CSB-1589
Closes #6194
> fix: Transpile vue tree in setup script

- package.json
- packages/app/package.json
- packages/app/src/app/overmind/effects/live/index.ts
- packages/app/src/app/overmind/effects/vscode/Linter.ts
- packages/app/src/app/overmind/effects/vscode/extensionHostWorker/common/fs.ts
- packages/app/src/app/overmind/effects/vscode/extensionHostWorker/common/global.ts
- packages/app/src/app/pages/Dashboard/Components/Folder/CreateFolder.tsx
- packages/app/src/embed/components/Content/Monaco/mode.ts
- packages/app/src/sandbox/codesandbox-overlay/index.ts
- packages/app/src/sandbox/eval/tests/jest-lite.ts
- packages/codesandbox-api/package.json
- packages/common/package.json
- packages/components/package.json
- packages/executors/package.json
- packages/node-services/package.json
- packages/react-embed/package.json
- yarn.lock
Fixes ESLint typescript Template Literal Types by updating typescript
Closes #6630
> fix: ESLint typescript Template Literal Types

- packages/homepage/content/articles/codesandbox-ci-embeds/index.md
- packages/homepage/content/docs/8-ci.md
- packages/homepage/content/features/ci/index.md
In preparation for renaming the existing GitHub App, this change fixes its URL.
Please wait to merge.
> Update references to renamed GitHub App

- packages/homepage/content/docs/1-x-faqs.md
Also updated on docs site.
Related to SPT-155
> Update file sizes in FAQs

- packages/app/src/app/pages/Dashboard/Components/Folder/FolderCard.tsx
- packages/app/src/app/pages/Dashboard/Components/Sandbox/SandboxCard.tsx
- packages/app/src/app/pages/Dashboard/Components/VariableGrid/index.tsx
- packages/app/src/app/pages/Profile/SandboxPicker/index.tsx
https://user-images.githubusercontent.com/4838076/182361284-5c233797-579c-4e90-996f-9e8f28ed9ca3.mov
> fix(dashboard): prevent double click on editing

- packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/GitHub/CreateRepo.tsx
> fix: show better message when exporting to GitHub

- packages/app/src/app/pages/VSCodeAuth/Prompt/index.tsx
A follow-up to #6836.
- Removes the `useEffect` that'd open the VS Code on component's mount.
We don't have the on mount logic in the previous implementation and it looks like I've migrated it incorrectly. You need explicitly click on the "Open in Visual Studio Code" button for the login to happen, just as the text above the button suggests.
> fix(vscode): remove open effect on mount

- packages/app/src/sandbox/eval/tests/jest-lite.ts
- Add support for `.jsx` test files (`.tsx` is already supported so seems strange that `jsx` isn't - not sure if I missing something?)
- Add missing `mode` value to Codesandbox `add_test` event. This value is part of the jest-circus event and would be useful to propagate as part of the codesandbox event.
By adding this missing `mode` it will be easier to report the tests correctly in [SandpackTests](https://github.com/codesandbox/sandpack/pull/562) which currently assumes anything not `running`/`pass`/`fail` to be skipped which isn't strictly true. 
You can see that `mode` is part of the jest-circus event type [here](https://github.com/codesandbox/codesandbox-client/blob/master/packages/app/src/sandbox/eval/tests/types.ts#L48) and …
> [jest-lite]: Support test mode and jsx files

- packages/homepage/content/seo/react/index.md
The React code samples  link was split in two links [React c][ode samples] and it was wrongly (I hope) linked to a new project start page
it is a Bug fix for the bottom links
Esthetically wrong linked and I think with the wrong link too.
One link to the react examples
> fix: fixes a split markdown link

- packages/common/src/config/env.ts
We never set the `ENDPOINT`, so I never thought it would break anything. But apparently it's used in places, even though we never set it. The problem is that there was not a protocol introduced as part of the `ENDPOINT`. 
Fixes #6892
> fix: sse sandboxes ENDPOINT

- packages/app/src/app/pages/Dashboard/Components/Breadcrumbs/index.tsx
- packages/app/src/app/pages/Dashboard/Components/Header/index.tsx
- packages/app/src/app/pages/Dashboard/Components/Selection/index.tsx
- packages/app/src/app/pages/Dashboard/Content/routes/Liked/index.tsx
- packages/app/src/app/pages/Dashboard/Content/routes/Shared/index.tsx
Correct title copy 
Adjust font-size, font-weight 
Change padding-top of header title to align with improvements introduced by [PR #6919](https://github.com/codesandbox/codesandbox-client/pull/6919)
> Facelift: Page header copy and type review

- packages/app/src/app/pages/Dashboard/Components/Breadcrumbs/index.tsx
- packages/app/src/app/pages/Dashboard/Components/Header/index.tsx
- packages/app/src/app/pages/Dashboard/Components/Selection/index.tsx
- packages/app/src/app/pages/Dashboard/Components/VariableGrid/index.tsx
- packages/app/src/app/pages/Dashboard/Content/routes/Discover/index.tsx
- packages/app/src/app/pages/Dashboard/Content/routes/Settings/TeamSettings/TeamSettings.tsx
- packages/app/src/app/pages/Dashboard/Content/routes/Settings/UserSettings/index.tsx
- Adjust Page Header paddings
- Adjust type size on Discover page
- Adjust type size on Archive page
- Add + icon to New Folder on the Sandboxes page
> Facelift: Extra type review

- packages/app/src/app/components/SandboxList/DeleteSandboxButton/index.tsx
- packages/app/src/app/pages/Dashboard/Components/Branch/BranchCard.tsx
- packages/app/src/app/pages/Dashboard/Components/Branch/BranchListItem.tsx
- packages/app/src/app/pages/Dashboard/Components/Branch/index.tsx
- packages/app/src/app/pages/Dashboard/Components/Branch/types.ts
- packages/app/src/app/pages/Dashboard/Components/Sandbox/SandboxListItem.tsx
- packages/app/src/app/pages/Dashboard/Components/Sandbox/index.tsx
- packages/app/src/app/pages/Dashboard/Components/Sandbox/types.ts
- packages/app/src/app/pages/Dashboard/Components/Selection/ContextMenu.tsx
- packages/app/src/app/pages/Dashboard/Components/Selection/ContextMenus/BranchMenu.tsx
- packages/app/src/app/pages/Dashboard/Components/Selection/ContextMenus/FolderMenu.tsx
- packages/app/src/app/pages/Dashboard/Components/Selection/ContextMenus/SandboxMenu.tsx
- packages/app/src/app/pages/Dashboard/Components/Selection/DragPreview.tsx
- packages/app/src/app/pages/Dashboard/Components/Selection/index.tsx
- packages/app/src/app/pages/Dashboard/Sidebar/ContextMenu.tsx
- packages/app/src/app/pages/Profile/ContextMenu.tsx
- packages/app/src/app/pages/common/Modals/DeleteProfileSandboxModal/index.tsx
- packages/app/src/app/pages/common/Modals/DeleteSandboxModal/index.tsx
- packages/app/src/app/pages/common/Modals/MoveSandboxFolderModal/DirectoryPicker/SandboxesItem/FolderEntry/index.tsx
this is pointing to #6925, as I started with some facelift work and continued on the same source to implement the context menu.
It was a bit awkward, because context menus are tied to the selection. Added a context menu component for branches that works for regular and for contribution branches.
Also modified the sandbox card/list view for the recent page to support direct link instead of select on click and open on double click
Will create two follow-up linear tasks:
* Implement context menu for repos
* Implement branch removal via the context menu (felt too much for this PR which was already big)
> feat: add context menu for branch cards

- packages/app/src/app/pages/Pro/upgrade.tsx
- packages/app/src/app/pages/Pro/upgrade/Switcher.tsx
- packages/app/src/app/pages/Pro/upgrade/elements.ts
Closes XTD-167
(before)
(after)
> Facelift: Update margins and font-sizes on Upgrade to Pro page

- packages/app/src/app/pages/Dashboard/Sidebar/index.tsx
Closes XTD-153
Added an element that pushes the last group all the way down (made the whole sidebar a vertical flex)
Works well when overflowing
> facelift: push bottom group down the sidebar

- packages/app/src/app/overmind/namespaces/dashboard/types.ts
- packages/app/src/app/pages/Dashboard/Components/Branch/index.tsx
- packages/app/src/app/pages/Dashboard/Components/Branch/types.ts
- packages/app/src/app/pages/Dashboard/Components/Repository/index.tsx
- packages/app/src/app/pages/Dashboard/Components/Sandbox/index.tsx
- packages/app/src/app/pages/Dashboard/Components/VariableGrid/index.tsx
- packages/app/src/app/pages/Dashboard/Sidebar/index.tsx
- packages/common/src/utils/analytics/index.ts
Closes XTD-96
Closes XTD-97
Adds new analytics events to the dashboard.
- Dashboard - Open Contribution Branch from My Contributions
- Dashboard - Open Branch from Repository
- Dashboard - Open Branch from Recent
- Dashboard - Open Repository
- Dashboard - Open Sandbox from Recent
- Dashboard - Open Sandbox from My Drafts (not in the events table)
- Dashboard - Open Sandbox from Sandboxes (not in the events table)
- Dashboard - View Recent
- Dashboard - View My Contributions
- Dashboard - View Repositories
- Dashboard - View Drafts
- Dashboard - View Templates
- Dashboard - View Synced Sandboxes
- Dashboard - View Archive
- Dashboard - View Sandboxes
It sunsets one event:
- Dashboard - Recent sandbox opened (source: 'Home', dashboardVersion: 2)
> feat(dashboard): analytics

- packages/app/src/app/pages/Dashboard/Components/Repository/RepositoryCard.tsx
- packages/app/src/app/pages/Dashboard/Components/Repository/RepositoryListItem.tsx
- packages/app/src/app/pages/Dashboard/Components/Repository/index.tsx
- packages/app/src/app/pages/Dashboard/Components/Repository/types.ts
- packages/app/src/app/pages/Dashboard/Components/Selection/ContextMenu.tsx
- packages/app/src/app/pages/Dashboard/Components/Selection/ContextMenus/RepositoryMenu.tsx
- packages/app/src/app/pages/Dashboard/Components/Selection/ContextMenus/index.ts
- packages/app/src/app/pages/Dashboard/Components/Selection/index.tsx
- packages/common/src/utils/url-generator/dashboard.ts
Splits the Repository component into two elements: `RepositoryCard` and `RepositoryListItem`.
Adds the context menu to said elements.
|Repo card|
|:-:|
|<img width="384" alt="Screen Shot 2022-09-29 at 02 07 10" src="https://user-images.githubusercontent.com/24959348/192943697-22da80bd-9fc0-42b2-a96e-0a4373b8500a.png">|
|List item|
|:-:|
|<img width="882" alt="Screen Shot 2022-09-29 at 02 08 34" src="https://user-images.githubusercontent.com/24959348/192943883-63975f94-977d-42cb-94c5-d04d476326e2.png">|
> feat(dashboard): add context menu to repositories

- packages/app/src/app/graphql/types.ts
- packages/app/src/app/overmind/effects/gql/dashboard/queries.ts
- packages/app/src/app/overmind/namespaces/dashboard/actions.ts
- packages/app/src/app/pages/Dashboard/Content/routes/Repositories/index.tsx
Adds progressive loading to the repositories page. I've also added the behavior of fetching only the selected repo if the user accesses the page directly.
Decreases initial loading time for a team with almost 100 projects and around 2000 branches from nearly 14s to less than 5s.
|Now|Previously|
|:-:|:-:|
|![image](https://user-images.githubusercontent.com/24959348/192923913-1320e0f6-0222-4acf-8151-f453a884ad6b.png)|![image](https://user-images.githubusercontent.com/24959348/192923928-259aac3f-8106-4324-9436-6b33b57bb401.png)|
> feat(dashboard): improve repositories loading

- packages/app/src/app/components/Notifications/Content.tsx
- packages/app/src/app/pages/common/Modals/Common/Alert.tsx
- packages/app/src/app/pages/common/Modals/DeploymentModal/index.tsx
- packages/app/src/app/pages/common/Modals/MoveSandboxFolderModal/index.tsx
- packages/app/src/app/pages/common/Modals/PilotPaymentModal/index.tsx
- packages/app/src/app/pages/common/Modals/PreferencesModal/Appearance/index.tsx
- packages/app/src/app/pages/common/Modals/PreferencesModal/CodeFormatting/index.tsx
- packages/app/src/app/pages/common/Modals/PreferencesModal/Editor/Editor.tsx
- packages/app/src/app/pages/common/Modals/PreferencesModal/Experiments/index.tsx
- packages/app/src/app/pages/common/Modals/PreferencesModal/Integrations/index.tsx
- packages/app/src/app/pages/common/Modals/PreferencesModal/KeyMapping.tsx
- packages/app/src/app/pages/common/Modals/PreferencesModal/MailPreferences/index.tsx
- packages/app/src/app/pages/common/Modals/PreferencesModal/PreferencesSync/index.tsx
- packages/app/src/app/pages/common/Modals/PreferencesModal/Preview/Preview.tsx
- packages/app/src/app/pages/common/Modals/PreferencesModal/SideNavigation.tsx
- packages/app/src/app/pages/common/Modals/PreferencesModal/SideNavigation/elements.js
- packages/app/src/app/pages/common/Modals/PreferencesModal/index.tsx
IMPORTANT: Changes affect **only** the dashboard. 
**1. Adjust style of Notifications menu**
(before)
(after)
**2. Adjust style of Preferences modal**
(before)
(after)
**3. General modal type adjustment**
(before)
(after)
Closes XTD-158.
> Facelift: Modals UI review on Dashboard

- packages/app/src/app/overmind/namespaces/dashboard/actions.ts
Noticed the skeleton views are permanent if the repositories call returns an empty array, so I made the empty array a valid state
> fix: empty state for repos and contributions

- packages/app/src/app/pages/Dashboard/Components/VariableGrid/index.tsx
- packages/components/src/components/Menu/index.tsx
- packages/components/src/utils/polyfill-theme.ts
- New styles for the context menu following the new editor
- Increase the max width of the container to show more columns in large screens
> feat(new-style): Update context menu and grid max width

- packages/app/src/app/components/CreateNewSandbox/CreateSandbox/CreateSandbox.tsx
- packages/app/src/app/components/CreateNewSandbox/CreateSandbox/FromTemplate.tsx
- packages/app/src/app/components/CreateNewSandbox/CreateSandbox/SearchBox/elements.ts
- packages/app/src/app/components/CreateNewSandbox/CreateSandbox/TemplateCard.tsx
- packages/app/src/app/components/CreateNewSandbox/CreateSandbox/TemplateCategoryList.tsx
- packages/app/src/app/components/CreateNewSandbox/CreateSandbox/elements.ts
- packages/app/src/app/components/Modal/index.js
- packages/components/src/components/Checkbox/index.tsx
* Mobile view
* Modal window sized according to the design (but need to look into the weird max-width set on react-modal
* Template cards padding reduced
* Text overflow handled and title added for tooltip info
Tested responsive design on different screen sizes
https://user-images.githubusercontent.com/9945366/193804177-9ca43119-a4da-4e7f-ac50-56a42e1f7b02.mov
> ui(create-modal): polish card sizes and overflow

- packages/app/src/app/overmind/actions.ts
- packages/app/src/app/pages/Dashboard/Sidebar/index.tsx
Fixes the problem with data reset on changing the workspace. It also addresses the problem of figuring out something changed, since you are redirected to the `recent` page everytime you change the team/workspace.
Also, I removed `my contributions` link from the sidebar if you are in a team (Closes XTD-197)
NOTE: Recent page still shares the branch data between the teams, there's a pending request to the backend team to help us with that, so you might see the same items in the recent page while you switch
> feat: move to recent on workspace change and reset state data

- packages/app/src/app/components/CreateNewSandbox/CreateSandbox/CreateSandbox.tsx
- packages/app/src/app/pages/Dashboard/Sidebar/index.tsx
Focused on the text-overflow which is more problematic for the release, left the animation and other details for later on.
> fix: text-overflow for folders in sidebar

- packages/app/src/app/pages/Dashboard/Components/Repository/RepositoryCard.tsx
- packages/app/src/app/pages/Dashboard/Components/Repository/RepositoryListItem.tsx
- packages/app/src/app/pages/Dashboard/Components/Sandbox/index.tsx
Makes sure the navigation is added to history and is only rendering routes and not reloading the whole page.
Closes XTD-229
Video shows no refresh:
https://user-images.githubusercontent.com/7533849/194079444-f0474483-37f4-4376-9a9c-4b15cd5d8458.mov
> Fix(dashboard): Use react router links

- packages/app/src/app/pages/Dashboard/Components/Notification/Notification.tsx
- packages/app/src/app/pages/Dashboard/Components/Notification/NotificationIndicator.tsx
- packages/app/src/app/pages/Dashboard/Content/routes/MyContributions/index.tsx
- packages/app/src/app/pages/Dashboard/Content/routes/Repositories/index.tsx
- packages/app/src/app/pages/Dashboard/Content/routes/SyncedSandboxes/index.tsx
- packages/app/src/app/pages/Dashboard/Sidebar/index.tsx
The only thing that we might want to update is the dismissal of the notifications and when the dots in the sidebar update. If we want to update the dots in the sidebar when a notification is dismissed, we need to keep track of the state higher up in the tree instead of just inside the notifications. Right now the notification indicator dots are gone when the routes change.
https://user-images.githubusercontent.com/7533849/194049924-10dba198-0778-4bcc-b531-f98a86c50681.mov
> feat(dashboard): Implement notifications

- packages/app/src/app/pages/Dashboard/Components/Breadcrumbs/index.tsx
- packages/app/src/app/pages/Dashboard/Sidebar/index.tsx
Change name of sections `Sandboxes` and `Synced Sandboxes` on sidebar and internal page
(before)
(after
)
> Change section names on sidebar

- packages/app/src/app/pages/Dashboard/Header/index.tsx
- packages/app/src/app/pages/Sandbox/Editor/Header/Actions.tsx
Change text of CTA on Dash and Editor header to '`Create`' 
(`Create` does not clash with the `New` cards in the grid)
(before)
(after)
> Facelift: Change CTA text on Header

- packages/app/src/app/pages/Dashboard/Components/Notification/Notification.tsx
- packages/app/src/app/pages/Dashboard/Content/routes/Recent/index.tsx
- packages/app/src/app/pages/Dashboard/Content/routes/Repositories/index.tsx
- packages/app/src/app/pages/Dashboard/Content/routes/SyncedSandboxes/index.tsx
1. Change Recent page title to `Recent`
2. Change notification text base and highlight color.
(before)
(after)
> QA: Change 'Recent'page title and notification colors

- packages/app/src/app/pages/Dashboard/Content/routes/Repositories/index.tsx
To check this, open repositories page on the dashboard with a team with 0 repositories. To confirm that it still works with repositories check out the page with a team with repositories.
> fix(dashboard): show empty state on repositories page

- packages/app/src/app/components/CreateNewSandbox/CreateSandbox/CreateSandbox.tsx
- packages/app/src/app/components/CreateNewSandbox/CreateSandbox/types.ts
- packages/app/src/app/overmind/effects/router.ts
Closes XTD-240: Proper redirect for v2 sandboxes after fork
Closes XTD-241: Disable second screen for create from template (temporarily)
> fix: one-click sandbox create and proper redirect to v2 editor

- packages/app/src/app/pages/Dashboard/Components/EmptyScreen/index.tsx
Rendered a `button` because of a missing `as` prop. This fixes it.
> fix(dashboard): Button is actually an anchor

- packages/app/src/app/pages/common/UserMenu/index.tsx
- packages/common/src/utils/url-generator.ts
- packages/components/src/components/Menu/index.tsx
This fixes the problem of the relative `/docs` path in the menu and the fact that it was not opening the docs in a new tab. Since I was there, I created a helper that we can use for all docs link in the future, to target any specific page on `codesandbox.io/docs`
> chore: add helper for docs links

- packages/app/src/app/pages/Dashboard/Components/Header/index.tsx
- packages/app/src/app/pages/Dashboard/Components/Selection/ContextMenus/BranchMenu.tsx
- packages/app/src/app/pages/Dashboard/Components/Selection/ContextMenus/MultiItemMenu.tsx
- packages/app/src/app/pages/Dashboard/Components/Selection/ContextMenus/RepositoryMenu.tsx
Add option to create branch from default on a repository card
Add link to repository overview on branch card
While there I fixed two issues noticed in yesterday's QA session:
* A small height jump when going to the list view for branches
* A wrong copy text on the multiselect context menu
> feat: more context menu options for branch/repo

- packages/app/src/app/pages/Dashboard/Components/Selection/ContextMenu.tsx
Fixes #7004 
When the context menu for an item in the dashboard is opened without somehow having an item selected, we create an array of selected items with an `undefined` value inside. This happens because non of the `if` statements are true and [the final `find` in the `map` function](https://github.com/codesandbox/codesandbox-client/pull/7007/files#diff-0c91eff0484478676cabb97d7c836696ec2bf811f5352d63730af0c697240414R114) creating the array returns `undefined`. We later [check for `selectedItems[0].type`](https://github.com/codesandbox/codesandbox-client/pull/7007/files#diff-0c91eff0484478676cabb97d7c836696ec2bf811f5352d63730af0c697240414R129), which fails when it's `undefined` resulting in a crash.
When item is `undefined` we check this first, before moving to the next if statement …
> fix(contextmenu): check if selected item is undefined

- packages/app/src/app/components/CreateSandbox/CreateSandbox.tsx
Fixes #7005
Add null check when reading active team, as it could still be loading the team info.
When team info is still loading (or failed) and the create new modal is opened, it tries to read the team name of `null`. This crashes the application.
Fallback to "Team templates" until team name is accessible.
1. Go to the dashboard
2. Select a team
3. Click the "New" button top right
4. Confirm that application doesn't crash
> fix(create-modal): add fallback for teaminfo null when loading

- packages/app/src/app/overmind/namespaces/dashboard/actions.ts
- packages/app/src/app/overmind/namespaces/dashboard/state.ts
- packages/app/src/app/pages/Dashboard/Components/Header/index.tsx
- packages/app/src/app/pages/Dashboard/Components/Selection/ContextMenus/RepositoryMenu.tsx
- packages/app/src/app/pages/Dashboard/Content/routes/Repositories/index.tsx
- packages/app/src/app/pages/Dashboard/Sidebar/index.tsx
Not on the roadmap yet and **not supported by the backend**, but I really felt the need to have this feature while working in the dashboard. It relies on **localStorage** to persist the starred repos per team.
All the functionality is dependent on the value of `CSB_DEBUG` being set to `ENABLED`, similar with how the devtools appears for the v2 editor. v1 does not have the same feature flag system as v2, but it would be nice to add maybe?
* adds star/unstar in the context menu
* adds star/unstar for the repo page header (when showing the branches)
* shows the starred repos in the sidebar, under `All repositories`
* starred repos are reset everytime you change the workspace
Why merge this?
* we can use it internally for convenience
* it gives us time to think about the UX of the feature for …
> experimental(dashboard): star repo feature

- packages/app/src/app/graphql/types.ts
- packages/app/src/app/overmind/effects/gql/index.ts
- packages/app/src/app/overmind/effects/gql/sidebar/fragments.ts
- packages/app/src/app/overmind/effects/gql/sidebar/queries.ts
- packages/app/src/app/overmind/index.ts
- packages/app/src/app/overmind/namespaces/sidebar/actions.ts
- packages/app/src/app/overmind/namespaces/sidebar/index.ts
- packages/app/src/app/overmind/namespaces/sidebar/state.ts
- packages/app/src/app/pages/Dashboard/Sidebar/index.tsx
- packages/app/src/app/pages/Pro/legacy-pages/WorkspacePlanSelection.tsx
- yarn.lock
To make it easier to interact with the sidebar and conditionally render sidebar items using less data and requests we now have a separate sidebar state. In the future we will be able to use this for other things, e.g. showing sidebar notification indicators. In this PR we also conditionally render the Templates and Synced Sandboxes sidebar rows based on data.
Closes XTD-198
> feat(sidebar): Sidebar overmind state

- packages/app/src/app/components/CreateSandbox/CreateSandbox.tsx
- packages/app/src/app/components/CreateSandbox/Import/Import.tsx
- packages/app/src/app/components/CreateSandbox/TemplateCategoryList.tsx
- packages/app/src/app/overmind/internalActions.ts
Adds option to sign in via the cloud templates tab, as you need to be logged in to fork a cloud template:
Adds option to sign in via the error message:
I've also updated some CSS to align the headings in the different tab panels.
This is a first iteration to quickly improve UX. It makes it easier to find the login button in the create new modal. In the future we might remove this again when we have a better option.
> fix(create-new): Add login option to cloud beta template list and fix styles

- packages/app/src/app/components/CreateSandbox/CreateSandbox.tsx
- packages/app/src/app/pages/Dashboard/Components/Branch/BranchCard.tsx
- packages/app/src/app/pages/Dashboard/Components/Branch/BranchListItem.tsx
- packages/app/src/app/pages/Dashboard/Components/Filters/SortOptions/index.tsx
- packages/app/src/app/pages/Dashboard/Components/Folder/FolderCard.tsx
- packages/app/src/app/pages/Dashboard/Components/Folder/FolderListItem.tsx
- packages/app/src/app/pages/Dashboard/Components/Notification/Notification.tsx
- packages/app/src/app/pages/Dashboard/Components/Repository/RepositoryCard.tsx
- packages/app/src/app/pages/Dashboard/Components/Repository/RepositoryListItem.tsx
- packages/app/src/app/pages/Dashboard/Components/Sandbox/SandboxCard.tsx
- packages/app/src/app/pages/Dashboard/Components/Sandbox/SandboxListItem.tsx
- packages/app/src/app/pages/Dashboard/Content/routes/Settings/TeamSettings/WorkspaceSettings.tsx
- packages/app/src/app/pages/Dashboard/Content/routes/Settings/UserSettings/WorkspaceSettings.tsx
- packages/components/src/components/IconButton/index.tsx
A bit of polishing on the card/list items when hovering to the more button
* bigger icon
* default cursor
* square with border radius instead of circle shape
* hover on icon reverts hover on card (using [:has](https://developer.mozilla.org/en-US/docs/Web/CSS/:has) which doesn't work in firefox unfortunately)
* applies on: sandboxes, folders, branches & repos
https://user-images.githubusercontent.com/9945366/195557649-9674efa1-f299-41a9-8c1a-8e7c4bc5ae87.mov
https://user-images.githubusercontent.com/9945366/195557700-41a3481c-9db8-4231-9c48-e14255baf838.mov
Notes
* There's a lot of duplication already with these cards, might be a good idea to think of a way to reuse the card/list item component
> fix: hover interaction with more button

- packages/app/src/app/components/CreateSandbox/TemplateCategoryList.tsx
Removed the cloud beta badge from the panel title because it is already present in the tab button and every template in the panel.
> chore(create-new): remove cloud beta badge from title

- packages/app/src/app/components/CreateSandbox/SearchResults/SearchResultList.tsx
- packages/common/src/types/algolia.ts
- packages/common/src/types/index.ts
Adds `v2` to the Algolia search result types, and pass it to the template card. This way it will show the badge on the card when searching. This distinction makes it more clear what kind of template the user is selecting, conforming to expectations.
Closes XTD-275
No beta badge.
Beta badge!
> fix: Add v2 flag to search result to show beta badge

- packages/app/src/app/overmind/internalActions.ts
The message changed and we weren't checking for that so the previously added sign in button was lost again. Talked to Sanne and we agreed that this is not the ideal way to do this, but for now in v1 it is what it is.
> fix: show sign in on cloud sandbox message

- packages/app/src/app/components/CreateSandbox/TemplateCard.tsx
- packages/app/src/app/overmind/namespaces/dashboard/actions.ts
- packages/app/src/app/pages/Dashboard/Content/routes/Search/searchItems.ts
We're now able to search for repositories on the dashboard 🥳
https://user-images.githubusercontent.com/7533849/195845514-2bdd20b6-b2a5-498c-93bf-94e1abfeb028.mov
Right now, the search works a bit janky. We only fetch the sandboxes and repositories when we visit an empty search page - I haven't changed anything about that logic. The search itself or fetching the sandboxes and repositories can be slow too -maybe because it fetches all the branches as well? We can also make an effort of removing the `ts-ignores` from the search feature.
> feat(search): enable repository search

- packages/app/src/app/overmind/namespaces/dashboard/actions.ts
Prevents the recent page from loading forever when errors are thrown. This defaults to the empty screen and relies on the user seeing the notification error since we don't have an error state for that page.
> fix(dashboard): set sandboxes to empty array when catching errors

- packages/app/src/app/hooks/index.ts
- packages/app/src/app/hooks/useCreateCheckout.ts
- packages/app/src/app/overmind/namespaces/pro/actions.ts
- packages/app/src/app/pages/Pro/upgrade.tsx
- packages/app/src/app/pages/Pro/upgrade/utils.ts
- packages/app/src/app/pages/common/Modals/NewTeamModal/TeamSubscription.tsx
- packages/app/src/app/pages/common/Modals/NewTeamModal/index.tsx
- packages/components/src/components/Icon/icons.tsx
Adds UI for signing up for the trial on the create team flow.
Loom: https://www.loom.com/share/1cbc221612f444d0bf5940f0043c9618
⚠️ The trial flag is enabled on the back end only, so this should be tested against the stream.
1. Open the dashboard
2. In the workspace selector, click "Create a new team"
3. Go through step 1 (actual team creation)
4. Go through step 2 (placeholder for team members)
5. In step 3, click on "Start 14-day free trial"
6. In stripe, use a test card
7. After a successful subscription, get redirected to your new team settings
> feat(trial): create team and subscribe to pro

- packages/homepage/src/pages/pricing/_elements.js
- packages/homepage/src/pages/pricing/_intro.js
- packages/homepage/src/pages/pricing/_plans.js
- packages/homepage/src/pages/pricing/index.js
- title line height set to 1.1
- spotlight colors flipped
- plan card alignments (this is a bit annoying to get right because of the implementation)
- some content changes request by @filipelima18 
Closes MKT-67
> fix(website): alignments, colors, content

- packages/app/src/app/components/dashboard/InputText.tsx
- packages/app/src/app/pages/Dashboard/index.tsx
- packages/app/src/app/pages/SignIn/Onboarding.tsx
- packages/app/src/app/pages/SignIn/SignIn.tsx
Shows the create team modal after a new signup and dismisses the what's new modal. Only existing users get to see the what's new modal and new users get prompted to create a team.
This is quite hard to test on dev environments so we'll have to properly test this on stream. We can bypass certain steps to test if the modal shows up though:
1. Open the dashboard
2. Open the browser devtools console
3. Past and execute the following:
```
localStorage.setItem('NUOCT22', true);
```
4. Refresh the page
5. It should show the create team modal
6. Refresh the page again
7. The create team modal should not show up
> feat(trial): Show create team modal after new signup

- .codesandbox/tasks.json
- packages/app/src/app/components/CloudBetaBadge.tsx
- packages/app/src/app/components/CreateSandbox/CreateSandbox.tsx
- packages/app/src/app/components/CreateSandbox/FromTemplate.tsx
- packages/app/src/app/components/CreateSandbox/Import/FromRepo.tsx
- packages/app/src/app/components/CreateSandbox/TemplateCard.tsx
- packages/app/src/app/components/WorkspaceSelect/WorkspaceSelect.tsx
- packages/app/src/app/pages/Dashboard/Components/Header/index.tsx
- packages/app/src/app/pages/Dashboard/Components/Sandbox/SandboxCard.tsx
- packages/app/src/app/pages/Sandbox/Editor/Header/WorkspaceName/UpgradeToolTip.tsx
- packages/components/src/components/Badge/index.stories.tsx
- packages/components/src/components/Badge/index.tsx
- packages/components/src/index.ts
Nothing changed, the Badge was moved to components, added a small story and exposed the storybook task for the components package as a task.
There was no need for the `CloudBetaBadge` anymore as it was just an instance of `Badge`
> chore: move Badge to components package

- packages/app/src/app/components/dashboard/Textarea.tsx
- packages/app/src/app/overmind/effects/gql/dashboard/mutations.ts
- packages/app/src/app/overmind/namespaces/dashboard/actions.ts
- packages/app/src/app/pages/common/Modals/NewTeamModal/TeamInfo.tsx
- packages/app/src/app/pages/common/Modals/NewTeamModal/TeamMembers.tsx
No need to generate new GraphQL types, still using the `email` property and it still accepts a string.
1. Open the dashboard
2. Create a new team
3. Input emails in the textarea
4. Press submit
5. Check if the next step is active and emails have been sent
https://user-images.githubusercontent.com/7533849/197798843-2894ca83-feee-437d-92de-a68b11f14d5b.mov
> feat(trial): Invite team members

- packages/app/src/app/overmind/namespaces/editor/actions.ts
- packages/common/src/types/index.ts
Failsafe redirect when a v2 sandbox is loaded in v1
> fix: redirect v2 sandbox to the v2 editor

- packages/app/src/app/components/WorkspaceSelect/WorkspaceSelect.tsx
Checking if we the selected team is in the state before reading properties. I have videos with current behaviour and proof but those show an invite link so I'm not uploading them here :)
After an invite, the dashboard breaks when joining a team since the selected team is still `undefined` on first render.
After an invite, the dashboard works and after the second render the selected team is defined.
> fix(dashboard): nullcheck for selected team after accepting invite

- packages/app/src/app/pages/Dashboard/Components/EmptyScreen/index.tsx
- packages/app/src/app/pages/Dashboard/Components/Header/index.tsx
- packages/app/src/app/pages/Dashboard/Components/TemplatesRow/TemplatesRow.tsx
- packages/app/src/app/pages/Dashboard/Components/TemplatesRow/elements.ts
- packages/app/src/app/pages/Dashboard/Components/TemplatesRow/index.ts
- packages/app/src/app/pages/Dashboard/Content/routes/Recent/index.tsx
Creates templates row to display on the recent page if the user/team doesn't have any recent sandboxes/branches.
1. Create a team (or use a team without any recent sandboxes/branches)
2. Open the dashboard recent page
3. See empty state
> feat(dashboard): recent page empty state

- packages/app/src/app/overmind/actions.ts
- packages/app/src/app/overmind/effects/api/index.ts
- packages/app/src/app/overmind/effects/api/types.ts
- packages/app/src/app/overmind/internalActions.ts
- packages/app/src/app/pages/SignIn/Onboarding.tsx
- packages/common/src/types/index.ts
- Saves the user's role and usage during the signup.
- Adds the metadata fields to amplitude when identifying the user.
1. Step A
2. Step B
3. Step C
> feat(trial): save "role" and "usage" and add it to amplitude

- packages/app/package.json
- packages/app/src/sandbox/eval/transpilers/babel/index.ts
- packages/sandpack-core/src/transpiled-module/transpiled-module.ts
- yarn.lock
Use sucrase fork for compiling node modules.
Makes transformation about 2x faster, smaller bundle size and we can probably make this even faster in certain areas
> feat: Use csb-sucrase for compiling node modules

- packages/app/src/app/pages/Dashboard/Content/routes/Sandboxes/index.tsx
- packages/app/src/app/pages/Dashboard/Content/routes/Settings/TeamSettings/ManageSubscription/index.tsx
- packages/app/src/app/pages/Dashboard/Content/routes/Settings/TeamSettings/ManageSubscription/upgrade.tsx
- packages/app/src/app/pages/Dashboard/Sidebar/index.tsx
Started fixing a duplicate call to getAllFolders, ended up with 3 different things:
- **getAllFolders** called only once on the sidebar, when the activeTeam changes
- null/undefined error when no **subscription** exists for team in team settings
- **button in link** replaced with a simple button for upgrading to pro
For later: wasn't able to figure out why the router push to `/pro` doesn't work, so I left it as an anchor tag instead of using react router.
> fix: null error and duplicate call

- packages/app/src/app/pages/Sandbox/Editor/Header/index.tsx
- yarn.lock
When refreshing on the editor, there was a split second in which the activeTeam was there, but the personalWorkspaceId was not set, hence the username appeared, then it switched to `Personal`
> fix: user name flicker before Personal is shown

- packages/app/src/app/pages/Dashboard/index.tsx
- packages/app/src/app/pages/SignIn/Onboarding.tsx
When you're creating a new user it automatically showed the create team modal when viewing the dashboard page. As a user that created an account after an invitation, you don't want to immediately create a new team. For that reason we don't show the modal after creating a new account.
You're able to test multiple scenarios by setting / removing flags in `localStorage`:
1. Viewing the create team modal
1.1 Login and go to any dashboard page
1.2 Paste the code below in the console and execute
1.3 Refresh the page
```
localStorage.setItem('NUOCT22', true);
```
2. Viewing the what's new modal
2.1 Login and go to any dashboard page
2.2 Paste the code below in the console and execute
2.3 Refresh the page
```
localStorage.removeItem('NUOCT22');
localStorage.removeItem('wnoct22', true);
```
3. …
> feat(trial): dont show create team modal after accepting invite

- packages/app/src/app/pages/common/Modals/NewTeamModal/TeamMembers.tsx
Instead of removing all spaces, we remove spaces in front and behind the mail addresses. This way we catch emails with spaces as invalid emails.
1. Login and view dashboard
2. Create a new team
3. On the invite members step, input wrong emails with spaces and such
4. Result
> fix(trial): Properly catch spaces in email addresses instead of removing them all

- packages/app/src/app/pages/Dashboard/Components/Selection/ContextMenus/MultiItemMenu.tsx
- packages/app/src/app/pages/Dashboard/Components/Selection/ContextMenus/SandboxMenu.tsx
Disables zip exports and export settings for cloud sandboxes on single and multi items menus.
> fix(dashboard): remove unsupported zip export from cloud sandboxes

- README.md
docs update
This url leads to a 404 https://codesandbox.io/docs/start
The udpated url links to https://codesandbox.io/docs/learn/introduction/overview
1. Go to README.md
2. click the link for "website" on the README.md (line 35)
Result:
You'll receive a 404
- [ x] Documentation
- [x ] Testing 
- [x ] Ready to be merged
It's honestly a small change. I don't think it's worth being added to the contributors table 😅. It'd love to do some more meaningful improvements to earn that for myself 🙂!
VERY small change but I'd love to get more involved with contributing to codesandbox! Any suggestions on where to start on the UI realm of things? 🙂
> [Small Fix] Fixed 404 error on url linking to the docs

- packages/app/src/app/pages/Dashboard/Components/Branch/NewBranch.tsx
- packages/app/src/app/pages/Dashboard/Components/Repository/ImportRepository.tsx
Added `isDisabled` state for repository buttons. This state should be enabled when the repository is in view only mode. The logic to trigger this does not yet exist.
`NewBranch` and `ImportRepository` now have an `isDisabled` property. Since we don't have the data yet to properly populate this it's easiest to test by changing the destructured property to `isDisabled = true`.
> feat(trial): Disabled styles for import and create branch buttons

- packages/app/src/app/hooks/useDismissible.ts
- packages/app/src/app/hooks/useScript.ts
- packages/app/src/app/overmind/effects/browser.ts
- packages/app/tsconfig.strictNullChecks.json
In the future we'll be writing more dismissible banners etc. that we want to keep track of in `localStorage`. We already created a few in the past weeks but found that keeping track and DX wasn't optimal. From now on we can use this hook to dismiss and check if items are dismissed while keeping track of all values.
Example usage
```tsx
const Component = () => {
const { banners } = useAction();
const [isBannerDismissed, dismissBanner] = useDismissible('BANNER');
const onClose = () => {
banners.banner.close();
dismissBanner();
};
if (isBannerDismissed) {
return null;
}
return (
<Banner />
);
};
```
Keep in mind that this hook does not keep track of state, most of this is handled in overmind. This hook should mostly be used for initial state of showing banners by a flag in `localStorage`.
> feat: useDismissible

- packages/components/.storybook/config.tsx
- packages/components/src/components/Banner/Banner.stories.tsx
- packages/components/src/components/Banner/Banner.tsx
- packages/components/src/components/Button/index.tsx
- packages/components/src/components/MessageStripe/MessageStripe.stories.tsx
- packages/components/src/components/MessageStripe/MessageStripe.tsx
- packages/components/src/components/Stack/index.tsx
- packages/components/src/components/Text/index.tsx
- packages/notifications/src/component/Toast.tsx
Created `MessageStripe` and `Banner` components. I've also updated some components to be more flexible and to make sure we don't have to use the same `css` prop with the same values everytime.
**Message Stripe Trial**
**Message Stripe Warning**
**Message Stripe without action**
**Message Stripe with space between**
**Banner**
Note: Everett font does not work in Storybook
> feat(trial): Reusable banner components

- packages/app/src/app/pages/Dashboard/Content/routes/Repositories/index.tsx
Mount two instances of Notification to avoid (hopefully) the crash we see in reports
> fix: repositories page crash

- packages/app/src/app/pages/TeamInvitation/TeamInvitation.tsx
- packages/app/src/app/pages/common/Modals/NewTeamModal/TeamMembers.tsx
Gives a link to invite team members
Tested it by clicking the button, and verifying that the right url was on clipboard :D
> feat: add invite link URL support to team onboarding

- packages/app/src/app/components/CreateSandbox/CreateSandbox.tsx
Closes xtd-203.
Hides/shows the "my/team templates" section if they exist or not.
1. Open the create modal.
2. If the user/team has templates, the third item in the sidebar is "My/Team templates"
3. If the user/team doesn't have templates, there's no sidebar item.
> fix(create new): hide my/team templates if there are none

- packages/app/src/app/pages/Dashboard/Sidebar/BottomMessages/AdminStartTrial.tsx
- packages/app/src/app/pages/Dashboard/Sidebar/index.tsx
Since now it's possible to switch from monthly to yearly, we open the trial on a monthly subscription directly in stripe.
> fix: open stripe directly on start trial

- packages/app/src/app/hooks/index.ts
- packages/app/src/app/hooks/useDismissible.ts
- packages/app/src/app/pages/Dashboard/Components/UpgradeBanner/UpgradeBanner.tsx
- packages/app/src/app/pages/Dashboard/Components/UpgradeBanner/index.tsx
- packages/app/src/app/pages/Dashboard/Content/index.tsx
- packages/app/src/app/pages/Dashboard/Content/routes/Recent/index.tsx
- packages/components/src/components/Banner/index.tsx
- packages/components/src/components/Icon/icons.tsx
- packages/components/src/index.ts
- Updates the dismissible hook to instantly reflect the changes in state.
- Adds the `sandbox` icon.
- Adds the upgrade banner to the dashboard.
1. Visit the dashboard home: `/dashboard/recent`
2. Select a team on a free account
3. View banner
- See the "Upgrade now" CTA and the "Learn more" link if you are an admin.
- See the "Learn mode" CTA if you are not an admin.
> feat(dashboard): "Upgrade to Pro" banner

- packages/app/config/webpack.common.js
- packages/app/src/app/hooks/useSubscription.ts
- packages/app/src/app/pages/Dashboard/Content/routes/Sandboxes/index.tsx
- packages/app/src/app/pages/Dashboard/Sidebar/index.tsx
- packages/components/src/components/MessageStripe/MessageStripe.tsx
- packages/components/src/index.ts
- Fixed a few styling issues in the `MessageStripe` and made sure that the component and `Banner` are now properly exported from the package.
- Fixed an issue with `react-hot-reload` where mapping over children uses proxy components. With proxy components we aren't able to check the child type, which results in broken "augmented" children in the `MessageStripe` component.
- Added the `MessageStripe` with all the conditionals to the "All sandboxes" page.
- Created a hook `useSubscription` to contain subscription logic extracting it a way from the components and enabling reuse.
1. Open the code in the editor
2. Open `packages/app/src/app/pages/Dashboard/Content/routes/Sandboxes/index.tsx`
3. Change the `hasMaxSandboxes` boolean const to `true`
4. If you want to test certain scenario's use …
> feat(pro): Public sandbox limits

- packages/app/src/app/pages/Dashboard/Content/index.tsx
Am I overlooking something by changing this line? I've checked the dashboard pages and all seems OK!
Before:
After:
Page with Banner component:
> fix(discover): page banner position and scroll

- packages/components/src/components/IconButton/index.tsx
- packages/components/src/components/MessageStripe/MessageStripe.stories.tsx
- packages/components/src/components/MessageStripe/MessageStripe.tsx
Adds `onDismiss` function to be able to dismiss the `MessageStripe`.
> feat(messagestripe): add dismiss functionality

- packages/app/src/app/pages/Dashboard/Content/routes/Repositories/index.tsx
- packages/app/src/app/pages/Dashboard/Content/routes/Sandboxes/index.tsx
The stripe is essentially the same as the one on the sandboxes page, the text is slightly different. I've also updated the `Action` where the `as="a"` had a `to` prop instead of `href`.
> feat(subscription): repository messages

- packages/app/src/app/pages/Dashboard/Components/Branch/BranchCard.tsx
- packages/app/src/app/pages/Dashboard/Components/Branch/BranchListItem.tsx
- packages/app/src/app/pages/Dashboard/Components/Branch/types.ts
- packages/app/src/app/pages/Dashboard/Components/Repository/RepositoryCard.tsx
- packages/app/src/app/pages/Dashboard/Components/Repository/RepositoryListItem.tsx
- packages/app/src/app/pages/Dashboard/Components/Repository/types.ts
- packages/app/src/app/pages/Dashboard/Components/Sandbox/NewMasterSandbox.tsx
- packages/app/src/app/pages/Dashboard/Components/Sandbox/SandboxCard.tsx
- packages/app/src/app/pages/Dashboard/Components/Sandbox/SandboxListItem.tsx
- packages/app/src/app/pages/Dashboard/Components/Sandbox/types.ts
- packages/app/src/app/pages/Dashboard/Components/Selection/ContextMenus/RepositoryMenu.tsx
- packages/app/src/app/pages/Dashboard/Components/Selection/ContextMenus/SandboxMenu.tsx
- packages/app/src/app/pages/Dashboard/Components/SyncedSandbox/SyncedSandboxListItem.tsx
- packages/components/src/components/Badge/index.tsx
Dashboard cards and list items will have (slightly) different styles and a "View only" badge when they're in view only mode. Some actions in the context menu are disabled when in view only mode. 
`Cards` and `ListItem`s with changes now have an `isViewOnly` property. Since we don't have the data yet to properly populate this it's easiest to test by changing the destructured property to `isViewOnly = true`.
For the different context menus you can use the `isViewOnly` variable and set it to `true` instead of `false` to view the changes.
Depending on how this mode will be implemented, the property name can change. In the frontend it will behave the same though.
> feat(trial): view only state for dashboard cards and list items

- packages/app/src/app/components/CreateSandbox/TemplateCard.tsx
When a template has no `team`, it is a template that's been automatically created since it was imported from GitHub. Right now we show "CodeSandbox" as owner, but that's not true, it's probably GitHub.
> fix: show correct owner for template

- packages/app/src/app/hooks/useSubscription.ts
- packages/app/src/app/pages/Dashboard/Content/routes/Repositories/index.tsx
- packages/app/src/app/pages/Dashboard/Content/routes/Sandboxes/index.tsx
When working on `XTD-362` and `XTD-359` we weren't able to calculate the max public sandboxes and repositories yet. We are now, so I've added those flags to the `useSubscription` hook!
> feat(subscription): Public repo and sandbox max

- packages/app/src/app/graphql/types.ts
- packages/app/src/app/overmind/effects/gql/dashboard/fragments.ts
- packages/app/src/app/pages/Dashboard/Sidebar/BottomMessages/TrialExpiring.tsx
- packages/app/src/app/pages/Dashboard/Sidebar/index.tsx
Passing `cancelAtPeriodEnd` flag to the trial CTA in the sidebar
> fix(end-of-trial): show different message if trial has been canceled

- packages/app/src/app/pages/Dashboard/Content/routes/Settings/TeamSettings/ManageSubscription/index.tsx
- packages/app/src/app/pages/Dashboard/Content/routes/Settings/TeamSettings/ManageSubscription/stripe.tsx
Compared to the design, I had to drop some information we unfortunately don't have for stripe users:
* We don't have the price unit to show how much users will be billed
* We don't have the next billing date
Active trial
Cancelled trial
I believe we need to start modelling more details around the trial and subscription. We have the concept of an `ACTIVE` subscription, but we also have a `canceledAt` date time as well as a `cancelAtPeriodEnd` flag. For now I would leave it as it is, until after the release, but we could introduce for better clarity the following booleans:
* **isPro** - instead of checking for active subscription or trialing or any other combination, just return true or false if pro features apply for this user in this workspace
* **hasActiveSubscription** - this should …
> feat: add trial information on subscription card

- packages/app/src/app/graphql/types.ts
- packages/app/src/app/overmind/effects/gql/dashboard/fragments.ts
- packages/app/src/app/pages/Dashboard/Components/Branch/NewBranch.tsx
- packages/app/src/app/pages/Dashboard/Components/Branch/index.tsx
- packages/app/src/app/pages/Dashboard/Components/Header/index.tsx
- packages/app/src/app/pages/Dashboard/Components/Repository/ImportRepository.tsx
- packages/app/src/app/pages/Dashboard/Components/Repository/index.tsx
- packages/app/src/app/pages/Dashboard/Components/VariableGrid/index.tsx
- packages/app/src/app/pages/Dashboard/Content/routes/Repositories/index.tsx
- packages/app/src/app/pages/Dashboard/types.ts
- packages/app/src/app/pages/Pro/legacy-pages/WorkspacePlanSelection.tsx
Closes XTD-360 (2/2)
- ### Adds `viewOnly` flag to private repositories on teams that don't have an active subscription:
|Grid|
|:-:|
|![xwgwi1-3000 preview csb app_dashboard_repositories_github_olarclara_climbr_workspace=47968439-c1ee-494c-a6e1-ec7ea18ab162](https://user-images.githubusercontent.com/24959348/201800440-e3c3e828-772a-435c-b8c7-ce080b6e5cba.png)|
|List|
|:-:|
|![xwgwi1-3000 preview csb app_dashboard_repositories_github_olarclara_climbr_workspace=47968439-c1ee-494c-a6e1-ec7ea18ab162 (1)](https://user-images.githubusercontent.com/24959348/201800491-6f5dd3db-5ab6-4644-93e4-cf5457e21136.png)|
- ### Disables the `new branch` action on  private repositories on teams that don't have an active subscription:
|Grid|
|:-:|
|![xwgwi1-3000 preview csb …
> feat(subscription): enforce repositories limits

- packages/app/src/app/components/CreateSandbox/Import/Import.tsx
- packages/app/src/app/components/CreateSandbox/queries.ts
- packages/app/src/app/graphql/types.ts
- packages/app/src/app/hooks/useCreateCheckout.ts
- packages/app/src/app/pages/Dashboard/Content/routes/Repositories/index.tsx
- packages/app/src/app/pages/Dashboard/Content/routes/Sandboxes/index.tsx
- packages/app/src/app/pages/Dashboard/Content/routes/Settings/TeamSettings/ManageSubscription/upgrade.tsx
- packages/app/src/app/pages/Dashboard/Content/routes/Settings/TeamSettings/RegistrySettings.tsx
- packages/app/src/app/pages/Dashboard/Content/routes/Settings/components/Alert.tsx
- packages/app/src/app/pages/Dashboard/Content/routes/Settings/components/PermissionSettings.tsx
- packages/app/src/app/pages/Pro/legacy-pages/WorkspacePlanSelection.tsx
Prevents importing private repositories if the team doesn't have an active subscription.
Part of XTD-360 1/2
https://www.loom.com/share/d749e2970b77467bbb3acfee92f7cf31
1. Launch the app
2. Select a team w/o an active subscription
3. Open the import modal
4. Try to import a private GitHub repo
> feat(import): prevent if repo is private and account is free

- packages/app/src/app/pages/Dashboard/Components/UpgradeBanner/UpgradeBanner.tsx
- packages/app/src/app/pages/Dashboard/Content/routes/Recent/index.tsx
- Fixes the "Learn more" link if the workspace is not eligible for a trial
- Hides the upgrade banner is the workspace is a personal team
1. Sign up as a user with a free personal account
2. No banner should be shown
> fix(subscriptions/banner): hide upgrade banner and fix not eligible for trial link

- packages/app/src/app/pages/Dashboard/Content/routes/Repositories/index.tsx
- packages/app/src/app/pages/Dashboard/Content/routes/Repositories/stripes.tsx
- Centralizes the stripe messages for the repositories page:
- Max amount of public repositories (currently disabled)
- Selected repo is private and the team doesn't have an active subscription
No visual indicator of why the repository is read-only:
|Current|
|:-:|
|![codesandbox stream_dashboard_repositories_github_olarclara_project-template-nuxt_workspace=608e42de-934e-4a76-80ec-8addda9c620a](https://user-images.githubusercontent.com/24959348/202014849-9482c885-f855-4010-b054-75a0de8302a7.png)|
There's a banner explaining why it's read-only and a call to action to upgrade/start a trial.
|Admin|
|:-:|
|![1x54ks-3000 preview csb app_dashboard_repositories_github_olarclara_climbr_workspace=47968439-c1ee-494c-a6e1-ec7ea18ab162](https://user-images.githubusercontent.com/24959348/202015925-d1a …
> feat(subscriptions): stripe banner in repository view

- packages/app/src/app/components/CreateSandbox/CreateSandbox.tsx
- packages/app/src/app/components/WorkspaceSelect/WorkspaceSelect.tsx
- packages/app/src/app/pages/Dashboard/Components/Branch/BranchCard.tsx
- packages/app/src/app/pages/Dashboard/Components/Branch/BranchListItem.tsx
- packages/app/src/app/pages/Dashboard/Components/Repository/RepositoryCard.tsx
- packages/app/src/app/pages/Dashboard/Components/Repository/RepositoryListItem.tsx
- packages/app/src/app/pages/Dashboard/Components/Sandbox/NewMasterSandbox.tsx
- packages/app/src/app/pages/Dashboard/Components/Sandbox/SandboxCard.tsx
- packages/app/src/app/pages/Dashboard/Components/Sandbox/SandboxListItem.tsx
- packages/app/src/app/pages/Dashboard/Components/Sandbox/index.tsx
- packages/app/src/app/pages/Dashboard/Components/Selection/ContextMenus/RepositoryMenu.tsx
- packages/app/src/app/pages/Dashboard/Components/Selection/ContextMenus/SandboxMenu.tsx
- packages/app/src/app/pages/Dashboard/Components/SyncedSandbox/SyncedSandboxListItem.tsx
- packages/app/src/app/pages/Dashboard/Content/routes/Settings/TeamSettings/WorkspaceSettings.tsx
- packages/app/src/app/pages/Dashboard/Content/routes/Settings/UserSettings/WorkspaceSettings.tsx
- packages/app/src/app/pages/Pro/components/Switcher.tsx
- packages/app/src/app/pages/Sandbox/Editor/Header/WorkspaceName/UpgradeToolTip.tsx
- packages/components/src/components/Badge/index.stories.tsx
- packages/components/src/components/Badge/index.tsx
Quite some changes, but mostly updating the `Badge` component to reflect the prism version: 20px height, 12px font-size and same API
Still todo:
> feat(view-only): show badge on sandboxes and repos

- packages/app/src/app/components/CreateSandbox/Import/Import.tsx
- packages/app/src/app/components/CreateSandbox/Import/importLimits.tsx
- packages/app/src/app/constants.ts
- packages/app/src/app/hooks/useSubscription.ts
- packages/app/src/app/pages/Dashboard/Components/UpgradeBanner/UpgradeBanner.tsx
- Extracts import limits to a different file.
- Blocks the import form if the workspace has reached the limit for max public repos.
- Adds tracking to upgrade CTA when attempting to import a private repo.
- No UI limitation if the workspace has reached the limit for max public repos.
- Dims UI and removes form controls if importing is not allowed.
|Admin|Non-admin|
|:-:|:-:|
|![qqmd2g-3000 preview csb app_dashboard_recent_workspace=608e42de-934e-4a76-80ec-8addda9c620a](https://user-images.githubusercontent.com/24959348/202044155-088a46c5-1252-4af3-b9bb-64e41a0aff9c.png)|![qqmd2g-3000 preview csb app_dashboard_repositories_workspace=608e42de-934e-4a76-80ec-8addda9c620a](https://user-images.githubusercontent.com/24959348/202288806-2ae12896-730f-492f-9f65-e5806344b9d1.png)|
1. Launch the …
> feat(subscriptions): import limitations

- packages/app/src/app/pages/Dashboard/Content/routes/Repositories/index.tsx
Re-enables limitations on UI for teams w/o an active subscription with 3+ public repositories.
2. Select a team w/o an active subscription
3. If the team has 3+ public repositories
- Stripe banner is show
- "Import repo" action is disabled in both list and grid view
> feat(subscriptions): max public repos limitations

- packages/app/src/app/components/CreateSandbox/CreateSandbox.tsx
- packages/app/src/app/components/CreateSandbox/SearchResults/SearchResultList.tsx
- packages/app/src/app/components/CreateSandbox/SearchResults/SearchResults.tsx
- packages/app/src/app/components/CreateSandbox/TemplateCard.tsx
- packages/app/src/app/components/CreateSandbox/TemplateCategoryList.tsx
- packages/app/src/app/components/CreateSandbox/elements.ts
- packages/app/src/app/components/CreateSandbox/stripes.tsx
- packages/app/src/app/pages/Dashboard/Components/Selection/ContextMenus/MultiItemMenu.tsx
- packages/app/src/app/pages/Dashboard/Components/Selection/ContextMenus/SandboxMenu.tsx
- packages/app/src/app/pages/Dashboard/Components/Selection/index.tsx
- packages/app/src/app/pages/Dashboard/Components/TemplatesRow/TemplatesRow.tsx
- packages/app/src/app/pages/Dashboard/Content/routes/Sandboxes/index.tsx
- Adds stripe banner to the sandboxes page if the workspace has 20+ items:
- Adds stripe banner to the create sandbox modal if the workspace has 20+ items:
- Also handles disabling the template cards. 
|Templates list|Search results list|
|:-:|:-:|
|![m6m2dw-3000 preview csb app_s](https://user-images.githubusercontent.com/24959348/202638879-d2b825db-3ce7-43ec-b707-3429cc75a1fb.png)|![m6m2dw-3000 preview csb app_s (1)](https://user-images.githubusercontent.com/24959348/202639078-d0e19aaf-2376-4045-ad07-942a0b5b4e1c.png)|
- Removes 'Create new sandbox' from the container menu:
- I haven't disabled the `Fork sandbox` from the context menu because it creates sandboxes as drafts.
- Moving drafts to sandboxes
- Right now it doesn't have any feedback such as a `not-allowed` cursor.
- It's still …
> feat(subscriptions/sandboxes): soft limits

- packages/app/src/app/components/StripeMessages/FreeViewOnlyStripe.tsx
- packages/app/src/app/components/StripeMessages/index.tsx
- packages/app/src/app/pages/Sandbox/Editor/index.tsx
_Don't mind the editing in the screenshot - this has been resolved._
The `freePlanEditingRestricted` flag is `true` when accessing a private sandbox on a free account. If this is the case the message stripe should show up. Let me know if you need help setting this up! The flag is enabled on stream, not yet on production.
> feat(subscription): Add free team view only stripe to editor page

- packages/app/src/app/components/CreateSandbox/CreateSandbox.tsx
- packages/app/src/app/components/CreateSandbox/SearchResults/SearchResults.tsx
- packages/app/src/app/components/CreateSandbox/TemplateCategoryList.tsx
Unless the current page is under a collection (`/dashboard/sandboxes/*`), enables the create sandbox modal cards.
https://user-images.githubusercontent.com/24959348/203142671-b98d2ac9-fbc8-4dd9-81e2-686df8083e18.mov
2. Select a free team w/ 20+ public sandboxes
3. In collections (`/sandboxes`), launch the create modal
- Template cards are disabled
- Stripe message is shown
4. In other pages (such as `/drafts` and `/s`), launch the create modal
- Template cards are enabled
> feat(subscriptions): only restrict new sandbox if view collection and max amount reached

- packages/app/src/app/components/CreateSandbox/stripes.tsx
- packages/app/src/app/hooks/useSubscription.ts
- packages/app/src/app/pages/Dashboard/Content/routes/Settings/TeamSettings/WorkspaceSettings.tsx
- Fixes `MaxPublicSandboxes` for non-admin users by adding the proper links.
- Adds call to action to upgrade for max free editors.
- Adds message and call to action when the team has 20+ editors.
|20+ editors|
|:-:|
|![jbb2pl-3000 preview csb app_dashboard_settings_workspace=b5123bcc-da66-446f-88e2-5b89c9c37d27](https://user-images.githubusercontent.com/24959348/203468396-7a815428-cb7d-413d-ab92-d42e914256f6.png)|
|5+ editors (free)|
|:-:|
|![jbb2pl-3000 preview csb app_dashboard_settings_workspace=b5123bcc-da66-446f-88e2-5b89c9c37d27 (1)](https://user-images.githubusercontent.com/24959348/203468431-29de8474-a66b-43a2-91f0-b41517e5fea5.png)|
> feat(subscriptions): organization plan cta when 20+ editors

- packages/app/src/app/pages/Sandbox/Editor/index.tsx
Before:
After:
How to test:
1. Open a private sandbox on a free team (view only)
2. MessageStripe should no longer overlap the header in the editor
> fix(editor): MessageStripe overlapping header

- packages/app/src/app/pages/Dashboard/Components/Branch/index.tsx
Badge shown on the recent page
Not anymore on the repo page
Might be an idea to replace the `Beta` tag maybe with a view only at the top of the repo page (header)
> fix: remove viewOnly badge from branches inside the repo page

- packages/app/src/app/pages/Sandbox/Editor/Header/Collaborators/Collaborators.tsx
Add </OutsideClickHandler> from the existing package used in the project. It's a patch fix, probably this should be part of the Popover implemention in prism later on
> fix: close onboarding tooltip on click outside

- packages/app/src/app/pages/Dashboard/Content/routes/Repositories/stripes.tsx
- packages/app/src/app/pages/Dashboard/Content/routes/Sandboxes/index.tsx
Tex change to limit banner
Validated that the additional text didn't cause any major issues on various screen sizes - It's wordy on mobile but it looks kind of verbose even without the additional text which makes me wonder if we should have a different banner on small screens, but that's a discussion for a different ticket.
> Add reference to private SBXs and Repos on Pro

- packages/app/integration-tests/tests/sandboxes.test.js
- packages/vue3-browser-compiler/package.json
- packages/vue3-transpiler/src/index.ts
- packages/vue3-transpiler/src/select.ts
- packages/vue3-transpiler/src/stylePostLoader.ts
- packages/vue3-transpiler/src/templateLoader.ts
- yarn.lock
Given a Vue template with `style`, `script`, and `template` tags, the Vue transpiler needs to consider that `style` might be deleted at some point and there is no way to transpile this piece of code.
Plus, I upgrade `@vue/compiler-sfc` in order to support `<script setup>` new template config.
Maybe fix https://github.com/codesandbox/codesandbox-client/issues/6762
> fix: vue transpiler

- packages/app/src/app/hooks/useWorkspaceLimits.ts
- packages/app/src/app/pages/Dashboard/Content/routes/Repositories/index.tsx
- packages/app/src/app/pages/Dashboard/Content/routes/Repositories/stripes.tsx
Added `hasMaxPrivateRepositories` property to `useWorkspaceLimits` hook, so we're now able to show the message stripe to notify users that the max amount of private repositories has been reached. This is only a restriction for free users.
> fix(dashboard): Show MessageStripe when private repo limit is hit

- packages/vue3-transpiler/src/index.ts
- packages/vue3-transpiler/src/templateLoader.ts
Vue transpiler should use the hash of filename/query as the id, not a uuid, I assume it's because of hmr and replacing the correct element.
Haven't been able to break the current logic so not sure where this would show, but best to stay in sync with the vue plugins the maintainer of vue wrote.
Some vite code for reference: https://github.com/vitejs/vite/blob/main/packages/plugin-vue/src/template.ts#L109
Update: Tested a bunch of things, doesn't seem to be making a difference, but at least it should be faster and perhaps they don't use the id's for script yet? (also wouldn't be very semver compatible if they changed this now)
Uses uuid for hmr
Uses filename hash
> fix(vue): Use the correct id for vue compiler to ensure correct hmr logic

- packages/app/src/app/overmind/namespaces/dashboard/actions.ts
If the action to get repos is transparent (ie: first visibly fetch unsynced data and then silently fetch synced data), hide error notifications originating from a timeout because that can happen if there's too much data from GitHub.
- Turn on throttling to a slow network to make it easier to test
- Launch the dashboard
- Select a team with repos that have hundreds of branches
- See that the first call with unsynced data succeeds
- See that the second call with synced data throws a 504
> fix(dashboard/repositories): silently fail get repos

- packages/app/src/app/constants.ts
- packages/app/src/app/hooks/useCreateCustomerPortal.ts
- packages/app/src/app/overmind/actions.ts
- packages/app/src/app/overmind/namespaces/pro/actions.ts
- packages/app/src/app/pages/Dashboard/Content/routes/Settings/TeamSettings/ManageSubscription/index.tsx
- packages/app/src/app/pages/Dashboard/Content/routes/Settings/TeamSettings/ManageSubscription/paddle.tsx
- packages/app/src/app/pages/Dashboard/Content/routes/Settings/TeamSettings/ManageSubscription/stripe.tsx
- packages/app/src/app/pages/common/Modals/SubscriptionCancellation/SubscriptionCancellation.tsx
- packages/app/src/app/pages/common/Modals/SubscriptionCancellation/index.tsx
- packages/app/src/app/pages/common/Modals/index.tsx
- packages/app/src/app/utils/pluralize.ts
- packages/components/src/components/Badge/index.stories.tsx
- packages/components/src/components/Badge/index.tsx
2. Select a pro team that you are an admin
3. Go to settings -> "Cancel trial/Manage subscription"
4. See modal
5. Clicking on "Continue trial/Keep subscription", dismisses modal
6. Clicking on "I understand" opens the customer portal
> feat(subscription/polish): cancel subscription modal

- packages/app/src/app/pages/VercelAuth/index.js
The vercel callback passes multiple params with the newer integration, so this is fixed by taking the code value only from the query string
> fix: vercel integration

- packages/app/src/app/overmind/actions.ts
- packages/app/src/app/overmind/namespaces/dashboard/actions.ts
- packages/app/src/app/overmind/namespaces/dashboard/state.ts
- packages/app/src/app/pages/Dashboard/Content/routes/Repositories/index.tsx
Remodels the state in a record of teams and their repositories. This way, because canceling pending promises when changing the active team is not possible to implement, we make sure the data doesn't get overridden when delayed fetches are finished.
- Go to the repositories page
- Expected: loading state is shown and then, if the fetch is successful, it shows the list of repos.
- Select a repo from the list
- Expected: list of branches from the selected repo is shown w/o a loading state in between. 
- Navigate back to the list of repositories using the breadcrumbs.
- Expected: list of repos is show w/o a loading state in between.
- Select a repo from the list
- Refresh the page
- Expected: same repo is shown w/ a loading state (it's the only repo fetched to get data faster)
- Navigate back …
> fix: delayed repos fetch

- packages/components/src/components/ExternalCard/ArticleCard.tsx
- packages/components/src/components/ExternalCard/VideoCard.tsx
- packages/components/src/components/ExternalCard/elements.ts
- packages/components/src/components/ExternalCard/index.stories.tsx
- packages/components/src/components/ExternalCard/index.tsx
- packages/components/src/components/Icon/icons.tsx
Closes XTD-481.
Closes XTD-482.
- Creates `VideoCard`;
- Creates `ArticleCard`;
They are placed in the components section to make visual testing easier with Storybook since this component will be integrated on an upcoming task.
|Article|Video|
|:-:|:-:|
|![Screen Shot 2022-12-07 at 18 23 01](https://user-images.githubusercontent.com/24959348/206299519-6b0ad7d0-8549-477c-be5b-9a3a8e563987.png)|![Screen Shot 2022-12-07 at 18 23 19](https://user-images.githubusercontent.com/24959348/206299527-620bbf84-2177-48a0-8d8c-284c5c00f11b.png)|
> feat(dashboard/components): ExternalCard: article and video variant

- packages/app/src/app/pages/Dashboard/Content/routes/Search/searchItems.ts
- packages/app/src/app/pages/Dashboard/Header/index.tsx
Fixes three things:
1. Whenever we would do a search, we would fetch sandboxes but not update the search after the fetch is done. This made it look like search is broken, because you always get 0 results back (for your first few searches).
2. When you have a search with 1 character, it would lead you to an empty search page with no search query. It should search instead.
3. When you empty the search bar, it would also lead you to an empty search page. You should go to the dashboard overview instead.
Also improves efficiency of searching, before we used to recalculate the index for every new query. Now we recalculate the search index only if the data changes.
> fix: dashboard search loading and URL

- packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Explorer/Dependencies/Dependency/index.tsx
If you've configured a version for a dependency in `package.json` that doesn't match the version list, we randomly select a version from the version selector. Like here:
That's a bit confusing. With this change, we add the dependency that's in package.json to the list in case it's not in the list, so you'll get a view like this:
> fix(dependencies): show right version in version dropdown

- packages/app/src/app/pages/Dashboard/Components/Folder/FolderListItem.tsx
- packages/app/src/app/pages/Dashboard/Components/Sandbox/SandboxCard.tsx
- packages/app/src/app/pages/Dashboard/Components/Sandbox/SandboxListItem.tsx
- packages/app/src/app/pages/Dashboard/Components/Sandbox/index.tsx
A few fixes on the selected and focused states for sandbox cards and list items. Including the alignment of list item columns and some fixes for focusing the more button.
Selection
> fix: select and focus state for cards and list items

- packages/app/src/app/hooks/useCreateCheckout.ts
- packages/app/src/app/pages/Dashboard/Components/UpgradeBanner/UpgradeBanner.tsx
- packages/app/src/app/pages/Dashboard/index.tsx
Shows notification when a subscription through Stripe has been successful. Based on if the subscription webhook from Stripe came through fast enough we well show the user more information and an action.
1. Open the dashboard with a team without trial
2. Start a trial
3. When redirected by Stripe, it should show a notification on the dashboard
Based on if your internet speed and device are faster than the webhook, you should see different notifications. When the webhook didn't come yet in you should see a refresh action in the notifications. To mock the refresh action notification, you can also open the dashboard for a team without trial and add `&stripe=success` to the url. To mock the notification without action, you can add `&stripe=success` to the url for a team that already has a …
> feat(XTD-348): Stripe success param

- packages/app/src/app/overmind/namespaces/dashboard/actions.ts
- packages/app/src/app/overmind/namespaces/dashboard/state.ts
- packages/app/src/app/pages/Dashboard/Components/TemplatesRow/TemplatesRow.tsx
- packages/app/src/app/pages/Dashboard/Content/routes/Deleted/index.tsx
- packages/app/src/app/pages/Dashboard/Content/routes/Drafts/index.tsx
- packages/app/src/app/pages/Dashboard/Content/routes/Liked/EmptyLikes.tsx
- packages/app/src/app/pages/Dashboard/Content/routes/Liked/index.tsx
- packages/app/src/app/pages/Dashboard/Content/routes/MyContributions/EmptyContributions.tsx
- packages/app/src/app/pages/Dashboard/Content/routes/MyContributions/index.tsx
- packages/app/src/app/pages/Dashboard/Content/routes/Recent/EmptyRecent.tsx
- packages/app/src/app/pages/Dashboard/Content/routes/Recent/index.tsx
- packages/app/src/app/pages/Dashboard/Content/routes/Repositories/EmptyRepositories.tsx
- packages/app/src/app/pages/Dashboard/Content/routes/Repositories/index.tsx
- packages/app/src/app/pages/Dashboard/Content/routes/Sandboxes/index.tsx
- packages/app/src/app/pages/Dashboard/Content/routes/Shared/index.tsx
- packages/components/src/components/CreateCard/CreateCard.stories.tsx
- packages/components/src/components/CreateCard/CreateCard.tsx
- Updates the `CreateCard` to receive two props `title` and `label` (optional). The goal is to display the suggested repositories similarly to the imported repositories:
- Removes the view toggle, filter, and sort options from empty pages.
- Recent
- Shared
- Likes
- Contribution branches
- Repositories
- Drafts
- Sandboxes
- Deleted
- Hides suggested sandboxes if fetching the curated trending collection fails.
> chore(dashboard): misc updates

- packages/app/src/app/components/CreateSandbox/utils/api.ts
- packages/app/src/app/overmind/actions.ts
- packages/app/src/app/overmind/effects/api/apiFactory.ts
- packages/app/src/embed/components/App/index.js
This is a very basic change, but will help the backend team determine how the endpoints are used. Will follow-up with something similar on the codesandbox-applications side.
> chore: add client headers for backend analytics

- packages/app/src/app/pages/Dashboard/Content/routes/Deleted/index.tsx
- packages/components/src/components/Loading/Loading.stories.tsx
- packages/components/src/components/Loading/Loading.tsx
- packages/components/src/components/Loading/index.tsx
- packages/components/src/index.ts
- Imports the loading component from codesandbox-applications.
- Updates the logic to manage the internal state of the deleted page.
- Renders the loading instead of the variable grid according to the current state.
https://user-images.githubusercontent.com/24959348/209046784-3332ee21-82aa-409b-8ea3-7b320042179b.mov
https://user-images.githubusercontent.com/24959348/209046787-68328327-f97d-49fd-b699-4ecbf7098273.mov
> pages(deleted): update loading state

- packages/app/src/app/pages/Dashboard/Components/NewTeamModal/TeamMembers.tsx
Instead of removing the call to action, I updated the internals of the invitation to make the role of invitees based on the current user's role.
- If the user is an admin, the role of invitees is "write".
- If the user's role is other than admin, the role of invitees is "read".
> feat(invite): conditional authorization

- packages/app/src/app/overmind/namespaces/dashboard/actions.ts
- packages/app/src/app/pages/Dashboard/Content/routes/RepositoryBranches/index.tsx
Some branches/repositories come without a `lastAccessedAt` timestamp, which was breaking the sort algorithm and triggered different results in chrome and firefox.
> fix: remove unaccessed branches/repos from sorting

- packages/app/src/app/pages/Dashboard/Sidebar/index.tsx
> fix: duplicate message when trial is close to expire

- packages/app/src/app/components/StripeMessages/FreeViewOnlyStripe.tsx
- packages/app/src/app/overmind/namespaces/workspace/actions.ts
- packages/app/src/app/pages/Dashboard/Components/Selection/ContextMenus/SandboxMenu.tsx
- packages/app/src/app/pages/Sandbox/Editor/Header/Actions.tsx
- packages/app/src/app/pages/Sandbox/Editor/index.tsx
- packages/common/src/components/Preview/index.tsx
Creating private sandboxes for free teams is pretty easy when you have another pro team. On the pro team create a draft and make it private. In the dashboard, fork the draft a couple of times if you want to have multiple private sandboxes available. Then, move the sandbox to a folder via the context menu and make sure to select a free team. The sandbox is now moved to a free team, with restrictions in place.
<details>
<summary>As a PRO user forking a private or unlisted sandbox works</summary>
1. Open the dashboard on the sandboxes page for a PRO user
2. Right click a private sandbox
3. Confirm the option to make the sandbox public exists
4. Confirm the option to fork the sandbox exists
5. Fork the sandbox
1. Open the dashboard on the sandboxes page for a PRO user
2. Open a private …
> feat(privacy): Handle private sandbox forking and making public

- packages/components/src/components/Text/index.tsx
- packages/components/src/components/Text/text.stories.tsx
`truncate` adds the overflow styles to avoid duplicating them in the new cards that are being redesigned
> feat: add trucate prop for Text component

- packages/app/src/app/pages/Dashboard/Components/Branch/BranchCard.tsx
- packages/app/src/app/pages/Dashboard/Components/SyncedSandbox/SyncedSandboxCard.tsx
Adding truncate on existing card implementations. Still need to rely on some overflows placed around certain elements, which I don't particularly dig, but I also don't see another solution in a fluid card sizing
> chore: use Text truncate for existing cards

- packages/app/src/app/hooks/useDashboardVisit.ts
- packages/app/src/app/pages/Dashboard/Components/UpgradeBanner/UpgradeBanner.tsx
- packages/app/src/app/pages/Dashboard/index.tsx
Closes XTD-517.
Instead of using cookies, I decided to use the local storage following @tristandubbeld's suggestion here: https://github.com/codesandbox/codesandbox-client/pull/7243#discussion_r1050630876.
https://www.loom.com/share/e4b6610b135b4b7ba569568b6791fec2
> feat(dashboard/recent): hide upgrade banner on first visit

- packages/template-icons/tsconfig.json
Removes `emitDeclarationOnly` flag as it conflicts with `--noEmit` when running `tsc`.
> fix(typecheck): Remove emitDeclarationOnly flag

- packages/app/src/app/graphql/types.ts
- packages/app/src/app/overmind/effects/api/index.ts
- packages/app/src/app/overmind/effects/gql/dashboard/mutations.ts
- packages/app/src/app/overmind/namespaces/dashboard/actions.ts
Closes XTD-529.
Replaces the previous API call that would remove a branch from a repo with a gql mutation that deletes a branch given the id. With this new method, we can delete contribution branches even if the parent repo has been deleted.
2. Click on "remove branch from CodeSandbox" in any branch card
3. Branch should be removed as expected
> feat(dashboard): replace api call w/ gql mutation to delete branches

- packages/app/src/app/pages/Dashboard/Content/routes/Liked/EmptyLikes.tsx
Fixes a regression where there was no space between the title and the suggested sandboxes in the "empty likes" view.
> fix(dashboard): empty likes spacing

- packages/common/src/templates/index.ts
- packages/common/src/templates/remix.ts
The name of the Remix template was named `remix-starter` so I changed the name to fix the icon. It currently shows the React icon though, so we should update that.
1. Open the create new modal
2. Click through all the tabs to see if it doesn't crash
3. In the official templates, there should be a Remix template with a React icon
> fix(icons): Rename remix to remix-starter to fix icon

- packages/app/src/app/pages/Dashboard/Content/routes/Settings/TeamSettings/WorkspaceSettings.tsx
Fixes #7334. Subscription can be `null` or `undefined`. Feel free to merge this PR when approving!
> fix(settings): Add optional chaining to potentially undefined or null object

- packages/app/src/app/pages/Dashboard/Components/Selection/ContextMenus/CommunitySandboxMenu.tsx
- packages/app/src/app/pages/Dashboard/Components/Selection/ContextMenus/MasterMenu.tsx
- packages/app/src/app/pages/Sandbox/Editor/Header/Collaborators/ButtonActions.tsx
Before
After
Also changed some other copy messages I found that were all capital words
> fix: share popup copy

- packages/app/src/app/components/StripeMessages/UpgradeSSEToV2.tsx
- packages/app/src/app/pages/Sandbox/Editor/index.tsx
- packages/components/src/components/MessageStripe/MessageStripe.tsx
- yarn.lock
This PR adds a new banner at the top of SSE sandboxes giving the opportunity for users to upgrade their sandbox into a V2 cloud sandbox. If they do not have "write_code" permissions, it will instead fork it into a V2 cloud sandbox.
> feat(cloud sandboxes): Banner for upgrading to V2

- packages/app/src/app/graphql/types.ts
- packages/app/src/app/overmind/effects/gql/dashboard/fragments.ts
- packages/app/src/app/pages/Dashboard/Components/Sandbox/TemplateIcon.tsx
If a sandbox is a template, we should show that as the template icon. But right now we show the template icon it is forked from. This would fix that.
> fix: template icon for templates

- packages/app/src/app/components/dashboard/Textarea.tsx
- packages/app/src/app/hooks/useWorkspaceAuthorization.ts
- packages/app/src/app/pages/Dashboard/Components/NewTeamModal/TeamMembers.tsx
- packages/app/src/app/pages/Dashboard/Content/routes/Recent/RecentHeader.tsx
- Hides the `Invite members` card on the recent page for members who are viewers of the team.
- Adds copy to the invitation modal explaining the role of invitees.
- UI adjustments.
|Admins|Editors|
|:-:|:-:|
|![ut8gkw-3000 preview csb app_dashboard_recent_workspace=cab9e635-ec49-4c82-806c-c521babd3a6c (1)](https://user-images.githubusercontent.com/24959348/213560557-d493a05d-bfd9-4a34-baf7-51c3f7991cdc.png)|![ut8gkw-3000 preview csb app_dashboard_recent_workspace=cab9e635-ec49-4c82-806c-c521babd3a6c (2)](https://user-images.githubusercontent.com/24959348/213560587-ba152b21-0826-4ca9-8b94-79997b67ea38.png)|
> feat(dashboard): update team members invitation modal

- packages/app/src/app/components/CreateSandbox/CreateSandboxModal.tsx
When navigation to a different url through the client side route change (`react-router` `Link`) the create new modal will now be closed.
Modal will persist when navigating.
Modal will close when navigating.
1. Log in and navigate to the dashboard
2. Select a free team
3. Open the create new modal on the import tab
4. Try to import a private repository
5. Follow the link to the pro page in the error message
6. Modal should be closed
> feat(create-new): Close create sandbox modal when navigating to a different page

- packages/app/src/app/components/CreateSandbox/CreateSandbox.tsx
- packages/app/src/app/components/CreateSandbox/SearchResults/SearchResultList.tsx
- packages/app/src/app/components/CreateSandbox/TemplateCard.tsx
- packages/app/src/app/components/CreateSandbox/queries.ts
- packages/app/src/app/components/CreateSandbox/utils/api.ts
- packages/app/src/app/graphql/types.ts
Changed the team name query for templates from `collection -> team -> name` to `team -> name` as sometimes templates are created in draft and moved to templates by the team, so they don't belong to any collection. Not sure why the query was originally like that.
This changes the `GitHub` fallback label under some of the templates to `CodeSandbox` or the correct owner (user or team)
Because `/official` and `/essential` are still two REST endpoints we use to show some of the templates in the create modal, I decided to hardcode `CodeSandbox` there for now, to have it show nice in prod and later we can update the endpoints.
Before
After
> fix: template owner

- packages/app/src/app/pages/Dashboard/Components/EmptyPage/index.tsx
Aligns the "create" buttons and the information cards with the recent sandboxes and branch cards.
Closes XTD-564
> fix(dashboard): Align recent page grid columns

- packages/app/src/app/components/StripeMessages/UpgradeSSEToV2.tsx
I was passing the incorrect value into the fork api endpoint. It was not properly converting the sandbox into V2.
It would redirect to the v2 fork of the sandbox, but if you re-opened it from the dashboard it would be v1.
The newly forked sandbox will always be v2
> fix(upgrade): Pass correct property to fork api call

- packages/app/src/app/pages/Dashboard/Sidebar/BottomMessages/TrialExpiring.tsx
Changed the conditional to show the "update payment method" message to always (5 days before end) show up properly rather than just two days before the end of the trial.
Closes XTD-607
> fix(sidebar): Show payment method text and CTA when applicable

- packages/app/src/app/components/CreateSandbox/SearchResults/SearchResults.tsx
Git templates clutter the template search quite a bit. We have over 1.7M templates, of which 1.62M are git. They make the template search unusable. We now mark which template is git, and make sure to filter those out, as less than 1% of the git templates are really valuable.
> fix: don't show git templates in the template search

- packages/app/src/app/overmind/namespaces/dashboard/actions.ts
- packages/app/src/app/pages/Dashboard/Components/NewTeamModal/TeamInfo.tsx
- packages/app/src/app/pages/Dashboard/Content/routes/Settings/TeamSettings/WorkspaceSettings.tsx
Closes XTD-609.
- Allows whitespace in team names when creating a new team.
- Fixes whitespace behavior in team names when editing an existing team.
> fix(dashboard): create/edit team name

- packages/app/src/app/overmind/effects/api/index.ts
- packages/app/src/app/overmind/internalActions.ts
- packages/app/src/app/overmind/state.ts
- packages/app/src/app/pages/Pro/legacy-pages/WorkspacePlanSelection.tsx
- packages/app/src/app/pages/common/Modals/SurveyModal/index.tsx
In rare cases user.subscription can be null for legacy subscriptions. Trying to access the page causes a crash. This is a quick fix but I'll make sure to look into why it can be null but the page can still be accessed. Decided with the BEOPS team that we want to clean up other old `user.subscription` values and use `activeTeamInfo.subscription` instead.
Fixes #7339
Closes XTD-608
> fix(pro): Stop using user.subscription and clean up uses

- packages/app/src/app/components/CreateSandbox/Import/Import.tsx
- packages/app/src/app/components/CreateSandbox/Import/utils.test.ts
- packages/app/src/app/components/CreateSandbox/Import/utils.ts
Closes XTD-298.
Closes XTD-383.
Improve the GitHub import by allowing more formats (`owner/repo` included) and adds tests to verify the utilities.
1. Automated tests to verify that the regular expressions are validating and extracting info as expected.
2. Manually went through the flow to test if the import happens as expected.
- Validated: `owner/repo`, `https://github.com/owner/repo`, and `git@github.com:owner/repo.git`
> feat(dashboard): improve GH import input

- packages/app/src/app/pages/Pro/legacy-pages/WorkspacePlanSelection.tsx
Fixes an error where we render `null`:
> fix(legacy-pro): default to dollar when currency is unavailable

- packages/app/src/sandbox/eval/transpilers/babel/ast/syntax-info.ts
- packages/app/src/sandbox/eval/transpilers/babel/ast/syntax.ts
- packages/app/src/sandbox/eval/transpilers/babel/index.ts
Ensures we transpile dynamic imports in commonjs node modules, this is probably not valid JavaScript, but we should support it regardless.
Fixes #7357
> fix: allow dynamic imports in cjs node_modules

- packages/app/src/app/components/CreateSandbox/CreateSandbox.tsx
- packages/app/src/app/components/CreateSandbox/useTeamTemplates.ts
- packages/common/package.json
- packages/common/src/templates/icons.ts
- packages/common/src/utils/getTemplateIcon.tsx
- yarn.lock
- Anonymous users were seeing an error notification when opening /s, we now don't do the request if not signed in
- Our template icons were fetched from npm when I renamed the package, resulting in old icons
> fix: don't try request when signed in and update template icons

- packages/app/src/app/pages/Dashboard/Content/routes/Settings/UserSettings/WorkspaceSettings.tsx
Closes XTD-645.
Because the `submit` is outside of the `form` element, the action was never triggered. This adds a relationship between the form and the submit button.
> fix(dashboard): user settings form

- packages/app/src/app/components/CreateSandbox/CreateSandboxModal.tsx
Closes XTD-634
Close modal was called for a modal which caused all modals to close. This extra check makes sure it's only called when necessary and the modal is actually open.
> fix(dashboard): Only close modal when modal is open

- packages/app/src/app/components/CreateSandbox/CreateSandboxModal.tsx
- packages/app/src/app/components/CreateSandbox/Import/importLimits.tsx
Closes XTD-634
And this time for real. I've reverted the buggy behaviour that was supposed to close modals on navigation, as it wasn't necessary. I found that the logic to generate the URL and close the create new modal was behaving weird. The "upgrade to pro" URL shows up when a free team tries to import a private repository.
The link can either point to `/pro`, `/docs/*` or Stripe. When it's pointing to `/pro` it stays on the "dashboard" pages and uses a React Router link to navigate. This is done client side, so modals won't close. Adding an `onClick` where we close the modal for this case fixes this.
- The link is pointing to `/pro` when the user is **admin and the stripe URL hasn't been generated yet**
- The link is pointing to `/docs` when the user is **not admin and not on a …
> fix(dashboard): Import link with right URL and close modal after navigation

- packages/app/src/app/components/StripeMessages/UpgradeSSEToV2.tsx
- packages/app/src/app/overmind/namespaces/git/actions.ts
- packages/common/src/types/index.ts
- packages/common/src/utils/url-generator.test.ts
- packages/common/src/utils/url-generator.ts
When upgrading from a V1 sandbox to a V2 repo/sandbox, we want to append `welcome=true` to the query params to show a nice modal on the other end.
There are two ways of using this - 
1. When you fork/upgrade using the new upgrade stripe.
2. When you export your sandbox to github and get redirect to V2.
The redirect URL does not contain `welcome=true`
The redirect URL contains `welcome=true`
> feat(upgrade): Append welcome=true to upgrade redirect URLs

- packages/app/src/app/overmind/actions.ts
- packages/app/src/app/overmind/internalActions.ts
- packages/app/src/app/pages/Dashboard/index.tsx
Closes XTD-632
Closes XTD-630
Closes XTD-631
https://user-images.githubusercontent.com/7533849/215761133-8d62ea0e-cabd-4030-85fa-97221828bb3f.mov
1. First we show that the application gracefully changes to the personal workspace when no id is present in the url or `localStorage`. No message is shown.
2. We then show behaviour when the suggested id is wrong. We change to the personal workspace and make sure we're not trying to fetch any data with the wrong id. We also notify the user that the "saved" id is wrong and we've activated the personal workspace.
3. We than show the same behaviour, but with an existing team id the user does not have access to. This behaves the same way as described above.
4. And finally we use the url with a wrong team id. This behaves the same way as described …
> fix(dashboard): Gracefully change to personal workspace

- packages/app/src/app/hooks/useWorkspaceAuthorization.ts
- packages/app/src/app/pages/Pro/Upgrade.tsx
When creating the checkout URL on the pro page we check if the user is a team admin, but this was only true for team spaces. Changed it to make sure we have an `isAdmin` property unrelated to personal or teams, but just to the user.
> fix(pro): Make personal team user team admin by default

- packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/NotOwnedSandboxInfo/Summary.tsx
Closes XTD-646
Makes sure that all the fork buttons are disabled, as it is not possible to fork a private SSE sandbox on a free team. Disabling the editor still needs to be done, but the flag we use for this (`free_plan_editing_restricted`) always returns `false` for SSE sandboxes. I've asked to look into this with the BEOPS team.
Update: We're disabling the editor in another iteration. I've created various Linear tickets for this.
> fix(sse): Update message and disable forking for free teams

- packages/app/src/app/constants.ts
- packages/app/src/app/pages/common/Modals/SubscriptionCancellation/SubscriptionCancellation.tsx
Change VM spec text 
displays 4GB RAM
displays 3GB RAM
1. Reviewed cancellation modal, pro page and trial invitation on the preview
> Reduce free RAM

- packages/app/src/app/components/CreateSandbox/Import/useForkAndRedirect.ts
- packages/app/src/app/components/CreateSandbox/Import/useImportAndRedirect.tsx
- packages/common/src/utils/url-generator.ts
I already solved this in #7215 but this might go to prod faster. Doesn't make sense to create draft branches by default now that we have the seamless branching in production
Need to test the onboarding flow on the editor side
> fix: redirect to default branch opposed to a new draft one

- packages/app/src/app/components/Preview/DevTools/TerminalUpgrade/elements.tsx
- packages/app/src/app/components/Preview/DevTools/TerminalUpgrade/index.tsx
- packages/app/src/app/components/Preview/DevTools/index.tsx
- packages/app/src/app/components/StripeMessages/UpgradeSSEToV2.tsx
- packages/app/src/app/hooks/useUpgradeFromV1ToV2.ts
- packages/common/src/templates/helpers/react-template.ts
- packages/common/src/templates/template.ts
This PR adds a new devtool tab for client sandboxes. It is a upgrade lever to show users that they can have a terminal in V2.
> feat(upgrade): Add terminal tab to client sandboxes for upgrade lever

- packages/app/src/app/pages/Dashboard/Content/routes/Settings/components/PermissionSettings.tsx
In the past personal pro users could update the minimum privacy, but after changing the conditional it seems that we disabled this. We used to check for `isTeamAdmin` but now we check for `isAdmin` which includes personal workspaces.
Some (pseudo) code from before using `isTeamAdmin` showing that personal pro workspaces shouldn't disable the minimum privacy setting:
```
if (isPersonalWorkspace) {
if (!isPersonalPro) alert = true;
}
else if (!isTeamPro) alert = true;
else if (!isAdmin) alert = true;
[...]
<MinimumPrivacy disabled={Boolean(alert)} />
```
> fix(privacy): Re-enable minimum privacy setting for personal pro

- packages/app/src/app/pages/common/Modals/PreferencesModal/Integrations/GitHubPermissions.tsx
`Autorize` (which is the correct spelling in 🇧🇷 ) -> `Authorize` 🤦🏽‍♀️
> fix(permissions): typo

- packages/app/src/app/pages/Dashboard/Content/index.tsx
- packages/app/src/app/pages/Dashboard/index.tsx
- packages/common/src/utils/url-generator/dashboard.test.ts
- packages/common/src/utils/url-generator/dashboard.ts
Makes the new team modal appear when opening `dashboard?create_team=true`.
https://www.loom.com/share/eac98b5064794efdb8f99f22fd7008a1
1. Go to `/dashboard?create_team=true`.
2. The URL will change to `/dashboard?workspace={id}&create_team=true`
3. The create team modal will open automatically.
> feat(dashboard): support opening new team modal from the url

- packages/app/src/app/graphql/types.ts
- packages/app/src/app/overmind/effects/gql/dashboard/fragments.ts
Regenerating the types to be up to date. However, there was a type mismatch so I had to add the `teamManager` property to `userAuthorizations` a the `teamFragmentDashboard` fragment.
> chore(graphql): Re-generate types and fix TS error

- packages/app/src/app/pages/Dashboard/index.tsx
The redirect to the dashboard on sign-in removed the search params from the URL thus not prompting the new team modal to open, this PR fixes it.
https://www.loom.com/share/502cf0b0bf3c4233add5e38a0b4596b6
> fix: pass search params to redirect after sign-in

- packages/app/src/app/components/StripeMessages/PaymentPending.tsx
- packages/app/src/app/hooks/useDismissible.ts
- packages/app/src/app/hooks/useWorkspaceSubscription.ts
- Adds the option to dismiss the banner.
- Adds a new field `hasExpiredTeamTrial` to the `useWorkspaceSubscription` hook.
- Updates the copy of the payment pending banner to handle expired trials.
- Adds tracking to the banner actions.
|Expired trial (non-admin)|
|:-:|
|![b9m0xn-3000 preview csb app_dashboard_recent_workspace=0035a776-40cc-40a4-847a-416f2006e254 (1)](https://user-images.githubusercontent.com/24959348/219499710-5bad3e2c-efd3-479f-b665-8c06fa55c8f1.png)|
2. Visit a team with an unpaid subscription
> feat(dashboard): update pending payment banner

- packages/app/src/app/components/CreateSandbox/Import/utils.test.ts
- packages/app/src/app/components/CreateSandbox/Import/utils.ts
Updates the `getOwnerAndRepoFromInput` to handle more cases. I tried getting rid of the most complex regular expressions because they can make maintainability harder, instead, it checks some cases separately.
> fix(import): extract owner and repo from input

- packages/app/package.json
- yarn.lock
Should fix Sentry issue 1483077395.
The error was an `UnhandledRejection: Non-Error promise rejection`. A promise rejection was called with an object which had certain keys that pointed to a font. It turns out that it errored when trying to [load MonoLisa font when initializing the v1 editor](https://github.com/codesandbox/codesandbox-client/blob/master/packages/app/src/app/overmind/effects/vscode/index.ts#L217).
Digging around in [the `fontfaceobserver` package](https://www.npmjs.com/package/fontfaceobserver) I found that the class is constructed with the initial values visible in the Sentry error. It turns out that it was not properly handling errors and [passed an object instead of an Error instance](https://github.com/bramstein/fontfaceobserver/blob/v2.0.13/src/observer.js#L222) to …
> Fix(sentry): Update fontfaceobserver to version with proper error handling

- packages/app/src/app/overmind/factories.ts
- packages/app/src/app/overmind/namespaces/editor/internalActions.ts
Should fix Sentry issue 3587048851.
The error had to do with an unauthorized API call (returned a `401`). The API was called when an anonymous user tried to save a file which resulted in CSB trying to stop it from being forked. This was done successfully, but the "save" action wasn't properly canceled after that. This PR changes that behaviour and throws an error rather than returning nothing to end up in a `catch` block - which then properly stops the save action from happening.
I've also made sure we don't trigger an "unknown" editor error while also showing the fork alert. The fork alert with sign in button should be enough.
https://user-images.githubusercontent.com/7533849/220662233-961e6e2c-7755-48d1-ad0b-3f460ebd8920.mov
https://user-images.githubusercontent.com/7533849/220662297-c23 …
> fix(sentry): Ensure continue action is not called when forking is not allowed

- packages/app/src/app/pages/Dashboard/Sidebar/index.tsx
- packages/app/src/app/pages/Dashboard/index.tsx
- packages/app/src/app/pages/Sandbox/Editor/index.tsx
Manually calculate the height based on whether the stripe banner is visible or not. Because of some absolutely positioned elements, it's hard to simplify this since doesn't follow a proper flow layout.
|Desktop|
|:-:|
|![ur44et-3000 preview csb app_dashboard_recent_workspace=47968439-c1ee-494c-a6e1-ec7ea18ab162 (2)](https://user-images.githubusercontent.com/24959348/215956143-b98a812e-ff19-40f7-b3c1-a38d4de3bb05.png)|
|Mobile - Sidebar closed|Mobile - Sidebar open|
|:-:|:-:|
|![ur44et-3000 preview csb app_dashboard_recent_workspace=47968439-c1ee-494c-a6e1-ec7ea18ab162 (1)](https://user-images.githubusercontent.com/24959348/215955982-e689e35d-06f9-4ae3-b57b-a619513e5130.png)|![ur44et-3000 preview csb app_dashboard_recent_workspace=47968439-c1ee-494c-a6e1-ec7ea18ab162](https://user-images.gi …
> fix(dashboard): bottom being cut if stripe banner is visible at the top

- packages/app/src/app/components/StripeMessages/PaymentPending.tsx
Adds tracking to the PaymentPending banner.
- If the banner is shown because the trial has expired, track an event named "Stripe banner - expired trial seen"
- If the banner is shown because the subscription is unpaid, track an event named "Stripe banner - unpaid - seen"
> feat(tracking): "seen" event on PaymentPending banner

- packages/app/src/app/overmind/effects/api/index.ts
- packages/app/src/app/overmind/namespaces/pro/actions.ts
- packages/app/src/app/overmind/namespaces/pro/state.ts
- packages/app/src/app/overmind/namespaces/pro/types.ts
There are still some references to legacy pricing, but those are in the old homepage pages, which we will remove in another PR.
> chore: Remove references to legacy pricing

- packages/app/src/app/pages/Dashboard/Header/index.tsx
- packages/app/src/app/pages/Dashboard/Sidebar/index.tsx
- packages/app/src/app/pages/common/UserMenu/index.tsx
This item is out of context in this place, all items here are relative to things owned by the user.
| Old      | New |
| ----------- | ----------- |
| <img width="279" alt="image" src="https://user-images.githubusercontent.com/2926010/219066219-f94e9f62-62dd-45d5-9dd3-a4c022d466dc.png">      | <img width="284" alt="image" src="https://user-images.githubusercontent.com/2926010/219066297-7c2c6bb5-3a32-43ee-9b89-af37baa2d119.png">       |
| Old      | New |
| ----------- | ----------- |
| <img width="226" alt="image" src="https://user-images.githubusercontent.com/2926010/219067549-d35def37-1054-4082-9102-7151f32f430e.png">      | <img width="220" alt="image" src="https://user-images.githubusercontent.com/2926010/219067628-46696fcb-3431-42da-8dd0-b93123482111.png">       |
Move to the new …
> feat(Dashboard): discover button to the new discover page

- packages/app/src/app/components/CreateSandbox/Import/ImportInfo.tsx
- packages/app/src/app/graphql/types.ts
- packages/app/src/app/overmind/effects/gql/dashboard/mutations.ts
- packages/app/src/app/overmind/namespaces/dashboard/actions.ts
- packages/app/src/app/overmind/namespaces/dashboard/state.ts
- packages/app/src/app/pages/Dashboard/Components/Header/index.tsx
- packages/app/src/app/pages/Dashboard/Components/Repository/stripes.tsx
- packages/app/src/app/pages/Dashboard/Components/Selection/ContextMenus/RepositoryMenu.tsx
- packages/app/src/app/pages/Dashboard/Components/VariableGrid/index.tsx
- packages/app/src/app/pages/Dashboard/Content/routes/Repositories/index.tsx
- packages/app/src/app/pages/Dashboard/Content/routes/RepositoryBranches/index.tsx
- packages/app/src/app/pages/Dashboard/types.ts
- packages/common/src/utils/url-generator.ts
- packages/components/src/components/MessageStripe/MessageStripe.tsx
Starting with the workspace scopes phase 2 PR, the editor no longer supports the `create=true` query to create a draft branch.
Hence, this PR replaces the use of the create=true with a mutation to create the draft branch and then redirect to it.
Note: The contribution branch creation might be a bit more tricky to solve, so I just commented it out for now. A linear task will explain the changes needed for that.
Closes XTD-549
> feat: add createBranch mutation instead of editor redirect

- packages/app/src/app/constants.ts
- packages/app/src/app/overmind/actions.ts
- packages/app/src/app/pages/Pro/Legacy.tsx
- packages/app/src/app/pages/Pro/Upgrade.tsx
- packages/app/src/app/pages/Pro/components/SubscriptionCard.tsx
- packages/app/src/app/pages/Pro/components/UpsellTeamPro.tsx
- packages/app/src/app/pages/Pro/components/UpsellTeamProCard.tsx
- packages/app/src/app/pages/Pro/components/elements.ts
- packages/app/src/app/pages/Pro/legacy-pages/WorkspacePlanSelection.tsx
- packages/app/src/app/pages/common/Modals/SelectWorkspaceToUpgrade/index.tsx
- packages/app/src/app/pages/common/Modals/index.tsx
Adds a third card listing "Team Pro" benefits on the `/pro` page even if the selected workspace is personal.
https://user-images.githubusercontent.com/24959348/222035716-f98028ac-2e05-40db-8c4e-2f6eb01801e8.mov
If no _upgradeable_ teams are available, open the create team flow:
1. Visit https://llqorv-3000.preview.csb.app/pro
2. Select your personal workspace
3. A third card upselling Team Pro should be visible
> feat(pro): upsell team pro

- packages/app/src/app/pages/Dashboard/Components/Repository/stripes.tsx
- packages/app/src/app/pages/Dashboard/Content/routes/Recent/RecentContent.tsx
We were already showing a message to users on the repositories page, but users might also miss their branches on the recent page.
Closes XTD-753
---
Changed the text from
> Is your repository gone? It is not deleted, but needs to be re-imported due to a change.
to
> Can't find a repository? It is not deleted, but needs to be re-imported due to a change.
---
Updated the message to use either `branch` or `repository` in the text.
---
> feat(workspace-scopes): Add temporary workspace scopes message to recent page

- packages/app/src/app/components/CreateSandbox/Import/AccountSelect.tsx
- packages/app/src/app/overmind/utils/auth.ts
Fixes XTD-755
Instead of using the "grant access to private repos" function we redirect to the GitHub OAuth application page. This ensures users will always be able to grant access to organizations, no matter if access is granted to private repos for other orgs already.
> fix(import): Authorizing GitHub organizations via Account picker

- packages/app/src/app/components/StripeMessages/TrialWithoutPaymentInfo.tsx
- packages/app/src/app/components/StripeMessages/index.tsx
- packages/app/src/app/pages/Dashboard/index.tsx
- packages/app/src/app/pages/Sandbox/Editor/index.tsx
- packages/components/src/components/MessageStripe/MessageStripe.stories.tsx
- packages/components/src/components/MessageStripe/MessageStripe.tsx
- Adds the `corners` prop to the `MessageStripe` component.
- Creates a new component `TrialWithoutPaymentInfo`
- Adds it to the dashboard and to the editor
2. Open (or create) a team with an active trial and no payment info
3. The banner should be visible
4. The banner can be dismissed
5. If the banner was dismissed before the current day, it'll appear again
- You can test this by opening the devtools, searching for the key `TRIAL_PAYMENT_INFO_REMINDER_${activeTeam}` and setting the date to the day before.
> feat: remind users to add their payment details

- packages/app/src/app/components/StripeMessages/TrialWithoutPaymentInfo/TrialWithoutPaymentInfo.tsx
- packages/app/src/app/components/StripeMessages/TrialWithoutPaymentInfo/index.ts
- packages/app/src/app/components/StripeMessages/TrialWithoutPaymentInfo/useShowBanner.ts
- packages/app/src/app/pages/Dashboard/index.tsx
- packages/app/src/app/pages/Sandbox/Editor/index.tsx
Height is not re-calculated when the banner is dismissed.
https://user-images.githubusercontent.com/24959348/222838977-ede361a8-aec1-40da-b1a5-bccad33c9eba.mov
(Screen recording is laggy because the editor is quite sluggish in dev mode).
1. Step A
2. Step B
3. Step C
> fix(editor): height when stripe message is dismissed

- packages/app/src/app/graphql/types.ts
- packages/app/src/app/overmind/actions.ts
- packages/app/src/app/overmind/effects/gql/dashboard/fragments.ts
- packages/app/src/app/pages/Dashboard/Components/UpgradeBanner/UpgradeBanner.tsx
- packages/app/src/app/pages/Dashboard/Content/routes/Recent/RecentHeader.tsx
- packages/app/src/app/pages/common/Modals/SelectWorkspaceToStartTrial/index.tsx
- packages/app/src/app/pages/common/Modals/index.tsx
- Shows the `UpgradeBanner` in personal workspaces.
- Adjust the `UpgradeBanner` to inform about free trials for Team Pro.
1. Visit the dashboard
- Select your personal workspace if it's not already selected.
2. Refresh the page (the banner is designed to not appear the first time the dashboard is visited)
3. The banner should be visible, the CTA will:
- Open a selection modal if any of the user's workspaces are eligible for a trial.
- Open the new team modal if no workspace is eligible for a trial.
> feat(dashboard): adds upgrade banner in personal workspaces

- packages/components/src/components/Button/button.stories.tsx
- packages/components/src/components/Button/index.tsx
- packages/components/src/components/ComboButton/ComboButton.stories.tsx
- packages/components/src/components/ComboButton/ComboButton.tsx
Turns out, some variants  (`light`, `dark` and `trial`) of the `Button` were missing focus states. So I adjusted the background and added the border using the [Design System](https://www.figma.com/file/8BBHbEXBqKclOyarnViclf/Design-System-v2.0?node-id=446-636&t=8gjgf6MN9GHAkQ5x-4) as reference:
With the `Button` fixed, it was only a matter of adjusting the `z-index` to make the focus work properly in the `ComboButton`:
https://user-images.githubusercontent.com/24959348/223834684-f681af21-8583-416d-bb57-a83ceab81652.mov
1. Open storybook
2. Check `?path=/story/components-button--variants`
3. Check `?path=/story/components-facelift-combobutton--base-variant`
> fix(ComboButton): focus styles

- packages/app/src/app/pages/Dashboard/Sidebar/index.tsx
- packages/app/src/app/pages/Dashboard/index.tsx
Part of XTD-803.
Account for the topbar banner in the sidebar height.
Content at the bottom of the sidebar touches the bounds/is cut off.
https://user-images.githubusercontent.com/24959348/225689171-e071ce5e-3e26-4110-aea7-104cc1274bb4.mov
> fix: sidebar height when banner is visible

- packages/app/src/app/graphql/types.ts
- packages/app/src/app/overmind/actions.ts
- packages/app/src/app/overmind/effects/gql/dashboard/fragments.ts
- packages/app/src/app/overmind/effects/gql/dashboard/queries.ts
- packages/app/src/app/overmind/namespaces/dashboard/actions.ts
- packages/app/src/app/overmind/namespaces/dashboard/state.ts
- packages/app/src/app/pages/Dashboard/index.tsx
- packages/app/src/app/pages/common/Modals/MidTrialModal/index.tsx
- packages/app/src/app/pages/common/Modals/index.tsx
- packages/components/src/components/Badge/index.tsx
Added a modal with an AB test that shows up mid-trial. The modal shows up when:
- the active user is admin
- the workspace is in an active trial
- the workspace has no payment method specified
- the days left in the trial are equal to 7 or smaller
- the mid-trial modal hasn't been dismissed before
Note: the title says 14 days left because I had to force the modal to show up.
Note: the title says 14 days left because I had to force the modal to show up.
> feat(trial): Mid-trial reminder modal

- packages/app/src/app/pages/Dashboard/Components/NewTeamModal/TeamInfo.tsx
This image makes the user to think that there is functionality to upload an image. While the feature is not implemented, it makes no sense to keep this "fake button".
Old:
New:
> style(dashboard): remove fake button to upload team image at the create team flow

- packages/app/src/app/components/LoseFeatures/LoseFeatures.tsx
- packages/app/src/app/pages/common/Modals/MidTrialModal/index.tsx
- packages/app/src/app/pages/common/Modals/SubscriptionCancellation/SubscriptionCancellation.tsx
- packages/app/src/app/pages/common/Modals/index.tsx
- packages/components/src/components/Badge/index.tsx
Combined the mid trial reminder with the cancel subscription modal so they share one style and one component to view the lost benefits.
Note: I've also fixed an **important** bug where we would try and load the checkout url for a team that's currently on trial - which doesn't work. Instead we're now creating a customer portal.
> fix(trial): Create customer portal instead of checkout url and combine components

- packages/app/src/app/pages/Dashboard/Content/routes/Repositories/EmptyRepositories.tsx
Fixes #7530
Fixes #7524
And probably fixes #7517 too.
And probably fixes #7516 too.
Just checking for the `githubAccounts.state` wasn't enough as we need to make sure there's actually accounts that can be selected. We do this by checking if `selectedAccount` exists. To check if this actually fixes the issues I've rendered the `AccountSelect` without checks and it crashes and throws exactly the same error.
> fix(import): Check if selectOptions exist before rendering options

- packages/app/src/app/hooks/useWorkspaceSubscription.ts
- packages/app/src/app/pages/Dashboard/Content/routes/Settings/components/InviteMember.tsx
Closes XTD-854.
- Checks if it should restrict new editors before showing the upgrade alert.
- Fix the number of seats for teams that never had a subscription.
> fix(settings): editor seats

- packages/app/src/app/pages/Dashboard/Content/routes/Settings/TeamSettings/RegistryForm.tsx
- packages/app/src/app/pages/Dashboard/Content/routes/Settings/TeamSettings/RegistrySettings.tsx
Closes XTD-841.
- When visiting `dashboard/settings/npm-registry` as a non-admin, an error was shown:
- When visiting `dashboard/settings/npm-registry` as a non-admin, we don't try to fetch the registry so no error is shown.
> fix(registry): prevent non-admins from performing actions

- packages/app/src/app/components/SignInModal.tsx
- packages/app/src/app/pages/SignIn/ChooseProvider.tsx
- packages/app/src/app/pages/SignIn/SignIn.tsx
- packages/app/src/app/pages/SignIn/components/Button.tsx
- packages/components/src/components/Icon/icons.tsx
I might need to change the API a bit when hooking things with the API but wanted to get most of the UI out of the way.
You can directly access this by opening `/signin?sso_mode=true`
|IDLE|
|:-:|
|![xkrisk-3000 csb app_signin_sso_mode=true (2)](https://user-images.githubusercontent.com/24959348/228023128-a9c17a14-dbbc-4f7e-9c26-7dfc2499007f.png)|
|VALIDATING|
|:-:|
|![xkrisk-3000 csb app_signin_sso_mode=true (1)](https://user-images.githubusercontent.com/24959348/228023160-633c9e81-cdfa-4d58-a28c-35d51dc82392.png)|
|INVALID|
|:-:|
|![xkrisk-3000 csb app_signin_sso_mode=true](https://user-images.githubusercontent.com/24959348/228023260-454a9c30-adcf-48b4-b506-d1a8cab16f36.png)|
> feat(sso): UI

- packages/app/src/app/hooks/useCurrencyFromTimeZone.ts
- packages/app/src/app/overmind/namespaces/pro/actions.ts
- packages/app/src/app/pages/Pro/Upgrade.tsx
- packages/app/src/app/pages/Pro/components/UpsellTeamProCard.tsx
- packages/app/src/app/pages/Pro/legacy-pages/WorkspacePlanSelection.tsx
- packages/app/src/app/utils/currency.ts
In this PR we're fixing the price calculation. There were some bugs and we also needed to calculate and format the pricing based on the users locale and currency.
We're determining the user location based on their timezone. This isn't fool proof but we expect Stripe to take care of that. The timezone will tell us what the country of origin is.
1. On an Apple device, turn off automatic time and location in the date & time settings. Change your "closest city" to an Indian one (e.g. Kolkata). This will update your timezone.
2.  Visit the pro page and select a personal workspace without subscription.
3. You should now see the price in Rupees.
We base the formatting locale on the currency. When the timezone is set to the Indian one, the currency will be Rupees and the locale will be set to …
> feat(pricing): Determine user location and show appropriate price

- packages/sandpack-core/src/npm/dynamic/fetch-protocols/npm-registry.ts
It avoids throwing an error on regular sandboxes that contain private packages. Initially, I thought this would only affect Sandpack, but it seems it has also been used on csb.io sandboxes.
> fix(npm-private): dont throw error on sandboxes

- packages/app/integration-tests/tests/sandboxes.test.js
- packages/app/package.json
- packages/sandbox-hooks/package.json
- yarn.lock
Fixes: #5981.
Codesandbox's console fatals when you try to log `bigints`.
It works.
Added an integration test. Can you please update the snapshots for me?
> Update to a version of `console-feed` that can log `bigint` values

- packages/app/src/app/pages/Pro/Upgrade.tsx
A small bug got reported:
We showed the local currency symbol with the USD price if no local currency price is available.
EDIT: hard to test, unless we get someone in India to open /pro
> fix: always show USD symbol if no local currency is present

- packages/sandbox-hooks/errors/index.js
When we send many errors in quick succession, we clog up the editor, leaving everything unresponsive. This is because we sent thousands of errors _per second_ to the editor, which it has to parse and then show in the Problems section. With this change we introduce a rate limit, so we don't flood the editor with errors.
> fix: introduce rate limit on errors

- packages/app/src/app/components/CreateSandbox/TemplateCard.tsx
Adds a tooltip that gives a bit more information (in context) on what the difference between a cloud sandbox and browser sandbox is.
> chore: add more info about cloud sandboxes through a tooltip

- packages/app/src/app/pages/Dashboard/Components/NewTeamModal/TeamMembers.tsx
Clarify that you have only 4 additional editor spaces to invite on a free team.
> Warn users about team invitation limit during new team creation

- packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Deployment/index.tsx
- packages/common/src/types/index.ts
This is to prevent abuse of Netlify anonymous deployments.
> fix: only enable netlify deploy for older accounts

- .all-contributorsrc
- README.md
- packages/app/src/sandbox/compile.ts
Bug fix
This is a proposed upstream fix for a [related Sandpack issue](https://github.com/codesandbox/sandpack/issues/927).
If you call the `compile` logic multiple times in a short amount of time, then the create `TestRunner` logic won't work as expected. Since the `testRunner` is shared between compiles, this is what ends up happening:
1. Call compile (**Compile A**)
2. Call compile again immediately (**Compile B**)
3. **Compile A**: `setTimeout` is called (wait `600ms`)
4. **Compile B**: `setTimeout` is called (wait `600ms`)
5. **Compile A**: `setTimeout` runs
6. **Compile A**: Because `testRunner` is `undefined`, await `jest-lite` module import
7. **Compile B**: `setTimeout` runs (step 6 is suspended because of the `await`)
8. **Compile B**: Because step 6 was suspended because of the …
> fix(compile): create one TestRunner between sandbox compiles

- packages/app/src/app/components/LoseFeatures/LoseFeatures.tsx
- packages/app/src/app/constants.ts
- packages/app/src/app/pages/Dashboard/Components/UpgradeBanner/UpgradeBanner.tsx
- packages/app/src/app/pages/common/Modals/MidTrialModal/index.tsx
> refactor(Dashboard): update RAM labels and capacity pills

- packages/app/src/app/pages/Sandbox/SearchDependencies/SearchBox.tsx
Adds a debounce to the algolia search, so we don't fire off too many requests while someone is still typing.
Let me know if there's a better way to do this? But I noticed we use this `debounce` function in lots of places, so it seemed like the right thing to do?
1. Step A
2. Step B
3. Step C
> Debounce Algolia Search

- packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/AI/index.tsx
- packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Docker/index.tsx
- packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/VSCode/index.tsx
This PR simply updates 3 links to the Docs in the left sidebar (Docker, VS Code, and AI).
Open a sandbox and check the Docker, VS Code, and AI tabs on the left. The "Learn More" link now points to the "Convert a browser sandbox into a cloud sandbox" tutorial.
> docs(editor): update links to CodeSandbox tutorial in AI, Docker, and VS Code

- packages/app/src/sandbox/compile.ts
`web-vitals` is blocked by adblockers, many times. Also not really used in imports, so removing it from the installation step.
> refactor(sandbox): remove web-vitals from sandbox dependencies

- packages/app/src/app/graphql/types.ts
- packages/app/src/app/overmind/effects/gql/notifications/mutations.ts
- packages/app/src/app/overmind/effects/gql/notifications/queries.ts
- packages/app/src/app/overmind/namespaces/userNotifications/state.ts
- packages/app/src/app/pages/common/Modals/PreferencesModal/MailPreferences/index.tsx
- packages/app/src/app/pages/common/Modals/PreferencesModal/index.tsx
As preparation for more possible future notification types, I updated the notification preferences part of the Preferences Modal.
I want to create a follow-up PR that allows users to open this from the notifications icon in the top right too, but turns out that is not as simple as I had hoped. (But hey, I'm learning some stuff as I go I suppose)
To look at it: sign in, and click the menu in the top right > preferences > notification preferences
1. Step A
2. Step B
3. Step C
> PTB-451 -- Revamp Notification Preferences

- packages/app/src/app/pages/Sandbox/SearchDependencies/SearchBox.tsx
Using the debounce inline was not passing the event argument properly. I also moved it into a useCallback to avoid calling debounce again on each re-render.
Closes PC-981
> fix: debounce error in dependencies

- packages/app/src/app/pages/Dashboard/Content/routes/Settings/components/PermissionSettings.tsx
It shows a back-to-project button after saving permission if it contains `continueUrl` query params.
Closes PC-969
Depends on https://github.com/codesandbox/codesandbox-applications/pull/2917
> feat(permission): back to project button

- packages/app/src/app/components/UserSearchInput/UserSearchInput.tsx
- packages/app/src/app/pages/Dashboard/Content/routes/Settings/components/InviteMember.tsx
Pre-populate the input with the invite_email from the query string
Also removes autoComplete on the input
> feat(Dashboard): prefill invite_email into the input on team settings

- .codesandbox/tasks.json
- packages/app/src/app/components/WorkspaceSelect/WorkspaceSelect.tsx
- packages/app/src/app/graphql/types.ts
- packages/app/src/app/hooks/useWorkspaceAuthorization.ts
- packages/app/src/app/hooks/useWorkspaceSubscription.ts
- packages/app/src/app/overmind/effects/gql/dashboard/fragments.ts
- packages/app/src/app/pages/Dashboard/Components/UpgradeBanner/UpgradeBanner.tsx
- packages/app/src/app/pages/Dashboard/Content/routes/Settings/UserSettings/WorkspaceSettings.tsx
- packages/app/src/app/pages/Dashboard/Content/routes/Settings/components/TeamInfo.tsx
- packages/app/src/app/pages/Pro/Upgrade.tsx
- packages/app/src/app/pages/Pro/components/Switcher.tsx
- packages/app/src/app/pages/Pro/components/UpsellTeamProCard.tsx
- packages/app/src/app/pages/Pro/legacy-pages/WorkspacePlanSelection.tsx
- packages/app/src/app/pages/Profile/AllSandboxes.tsx
- packages/app/src/app/pages/Profile/MinimumPrivacy.tsx
- packages/app/src/app/pages/Sandbox/Editor/Header/ForkButton/ForkButton.tsx
- packages/app/src/app/pages/Sandbox/Editor/Header/index.tsx
- packages/app/src/app/pages/common/Modals/SelectWorkspaceToStartTrial/index.tsx
- packages/app/src/app/pages/common/Modals/SelectWorkspaceToUpgrade/index.tsx
- packages/app/src/app/utils/teams.ts
Closes PC-1040
Remove `Personal` and use username everywhere
Use team.type instead of always verifying the `personalWorkspaceId`
Add the proper badges based on the state of the workspace:
* Pro for legacy personal pro (to be decided if this remains)
* Free for legacy free teams
* Inactive for new teams that have cancelled or have trials expired
> feat(pricing): remove personal refs and use legacy flag for determining badges

- packages/app/src/app/overmind/actions.ts
- packages/app/src/app/overmind/effects/api/apiFactory.ts
- packages/app/src/app/overmind/effects/api/index.ts
- packages/app/src/app/overmind/effects/api/types.ts
- packages/app/src/app/overmind/state.ts
- packages/app/src/app/pages/SignIn/ChooseProvider.tsx
- packages/app/src/app/pages/SignIn/SignIn.tsx
Integrates the new `/meta/features` endpoint that tells the client (for now) which login options are available. SSO and OAuth login options are now conditioned by these flags.
The new api routes that are no longer on /v1 will need some better support with the current implementation of apiFactory, but I'll change that in a subsequent PR to avoid dragging this for too long or blowing the scope here.
Closes PC-1113
> feat(api): add new endpoint for retrieving features

- packages/common/src/templates/parcel.ts
Currently vanilla templates do not handle correctly the case of `/src/index.html`, this PR fixes it
> fix: vanilla template html entry handling

- packages/app/src/app/components/LoseFeatures/LoseFeatures.tsx
- packages/app/src/app/constants.ts
- packages/app/src/app/graphql/types.ts
- packages/app/src/app/hooks/useWorkspaceSubscription.ts
- packages/app/src/app/overmind/effects/gql/dashboard/queries.ts
- packages/app/src/app/overmind/internalActions.ts
- packages/app/src/app/overmind/namespaces/dashboard/actions.ts
- packages/app/src/app/overmind/state.ts
- packages/app/src/app/pages/Dashboard/Components/UpgradeBanner/UpgradeBanner.tsx
- packages/app/src/app/pages/Dashboard/Content/routes/Settings/UserSettings/ManageSubscription/Upgrade.tsx
- packages/app/src/app/pages/Dashboard/Content/routes/Settings/UserSettings/ManageSubscription/index.tsx
- packages/app/src/app/pages/Dashboard/Sidebar/BottomMessages/CreateProWorkspace.tsx
- packages/app/src/app/pages/Dashboard/Sidebar/BottomMessages/StartTrial.tsx
- packages/app/src/app/pages/Dashboard/Sidebar/index.tsx
- packages/app/src/app/pages/Pro/Create.tsx
- packages/app/src/app/pages/common/Modals/MidTrialModal/index.tsx
New field coming from BE, if the current user has the ability to start a trial.
Each user gets one trial after the release.
A team/workspace can be on a trial if it is legacy free and the user has the ability to start the trial and is an admin.
> feat: check user trial eligible

- packages/app/src/app/components/CreateSandbox/Import/Import.tsx
- packages/app/src/app/components/CreateSandbox/Import/SuggestedRepositories.tsx
- packages/app/src/app/hooks/useGitHubPermissions.ts
- packages/app/src/app/pages/Dashboard/Components/NewTeamModal/TeamImport.tsx
- packages/app/src/app/pages/Dashboard/Components/SuggestionsRow/SuggestionsRow.tsx
- packages/app/src/app/pages/Dashboard/Components/shared/ReadOnlyRepoDisclaimer.tsx
- packages/app/src/app/pages/Dashboard/Components/shared/RestrictedImportDisclaimer.tsx
- packages/app/src/app/pages/Dashboard/Content/routes/Recent/RecentContent.tsx
- packages/app/src/app/pages/Dashboard/Content/routes/Repositories/EmptyRepositories.tsx
- packages/app/src/app/pages/Dashboard/Content/routes/Repositories/index.tsx
- packages/app/src/app/pages/Dashboard/Sidebar/BottomMessages/TrialExpiring.tsx
- packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Deployment/GithubPages/index.tsx
- packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/GitHub/index.tsx
- packages/app/src/app/pages/common/Modals/PreferencesModal/Integrations/GitHubPermissions.tsx
This solves a few issues like unnecessary requests being made by the SuggestionRow (which throw errors to the users) when no permissions are given. Also renamed a typo in hook and changed the text on the sidebar trial expiration message
> fix: don't show GH suggested cards if no permission is given

- packages/app/src/app/hooks/useGitHubPermissions.ts
- packages/app/src/app/pages/Dashboard/Components/shared/RestrictedImportDisclaimer.tsx
- packages/app/src/app/pages/Dashboard/Content/routes/Recent/RecentContent.tsx
- packages/app/src/app/pages/Dashboard/Content/routes/Repositories/EmptyRepositories.tsx
For all the flags that dictate different messages and banners we need 3 states:
* undefined - value is not yet computed / loaded
* false / true
Otherwise, some of these flags flash between false/true while the page loads.
Before
https://github.com/codesandbox/codesandbox-client/assets/9945366/4daa2f8f-b9e7-4804-b19e-616342631ce3
After
https://github.com/codesandbox/codesandbox-client/assets/9945366/1069cb5f-4bcd-4233-9884-3f3302755439
> fix(UI): avoid flashing the GH permissions banners

- packages/app/src/app/components/CreateSandbox/Import/SuggestedRepositories.tsx
- packages/app/src/app/pages/Dashboard/Components/NewTeamModal/TeamImport.tsx
- packages/components/src/components/Button/index.tsx
- packages/components/src/components/InteractiveOverlay/InteractiveOverlay.tsx
There was a bug on the `new_workspace` triggered screen, the modal no longer closes now after the import. 
Fixes PC-1152
While there, I tweaked the import experience and allowed multiple repos to be imported in parallel.
https://github.com/codesandbox/codesandbox-client/assets/9945366/6f4e93ab-1d93-4008-b4d9-59377beb2d0a
The experience can be further improved, but let's talk on Monday about the onboarding flow.
> feat(SuggestedRepositories): allow multi/parallel import

- packages/app/src/app/overmind/actions.ts
- packages/app/src/app/overmind/internalActions.ts
The terms of service update is from 2021, so it's not up-to-date anymore.
> refactor(actions): remove privacy policy function and its dependencies

- packages/app/src/app/components/dashboard/InputText.tsx
- packages/app/src/app/components/dashboard/Textarea.tsx
- packages/app/src/app/overmind/actions.ts
- packages/app/src/app/pages/Dashboard/Components/NewTeamModal/TeamImport.tsx
- packages/app/src/app/pages/Dashboard/Components/NewTeamModal/TeamMembers.tsx
- packages/app/src/app/pages/Dashboard/Components/NewTeamModal/TeamName.tsx
- packages/app/src/app/pages/Dashboard/Components/NewTeamModal/index.tsx
- packages/app/src/app/pages/Dashboard/index.tsx
- packages/app/src/app/pages/Pro/Create.tsx
Closes PC-1222
Removes the step to name the workspace / create team before going to stripe.
On the pro page, when you start trial / upgrade to pro you go directly to stripe
When stripe redirects to the dashboard, you end up with `new_workspace=true` in the query string.
The modal window now has 3 steps:
A few style adjustments to match on all 3 screens
> feat: move workspace name in post-pro flow

- packages/app/src/app/overmind/effects/vscode/index.ts
With the new version of TypeScript, sandboxes start with an error state because the typings are not available on boot (we dynamically download the typings, to improve editor load time). TS doesn't like this and gives a big error for all React code, from the start.
With this change, we tell the extension to explicitly check again for types after we've downloaded the types. That way, TS gets updated with the latest version and the errors are removed.
Fixes #8078
Used this sandbox to verify: https://vjl7jl-3000.csb.app/s/cocky-liskov-px6sj7?file=/src/App.tsx
> fix(ts): reload TS projects once we have loadad the typings

- packages/app/src/app/components/CreateSandbox/CreateSandbox.tsx
- packages/app/src/app/components/CreateSandbox/Import/InactiveTeam.tsx
- packages/app/src/app/components/CreateSandbox/Import/MaxPublicRepos.tsx
- packages/app/src/app/components/CreateSandbox/Import/PrivateRepoFreeTeam.tsx
- packages/app/src/app/hooks/useCreateCheckout.ts
- packages/app/src/app/pages/Dashboard/Components/Repository/stripes.tsx
- packages/app/src/app/pages/Dashboard/Components/TeamSubscriptionOptions/TeamSubscriptionOptions.tsx
- packages/app/src/app/pages/Dashboard/Components/UpgradeBanner/UpgradeBanner.tsx
- packages/app/src/app/pages/Dashboard/Components/shared/InactiveTeamStripe.tsx
- packages/app/src/app/pages/Dashboard/Content/routes/Sandboxes/MaxSandboxesRestrictionsBanner.tsx
- packages/app/src/app/pages/Dashboard/Content/routes/Settings/TeamSettings/ManageSubscription/upgrade.tsx
- packages/app/src/app/pages/Dashboard/Content/routes/Settings/TeamSettings/WorkspaceSettings.tsx
- packages/app/src/app/pages/Pro/Create.tsx
- packages/app/src/app/pages/Pro/Upgrade.tsx
- packages/app/src/app/pages/common/Modals/EditorSeatsUpgrade/index.tsx
- packages/app/src/app/pages/common/Modals/LiveSessionRestricted/index.tsx
Deploying it on stream for testing the full flow (+stripe)
The main change is on the /pro page where the dropdown appears instead of the single CTA button. All other changes are just params passing and renames / cleanup
> feat: add all checkout options on the pro page

- packages/common/src/components/Preview/index.tsx
- packages/common/src/utils/url-generator.ts
Only domain is specified in ENV, so this PR adds the logic to prepend the protocol and also adds the initialPath to the preview URL
> fix: preview URL generation when domain is coming from env

- env.sh
Include env vars even if they are empty.
> fix(env.sh): Include empty environment variables in env.sh

- packages/app/src/app/components/StripeMessages/FreeViewOnlyStripe.tsx
- packages/app/src/app/pages/Dashboard/Content/routes/Settings/components/PermissionSettings.tsx
Last two places where it was possible to go to the pro page with the personal workspaceId in the URL
> fix(pro): Ensure /pro link does not upgrade personal accounts

- packages/app/src/app/components/Preview/DevTools/index.tsx
Patching a previous fix to ensure a tab list which is filtered (because of the removal of some tabs) does not render anymore
Closes #8099
> fix: prevent empty tab list from rendering

- packages/sandbox-hooks/console/index.js
Enable Chrome DevTools functionality in editor context
This is now running on `stream`
Ensure both `codesandbox.stream/s/new` works and also `codesandbox.stream/p/sandbox/new`
> feat: Add Chrome DevTools functionality to console

- .codesandbox/Dockerfile
- packages/app/src/embed/components/App/index.js
Really small change, but perhaps someone could forge a sandbox with `postMessage` and then change the sandbox id. Even then, we would do a request with a weird body that the server will reject, but it's better safe than sorry.
> fix: check for sandboxId before giving like

- packages/app/src/app/pages/Dashboard/Components/Folder/FolderCard.tsx
- packages/app/src/app/pages/Dashboard/Components/Folder/types.ts
- packages/app/src/app/pages/Dashboard/Components/Sandbox/SandboxCard.tsx
- packages/app/src/app/pages/Dashboard/Components/Sandbox/types.ts
- packages/app/src/app/pages/Dashboard/Components/Selection/DragPreview.tsx
- packages/app/src/app/pages/Dashboard/Sidebar/RowItem.tsx
- packages/app/src/app/pages/Dashboard/Sidebar/utils.tsx
There were a couple regressions in the editor that I noticed recently:
1. When dragging to select sandboxes and folders, they only get selected when you hover over the title of the card.
2. Clicking on a folder / link in the sidebar only works if you click the actual `a` element, not the surrounding `li` with all styles
3. Dragging sandbox cards looks _ugly_ if there is not thumbnail
4. We stopped highlighting the active folder in the sidebar
This PR fixes those regressions!
> fix(dashboard): dragging & selecting sandboxes

- packages/sandpack-core/src/manager.ts
Bug fix
vue2 project HRM fails
https://github.com/codesandbox/codesandbox-client/issues/2058
vue2 project HRM works
1. create a vue2 project
2. modiy App.vue file
3. see if HRM work correctly
when a vue componet is created, [vue-hot-reload-api](https://github.com/vuejs/vue-hot-reload-api/blob/master/src/index.js#L3) will call createRecord() and keep its records in module scope. when HRM is triggered, vue-hot-reload-api will call rerender which reference saved records. so if we replace its tModule, we lost the records, thus raise an error.
the previous PR https://github.com/codesandbox/codesandbox-client/pull/8127 was colsed by accident. so i recreate a new one
> fix(sandpack-core): loaderContext.emitModule() may replace tModule directly

- yarn.lock
Fixes #8146
We have recently updated some dependencies in this repo, including `esquery`. And well, our in-browser eslint tries to use esquery, but it now exports `{ default() {} }` instead of `{ parse() }`, which causes our eslint integration to fail.
We revert esquery to an older version to fix it, for now. In the future we're going to replace eslint completely with a newer versiom.
> fix: revert esquery to old version

- packages/app/src/app/components/Preview/DevTools/index.tsx
- packages/app/src/app/overmind/namespaces/editor/actions.ts
- packages/app/src/app/pages/common/Modals/PreferencesModal/Experiments/BetaSandboxEditor.tsx
Fixed rows integration to ensure we get the data from the current experiment
Also added a hard redirect when the editor loads in v1 but the user activated the experiment
Unrelated, fixed a potential env error at runtime, which shouldn't happen outside of testing environments, but still
> fix: redirect to v2 editor fallback

- packages/app/src/app/pages/Dashboard/Content/routes/Repositories/index.tsx
- packages/app/src/app/pages/common/Modals/PreferencesModal/Experiments/BetaSandboxEditor.tsx
Import repository should not be disabled because there's no limit for public repos.
Also there was a sentry error on user being null when sending the form to rows, not sure how, but added a failsafe just in case
> fix: a ui bug and a potential error that was reported in sentry

- packages/app/src/app/pages/common/Modals/PreferencesModal/Experiments/BetaSandboxEditor.tsx
> feat: Add feedback textarea to BetaSandboxEditor

- packages/app/src/app/components/CreateSandbox/ExperimentalBetaEditor.tsx
This PR is a simple update to the copy of the new "experimental beta editor" banner. It should make it more clear to users how to opt out if they wish to.
> fix(BetaSandboxEditor): Clarify copy of the experimental sandbox editor messages

- packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Explorer/Files/DirectoryEntry/DirectoryChildren/index.tsx
- packages/common/src/templates/constants/files.ts
To enable smoother transition to Devboxes we are adding the ESLint configuration, but hiding it for Sandboxes.
> Feat: Hide .eslintrc.cjs file

- packages/app/src/app/constants.ts
- packages/app/src/app/pages/Pro/Upgrade.tsx
- packages/app/src/app/pages/Pro/components/UBBWaitlist.tsx
- packages/app/src/app/pages/Pro/legacy-pages/WorkspacePlanSelection.tsx
A few small UI differences compared to the figma design:
- `Pay only for what you use` in Everett, not in Inter
- no border radius to match the subscription cards
> feat: ubb waitlist banner

- packages/sandbox-hooks/url-listeners.js
We need this to be configurable or the V2 protocol loaded on Sandboxes will not be able to override the history API in the browser.
> feat: Added configurable property

- packages/app/src/app/components/Create/CreateBox.tsx
- packages/app/src/app/overmind/namespaces/editor/actions.ts
We were setting the `alias` to the input field, but the `alias` should almost always be auto-generated (with some exceptions). The fact that the server didn't reject this was probably a bug. Newly created sandboxes with custom titles result in a 404 in the editor.
With this change, we're setting the title instead of the alias to the field. That should make it work now! I'll fast-track this change and merge it immediately.
This is something confusing, and a bit legacy. We _should_ allow people to set custom aliases, but it looks like our infra does not handle that right now.
> fix(create): set title to name instead of alias

- packages/app/src/app/components/Create/CreateBox.tsx
- packages/app/src/app/components/Create/CreateBox/TemplateInfo.tsx
- packages/app/src/app/components/Create/utils/api.ts
- packages/app/src/app/components/Create/utils/queries.ts
- packages/app/src/app/graphql/types.ts
- packages/app/src/app/overmind/namespaces/editor/actions.ts
- packages/common/src/utils/url-generator.ts
A few different changes/improvements:
1. Add open_in_editor data to the tracking object when forking a template
2. Open `/p/vscode` or directly the vscode link based on the `CSB/AUTO_LAUNCH_VSCODE` flag
3. Add view and fork count on the template info component
> feat: improve create modal second screen

- packages/app/src/app/components/Create/ImportRepository/ForkRepoForm.tsx
Not sure how activeTeamInfo can be null at this stage, but saw a sentry error coming in and I added an extra check to be safe
> fix: Add condition to check active team info

- packages/app/src/app/overmind/namespaces/dashboard/actions.ts
- packages/app/src/app/pages/Dashboard/Components/Sandbox/SandboxCard.tsx
- packages/app/src/app/pages/Dashboard/Components/Selection/ContextMenus/MultiItemMenu.tsx
- packages/app/src/app/pages/Dashboard/Components/Selection/ContextMenus/SandboxMenu.tsx
- packages/app/src/app/pages/Sandbox/Editor/ForkFrozenSandboxModal/ForkFrozenSandboxModal.tsx
- packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/ProjectInfo/Summary/index.tsx
Pretty rough rename/replace for the concept. The frozen icon was kept on the cards as there's no clear icon to differentiate between privacy and protection. Will sync with design and product after the holidays to figure out some of the low hanging fruits for improving the dashboard.
> feat: rename frozen to protected

- packages/app/src/app/components/Create/hooks/useTeamTemplates.ts
- packages/app/src/app/overmind/namespaces/dashboard/actions.ts
- packages/app/src/app/pages/Dashboard/Components/Sandbox/SandboxBadge.tsx
- packages/app/src/app/pages/Dashboard/Components/Sandbox/SandboxCard.tsx
- packages/app/src/app/pages/Dashboard/Components/Sandbox/SandboxListItem.tsx
- packages/app/src/app/pages/Dashboard/Components/Selection/ContextMenus/SandboxMenu.tsx
* Default badge is `Devbox/Sandbox`
* Icon is always reflecting the type of box
* If turned into a template, the label `Template` replaces the `Devbox/Sandbox`
* If restricted (will be deprecated soon) the label turns into `Restricted` with a warning color instead of the bright purple one
* Same logic applies for the list view now as well
> feat: improve templates management

- packages/app/scripts/start.js
- packages/app/src/app/hooks/useCreateCheckout.ts
- packages/app/src/app/hooks/useCreateCustomerPortal.ts
- packages/app/src/app/pages/Dashboard/Content/routes/Settings/TeamSettings/TeamSettings.tsx
- packages/app/src/app/pages/Dashboard/Content/routes/Settings/UserSettings/index.tsx
- packages/app/src/app/pages/Dashboard/Content/routes/Settings/components/Navigation.tsx
- packages/app/src/app/pages/Dashboard/Sidebar/index.tsx
- packages/app/src/app/pages/common/UserMenu/index.tsx
- packages/common/src/utils/url-generator/dashboard.ts
All URLs pointing to the dashboard settings page are absolute paths to the workspace portal
Dashboard settings remains for now until we get this tested
Closes PC-1578
> feat: replace workspace settings with workspace portal

- packages/app/src/app/pages/WorkspaceFlows/UpgradeWorkspace.tsx
Right now when you hit cancel when doing the upgrade you get to the portal, which doesn't make too much sense.
> fix: redirect back to recent when upgrade flow is not going to stripe

- packages/app/src/app/components/WorkspaceSetup/steps/Plans.tsx
- packages/app/src/app/components/WorkspaceSetup/steps/SelectWorkspace.tsx
- packages/app/src/app/graphql/types.ts
- packages/app/src/app/overmind/effects/gql/dashboard/mutations.ts
- packages/app/src/app/pages/WorkspaceFlows/SignUpUBB.tsx
- packages/app/src/app/pages/WorkspaceFlows/index.ts
- packages/app/src/app/pages/index.tsx
`/signup-beta` works the same as `/upgrade`, it just runs the new mutation AJ implemented, so the workspaces are flipped to UBB during the flow
> feat: sign up for ubb self-serve flow

- packages/app/src/app/pages/Dashboard/Content/routes/Recent/RecentContent.tsx
Based on user feedback, for edge cases where a lot of repos are in use and work in primarily done on the main branch, I limited the number of cards that show to create a new branch to a single row in the grid
See the video (with mocked data)
https://github.com/codesandbox/codesandbox-client/assets/9945366/e28ab726-0860-4f24-a2e9-bd6f1f820646
> fix: limit create branch buttons to a single row

- packages/app/src/app/components/WorkspaceSetup/WorkspaceSetup.tsx
- packages/app/src/app/components/WorkspaceSetup/steps/Addons.tsx
- packages/app/src/app/components/WorkspaceSetup/steps/ChangePlan.tsx
- packages/app/src/app/components/WorkspaceSetup/steps/Create.tsx
- packages/app/src/app/components/WorkspaceSetup/steps/Finalize.tsx
- packages/app/src/app/components/WorkspaceSetup/steps/Payment.tsx
- packages/app/src/app/components/WorkspaceSetup/steps/Plans.tsx
- packages/app/src/app/components/WorkspaceSetup/steps/SelectWorkspace.tsx
- packages/app/src/app/components/WorkspaceSetup/types.ts
- packages/app/src/app/graphql/types.ts
- packages/app/src/app/hooks/useWorkspaceSubscription.ts
- packages/app/src/app/overmind/effects/gql/dashboard/mutations.ts
- packages/app/src/app/overmind/namespaces/checkout/actions.ts
- packages/app/src/app/overmind/namespaces/checkout/state.ts
- packages/app/src/app/pages/WorkspaceFlows/CreateWorkspace.tsx
- packages/app/src/app/pages/WorkspaceFlows/UpgradeWorkspace.tsx
To test:
* Ensure you have an old pro workspace (seat based, not flagged as ubb)
* Go to `/upgrade`, select the workspace
* Choose the pro plan, choose some addons, go over spending limit
* Last step is the accept changes now which should redirect to the portal instead of going to stripe
> feat: allow pro workspaces to use /upgrade to convert to ubb

- packages/app/src/app/components/WorkspaceSetup/WorkspaceSetup.tsx
- packages/app/src/app/components/WorkspaceSetup/steps/Plans.tsx
- packages/app/src/app/components/WorkspaceSetup/types.ts
- packages/app/src/app/pages/WorkspaceFlows/UpgradeWorkspace.tsx
There were a few issues with the plans upgrade because of the complications with opting into ubb. So I cleared the paths.
Closes PC-1645
Option 1. Existing old free workspace, converting to UBB
Option 2. Existing old pro workspace, converting to UBB
Option 3. Existing UBB free, wanting to upgrade
Option 4. New workspace
> fix: plans options

- packages/app/src/app/components/Create/GenericCreate.tsx
- packages/app/src/app/pages/Sandbox/Editor/index.tsx
Noticed that people can get lost when they get redirected to the "Create Sandbox" modal, with this change we do give them a way to go to the dashboard:
> feat: add a "Go to Dashboard" button to /s

- packages/app/src/app/components/WorkspaceSetup/steps/Addons.tsx
- packages/app/src/app/components/WorkspaceSetup/steps/PlanOptions.tsx
- packages/app/src/app/components/WorkspaceSetup/steps/Plans.tsx
@tromika can you review this as well?
Closes PC-1670
3 events on the Plans page -> for the 3 buttons you can click
2 events on the Addons page
* Click on addon
* Click on proceed
1 event for Proceed to checkout
> feat: add tracking

- packages/app/src/app/overmind/namespaces/editor/actions.ts
- packages/common/src/types/index.ts
Fixes https://github.com/codesandbox/codesandbox-client/issues/8299
When redirecting to v2, we were not passing on the query params. Because of this, e.g. the `file` parameter would get lost.
Tested this on the dev server inside CodeSandbox, now it's passed along.
> fix: pass on query params when redirecting to v2

- packages/app/src/app/components/Create/CreateBox.tsx
- packages/app/src/app/components/Create/TemplateCard.tsx
- packages/app/src/app/components/Create/TemplateList.tsx
We don't really have a nice variety of devboxes on stream but I removed the sign in button from the templates list and I changed the action for `selectTemplate` to open for anonymous users and fork for signed in users.
Clicking on the template opens in the same window
Cmd+click still works to open in a new tab
> feat: allow anonymous user to open devbox templates from /s

- packages/app/src/app/graphql/types.ts
- packages/app/src/app/overmind/effects/gql/dashboard/fragments.ts
- packages/app/src/app/pages/Dashboard/Content/routes/Recent/TopBanner.tsx
After some discussions with Ed, I adjusted the logic for our 3 possible banners on the home page:
1. Welcome to UBB (only for workspaces that were created BEFORE Feb 1st)
2. Upsell Pro UBB (only for FREE workspaces created AFTER Feb 1st)
3. Convert to UBB (only for seat-based PRO workspaces)
In a few weeks, we can change the content of the welcome to ubb to a more generic welcome banner for the dashboard.
> feat: update conditions for showing home banners

- packages/app/src/app/pages/Dashboard/index.tsx
- packages/app/src/app/pages/Sandbox/index.tsx
- packages/app/src/app/pages/index.tsx
/s is a bit more confusing for signed in users, so it's best that the modal opens on top of the dashboard
also changed the redirect from the `/` to `/dashboard`, but this affects only local development
we don't have significant traffic on it, but it is still used to quickly create something
> feat: redirect /s to /dashboard when signed in

- packages/app/src/app/overmind/namespaces/editor/internalActions.ts
- packages/app/src/app/pages/Dashboard/Content/routes/Recent/TopBanner.tsx
While the v1 editor is not used so much anymore, this ensures the draft limit fork error is handled properly with a nice message
> fix: proper fork error handling in v1 editor

- packages/app/src/app/components/WorkspaceSelect/WorkspaceSelect.tsx
- packages/app/src/app/pages/common/Modals/MoveSandboxFolderModal/index.tsx
This is more of a business/product decision, but since we know some teams use this feature, should we allow moving content into other free workspaces? Could be a way to bypass restrictions, especially since we don't yet enforce a fixed number of free workspaces users can create. 
Before
After
> feat: allow only pro workspaces when moving out of current workspace

- packages/app/src/app/pages/Dashboard/Components/Branch/BranchCard.tsx
- packages/app/src/app/pages/Dashboard/Components/Branch/BranchListItem.tsx
- packages/app/src/app/pages/Dashboard/Components/Branch/index.tsx
- packages/app/src/app/pages/Dashboard/Components/Branch/types.ts
- packages/app/src/app/pages/Dashboard/Components/Sandbox/SandboxCard.tsx
- packages/app/src/app/pages/Dashboard/Components/Sandbox/SandboxListItem.tsx
- packages/app/src/app/pages/Dashboard/Components/Sandbox/index.tsx
- packages/app/src/app/pages/Dashboard/Components/Sandbox/types.ts
Shows `lastAccessedAt` for branches and sandboxes for the current user on the recent page
Shows `lastAccessedAt` for branches on the branch list page
Shows `lastUpdatedAt` for sandboxes on all other pages (as before)
> feat: standardize last access at

- packages/app/src/app/graphql/types.ts
- packages/app/src/app/overmind/effects/gql/sidebar/fragments.ts
- packages/app/src/app/overmind/effects/gql/sidebar/queries.ts
- packages/app/src/app/overmind/namespaces/dashboard/actions.ts
- packages/app/src/app/overmind/namespaces/sidebar/actions.ts
- packages/app/src/app/overmind/namespaces/sidebar/state.ts
- packages/app/src/app/pages/Dashboard/Content/routes/Repositories/index.tsx
- packages/app/src/app/pages/Dashboard/Content/routes/RepositoryBranches/index.tsx
- packages/app/src/app/pages/Dashboard/Sidebar/ExpandableReposRowItem.tsx
- packages/app/src/app/pages/Dashboard/Sidebar/RowItem.tsx
- packages/app/src/app/pages/Dashboard/Sidebar/index.tsx
Core feature:
- show all repos under `All repositories`
- repos are ordered by name alphabetically
- the expanded state is persisted in local storage
Other fixes:
- switching from one repo to another triggers the data fetching
- repos shown alphabetically in list
> feat: fetch repositories for sidebar

- packages/app/src/app/pages/Sandbox/Editor/index.tsx
- packages/app/src/app/pages/Sandbox/index.tsx
- packages/app/src/app/pages/index.tsx
This PR clarifies the old /s page with introducing 3 version of it.
/s -> shows directly the sandbox templates
/d -> shows directly the devbox templates
/new -> shows the generic create modal with the 3 buttons (the previous /s)
Running this on stream (not a lot of templates available)
Keep in mind that in all of this "shortcut" pages, there's a redirect to the dashboard for signed in users to provide better context into the current workspace where things are created
> feat: clarify /s and create new pages as alternatives

- packages/app/src/app/overmind/namespaces/dashboard/actions.ts
Ok, this was lacking a flag cleanup, so a secondary cmd+click on the create branch was not doing anything
> fix: create branch with cmd+click

- packages/app/src/app/pages/Dashboard/Components/Branch/index.tsx
- packages/app/src/app/pages/Dashboard/Components/Sandbox/index.tsx
There was a regression because I removed the list/grid toggle on the recent items on Friday
> fix: ensure cards are always rendered on recent page

- packages/app/src/app/components/Create/ImportRepository/AuthorizeForSuggested.tsx
- packages/app/src/app/overmind/internalActions.ts
- packages/app/src/app/pages/Dashboard/Components/shared/RestrictedPublicReposImport.tsx
Minor PR that will give us more insight into the drop-off rate of users when asked to sign in for repo access
> chore: add tracking for requesting repo access

- packages/app/src/app/components/Notifications/Content.tsx
- packages/app/src/app/components/Notifications/index.tsx
The more (dots) button aligned with the notification items
The notification bell itself + the dot better aligned with the header
> fix: adjust spacing for notifications

- packages/app/src/app/overmind/actions.ts
- packages/app/src/app/pages/TeamInvitation/TeamInvitation.tsx
- packages/app/src/app/pages/WorkspaceFlows/CreateWorkspace.tsx
- packages/app/src/app/pages/common/Modals/TeamInviteModal/index.tsx
Noticed a bug yesterday on the stream, as accepted invitations were not redirecting you to the actual workspace.
Also added a query param for future welcome banners
> fix: redirect to workspace after invitation accepted

- packages/app/src/app/components/Create/CreateRepoFiles.tsx
- packages/app/src/app/overmind/namespaces/git/actions.ts
- packages/app/src/app/pages/Standalone/index.tsx
Add createRepoFiles function to handle creation of repo files in the app/overmind/namespaces/git/actions.ts file and add CreateRepoFiles component with functionality to create repo files in the app/components/Create/CreateRepoFiles.tsx file
Because the logic for creating the payload to create a repo from a Sandbox has so many dependencies we use an iFrame to convert a Sandbox from the V2 editor.
> feat: standalone Sandbox to GitHub converter

- packages/sandbox-hooks/preview-secret.js
This enables private previews for users with third party cookies disabled.
> fix: use partitioned cookie for sandbox preview secret

- packages/app/src/embed/components/Sidebar/AvatarBlock/elements.js
- packages/app/src/embed/components/Sidebar/AvatarBlock/index.js
- packages/app/src/embed/components/Sidebar/SandboxInfo/index.tsx
This was a request from someone on support, it will show the team name rather than the author name.
> fix(embed): show team name instead of author name

- packages/sandpack-core/src/manager.ts
- packages/sandpack-core/src/npm/dynamic/fetch-npm-module.ts
- packages/sandpack-core/src/resolver/resolver.ts
Work in progress to figure out best approach on fixing this without breaking existing functionality
Next steps:
- ~Either reduce resolver overhead~
- ~Find a way to download all files at once (sandpack-cdn?)~
Broken sandbox http://localhost:3000/#yrncs3
> fix: issue with npm fetcher in sandpack, looks stuck in a loop

- packages/app/src/app/overmind/namespaces/dashboard/actions.ts
- packages/app/src/app/overmind/namespaces/sidebar/actions.ts
- packages/app/src/app/overmind/namespaces/sidebar/state.ts
- packages/app/src/app/pages/Dashboard/Sidebar/ExpandableReposRowItem.tsx
- packages/app/src/app/pages/Dashboard/Sidebar/index.tsx
Noticed in production that the sidebar data request can be slow when you have a lot of repositories. When switching between workspaces while the sidebar data is still loading, you can get the responses in random order so the state would be overriden.
With this solution, each sidebar data is kept in a record indexed on the workspace id
> fix: cache sidebar data per workspace to avoid slower requests overriding the state

- packages/app/src/app/overmind/internalActions.ts
- packages/notifications/src/component/elements.ts
With this change, we show users that registered before March 10th that our ToS has been updated. After we've shown the notification, we don't show it again.
> feat: show that we've updated our ToS

- packages/sandpack-core/src/manager.ts
- packages/sandpack-core/src/npm/dynamic/fetch-npm-module.ts
- packages/sandpack-core/src/resolver/resolver.ts
Fixes #8384
Tested the repro case without this change, and it worked again. I think we might be returning too early somewhere here.
> Revert "fix: issue with npm fetcher in sandpack, looks stuck in a loop (#8361)

- packages/app/src/app/components/Create/ImportRepository/steps/AuthorizeGitHubPermissions.tsx
- packages/app/src/app/components/Create/ImportRepository/steps/ConfigureRepo.tsx
- packages/app/src/app/components/Create/ImportRepository/steps/FindByURL.tsx
- packages/app/src/app/components/Create/ImportRepository/steps/ForkRepo.tsx
- packages/app/src/app/components/Create/ImportRepository/steps/SearchInOrganizations.tsx
- packages/app/src/app/components/Create/hooks/useGithubRepos.ts
- packages/app/src/app/overmind/effects/gql/dashboard/queries.ts
Uses the new sort option for organizationRepos, so there's no more jumping around when the entire list is loaded
Also made some changes to the tracking events, to ensure consistency
> fix: improve sort order for org repos

- packages/app/src/app/components/Create/CreateBox.tsx
- packages/app/src/app/components/Create/CreateBox/CreateBoxForm.tsx
- packages/app/src/app/components/Create/elements.tsx
- packages/app/src/app/hooks/useCookieConsent.ts
- packages/app/src/app/overmind/internalActions.ts
- packages/app/src/app/overmind/namespaces/editor/actions.ts
- packages/app/src/app/pages/Dashboard/Components/Selection/ContextMenus/SandboxMenu.tsx
- packages/app/src/app/pages/Profile/ContextMenu.tsx
- packages/app/src/app/pages/Standalone/index.tsx
Couple of changes:
- Folder & privacy are now coupled to each-other
- We can create sandboxes from the standalone modal
- We can pass in a minimum privacy
> feat: create sandbox from standalone modal

- packages/app/src/sandbox/eval/transpilers/babel/ast/__snapshots__/convert-esmodule.test.ts.snap
- packages/app/src/sandbox/eval/transpilers/babel/ast/convert-esmodule.test.ts
- packages/app/src/sandbox/eval/transpilers/babel/ast/convert-esmodule.ts
When converting ESM, and there's an expression like `--counter`, where `counter` is exported, we would wrongly convert it to `--exports.counter = counter`, which is invalid syntax. In this case, it's sufficient to do `--exports.counter`, and with this change we do that.
> fix(esm-convert): read + write cases

- packages/sandbox-hooks/not-found-screen/overlay-manager.js
We were checking for the wrong id, and in firefox that's needed because FF loads iframes lazily
> fix: 404 showing in firefox

- packages/app/src/app/components/WorkspaceSetup/Layout.tsx
- packages/app/src/app/components/WorkspaceSetup/Summary.tsx
- packages/app/src/app/components/WorkspaceSetup/WorkspaceSetup.tsx
- packages/app/src/app/components/WorkspaceSetup/steps/Addons.tsx
- packages/app/src/app/components/WorkspaceSetup/steps/ChangeAddons.tsx
- packages/app/src/app/components/WorkspaceSetup/steps/ChangePlan.tsx
- packages/app/src/app/components/WorkspaceSetup/steps/Finalize.tsx
- packages/app/src/app/components/WorkspaceSetup/steps/Payment.tsx
- packages/app/src/app/components/WorkspaceSetup/steps/Plans.tsx
- packages/app/src/app/components/WorkspaceSetup/steps/SpendingLimit.tsx
- packages/app/src/app/components/WorkspaceSetup/types.ts
- packages/app/src/app/graphql/types.ts
- packages/app/src/app/overmind/effects/gql/dashboard/fragments.ts
- packages/app/src/app/overmind/effects/gql/dashboard/mutations.ts
- packages/app/src/app/overmind/namespaces/checkout/actions.ts
- packages/app/src/app/overmind/namespaces/checkout/constants.ts
- packages/app/src/app/overmind/namespaces/checkout/state.ts
- packages/app/src/app/overmind/namespaces/checkout/types.ts
- packages/app/src/app/pages/WorkspaceFlows/CreateWorkspace.tsx
- packages/app/src/app/pages/WorkspaceFlows/ManageAddons.tsx
- packages/app/src/app/pages/WorkspaceFlows/UpgradeWorkspace.tsx
- packages/app/src/app/pages/WorkspaceFlows/index.ts
- packages/app/src/app/pages/index.tsx
Still working on some details, but the core feature is there.
New page on `/manage-addons` which will be linked from the portal
It shows the first step where it populates the checkout with the existing subscription and allows users to add/remove addons
Then you get a comparison of the old and new plans to confirm the change
> feat: allow managing addons from the checkout flow

- packages/app/src/app/graphql/types.ts
- packages/app/src/app/overmind/effects/gql/dashboard/fragments.ts
- packages/app/src/app/overmind/effects/gql/dashboard/queries.ts
- packages/app/src/app/overmind/namespaces/dashboard/utils.ts
- packages/app/src/app/pages/Dashboard/Components/Branch/BranchCard.tsx
- packages/app/src/app/pages/Dashboard/Components/Branch/BranchListItem.tsx
- packages/app/src/app/pages/Dashboard/Components/Branch/index.tsx
- packages/app/src/app/pages/Dashboard/Components/Branch/types.ts
- packages/app/src/app/pages/Dashboard/Components/Header/index.tsx
- packages/app/src/app/pages/Dashboard/Components/VariableGrid/index.tsx
- packages/app/src/app/pages/Dashboard/Content/routes/RepositoryBranches/index.tsx
A few main changes (along with css tweaks)
- allow only list view for branch listing, as branch cards are not really working with long branch names and long pr titles
- show PR titles when they are attached to the branch
- show branches with PRs first, before other branches
- don't show draft branches (not pushed on GH) that the user has not visited
> feat: small improvements for the branch listing in the repository page

- packages/app/src/sandbox/eval/transpilers/babel/ast/__snapshots__/convert-esmodule.test.ts.snap
- packages/app/src/sandbox/eval/transpilers/babel/ast/convert-esmodule.test.ts
- packages/app/src/sandbox/eval/transpilers/babel/ast/convert-esmodule.ts
Important fix. Our quick esm->cjs converter doesn't handle write + read references well. When there's code like:
```js
character = position > 0 ? charat(characters, --position) : 0
```
It converts `--position` to `--exports.position`. That's wrong, because now the local variable does not get changed. We can solve this by resolving the ast node higher, and change it to:
```js
exports.character = character = position > 0 ? charat(characters, exports.position = exports.position = --position) : 0;
```
But right now we cannot do that. Because of that, we throw an error and rely on the slower converter (babel) to convert esm to cjs. That will solve an infinite loop problem that people using emotion are seeing, which crashes the whole browser..
> fix: converting write ref with esm to cjs

- packages/app/src/app/components/WorkspaceSelect/WorkspaceSelect.tsx
- packages/app/src/app/pages/common/Modals/MoveSandboxFolderModal/index.tsx
Reverts codesandbox/codesandbox-client#8429
> Revert "feat: remove restriction for moving to free ws"

- packages/app/src/app/components/WorkspaceSetup/steps/Create.tsx
- packages/app/src/app/components/dashboard/InputText.tsx
- packages/app/src/app/graphql/types.ts
- packages/app/src/app/overmind/effects/gql/dashboard/mutations.ts
- packages/app/src/app/overmind/effects/gql/dashboard/queries.ts
> feat: auto-join workspace after sign-up

- packages/app/src/app/components/WorkspaceSetup/steps/Plans.tsx
> fix: align cards center

- packages/app/src/app/components/Create/ImportRepository.tsx
https://github.com/codesandbox/codesandbox-client/assets/9945366/7cbaf633-ad78-4fb4-8658-37ebb296c950
There's a weird React re-render here, that I explicitly bypassed with a 2nd param to the function that re-fetches the github repo once the app was installed
Closes PC-1837
> fix: loop on gh app install

- packages/app/src/app/components/WorkspaceSetup/steps/Plans.tsx
- packages/app/src/app/components/WorkspaceSetup/steps/constants.ts
- packages/app/src/app/overmind/namespaces/checkout/constants.ts
> chore: add SOC 2 to upgrade page

- packages/sandpack-core/src/sandpack-secret.ts
We set partitioned for new cookies, but not when we remove them
> fix: add partitioned to the removal

- packages/app/scripts/deploy.js
This PR changes the deployment script to use the deployer apis (https://deployer.csbops.io). The required env vars is already added to Circle CI
> chore: move deployment to deployer apis

- .codesandbox/tasks.json
- packages/common/src/templates/react-ts.ts
- packages/common/src/templates/react.ts
Our CRA bundler works already very similar to Vite, out of the box. Similar configuration, static files in the same place, transpilation logic is the same.
The only thing that is missing, is knowing that conventially `src/main.tsx` is the entrypoint.
With this change, we make the basic examples of Vite work, using our existing CRA bundler. When things get more advanced (Vite plugins, etc) it won't work, but then people can opt to export it to a Devbox. Until then, this should handle 90% of all cases.
One thing to note, is that maybe the `index.html` is not served properly by our static server. Could be the case. If it's loaded properly, it will try to load a JS file that's not there. The user will just get an error in the console, but nothing will happen to the preview itself.
> feat: make vite work in cra template

- packages/app/src/app/components/Create/CreateBox/CreateBoxForm.tsx
Closes a recurring API Sentry Error.
TIL that if you have something like this:
```
<option key="drafts" value={null}>
Drafts
</option>
```
It does _not_ actually give you `null` when you try accessing the value but it uses the text that's inside the tag. This explains why we keep getting API requests that have `collection_id: "Drafts"`. (I was suspicious and confirmed in the console)/
To make it explicit I added a value of `drafts` that we can check against, but open to alternatives! 
The reason that it's so intermittent and tricky to reproduce is that this _only_ happens when you select a different folder and then go back and select `Drafts` -- If you never select anything _other_ than `Drafts` it remains correctly initialised.
1. Step A
2. Step B
3. Step C
> FIX: set undefined collection id instead of 'Drafts'

- packages/app/src/app/components/Create/utils/queries.ts
- packages/app/src/app/graphql/types.ts
- packages/app/src/app/hooks/useWorkspaceAuthorization.ts
- packages/app/src/app/overmind/effects/gql/dashboard/fragments.ts
- packages/common/src/types/index.ts
Now the _huge_ houskeeping PR has been merged, I can do some more tiny cleanup.
These fields have been deprecated / resolved to a hard-coded value in the API for months already, and their values are no longer actually _used_ anywhere, so I removed them from the queries and regenerated the types.
1. Step A
2. Step B
3. Step C
> Remove deprecated fields from GQL fragments

- packages/app/src/app/pages/Dashboard/Content/routes/Sandboxes/useFilteredItems.ts
- packages/app/src/app/pages/Dashboard/Sidebar/NestableRowItem.tsx
- packages/app/src/app/pages/Dashboard/utils/path.ts
When creating a folder structure in the dashbboard like
- `/test/a/b`
- `/test2/b/b`
Then if you would open `/test/a`, it would show two `b` folders in the overview. It was a small logic error, which is fixed in this PR.
> fix(dashboard): folders with same name but different parents

- packages/sandpack-core/src/npm/dynamic/fetch-protocols/file.ts
Officially we should support `file://` for absolute files. We parsed it as `file:/`. This change fixes that.
> fix: absolute path file resolving

- packages/sandpack-core/src/npm/dynamic/fetch-protocols/file.ts
Actually... npm does not use uris as we know them, so it _is_ actually okay to use them this way.
> fix: revert change of file location

- packages/sandpack-core/src/npm/dynamic/resolve-dependency.ts
This ensures that for overridden versions (using the resolutions field) we never fetch from unpkg/jsdelivr if it resolves to a file
> fix: use resolution version for fetching transient dependencies

- .circleci/config.yml
Old one got deprecated, prevents us doing new releases
> fix(circleci): update remote docker version

- packages/sandpack-core/src/npm/merge-dependency.ts
Sometimes, a resolved version does not have to be an absolute version (e.g. `3.2.1`). Because of this, `semver` throws (which I hate). We now wrap it in a safe wrapper that defaults to `true` if it throws, because we expect that it's then a URL.
> fix: csb ci sandboxes

- packages/app/src/app/pages/Dashboard/Content/routes/Search/searchItems.ts
Non-draft sandboxes where ignored because of the faulty condition
> fix: search results for sandbox

- packages/app/src/app/constants.ts
This PR updates an outdated form URL used on the Upgrade page.
> chore: update Pipeform URL on 'Enterprise' CTA of Upgrade page

- packages/app/src/app/pages/Dashboard/Content/routes/Sandboxes/useFilteredItems.ts
Because of the `normalize` function, folders created in the root folder were not recognized when iterating on the items in the dashboard
Before
After
> fix(dashboard): show folders in root

- packages/app/src/app/components/WorkspaceSetup/steps/SelectWorkspace.tsx
Folks with billing permissions should be able to upgrade a workspace, not only admins.
1. Step A
2. Step B
3. Step C
> FIX: check for billing manager and admin on upgrade page

- packages/app/config/webpack.common.js
- packages/app/package.json
- yarn.lock
Upgrades React DevTools to make them work with React 19. Fixes https://github.com/codesandbox/codesandbox-client/issues/8673
> fix: upgrade react devtools

- packages/sandpack-core/src/resolver/utils/exports.ts
Similar to how we should nowadays prioritize `module` over `main`, we should also prioritize `import` over `require`. It will be a bit slower (as we need to transpile esmodules to commonjs to run it in the browser), but these days all bundlers prioritize esmodules over commonjs, and so not defaulting to it on CSB introduces some subtle bugs.
> fix(sandpack): prefer import over require for exports resolving

- packages/sandpack-core/src/resolver/utils/exports.ts
- packages/sandpack-core/src/resolver/utils/pkg-json.ts
After preferring esmodules in our export resolving, some sandboxes broke because of its reliance on `chevrotain@10.x.x`. This version of `chevrotain` has a version of ESM where `__esModule` is set to true, but where also a default export is set. This should not happen, if `__esModule` is set to true, all of its exports should be on the root.
Other bundlers also had issue with this, and as a result some libraries have updated `chevrotain` to v11, which fixes the issue. We want to keep backwards compatibility on our sandboxes, though, so we should instead force commonjs resolving for chevrotain 10.x.x.
An alternative solution is to alias chevrotain 10.x.x to 11.x.x
> fix: force commonjs resolving for chevrotain

- .circleci/config.yml
- .github/ISSUE_TEMPLATE/BUG.md
- CONTRIBUTING.md
- contributor-docs/adding-template.md
- packages/app/src/app/overmind/factories.ts
- packages/app/src/app/pages/Dashboard/Components/SyncedSandbox/SyncedSandboxListItem.tsx
- testpr-script.js
Move default branch to `main`, finally!
> chore: move default branch to main

- packages/app/src/sandbox/eval/transpilers/postcss/loader.ts
Angular uses `~` to define root paths, our resolver does not understand this. With this change we remove the `~` at the start.
Fixes https://github.com/codesandbox/codesandbox-client/issues/7411
> fix: starting ~ in style paths
